### ISSUE TITLE
alignment with OpenContainers

### ISSUE THREAD

**Issue by cgwalters** [containers/skopeo#100]
Hi, I'm wondering if anyone here has looked at the signing discussion here:

https://github.com/opencontainers/image-spec/issues/22

**Comment by runcom** [comment]
@mtrmac ^^

@cgwalters we're implementing something wrt OCI images right now fwiw (but no signing yet)

**Comment by rhatdan** [comment]
I am going to close this issue, since I don't think anyone is working on it, and signing is a black hole in the OCI.
