### ISSUE TITLE
Skopeo-sync: do not fail if a single image fails to copy

### ISSUE THREAD

**Issue by yannh** [containers/skopeo#1009]
When syncing large number of repositories, and hundreds / thousands of images, it is likely that skopeo sync will hit random errors - a 5xx error from dockerhub is not that uncommon. At the first 5xx error it receives from the registry, skopeo sync will log the error and exit.

I would suggest to log the error and continue. Would that be a reasonable default? If yes, I can have a go at the patch.

**Comment by mtrmac** [comment]
Thanks for the report. Let’s discuss in #1011.

**Comment by rhatdan** [comment]
Looks like the #1011 was fixed or closed with a work around.  Closing. Reopen if I am mistaken.
