### ISSUE TITLE
Build quay.io/skopeo/stable as multi-arch image

### ISSUE THREAD

**Issue by barthy1** [containers/skopeo#1010]
At this moment `quay.io/skopeo/stable` images are amd64 only.
We need s390x and ppc64le image versions to run e2e tests for Tekton on corresponding platforms.
The best case would be to have multi-arch image, which all platforms can use.
The discussion about the same request for quay.io/buildah/stable https://github.com/containers/buildah/issues/2002

**Comment by TomSweeneyRedHat** [comment]
@barthy1 thanks for the issue, especially so with the pointer.  I'm hopeful that we can do this, and will ping @james-crowley and @cevich to make sure they're aware of this request too.

**Comment by james-crowley** [comment]
@TomSweeneyRedHat Thanks for tagging me. Taking a brief look at Skopeo, it looks they are using Travis CI at least for their Mac OS builds. 

Adding building of `s390x` and `ppc64le` images via Travis should be pretty easy. 

If the builds for the images are done via another CI/CD pipeline, we can work with the community to get them access to `s390x` and `ppc64le` support.

Additionally, Travis also had some `arm64` resources as well. Which would be cool to see support for if Skopeo is looking at doing multi-arch images.

**Comment by barthy1** [comment]
Hi @TomSweeneyRedHat 
Are there any updates to get multi-arched skopeo image?
Considering Travis as a great option to run builds on real native hardware, I'd suggest to take into account also [Github actions](https://github.com/crazy-max/ghaction-docker-buildx)
with option to build multi-arch images with emulation. For instance, for skopeo upstream image I was able to verify that it works and produces multi-arch image with `amd64`, `s390x` and `ppc64le` support.
Have a look at the [code](https://github.com/barthy1/skopeo/blob/master/.github/workflows/build-and-push.yml) and [build logs](https://github.com/barthy1/skopeo/runs/1193910387).

**Comment by TomSweeneyRedHat** [comment]
Hi barthy1, high on the list, but have been tending to other fires.

**Comment by barthy1** [comment]
Hi @TomSweeneyRedHat sorry for bothering you again. I'd like to be more specific in my question :) Do you consider to use Github actions to build multi-arch skopeo images? if yes, I can prepare the PR.

**Comment by TomSweeneyRedHat** [comment]
@barthy1 I never turn down an offer of a PR.  If you have a good thought on how to pull this off, I'd be very happy to review it.

**Comment by barthy1** [comment]
@TomSweeneyRedHat I played a little bit with Github Actions and decided to create the PR to build multi-arch image with Travis using native hardware :)
Will be appreciated for review https://github.com/containers/skopeo/pull/1066

**Comment by james-crowley** [comment]
@barthy1 Github Actions sounded super cool! It is something I been trying to play around with myself. Did you get far with using the GitHub actions buildx? I assume with buildx you were planning on using the qemu option for building multi-arch images? 

Travis has been my go to for building on arch as its very simple. We have a couple internal scripts for building multi-arch images. Feel free to reach out to me if you want to take a look!

Github actions would be super cool to get working, one major blocker is a the lack of support for running the Github runner on s390x and ppc64le. As most of the runner is developed in `.Net` code.

**Comment by barthy1** [comment]
@james-crowley yes, agree that Github Actions are great for many things :)

> I assume with buildx you were planning on using the qemu option for building multi-arch images?

I tried to run the skopeo multi-arch builds with `buildx` using `qemu`. However after some time I learnt, that there are several drawbacks in emulation when we are talking about something more than "install several packages to default image".
Based on my tests it turns out that build for 3 archs took 30 mins (which is just natural for emulation, but still) + there were Segmentation fault error for some cases.

> Github actions would be super cool to get working, one major blocker is a the lack of support for running the Github runner on s390x and ppc64le. As most of the runner is developed in .Net code.

Yeah, however I saw discussion to port the runner to Golang, so look forward to it..

Anyway, Travis with native hardware is fast and zero-problematic so far for skopeo case :) And in my PR I was able to build multi-arch `skopeo/upstream` image just easily.

**Comment by barthy1** [comment]
Fixed with https://github.com/containers/skopeo/pull/1066 and https://github.com/containers/skopeo/pull/1066

**Comment by james-crowley** [comment]
@barthy1 Great job pushing forward with Travis CI. For future reference, our team does have some build scripts/examples for Travis multi-arch builds. Feel free to check them out. 

https://github.com/LinuxCoC/travis-docker-manifest-example
https://github.com/jordan-cartwright-ibm/example-docker-manifest
