### ISSUE TITLE
skopeo inspect does not work on oci-archives when running as non-root user

### ISSUE THREAD

**Issue by rudolpho1** [containers/skopeo#1025]
When running `skopeo inspect` on an oci-archive as non-root user, I get the following error:

```
>skopeo inspect oci-archive:xxx.tar
FATA[0000] Error parsing image name "oci-archive:xxx.tar": error creating temp directory: error untarring file "/var/tmp/oci811877667": lchown /var/tmp/oci811877667/blobs: operation not permitted

```
Of cause the user has write access to `/var/tmp`. The same call runs fine as root.
Probably, the `lchown` error should be suppressed in the non-root case.

**Comment by QiWang19** [comment]
storage/pkg/archive has `IgnoreChownErrors`, inspect on an oci-archive can success if suppress the error by setting `IgnoreChownErrors` to true. Does this should be fixed in storage/pkg/archive, does the pkg tell whether the user is a root or non-root user?

**Comment by mtrmac** [comment]
This is tracked in c/image as https://github.com/containers/image/issues/1017 ; let’s discuss there.

> does the pkg tell whether the user is a root or non-root user?

This really doesn’t matter for `oci-archive`; the user/group/permission bits of the archive carry no semantic information, we only want to access the index/manifest/blob _contents_. So, hard-coding `IgnoreChownErrors` (if that’s the right c/storage API to do this, I haven’t checked in detail) to always be enabled in the OCI archive transport should be fine.
