### ISSUE TITLE
Add support for docker-archive: to skopeo list-tags

### ISSUE THREAD

**Issue by guanxingfeng** [containers/skopeo#1029]
command: skopeo inspect docker-archive:/root/busybox.tar
{
    "Digest": "sha256:d8db71d650ed60da14a6c6d46ea1103d253a1117586e846020b82726e71d3b19",
    "RepoTags": [],
    "Created": "2020-06-29T20:21:41.42102751Z",
    "DockerVersion": "18.09.7",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:50761fe126b6e4d90fa0b7a6e195f6030fe250c016c2fc860ac40f2e8d2f2615"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}

expect display right ,eg "RepoTags":["busybox:latest"]!!

**Comment by mtrmac** [comment]
Thanks for your report.

Conceptually, `skopeo inspect` exists to provide information about an _image_; the way it also provides repository tags, _only_ for docker/distribution registries, does not really generalize (and is often _actively unwanted_ in `inspect` due to the extra overhead). It’s more or less a historical accident preserved for compatibility, and not something that we want to further enhance.

This functionality would be a good fit for `skopeo list-tags`, though.

**Comment by rhatdan** [comment]
@guanxingfeng Does list-tags satify your needs?

**Comment by mtrmac** [comment]
@rhatdan `skopeo list-tags` doesn’t currently implement `docker-archive:`.

**Comment by guanxingfeng** [comment]
@rhatdan I want to get tags from a image tar，skopeo list-tags doesn’t currently implement docker-archive:

**Comment by rhatdan** [comment]
Would that change make more sense? Using skopeo list-tags on a docker-archive?

**Comment by guanxingfeng** [comment]
I wang to implement upload multiple docker tars to image hub using UI，like this，

![image](https://user-images.githubusercontent.com/25924966/97379789-8d861080-1900-11eb-8423-f0769cac5fc0.png)

It will be very useful and convenient to get the image tags automatically instead of manual input.

**Comment by mtrmac** [comment]
FWIW https://github.com/containers/image/pull/991 has built the infrastructure necessary to implement this.

**Comment by zhangguanzhang** [comment]
> FWIW [containers/image#991](https://github.com/containers/image/pull/991) has built the infrastructure necessary to implement this.

Is there any update for this? I use the latest code, it still not implement this
```
$ skopeo --version
skopeo version 1.7.0-dev commit: 22d187181b0e92a3290c9e63909c4bde98353ed7
skopeo list-tags  docker-archive:test.tar
FATA[0000] Unsupported transport 'docker-archive' for tag listing. Only 'docker' currently supported
```

**Comment by djpbessems** [comment]
I could definitely use this; right now I have to resort to parsing the manifest *inside* the tarball with `jq`, this is far from efficient.

**Comment by vrothberg** [comment]
You can use it with the latest version of Skopeo.

**Comment by djpbessems** [comment]
Yeah sorry, I did not realise that I'm still stuck on an ancient version; SLES' repository still has 1.4.1.

I'll instead run my commands within the official container image.
