### ISSUE TITLE
install.md is wrong w.r.t. building

### ISSUE THREAD

**Issue by duglin** [containers/skopeo#1034]
install.md says to `make binary-static` but that target is not there - I think it's meant to be
`static`.

However, I'm trying this as part of the "build in a container" option and in order to do that I first need to install stuff like `nix`. Doesn't that defeat part of the reason people build in containers? Granted people need to install Docker, but to me one reason to do a build in a container is so that other people don't need to install all of the other stuff (golang, nix, etc...) just to build?

**Comment by TomSweeneyRedHat** [comment]
@duglin I'm not sure what's going on with the make stuff, @mtrmac will probably have a thought or two there.  I did want to ask about what you're trying to do in the end?  Would using a premade container image of skopeo work for you and then you could avoid the build step?  The container image quay.io/containers/skopeo:latest is available for use and has the latest released version of skopeo within it.

**Comment by duglin** [comment]
In my current case I'm looking for a staticly-bound exe so I can include it in my own image and not have to pull in any other libs.  I guess I could grab skopeo:latest and just `cp` the exe from there... is that one staticly built?

**Comment by TomSweeneyRedHat** [comment]
@duglin thanks for the clarification.  The container image on quay.io is not statically built.  It's created using `podman build` and the Dockerfile [here](https://github.com/containers/skopeo/blob/master/contrib/skopeoimage/stable/Dockerfile).

**Comment by mtrmac** [comment]
The overall background is that the developers mostly don’t use static or in-container builds, and that it shows; at best static builds are tolerated if PRs come. Historically we’ve had four ways of building Skopeo in the `Makefile`, and only one frequently used, with predictable results…

The Make targets were last changed in https://github.com/containers/skopeo/pull/932 (and we missed in there that the documentation needs updating, I’m afraid), which supposedly standardized the static build / Nix approach, and build targets, across Skopeo/Buildah/Podman. Apparently, as part of that standardization, the “build in a container and store a static binary outside of a container” Make target was removed. So, now we are down to 3 ways of building Skopeo, with only one frequently reused, and with a bit more consistency.

If you need just the static binary, it’s probably quite possible to create use a container to do it in, but that PR has not provided one (and to the extent the Make targets are supposedly consistent now, I’m not too enthusiastic to add a badly-maintained Skopeo-specific Make target).

(Regardless, my general recommendation is to use a Skopeo package provided by your Linux distribution, but I realize some people have strong, and sometimes good :) reasons, not to do that, like wanting to use the latest version immediately.)

**Comment by mtrmac** [comment]
I have filed https://github.com/containers/skopeo/pull/1035 to at least remove the incorrect paragraph.

**Comment by lsm5** [comment]
@mtrmac can this be closed? If all projects have agreed on a way to build static binaries, then doesn't look like there's anything else to do here.

**Comment by rhatdan** [comment]
Since this is no longer on the install.md we can close this issue.
