### ISSUE TITLE
Sync fails to copy manifest lists

### ISSUE THREAD

**Issue by HeroCC** [containers/skopeo#1044]
Hello! I'm trying to copy a bunch of images from Docker Hub to Quay, and tried running `skopeo sync --src docker --dest docker docker.io/moosivp/moos-ivp quay.io/moosivp`, which appeared to be working, until I realized that the manifest lists weren't being copied correctly. I have images tagged with `:r1234` which are actually multi-arch manifests that point to each respective arch's image. I'd expect the resulting quay repo to have these copied over correctly, however they only have the amd64 variant. 

I didn't see a `--all` flag similar to `skopeo copy`. Is there some way to force `skopeo sync` to detect and respect these multi-arch tags?

**Comment by HeroCC** [comment]
As an aside, I was able to make a script to copy the tags by hand. May be useful for others. You can drop the final grep if you'd like, it excludes tags with the arch in the name (they are contained in the manifest list and are redundant).

```bash
IMAGES="$(skopeo list-tags docker://docker.io/ORG/REPO | jq -r '.Tags[]' | grep -Ev 'amd64|arm64|armv7')"
for tag in $IMAGES; do 
  echo "Copying $tag"
  skopeo copy -a "docker://docker.io/ORG/REPO:$tag" "docker://quay.io/ORG/REPO:$tag"
done
```

**Comment by muff1nman** [comment]
See https://github.com/containers/skopeo/pull/880

**Comment by mtrmac** [comment]
#880 has added the `--all` option.
