### ISSUE TITLE
Different Digest than source registry with skopeo copy to local directory

### ISSUE THREAD

**Issue by fjcloud** [containers/skopeo#1046]
Hello, 

I have an issue; when i want to copy an image with skopeo it give a different digest than original image. I don't understand why.

For example >>

Here a Digest from docker.io 

```
# skopeo inspect docker://docker.io/nginx:1.19.2 | grep Digest
"Digest": "sha256:c628b67d21744fce822d22fdcc0389f6bd763daac23a6b77147d0712ea7102d0",
```

Then I copy the image in my local directory 

`# skopeo copy docker://docker.io/nginx:1.19.2 dir:images/nginx `

And when i inspect it , i find a different digest.

```
skopeo inspect dir:images/nginx | grep Digest
"Digest": "sha256:794275d96b4ab96eeb954728a7bf11156570e8372ecd5ed0cbc7280313a27d19",
```

I have a use case where i need to have exactly the same sha256 on destination registry that's why i found this issue. 

Maybe there is something that i don't understand ! 

```
# skopeo --version
skopeo version 0.1.40
```

Thank you for your help.

**Comment by mtrmac** [comment]
Thanks for your report.

The image is a multi-architecture image, and `skopeo copy` by default copies only the image for the current architecture. Recent versions of Skopeo provide `skopeo copy --all` to copy the full multi-architecture image; that should preserve the digest (as long as the destination registry supports the format).

**Comment by fjcloud** [comment]
Okay, look like it works now. :+1: 

Thank you !
