### ISSUE TITLE
copy.Image manifest mismatch on containerd

### ISSUE THREAD

**Issue by carlpett** [containers/skopeo#1054]
Hi,
I'm copying images between registries with `image.Copy`. I noticed that our GKE clusters which run containerd instead of Docker are unable to pull the images afterwards, due to a one byte size mismatch:
`PullImage "the-image" from image service failed: rpc error: code = Unknown desc = failed to pull and unpack image "the-image": failed commit on ref "layer-sha256:b5c2fd1d2fe1f679197702e3dd5baec6040a4ac053ccf81c482112d71ac52e33": "layer-sha256:b5c2fd1d2fe1f679197702e3dd5baec6040a4ac053ccf81c482112d71ac52e33" failed size validation: 13618649 != 13618650: failed precondition`

Both podman locally on my laptop and clusters running docker can pull the image successfully. 
My program basically consists of some `reference` mangling to figure out the new registry to copy to, and then a call to `copy.Image(ctx, policyContext, dstImgRef, srcImgRef, nil)`, so pretty simple. Any idea where I could be going wrong?

**Comment by mtrmac** [comment]
Thanks for your report.

This does not ring a bell. I’d suggest first isolating whether this is a bug in the writer or in the reader:
- read the raw manifest with `skopeo inspect --raw` and see the data in the manifest
- `skopeo copy docker://… dir:$tmpdir`, verify the layer digest, and see its size.
- If the on-registry contents are already unexpected, maybe try using a `dir:` destination or a different registry implementation to check whether it might be registry-specific.

**Comment by carlpett** [comment]
Hm. Of course I'm now unable to repro this... Not sure if there was a glitch on the registries' side (source is Github Packages, destination Google Artifact Registry), or whatever happened.
Sorry for the noise, I'll get back if I somehow manage to trigger this again.
