### ISSUE TITLE
skopeo inspect ignores docker login credentials

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#1059]
The readme currently says this:
> skopeo uses credentials from the --creds (for skopeo inspect|delete) or --src-creds|--dest-creds (for skopeo copy) flags, if set; otherwise it uses configuration set by skopeo login, podman login, buildah login, or docker login.

I have already logged into my private registry via `docker login`. My ~/.docker/config.json file looks like this:
```
{
	"auths": {
		"<private-registry>": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.12 (darwin)"
	},
	"credsStore": "desktop",
	"experimental": "disabled",
	"stackOrchestrator": "swarm"
}
```

However, using skopeo v1.2.0, `skopeo inspect docker://<private-registry>/<img>:<tag>` always fails with an error:
```
FATA[0000] Error parsing image name "docker://<private-registry>/<img>:<tag>": unable to retrieve auth token: invalid username/password: unknown: Authentication is required 
```

Passing credentials manually via `--creds` does work as expected. The private registry is hosted on JFrog Artifactory, if it matters.

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by rittneje** [comment]
Looking deeper, this appears to be an issue with one of your dependencies.

https://github.com/containers/skopeo/blob/44beab63c975b23ce2b1782035b1f3b1a972369e/vendor/github.com/containers/image/v5/pkg/docker/config/config.go#L26-L29

It incorrectly ignores the `credsStore` field while unmarshaling. This is a known issue over there. https://github.com/containers/image/issues/111

**Comment by gzm55** [comment]
`copy` and `login` commands also have this issue.

**Comment by mtrmac** [comment]
Thanks for your report. As you note, this is a missing functionality in c/image, and will be fixed in there.
