### ISSUE TITLE
v1.2.0 image missing from quay.io registry

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#1060]
I checked both https://quay.io/repository/containers/skopeo?tab=tags and https://quay.io/repository/skopeo/stable?tab=tags. The latest version available on quay.io is v1.1.1.

**Comment by TomSweeneyRedHat** [comment]
@rittneje I just double checked, skopeo v1.2 has yet to be moved to stable here:  https://bodhi.fedoraproject.org/updates/FEDORA-2020-e7b88e4fa0.  That usually happens after a week or after sufficient karma has been applied.

**Comment by rhatdan** [comment]
@lsm5 PTAL.  I think this is stable via modules?

**Comment by lsm5** [comment]
@TomSweeneyRedHat @rhatdan So, IIUC, this uses fedora 32, right? v1.2.0 is yet to land in stable https://bodhi.fedoraproject.org/updates/FEDORA-2020-71d09b6ffe . Please add karma there so it can land faster.

**Comment by rhatdan** [comment]
Closing since this has nothing to do with github.
