### ISSUE TITLE
skopeo ignores DOCKER_CONFIG environment variable

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#1061]
The docker CLI lets you set the `DOCKER_CONFIG` env var to point to the directory containing config.json. https://docs.docker.com/engine/reference/commandline/cli/#environment-variables However, right now skopeo just looks at `$HOME/.docker/config.json`. It would be nice if it consulted `$DOCKER_CONFIG/config.json` instead if the env var is set.

**Comment by rittneje** [comment]
Upon further review, this is an issue in github.com/containers/image, so I've filed a separate issue there. https://github.com/containers/image/issues/1055

**Comment by mtrmac** [comment]
FWIW the `--authfile` option allows directing Skopeo to use a specific file in a much more direct and transparent way.

**Comment by rittneje** [comment]
For me the reason the env var is preferable is that way I can configure which file to use once in my Dockerfile instead of having to explicitly pass the option via the command line every time.
