### ISSUE TITLE
[RFE] Support manifests list (Docker & OCI)

### ISSUE THREAD

**Issue by runcom** [containers/skopeo#107]

**Comment by SvenDowideit** [comment]
@runcom is this likely to happen soon? or is https://github.com/estesp/manifest-tool the way to go?

**Comment by runcom** [comment]
@SvenDowideit I'd love estesp's tool merged back here (where it was forked from, skopeo). I have this on my todo but if anyone wants to take it and help, please do so, I don't have any ETA otherwise.

**Comment by rhatdan** [comment]
I too think this would be good to get these tools merged back. @estesp What do you think?

**Comment by runcom** [comment]
Note that docker upstream is basically merging Phil's tool in the Docker cli (via a subcommand called "manifest").

**Comment by mtrmac** [comment]
FWIW containers/image, and skopeo, can consume docker schema2 manifest lists (by choosing the current architecture). 

That’s by no means a comprehensive support, of course — but it would be nice to flesh out what this ticket means, “support manifest lists” is too vague to ever say “yes, this has happened”.

**Comment by mtrmac** [comment]
There is a WIP PR at https://github.com/containers/image/pull/400 , I’m afraid the progress has stalled for some time.

**Comment by rhatdan** [comment]
Still open issue, though no one is working on it right now, have to gauge priority.

**Comment by mtrmac** [comment]
Skopeo has `skopeo copy --all` after #741.
