### ISSUE TITLE
Sync: Add option to keep full name on target when using YAML

### ISSUE THREAD

**Issue by mfriedenhagen** [containers/skopeo#1072]
Hello,

* I know that this was already discussed in #898 and especially in #854.
* However, maybe I can add an usecase:
   * We currently use another program to sync images from a 8 registries to our internal one (docker.example.com).
   * To ease the use, all our internal users (and build systems) have configured docker.example.com as `registry-mirrors`.
   * So when they run `docker run --rm -it alpine`, they automatically pull this from docker.example.com/library/alpine and same goes for `docker run --rm jenkins/jnlp-slave`.
   *  We did not find any collisions when using the "group" as path.
   * Now I would like to keep all synced images from e.g. registry.hub.docker.com in one YAML file (currently we sync 185 repositories from there).
   * Another feature which only seems to be available in the YAML file is to define `images-by-tag-regex`. 
   * Without the option to keep the full name, I would need to split this into 185 files and commands.
* So I really would like to see something like `--scoped-without-registry` as outlined in #854.

**Comment by art-shutter** [comment]
Can second this issue as needed

**Comment by tbrasser** [comment]
Currently I need to create a yaml per group and loop skopeo-sync over those. This would alleviate that need.

**Comment by art-shutter** [comment]
@tbrasser 
please see the discussion here https://github.com/containers/skopeo/pull/1531

**Comment by mtrmac** [comment]
Closing in favor of #1531 to decrease the number of places collecting ideas about the sync mapping design.
