### ISSUE TITLE
No Docker image for v1.2.0 in quay.io

### ISSUE THREAD

**Issue by yannh** [containers/skopeo#1073]
Hello! Could you upload a Docker Image for 1.2.0 on https://quay.io/repository/skopeo/stable?tab=tags on quay.io, assuming all releases are considered stable? :pray: 
Thank you!!

**Comment by TomSweeneyRedHat** [comment]
The images here https://bodhi.fedoraproject.org/updates/?search=skopeo are not yet stable except for Fedora 31.  We need the F32 version to be stable.

**Comment by yannh** [comment]
@TomSweeneyRedHat I meant these releases: https://github.com/containers/skopeo/releases  - is the 1.2.0 version released there not considered stable? If not then :bow: that wasn't clear to me and this ticket can be closed.

**Comment by rhatdan** [comment]
It should be now.  Just because the upstream marks a release as stable, does not mean the package is instantly available in distros like Fedora.  Fedora goes at least  a week after the rpm is built before it is marked stable.

**Comment by rhatdan** [comment]
$ podman run quay.io/skopeo/stable -v
skopeo version 1.2.0

Looks like it is there now.
