### ISSUE TITLE
--authfile ignored if HOME unset

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#1079]
I am running skopeo v1.2.0 inside a docker container. If I don't set my `HOME` variable, skopeo fails to get creds even though I explicitly pass --authfile.

```
skopeo inspect --authfile /authfile.json docker://<image>
FATA[0005] Error parsing image name "docker://<image>": error getting username and password: credentials not found in native keychain 
```

If I set `HOME` it works.

**Comment by TomSweeneyRedHat** [comment]
@rittneje thanks for the report.  Just to verify, do you set `HOME` to `/` or to a user directory of some sort like `/usr/users/myuser`?
@QiWang19 PTAL

**Comment by rittneje** [comment]
Yes, I set it to `/`.

**Comment by rittneje** [comment]
Did some further testing. It seems this issue is actually the cred helper getting confused, not skopeo itself. Apologies for the false alarm.
