### ISSUE TITLE
Copy all tags for a digest

### ISSUE THREAD

**Issue by necccc** [containers/skopeo#1084]
Hi folks,

is there a way to pick an image by its digest at a _source_ and copy all its tags to _destination_?

**Comment by mtrmac** [comment]
Hello,
The registry API doesn’t provide any way to list tags that point at a specific digest. I guess one could list all tags in the repository, and download all referenced manifests to figure out which ones have that digest, and then create corresponding tags at a destination. Such software can of course be written (using HTTP directly, c/image, or just a shell script around Skopeo), but it scales badly and feels a bit too close to abusing the API for comfort.

Why do you need that? Intuitively this feels rather like a workaround for losing some information, or an attempt to manually optimize/deduplicate something the tools should do instead.

I imagine the common use case to be “copy app:1 , app:1.0 and app:2.0-beta to a different registry” — and in that case just copy by tags, and if the tags happen to point at the same image, that’s a bonus. A process never really _starts_ with a digest alone, it starts either with a human-understandable name for something that already exists (a product, an image, a nightly build), or with an intent to create a new image and getting an currently-untagged build output. In both cases the starting point contains some _intent_ for what the image should be, or be called.

**Comment by mtrmac** [comment]
@necccc Is there anything Skopeo can/should do?
