### ISSUE TITLE
How to install on Debian 9

### ISSUE THREAD

**Issue by AndreyNikiforov** [containers/skopeo#1092]
Running:
```
docker run -it --rm debian:9
```
Inside container:
```
root@8ba7e234e41b:/# apt-get install skopeo
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package skopeo
```
Tried running `apt-get update` before installing -- same outcome.

I will be installing and using skopeo as part of ci/cd pipeline.

**Comment by vrothberg** [comment]
We provide community packages on Debian >= 10 (see https://github.com/containers/skopeo/blob/master/install.md). Debian 9 might be too old.

However, you can run Skopeo in a container which may integrate well into your pipeline: https://www.redhat.com/sysadmin/how-run-skopeo-container

**Comment by AndreyNikiforov** [comment]
docker may work, thanks!
