### ISSUE TITLE
skopeo copy fails on GAR (Google Artifact Registry) due to no chunked-upload support

### ISSUE THREAD

**Issue by hijakebye** [containers/skopeo#1101]
I've been attempting to perform a skopeo copy from an on premise private artifactory instance to our GCP environment specifically a GAR (Google Artifact Registry) instance - in their documentation they clearly state they do not support the Chunked-Upload portion of the Docker API

https://cloud.google.com/artifact-registry/docs/reference/docker-api 

Artifact Registry does not support Docker chunked uploads. Some container image tools support uploading large container images with either chunked uploads or a single monolithic upload. You must use monolithic uploads when you push container images to Artifact Registry.

Sample skopeo command ( Certain data omitted ) 
skopeo --debug copy --src-no-creds --dest-tls-verify=false --src-tls-verify=false --dest-creds oauth2accesstoken:<token> docker://privaterepo.com/k8s.gcr.io/metrics-server-amd64:v0.3.6 docker://us-central1-docker.pkg.dev/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64:v0.3.6

Results in 

Copying blob e8d8785a314f [===========================>----------] 463.1KiB / 639.1KiB
Copying blob b2f4b24bed0d [=>------------------------------------] 431.1KiB / 9.4MiB
FATA[0003] Error writing blob: Error uploading layer chunked: StatusCode: 400, <HTML><HEAD>
<TITLE>Request Error</TITLE>
<style..

skopeo version 1.2.0

I assume this be because by default skopeo is attempting to use chunked-upload capability of the docker v2 API ( https://docs.docker.com/registry/spec/api/#chunked-upload )

Is there any way to have skopeo leverage the monolith upload approach ( https://docs.docker.com/registry/spec/api/#monolithic-upload ) such that it would be compatible with GAR / GCR ? Or perhaps someone else may have some insight into what my issue is, possibly something else all together

**Comment by mtrmac** [comment]
Thanks for your report.

This does not sound initially too likely to be precisely the reason, because at least some versions of Docker, can, AFAICT, only ever use the PATCH upload mechanism (I seem to vaguely remember the other one doesn’t even work for some registries? It’s been a long time): https://github.com/projectatomic/docker/blob/fd5a16ed4ffc92b0de0d580eec05d6153f487606/distribution/push_v2.go#L470 calls https://github.com/docker/distribution/blob/f4506b517a7e9e64cfdcc73c991d9e85b784dc3e/registry/client/blob_writer.go#L39 .

I may well be misremembering / missing something, and it’s very likely that there are other minor behavior differences that could cause failures.

https://github.com/containers/skopeo/issues/1054 suggests it works at least some of the time.

**Comment by jonjohnsonjr** [comment]
I'm looking into this from Google's side. We do support this POST/PATCH/PUT flow for uploading blobs, so I'm surprised to see failures here, especially because most clients do this exact thing without any problems. Reading through the skopeo code ([here](https://github.com/containers/skopeo/blob/1a3ae1411e01c4d34a793b24573b5192e4e126eb/vendor/github.com/containers/image/v5/docker/docker_image_dest.go#L146-L178), I think?), nothing jumps out to me as wrong, so I'll need to see if I can reproduce this and start tinkering from there.

**Comment by mtrmac** [comment]
> Reading through the skopeo code ([here](https://github.com/containers/skopeo/blob/1a3ae1411e01c4d34a793b24573b5192e4e126eb/vendor/github.com/containers/image/v5/docker/docker_image_dest.go#L146-L178), I think?)

Yes.

**Comment by mtrmac** [comment]
> FATA[0003] Error writing blob: Error uploading layer chunked: StatusCode: 400,
> 
> <TITLE>Request Error</TITLE> skopeo version 1.2.0

Another idea: Before https://github.com/containers/image/pull/1073 (i.e. in all released Skopeo versions), errors reading data from the source registry are reported without further context as errors writing to the destination. Is it possible that it’s in fact the _source_ registry that is failing with 400? Maybe try with that PR applied, possibly by using the latest development version of containers/image.

**Comment by hijakebye** [comment]
Here's a full HTTP debug dump ( masking the src domains etc ) 

DEBU[0000] Returning credentials from DockerAuthConfig  
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]   Using file:///var/lib/containers/sigstore  
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/us-central1-docker.pkg.dev 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] Trying to access "privaterepo.com/k8s.gcr.io/metrics-server-amd64:v0.3.6" 
DEBU[0000] Returning credentials from DockerAuthConfig  
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for privaterepo.com/k8s.gcr.io/metrics-server-amd64:v0.3.6 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/privaterepo.com 
DEBU[0000] GET https://privaterepo.com/v2/         
DEBU[0000] Ping https://privaterepo.com/v2/ status 401 
DEBU[0000] GET https://privaterepo.com:443/api/docker/docker/v2/token?scope=repository%3Ak8s.gcr.io%2Fmetrics-server-amd64%3Apull&service=privaterepo.com%3A443 
DEBU[0000] GET https://privaterepo.com/v2/k8s.gcr.io/metrics-server-amd64/manifests/v0.3.6 
DEBU[0000] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.v2+json" 
DEBU[0000] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0000] IsRunningImageAllowed for image docker:privaterepo.com/k8s.gcr.io/metrics-server-amd64:v0.3.6 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] Checking /v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:b2f4b24bed0dade029d7164c181e0c8b2c0846fb3a1e2aabf4141480382849b2 
DEBU[0000] GET https://us-central1-docker.pkg.dev/v2/   
DEBU[0000] Checking /v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff 
DEBU[0001] Ping https://us-central1-docker.pkg.dev/v2/ status 401 
DEBU[0001] GET https://us-central1-docker.pkg.dev/v2/token?account=oauth2accesstoken&scope=repository%3Amy-gcp-project%2Fmy-gar-repo%2Fk8s.gcr.io%2Fmetrics-server-amd64%3Apull%2Cpush 
DEBU[0001] GET https://us-central1-docker.pkg.dev/v2/token?account=oauth2accesstoken&scope=repository%3Amy-gcp-project%2Fmy-gar-repo%2Fk8s.gcr.io%2Fmetrics-server-amd64%3Apull%2Cpush 
DEBU[0001] HEAD https://us-central1-docker.pkg.dev/v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:b2f4b24bed0dade029d7164c181e0c8b2c0846fb3a1e2aabf4141480382849b2 
DEBU[0001] HEAD https://us-central1-docker.pkg.dev/v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff 
DEBU[0001] ... not present                              
DEBU[0001] Downloading /v2/k8s.gcr.io/metrics-server-amd64/blobs/sha256:b2f4b24bed0dade029d7164c181e0c8b2c0846fb3a1e2aabf4141480382849b2 
DEBU[0001] GET https://privaterepo.com/v2/k8s.gcr.io/metrics-server-amd64/blobs/sha256:b2f4b24bed0dade029d7164c181e0c8b2c0846fb3a1e2aabf4141480382849b2 
DEBU[0001] ... not present                              
DEBU[0001] Downloading /v2/k8s.gcr.io/metrics-server-amd64/blobs/sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff 
DEBU[0001] GET https://privaterepo.com/v2/k8s.gcr.io/metrics-server-amd64/blobs/sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff 
DEBU[0002] Detected compression format gzip             
DEBU[0002] Using original blob without modification     
DEBU[0002] Checking /v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:b2f4b24bed0dade029d7164c181e0c8b2c0846fb3a1e2aabf4141480382849b2 
DEBU[0002] HEAD https://us-central1-docker.pkg.dev/v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:b2f4b24bed0dade029d7164c181e0c8b2c0846fb3a1e2aabf4141480382849b2 
DEBU[0002] Detected compression format gzip             
DEBU[0002] Using original blob without modification     
DEBU[0002] Checking /v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff 
DEBU[0002] HEAD https://us-central1-docker.pkg.dev/v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/sha256:e8d8785a314f385d3675a017f4e2df1707c528c06e7a7989663fdab4900bd8ff 
Copying blob b2f4b24bed0d [--------------------------------------] 0.0b / 9.4MiB
Copying blob e8d8785a314f [--------------------------------------] 0.0b / 639.1KiB
DEBU[0002] ... not present                              
DEBU[0002] Uploading /v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/uploads/ 
DEBU[0002] POST https://us-central1-docker.pkg.dev/v2/my-gcp-project/my-gar-repo/k8s.gcr.io/metrics-server-amd64/blobs/uploads/ 
DEBU[0002] ... not present                              
Copying blob b2f4b24bed0d [--------------------------------------] 0.0b / 9.4MiB
Copying blob e8d8785a314f [--------------------------------------] 0.0b / 639.1KiB
DEBU[0003] PATCH https://us-central1-docker.pkg.dev/artifacts-uploads/namespaces/my-gcp-project/repositories/my-gar-repo/uploads/AI27aGCE0z-08wSkTFySXljHW3pLEd7is8n5SBBfInmcCgAi0Hs2MVFk4aR6RvM5TDyQAmtBkYaRLjbklYav-ag1zhvix3geP0rfhwhyRPPH6t56AfZl9SU-5OFwt4700yjNo-1v45IzzQDoEWejYZvxbW_hKTMefirsvYz_Qv7vG11vVRJsM-A-b60veUuFABkpSKDi_tnXzA1vbJZBTerTKgBlc3fEB5qLzMjlFxL7M9ISce9llNgEfhDvPmjCbCHtSVc5hnbwhnYCcc2X2j2cDZ5F5GtcJaLZQJ2Q8Rs05G44C0Ttl6D7gkr2PpSf1VT46OdnGxzVU-WF75HDMkaAHl-CBgGERUrP2gktQnkLtDblc1ne0dKXqxLVPSD1LTH-25r10Q2snFCrlo03GQTGVyIE1CWZo8mnFDFqaM42dJ_z5osI7HoYBQN-89bp18pmL_iMto-JfbeG4g3WkvngbJruMRTzqF1QM5q41W3A5tUQPiT_PShvwQP_FfG9fetuxnbOtx__hd-P_VKEEzN_hdlYWHICxWSU5immNB_DkhvBruvjxnwiH8Vphe5YC6jOrntwvjlkHjKVwF4ZRi9iRObq67eo7igxFUdW7KlC2-KNTWrLSIW8CZmIs4WyIR7pArBYufyNk6Zc0JdCpMe4MDfvoLQdW9Znek3P22GXMg223bWVRJnP1CWYKrlub5upVGQcYcS_YqpzH5xkfleYfrfJ4Btj5bHxTiyUFmOKnBUSD1Ghd0CX6jg98ox7XL485yLGWZOCcVCCJjejodEgsZ5WtG8xPTiJR-Vr2fANwXFxzxaDEHDExZkAXzr-aFYo-bz5EuEmcnnkW5LpqSS_tqMp8YOeWRLaKngClLuriejp2WpXb4uoWK8nQInjYexnqUOaLCjDO3RFN78SAbCP8TRTUVylZef_fCpWZUcxTRhl4-CfGOn9CzhL8IHtjIAtHnjPfz_0eHX0Lphb1aPLQGdIq-Caz2tFrA9wFbqJ0TGWqzGwkWxUWVYlzxRzS5fMnxCOdlJ-z2Mly6XlMgJOrNLc0A-9WbqnrN-FYx0h7Ncm69jSbbgWfsw5cqX-wBPrAiPDYNxs9cQkE2MdpzZ7cdNmc4m2zAvjtjDmzdRUXjPVWPFiHk57lqoygMEQ2yO_Zgt90r-NOWcSGSn91sm3S5J7o0yBVOv1nFDLGEQ_anl8frtUR89x-qDJhvDN0dbgaBo8bJhp0kxcGCpBf72UgMgOt39q8ui8uh_IBbe4mBGNAfKIILECfhvd5VPSd1OqWQs25c8hqOPBhFUaJB2MdVXrkuuJCxfCArczWTPmsMRUCrT_RbeoY1DdG9eDuj9CIEM7h4cUvZ_VQZfiLl2mdSo0BH9wO_tlqLd_JGKm0dScmgtN9oL3A-7-tVnCE1n7RBSIu7P6VbblX1gYPabCUl26oafizeby_RIePnnlev2DbUaBUh4Lmlln2gcCtT26bM2ixCJfkicCWvQPlgukBGkVjwHGVqic6PUWnDccmezCIZoFIyICby5YGsNUUO5lqrJ4JR4h-XQWkrQb74ipNLqUd7ZPLOs9PIjG_-bsbNKIP1Uti2RQZp3Rb71c56n26Zs53yCF3IR6Gm36mm8mIHvUqIQaUv6jh6OaipGBRHFVgOkJduo2JyrcP4CHoYp04wBpO1YeGqv3E03rzZf3LcXqE4eAKsPCdqaMCy4cBpdsIayEvXw_n60aSDldKKLBpudb4i_G_N_L-XNyLB0im30X6Xvm5iyHrXRGlNG_pLTRVHdVySmvdxJV7U-8PjdcMTgPb5JkGBgzp7flzQGOAnna5AEcljm0E7WcZJ9tcZTiVQYLOn7I4Om6cLIvlapbE4tX7AHP81YdQYr-29GmA7SBCsslEpHV47rnKPzI0KSh8SaTD12L930OVU0C_GHd8V08EzhIBxnBb0xueNGOXcSe 
DEBU[0003] PATCH https://us-central1-docker.pkg.dev/artifacts-uploads/namespaces/my-gcp-project/repositories/my-gar-repo/uploads/AI27aGBaBQvs_G6KypRTO-TS414EbP9LEZGjj53AUDawJ2kAG74H1UgBmdhs9sGkzxzN0OXUatyYT-KgGjsoPzHK5P3AVj34Ymd3ADtxwQTvUoYwAvLPXY-BB-0WmpOhm2fQLje0ki4-Qyot6YRgvMkPrJ7vwgeuHkZlnfiaUHJzQQTQ88rPId8sstuWINMFsR2pBogliZPGxQdsoJHBC5EzqJTMqsrfmyD6MLEIA8cMHcakGfcVSoZhr-9Q0b9LaAHJx7fn8FPvT94Zr4R5D5ePpDlb-0PLj7Ir1SzWl15MbmME8RcRr6BkFWcTH7em2HgUxLulTdXpLPGTfJY_Cr2Cntu-dl7RMDIONFGk0J_vGaWwACtlLYE2bEUqsYbUcCGUI8xvhImf-n520wVzX5iA2_PvIAvIlIqyV8XOwPNE19RYQpH5NswRMrCWejxswR131uAAX_VfDkNBy0Apt_42usOJVwx8v1ooOMjysQet1Qb6JCn4bB_rFI3XaJZyURHLQuwb7XQylUdgUPc1F2t0yaVYgD7XYyUE_71gjMSq-wRBjCV94JHD6s3dS4NfV5ikkOsZrqFHExiehJiklBhSFCdMxO3hbV2gC4QWC0OWMETjeiFDrfisLEuI6f8PT1CuvPmBzbxuS2cUH45J9HQL7UayBDIAT54O_B_WC0EfM7ugshUakkTmdrBlTv8iJrqVgtAicTL3wZ4tsH754O-MI98uzzImHLX1kJY5jxwgd6wdruhumqOJT3iYjbYzP6cEgtVJ5bjanLqz6VFX671J6M1aqxBs2WZySW0Q3_rQ34oGdHjwu4U5h7gxAe_QN5OUdeafjUNhpsaLiM9vIYnDDajSfpfkFpE6UDKWi9NLWdaFR3QKeDRigunJh0wdAk4OeF9Dh8Fzt7MQeALfK4cyiyazoHR15jo3XhGlzxbaTiDEGoqvNCZkLIcKpbFevRcykDbQvoD71y9DWviPGjK4PSGDV3LaYSXYHwm8EjaDEorYt079zK3FeE-t2k_oOjq8na6NaPCVR2ocSGUjTDm3cnqZvUACnUOGdL_wiZ33g0666hZUWEY8jTlWNdGHlqc3gyRwvRRqTSthRqeKVqLCP8dzNeJVrjm9AJtHUwdwEZT2mUtcTXt3O13Y0wImIYCnA7qQ3_bfDcnOYd7h_k1UYEu72crYMNtUXYwplH0tziGssoA2Eh65yF1otQZ3h_o3esLeha6qqDkOAp1Vkn48uS0g-4K0cEjzmpm1tWF2LvgXmmrHIvx7xjS4U2_UVP7FJ6nXDOIlpYUXR3pL4Rp_57Fp-nihwIKz6y1I4Sd3nakQYCzE6Gp2KOlGtCSE-fblNPF1ak3dk-K_WYiaI85P15gdX7oGk1iG0GYej_Mydl4yeMStXMF3IpOJrkN9513JKL0UAeOasI0XQGUPQtRXFea2ElQbGig9uyY8rM4BSyxGxbMCdMrm4466v9KcETTHYGOw2S3AXlCtcvM4KVHVUgdH294u06KKlWOuDUicqvwgKsLuqdthHRwqv4AUTQgEeDV0QULvYV0uPM6ljY4oZujSYnP3uLchYnbHdfTDT8FJDrgFsNEOnsEEpvvZu7AzvivQ6wDTGUA5jm_dNAe3OPjGg7CTXmIOgVnQzVKGHduxihdIBKciqb4a1NYh-7YKQJVLQKyAl-41RvXuxO6UYYJ1f7VuhlT93kABuwQvo_VPcEoxrVXXFm__dGVYHdnuVH72FH38L8X6jfz_-lAu_zCpKlMvsplsvjd
Copying blob b2f4b24bed0d [--------------------------------------] 0.0b / 9.4MiB
Copying blob e8d8785a314f [--------------------------------------] 0.0b / 639.1KiB
FATA[0003] Error writing blob: Error uploading layer chunked: StatusCode: 400, <HTML><HEAD>
<TITLE>Request Error</TITLE>
<style... 


Seems like it successfully pulls the image from the source repo but fails on copying it over to the destination - it does appear to be using the PATCH interface for uploading those blobs into GAR - so that may rule out my original hypothesis..

**Comment by hijakebye** [comment]
just to circle back on this - this mysteriously started working so looks like potentially GAR made some changes that must have fixed this - we will circle back with our google engineering partners on what may have been causing this..!
Thanks for your time/eyes on this one
