### ISSUE TITLE
Document cases when skopeo is "digest stable"

### ISSUE THREAD

**Issue by Jamstah** [containers/skopeo#1102]
Many users have turned to skopeo as a mechanism to copy images between registries. These users often believe that while docker pull and push can result in a different image digest at the other end, skopeo will keep the digests.

However, the situation is more nuanced, and skopeo can copy to and from many transports.

It would be good if the documentation explicitly said which options were "digest stable", ie, will always maintain the same image digest.

This would be good for both the `copy` and `sync` commands.

**Comment by mtrmac** [comment]
Thanks; or maybe change that, per #1097 .
