### ISSUE TITLE
Unable to install the latest skopeo version

### ISSUE THREAD

**Issue by hemajv** [containers/skopeo#1131]
I tried to install skopeo by following: https://github.com/containers/skopeo/blob/master/install.md#fedora, however it seems to install an older version i.e `0.1.37`. Is there a recommended way to update to the latest version? I am currently running Fedora 30.

**Comment by TomSweeneyRedHat** [comment]
@hemajv, v0.1.37 is probably the newest version on Fedora 30.  Two suggestions:

* Upgrade to Fedora 33 or better yet, 34, and then upgrade Skopeo
* Install Podman
  * dnf -y install podman
* Then run the Skopeo container image on quay.io
  * podman run quay.io/containers/skopeo:latest {skopeo command of choice}

i.e. `podman run quay.io/containers/skopeo:latest --version`

HTH

**Comment by TomSweeneyRedHat** [comment]
I believe my last comment explained how to do the upgrade, and as there's been no follow up questions for over a week, I'm going to close this issue now.  If you still have an issue or question, please reopen or create a new issue as pertinent.
