### ISSUE TITLE
Skopy copy by specified digest

### ISSUE THREAD

**Issue by bagnaram** [containers/skopeo#1133]
I need to be able to choose a specific digest when performing a Skopeo copy. On images with multiple architecture and  custom platform fields, it currently isn't possible to select certain digests. EX:

```bash
skopeo inspect --override-os windows --override-arch amd64 docker://mcr.microsoft.com/k8s/core/pause:1.2.0 --raw
```
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 526,
         "digest": "sha256:1c8444d6590c9840488382e8ce35307608e35f9a00364ab3f82becca67b4f6e0",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1360,
         "digest": "sha256:0dd292df3355ceffad2409b5481119fb8a0b5a77209cefa63c7d64c504e7fa27",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17134.829"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 1049,
         "digest": "sha256:406130851b87b942ba1575b0ca2665e5a0cabd7b816b919d084d24615d96c214",
         "platform": {
            "architecture": "amd64",
            "os": "windows",
            "os.version": "10.0.17763.557"
         }
      }
   ]
}
```

I want to select the bottom Windows digest in a `copy` but it is currently impossible to either select by digest or to select by `os.version` and the middle digest is selected instead.
```bash
skopeo copy --override-os windows --override-arch amd64 docker://mcr.microsoft.com/k8s/core/pause:1.2.0 docker-archive:/tmp/windows.tar
```

**Comment by mtrmac** [comment]
Thanks for your report.

How does that fail? I would expect `skopeo copy docker://mcr.microsoft.com/k8s/core/pause@sha256:406130851b87b942ba1575b0ca2665e5a0cabd7b816b919d084d24615d96c214 …` to work just fine.

**Comment by bagnaram** [comment]
You are right! I didn't realize that is supported in `docker-reference` syntax. We can consider adding to the mans page

**Comment by mtrmac** [comment]
https://github.com/containers/image/blob/master/docs/containers-transports.5.md#dockerdocker-reference discusses tags vs. digests fairly extensively, and skopeo(1) already points to that man page. Is there some other place where that needs to go?
