### ISSUE TITLE
skopeo sync always changes the time stamp on the destination registry

### ISSUE THREAD

**Issue by samdoran** [containers/skopeo#1134]
When running `skopeo sync` the last modified timestamp on the target registry is always updated even if no new blobs were copied.

From looking at the debug output, it looks like the manifest is always written. I'm not sure if that is what is causing the timestamps to always be updated. I don't know much about the inner workings of container registries.

I also double checked to make sure I was using the blob info cache. That did not make any difference in the timestamps changing.

```
Copying blob 6a5697faee43 [--------------------------------------] 0.0b / 0.0b
DEBU[0263] Downloading /v2/library/ubuntu/blobs/sha256:d70eaf7277eada08fca944de400e7e4dd97b1262c06ed2b1011500caa4decaf1
DEBU[0263] GET https://registry-1.docker.io/v2/library/ubuntu/blobs/sha256:d70eaf7277eada08fca944de400e7e4dd97b1262c06ed2b1011500caa4decaf1
DEBU[0264] No compression detected
DEBU[0264] Using original blob without modification
DEBU[0264] Checking /v2/bedrock/ubuntu/blobs/sha256:d70eaf7277eada08fca944de400e7e4dd97b1262c06ed2b1011500caa4decaf1
DEBU[0264] HEAD https://quay.io/v2/bedrock/ubuntu/blobs/sha256:d70eaf7277eada08fca944de400e7e4dd97b1262c06ed2b1011500caa4decaf1
DEBU[0264] ... already exists
Copying config d70eaf7277 [======================================] 3.3KiB / 3.3KiB
Writing manifest to image destination
DEBU[0264] PUT https://quay.io/v2/bedrock/ubuntu/manifests/focal-20201008
```

### Steps to reproduce

Run `skopeo sync  --src docker --dest docker  docker.io/nginx quay.io/[some repo you can write to]` two times.

**Expected results**

On the second run, no new blobs are copied and the last modified timestamp on the destination repo are not changed.

**Actual results**

Every time `skopeo sync` is run, the timestamp of _all_ tags are updated. `skopeo sync` should not be changing the timestamp of tags that do not change.

**Comment by mtrmac** [comment]
Thanks for your report.

I expect that will change with https://github.com/containers/skopeo/issues/1021 / https://github.com/containers/image/pull/1041 .

**Comment by samdoran** [comment]
Very nice!

**Comment by samdoran** [comment]
With `skopeo` 1.2.3 the timestamps are no longer updated unless the tag is changed. Thanks for the fix!
