### ISSUE TITLE
some man pages are missing from containers-common deb package

### ISSUE THREAD

**Issue by ybelleguic** [containers/skopeo#1139]
Hello,

I'm not sure if this is the right place to submit this issue but I couldn't find any repo related to the debian packaging of this project.
The `dpkg-deb --info containers-common_1.2.0\~7_all.deb` indicates this project as the project homepage.

I'm running Ubuntu 18.04 and using `deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /` apt source entry.

At the end of the `man podman`, we can read : 
```
SEE ALSO
       containers-mounts.conf(5), containers-registries.conf(5), containers-storage.conf(5), buildah(1),
       containers.conf(5), oci-hooks(5), containers-policy.json(5), crun(8), runc(8), subuid(5), subgid(5),
       slirp4netns(1)
```

But, when I run the command `man containers-storage.conf` or `man 5 containers-storage.conf`, I've got an error message saying there is no entry for containers-storage.conf

The file `/etc/containers/storage.conf` is provided by the `containers-common` package, so I think the man page should be also included in this package.

**Comment by vrothberg** [comment]
Thanks for reaching out!

@lsm5 PTAL

**Comment by rhatdan** [comment]
Yes containers-common should install that file.

On fedora

$ rpm -ql containers-common
/etc/containers
/etc/containers/certs.d
/etc/containers/containers.conf
/etc/containers/oci
/etc/containers/oci/hooks.d
/etc/containers/policy.json
/etc/containers/registries.conf
/etc/containers/registries.conf.d
/etc/containers/registries.conf.d/shortnames.conf
/etc/containers/registries.d
/etc/containers/registries.d/default.yaml
/etc/containers/storage.conf
/usr/share/containers
/usr/share/containers/containers.conf
/usr/share/containers/mounts.conf
/usr/share/containers/seccomp.json
/usr/share/man/man5/containers-auth.json.5.gz
/usr/share/man/man5/containers-certs.d.5.gz
/usr/share/man/man5/containers-mounts.conf.5.gz
/usr/share/man/man5/containers-policy.json.5.gz
/usr/share/man/man5/containers-registries.conf.5.gz
/usr/share/man/man5/containers-registries.conf.d.5.gz
/usr/share/man/man5/containers-registries.d.5.gz
/usr/share/man/man5/containers-signature.5.gz
/usr/share/man/man5/containers-storage.conf.5.gz
/usr/share/man/man5/containers-transports.5.gz
/usr/share/man/man5/containers.conf.5.gz
/usr/share/rhel/secrets
/usr/share/rhel/secrets/etc-pki-entitlement
/usr/share/rhel/secrets/redhat.repo
/usr/share/rhel/secrets/rhsm
/var/lib/containers/sigstore

**Comment by lsm5** [comment]
This will be fixed by the new standalone `containers-common` package on the Kubic Testing repo, https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/containers-common . I don't wanna push it to kubic stable repo until we're ready to release podman v3.0.0.

**Comment by lsm5** [comment]
should be fixed with the latest containers-common on kubic testing and stable projects. Please reopen if issue persists.
