### ISSUE TITLE
Skopeo copy: "Error creating signature: No SmartCard daemon"

### ISSUE THREAD

**Issue by krishnakumar27** [containers/skopeo#1147]
We have a build which copies and signs a list images from one container registry to another using `skopeo copy`.

It was working well for over a month till yesterday when I started getting the below error sporadically. It happens for a different image everytime I run the build.

```
level=fatal msg="Error creating signature: No SmartCard daemon"
``` 

scdaemon and gpg2 are installed in our build container and I can verify the card status using `gpg2 --card-status` and it looks correct during the build time. 

Using `--debug` didn't give me any additional error details... 

Skopeo version in use: `1.2.0`

**Comment by mtrmac** [comment]
Thanks for your report.

AFAIK the code is not doing anything special at all to configure GPG; I’m afraid I can’t suggest anything other than generic GPG troubleshooting and maybe https://gnupg.org/documentation/manuals/gpgme/Debugging.html#Debugging .

**Comment by mtrmac** [comment]
@krishnakumar27 Did you diagnose the failure? Is there anything that needs to be changed in Skopeo?

**Comment by krishnakumar27** [comment]
@mtrmac I was trying to sign multiple images (~50) in parallel using skopeo. The scdaemon was not available when multiple instances were trying to access it concurrently. Sequential signing worked. I don't think this is an issue with Skopeo. I can close this issue.

**Comment by mtrmac** [comment]
Thanks for the confirmation!
