### ISSUE TITLE
copying already pulled docker image to oci format 

### ISSUE THREAD

**Issue by gtrani** [containers/skopeo#1155]
This is what i currently do to convert to oci format:
`skopeo copy docker://redis:latest oci:redis:latest`
But it copies directly from docker repository, How can i convert an image to oci format which already exist on my machine and can been seen on running command `docker images`?

**Comment by mtrmac** [comment]
Use a `docker-daemon:` source, maybe `docker-daemon:redis:latest` .

**Comment by mtrmac** [comment]
@gtrani can you confirm that `docker-daemon:` works, please?

**Comment by gtrani** [comment]
@mtrmac Yes, as far as i remember it worked. Thanks.

**Comment by mtrmac** [comment]
Great, thanks for the confirmation.
