### ISSUE TITLE
skopeo inspect repo:latest to provide tag behind latest

### ISSUE THREAD

**Issue by Benjipede** [containers/skopeo#1160]
What I ultimately want is to look up the latest tag/version of an image, ideally remote. If you are not going to implement this, I would be grateful for some guidance of how to do it myself.

I have observed that `docker inspect repo` reports all tags, while `docker inspect repo:tag` reports only tag. Unfortunately, using tag=latest gives you 'latest' instead of what you obviously want. As far as I can see `skopeo inspect` reports all tags no matter what.

**Comment by mtrmac** [comment]
Could you be more precise about the expected inputs and inputs, please? If you ask about `repo:latest`, it seems natural for the output to be related to `repo:latest`, not some other tagged image.

If you are looking for some kind of version number, and want the highest one, or perhaps the most-recently-built one even if it is not the highest, note that tags are more or less free-form strings with no semantics, so there isn’t a way to order them automatically (but you can of course sort them based on conventions in your build process).

Just guessing, you might want `skopeo list-tags` + some custom sorting/scripting, or perhaps make the version number of an image available in the image config as a label, and then use `skopeo inspect $repo:latest` to see a label value.

**Comment by tonyplovich** [comment]
To jump in here, it'd be nice to be able to point Skopeo at a rolling tag like latest, and pull / list all the tags associated with it.  I'd use this as an easy, uniform way of syncing images to my private registry.

Typically, when you're syncing repositories you want to pull an image's versioned tags so you can easily switch between them in your environment.  Like if a new version breaks something, you can roll back the the previous one.

What would make something like this useful is that you can use the same script for every image.  It wouldn't need to be aware of the versioning scheme they use.

**Comment by rhatdan** [comment]
Are you looking for something that does

```
$ podman search --format '{{ .Name }}' docker.io/library
docker.io/library/node
docker.io/library/python
docker.io/library/redis
docker.io/library/mongo
docker.io/library/nginx
docker.io/library/postgres
docker.io/library/openjdk
docker.io/library/busybox
docker.io/library/wordpress
docker.io/library/golang
docker.io/library/alpine
docker.io/library/httpd
docker.io/library/mysql
docker.io/library/mariadb
docker.io/library/ubuntu
docker.io/library/traefik
docker.io/library/rabbitmq
docker.io/library/memcached
docker.io/library/nextcloud
docker.io/library/php
docker.io/library/haproxy
docker.io/library/docker
docker.io/library/ruby
docker.io/library/tomcat
docker.io/library/debian
```
And then does a list-tags on each of these images, and pulls all of the tags?

**Comment by mtrmac** [comment]
> To jump in here, it'd be nice to be able to point Skopeo at a rolling tag like latest, and pull / list all the tags associated with it.

If that means “all tags that point to the same image”, that’s only possible to do in a way that places a fair load on the server, compare #1084 .

**Comment by mtrmac** [comment]
Alternatively, if it is possible to affect how the images are built (which is admittedly not very often the case):
> make the version number of an image available in the image config as a label, and then use `skopeo inspect $repo:latest` to see a label value.

Either way, I’m afraid handling some specific semantics of the tag strings will almost certainly require some custom scripting.
