### ISSUE TITLE
c/common in the release-1.2 branch needs to be bumped

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/skopeo#1166]
containers/common in the versions of Buildah and Podman have been bumped to v0.33.1.  I believe the version in the release-1.2 branch also needs to be bumped (maybe the other c/* projects too?) and a Skopeo 1.2.2 release created for RHEL 8.4.

**Comment by mtrmac** [comment]
I think that’s #1164 , which needs https://github.com/containers/skopeo/pull/1164#issuecomment-760915217 .

**Comment by lsm5** [comment]
Closing. release-1.2 and v1.2.2 have v0.33.4 and master has v0.34.0.
