### ISSUE TITLE
Making the tls-verify flag visible

### ISSUE THREAD

**Issue by xocasdashdash** [containers/skopeo#1170]
Right now the tls-verify flag is never shown when you use "-h" on any subcommand even though it's not defined as hidden on the subcommands (login, inspect, list-tags). 

This is because the same flag is defined twice as a persisten flag  (and mark as [hidden](https://github.com/containers/skopeo/blob/efc0170ee8d590407df38b9ccbe5916eb11b18ce/cmd/skopeo/main.go#L57) ) and as a flag of the subcommands ([here](https://github.com/containers/skopeo/blob/efc0170ee8d590407df38b9ccbe5916eb11b18ce/cmd/skopeo/login.go#L32) for login).

If the global flag were to be removed and we only kept the definitions on the subcommands, everything would work as is and the flag would show up on them. I already have working code, but I wanted to reach out before opening up a PR. 

Is this something you're open to include?

**Comment by mtrmac** [comment]
Thanks for your report.

Removing that flag and breaking possible existing users is not a very attractive trade-off. Isn’t this ultimately a bug in the Cobra package that could, in principle, be fixed?

**Comment by xocasdashdash** [comment]
My understanding from cobra persistent flags is that they are supposed to be shared and available on all subcommands. I haven't found any option to override a flag from a subcommand, i do not believe it's possible because subcommands are created independently from the root command ([here](https://github.com/containers/skopeo/blob/efc0170ee8d590407df38b9ccbe5916eb11b18ce/cmd/skopeo/main.go#L75)).  

From my tests, if the flag is removed from the root command and it's kept on the subcommands (it already is), everything is working as usual without breaking anything. If this were the case, do you think it could be removed?

**Comment by mtrmac** [comment]
Oh, I might be thinking in terms of the previous CLI package, where the separation between the global/subcommand flags was stronger (in particular, the flag position vs. the subcommand name mattered).

---

Look at `skopeo copy` and `skopeo sync`: They have a source- and destination- specific TLS verify option, and the universal `--tls-verify` is not specific about intent an probably turning off more security than necessary, something we _don’t_ want to provide as a non-deprecated option. Just removing the global flag would break existing users of the deprecated variant for these two commands.

---

We really _do have_ two different `--tls-verify` flags: One visible and non-deprecated, one hidden and causing a warning when used. And we don’t know which one we got until the subcommand is specified. This could probably be restructured if we ~give up on the global/local flag distinction, which is somewhat meaningless for a hidden flag nowadays; but it would not be an one-line change.

**Comment by xocasdashdash** [comment]
Yeah, I see it now. The change would basically be moving the global tls-verify option to each sub-command right? 

I've raised the issue, because while using the skopeo docker image if execute "docker run --rm quay.io/skopeo/stable login -h", you don't really see the tls verify options. This does not happen on sync or copy because the "src-tls-verify" and "dest-tls-verify" flags show up. 

Another option would be keeping the deprecated tls-verify and adding a new flag to the subcommands that need this operation (login, list-tags and inspect at least). What do you think?

**Comment by mtrmac** [comment]
A differently-named flag would IMHO be even more confusing than the current status.

**Comment by xocasdashdash** [comment]
I'm gonna open up an issue on cobra to see if there's a clean way of modifying if a flag is hidden depending on the subcommand.

**Comment by mtrmac** [comment]
This was fixed in #1369; please reopen if there is still something wrong with the current behavior.
