### ISSUE TITLE
Login subcommand not part of skopeo

### ISSUE THREAD

**Issue by Siddsouza19** [containers/skopeo#1177]
Skopeo login command not part of the skopeo package. It doesn't reflect in the skopeo --help also.

![skopeo_login](https://user-images.githubusercontent.com/19501855/106238296-9b607000-6226-11eb-8e1e-0e05fae443b4.png)

**Comment by vrothberg** [comment]
Your version of Skopeo is _very_ old (0.2.0). The latest release is (1.2.0). If you want `login`, please use a more recent version.
