### ISSUE TITLE
Your a goofy site!

### ISSUE THREAD

**Issue by rukklespc** [containers/skopeo#1181]
Why is everybody running to you?Redhat says they have skopeo,only to send me to you.
There doesn't seem to be a download button,and I find your site obtuse! Ps,I downloaded a copy of github to my windoz box,only to find it useless,so I had to delete it from my registry!
Also a lot of other site reference you,but you don't have the dam download button!

**Comment by vrothberg** [comment]
We don't appreciate foul language or behavior in this community.  I am going to close and lock this issue.

If you want to interact, please remain polite.
