### ISSUE TITLE
support copying to compressed tarballs

### ISSUE THREAD

**Issue by ktdreyer** [containers/skopeo#1200]
Can we support writing compressed tarballs?

For example, this writes a large uncompressed tarball:
```
skopeo copy docker://registry.example.com/myrepo:latest  docker-archive:mycontainer.tar
```

It would be great to support `--dest-compress`, like
```
skopeo copy docker://registry.example.com/myrepo:latest  --dest-compress docker-archive:mycontainer.tar.gz
```

**Comment by rhatdan** [comment]
I think it would be better to have it output to stdout 

A quick hack

skopeo copy docker://alpine:latest  docker-archive:/dev/stdout | gzip mycontainer.tar.gz

But this does not work.

I think the best we can do for now is just

skopeo copy docker://registry.example.com/myrepo:latest  docker-archive:mycontainer.tar; gzip mycontainer.tar

But I don't see a reason to build any direct compression into skopeo.

**Comment by ktdreyer** [comment]
Thanks Dan.

For context, the reason I opened this ticket is that OSBS stores compressed tarballs in Koji, https://github.com/containerbuildsystem/atomic-reactor/issues/191 . There's been some discussion about that feature, and possibly updating OSBS handle archiving differently. If OSBS does not compress and archive images like that, users must use skopeo to download and archive all images uncompressed.

**Comment by ktdreyer** [comment]
Note `podman save` does have a `--compress` flag, for example:

```
podman save --compress -o BZ1234567-v1.tar.gz --format oci-archive registry.example.com/example:bz1234567-v1
```

**Comment by vrothberg** [comment]
I recommend using `podman save` as mentioned above. Unless there is no other way, I prefer to not have transport-specific options for transport-generic commands.
