### ISSUE TITLE
skopeo does not list only the tags aginst the supplied SHA value, instead it gives list of all the tags of the image

### ISSUE THREAD

**Issue by dinesh14nish** [containers/skopeo#1208]
I do have 2 tags (1.0 and 2.0) in the image "dinesh14/linux_tweet_app", SHA value of TAG 2.0 is "sha256:2711012c816eed226c8f43634a99efe7698a7b794f1edfbc1c90daaccb4ddf27" and SHA of TAG 1.0 is "sha256:869f1a714f3401ce1947301ec2b5c47a070b05faf3a33b220861b99c22993b76"

when i do perform skopeo inspect for the 2.0 tag SHA valueas per below command, i expect to get only TAG value "2.0" not both "1.0" and 2.0" but in output it is returning both the TAG values in "RepoTags" field. 

skopeo inspect docker://dinesh14/linux_tweet_app@sha256:2711012c816eed226c8f43634a99efe7698a7b794f1edfbc1c90daaccb4ddf27

{
    "Name": "docker.io/dinesh14/linux_tweet_app",
    "Digest": "sha256:2711012c816eed226c8f43634a99efe7698a7b794f1edfbc1c90daaccb4ddf27",
    "RepoTags": [
        "1.0",
        "2.0"
    ],
    "Created": "2018-05-18T14:00:16.083035039Z",
    "DockerVersion": "17.12.0-ce",
    "Labels": {
        "maintainer": "NGINX Docker Maintainers \u003cdocker-maint@nginx.com\u003e"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:f2aa67a397c49232112953088506d02074a1fe577f65dc2052f158a3e5da52e8",
        "sha256:3c091c23e29d0ddfc902b0be63b1a08a853ef39973f92fab39ad1727eac012bf",
        "sha256:4a99993b863683bef1c776732e14d2372f6ed52b48e94783f4a1b58af289db07",
        "sha256:3ba11aaafc53a1d18c51fa4c84637b9ee8ee6066a44ba00ebc31ee75d976d8c8",
        "sha256:8f236c0ddff963297a921aea98eb5d264654dbd9eba7fdf88c269fb7740989ff"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "NGINX_VERSION=1.13.12-1~stretch",
        "NJS_VERSION=1.13.12.0.2.0-1~stretch"
    ]
}

**Comment by narendrachoudhary** [comment]
Yes i also check and same issue persist for me also

**Comment by vrothberg** [comment]
Thanks for reaching out!  I understand the expectation but I fear there's nothing Skopeo can do.  The distribution spec doesn't allow for exploring tags like but  only allows for listing the tags of the entire repository [1]. In this case, `foo@digest`, `foo@tag1` and `foo@tag2` will all yield the same results in `skopeo inspect`.

[1] https://docs.docker.com/registry/spec/api/#listing-image-tags

**Comment by mtrmac** [comment]
FWIW this will be better documented in #1555 .
