### ISSUE TITLE
Configurable user-agent

### ISSUE THREAD

**Issue by shlevy** [containers/skopeo#1212]
We're using skopeo as part of end-to-end testing of our custom docker registry implementation, and we have some logic that depends on the user agent (specifically, some clients do not properly respect HTTP redirects). I'm not sure skopeo is meant as a testing tool, but if so it would be nice to be able to override the UA from the command line.

**Comment by mtrmac** [comment]
Thanks for your report.

The idea of User-Agent is to identify the client; it is less valuable if it is user-editable=unreliable.

The underlying containers/image library _does_ allow overriding the User-Agent value, so it should be quite easy to wrap it it with a test-only Go program that does exactly what you need.
