### ISSUE TITLE
Using workload identity to push images to GCR

### ISSUE THREAD

**Issue by yashbhutwala** [containers/skopeo#1214]
Can skopeo use workload identity to authenticate to GCR while pushing images from inside a container?

**Comment by JonathanRRogers** [comment]
Yes, it can via an credential helper. I use google-credential-gcr inside my Kubernetes cluster running on Google Kubernetes Engine. https://github.com/GoogleCloudPlatform/docker-credential-gcr

**Comment by vrothberg** [comment]
Thanks folks :)

**Comment by yashbhutwala** [comment]
Hi guys!  I did not find any documentation about this.  It'd be nice to add docs about how to get skopeo to use the credential helper before closing the issue at the very least.

**Comment by TomSweeneyRedHat** [comment]
Reopening to make sure we get the documentation piece covered.  Thanks for the poke @yashbhutwala !

**Comment by JonathanRRogers** [comment]
> Hi guys! I did not find any documentation about this. It'd be nice to add docs about how to get skopeo to use the credential helper before closing the issue at the very least.

AFAICT, skopeo uses credential helpers just like the docker client. Run "docker-credential-gcr configure-docker" to generate a configuration in "~/.docker/config.json". Everything specific to Google Container Registry is covered in the docker-credential-gcr documentation.

**Comment by vrothberg** [comment]
Using credhelpers is documented in `man containers-auth.json`.  I don't think there's any documentation work left to do.

@TomSweeneyRedHat I let you decide :)

**Comment by lsm5** [comment]
> Using credhelpers is documented in `man containers-auth.json`. I don't think there's any documentation work left to do.
> 
> @TomSweeneyRedHat I let you decide :)

@TomSweeneyRedHat can we close this?

**Comment by TomSweeneyRedHat** [comment]
Actually, I'll ping @yashbhutwala and see if they're happy with the doc.  We can close in 30 days if we don't hear back.

**Comment by rhatdan** [comment]
I prefer to go the otherway.  @yashbhutwala can reopen if they're are not happy.
