### ISSUE TITLE
Retry when EOF

### ISSUE THREAD

**Issue by paroque28** [containers/skopeo#1223]
Sometimes copying big images can be an issue depending on your connection.

```bash
INFO[4778] Copying image ref 2/4                         from="docker://***********:****" to="docker://***********:****"
Getting image source signatures
Copying blob 78bf9a5ad49e done
Copying blob 930bda195c84 done
Copying blob 92a4815b8fdc done
Copying blob f11b29a9c730 done
Copying blob 5bed26d33875 done
Copying blob 256327ca73ed done
Copying blob c06b616aa5c6 done
Copying blob efbf7d2f43fc done
Copying blob dae5c0fb39f7 done
Copying blob 7579c852e771 [================================>-----] 3.4GiB / 3.9GiB
FATA[6852] Error copying ref "docker://***********:****": Error writing blob: Patch "https://***********/blobs/uploads/5c3f5598-bf00-4617-bdec-7e88b14fc25c?_state=RkbqC1Z_6VVmhAljYz7Q7O6MoyipL2v1afNjPetTXaZ7Ik5hbWUiOiJ3ci1zdHVkaW8tcHJvZHVjdC92eHdvcmtzL2J1aWxkIiwiVVVJRCI6IjVjM2Y1NTk4LWJmMDAtNDYxNy1iZGVjLTdlODhiMTRmYzI1YyIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMS0wMy0xMVQwMDo0MjoxOC40OTg4OTE5MDlaIn0%3D": EOF
```

Is it possible to try if the first attempt failed?
If not, would you be open to the feature? I might have some time

**Comment by vrothberg** [comment]
Thanks for reaching out!

You can use the `--retry-times` flag for that.

**Comment by paroque28** [comment]
@vrothberg Does this option displays any output?
How can I test if it worked?
I disconnected my network adapter but I can't check if it worked.

**Comment by vrothberg** [comment]
> @vrothberg thanks for your quick response!
> Does this option display any output? How can I test that it worked?

Yes, it displays the same output as before but will restart the copy operation for certain errors. Some errors are fatal (e.g., when the image doesn't exist or when credentials are missing or wrong).

> I tried by disconnecting my network adapter but I can't check if it worked.

You can copy an image to a local directory:
```
$ mkdir test
# Change the ownership, so that a rootless user cannot write it to the directory
$ sudo chwon -R root:root test
# Now copy an image
~ $ skopeo copy --retry-times=20  docker://nginx dir:test
INFO[0000] Warning: failed, retrying in 1s ... (1/20)   
INFO[0001] Warning: failed, retrying in 2s ... (2/20)   
INFO[0003] Warning: failed, retrying in 4s ... (3/20)   
[...]
```

Note that I am going to close the issue but feel free to continue the conversation here.
