### ISSUE TITLE
About copy an image to oci storage path

### ISSUE THREAD

**Issue by yimin-zhao** [containers/skopeo#1229]
Hi, there
From the README file, it says skopeo supports to copy images from docker to the local oci storage path.
In my local machine, `/var/lib/containers/storage` is the path where crio used to storage images. I want to copy an image to this path, so I ran the following command, but after command completed, I cannot list the image files through `crictl images`. 
```
skopeo copy docker://registry.connect.redhat.com/hazelcast/hazelcast-3-rhel7 oci:/var/lib/containers/storage:registry.connect.redhat.com/hazelcast/hazelcast-3-rhel7
```
From my observation, the images list from `crictl images` are all saved in `/var/lib/containers/storage/overlay-images`.
The images fetch by skopeo are saved to `/var/lib/containers/storage/blobs/sha256`.
Am I misunderstanding the functionality of skopeo? Or did I do it in a wrong way?
Can anyone show me the correct way to get it done?

Thanks very much.

**Comment by nalind** [comment]
The format typically used in `/var/lib/containers/storage` isn't the one that's used for `oci:` locations.  Per the man page, `oci:` is for specifying an image tag in a directory compliant with "Open Container Image Layout Specification".
Provided that `/var/lib/containers/storage` is configured as the location in `/etc/containers/storage.conf` (it usually is), `containers-storage:registry.connect.redhat.com/hazelcast/hazelcast-3-rhel7:latest` is the destination name you would have specified for copying the image into the storage that CRI-O is using.

**Comment by yimin-zhao** [comment]
Cool, thanks for the clarification.
