### ISSUE TITLE
skopeo inspect does not work with public.ecr.aws: listing tags fails with 404 (Not Found)

### ISSUE THREAD

**Issue by paride** [containers/skopeo#1230]
Let's take https://gallery.ecr.aws/nginx/nginx as an example. The image is available at `public.ecr.aws/nginx/nginx:latest`, and indeed a `docker pull` works:

```
$ docker pull public.ecr.aws/nginx/nginx:latest
latest: Pulling from nginx/nginx
[...]
Digest: sha256:c63e27ebf8eb83d860155b926191b1b702e645797bc9e6f228d6b9b5a57282fa
Status: Downloaded newer image for public.ecr.aws/nginx/nginx:latest
public.ecr.aws/nginx/nginx:latest
```

however the image can't be inspected with skopeo:
```
$ skopeo inspect docker://public.ecr.aws/nginx/nginx:latest
FATA[0007] Error determining repository tags: Error fetching tags list: invalid status code from registry 404 (Not Found) 
```
same for `list-tags` (likely the underlying problem):
```
$ skopeo list-tags docker://public.ecr.aws/nginx/nginx
FATA[0001] Error listing repository tags: Error fetching tags list: invalid status code from registry 404 (Not Found) 
```
The same syntax works on `docker.io`:
```
$ skopeo list-tags docker://docker.io/nginx/unit
{
    "Repository": "docker.io/nginx/unit",
    "Tags": [
        "0.4-full",
[...]
```

**Comment by TomSweeneyRedHat** [comment]
@paride thanks for the note.  There's something that containers/image doesn't like about that registry when doing a search.  This isn't a skopeo problem, but a containers/image problem.

I'm seeing similar issues using Podman:

```
# podman search --list-tags public.ecr.aws/nginx/nginx
Error: error getting repository tags: Error fetching tags list: invalid status code from registry 404 (Not Found)
```

Yet a Podman build works:

```
# podman build -t tom .
STEP 1: FROM public.ecr.aws/nginx/nginx
Getting image source signatures
Copying blob 158aac73782c done  
Copying blob de58cd48a671 done  
Copying blob 6f28985ad184 done  
Copying blob be704f37b5f4 done  
Copying blob 29f7ebf60efd done  
Copying blob 879a7c160ac6 done  
Copying config 6084105296 done  
Writing manifest to image destination
Storing signatures
STEP 2: COMMIT tom
--> 6084105296a
6084105296a952523c36eea261af38885f41e9d1d0001b4916fa426e45377ffe
```

So I'm guessing the public.ecr/aws registry is not responding to the request that  c/image is sending it when asking for tags as something has changed within the registry code that's being used there?  The 404 is very suspicious.  @vrothberg any thoughts?

**Comment by sergiodj** [comment]
FWIW, I have been developing a set of scripts whose purpose overlaps a bit with what skopeo does, and I also noticed 404's when consulting public.ecr.aws.  Maybe their API is not fully functional yet?

**Comment by vrothberg** [comment]
This looks like an ECR error to me.  `skopeo copy` works, so it seems the API for listing tags is sick.  `docker search` is failing as well.

I suggest to reach out to ECR to resolve the issue. There is nothing we can do, unfortunately.

**Comment by raxod502** [comment]
Looks like this has been reported to AWS: https://github.com/aws/containers-roadmap/issues/1262

**Comment by mtrmac** [comment]
`list-tags` failing is a server-side issue; but this also breaks `skopeo inspect`, as reported in https://github.com/containers/skopeo/issues/785#issuecomment-846230503 . Let’s keep this open to track that.

Adding another workaround case to the existing code to not fail on 404 is easy enough, but enough is enough: let’s make that a proper Go value check instead of a substring match.

**Comment by mtrmac** [comment]
> Adding another workaround case to the existing code to not fail on 404 is easy enough, but enough is enough: let’s make that a proper Go value check instead of a substring match.

I’m building that in https://github.com/containers/image/pull/1299 .

**Comment by mtrmac** [comment]
FWIW there’s now a `skopeo inspect -n` = `skopeo inspect --no-tags` that will work around this failure.

Skopeo should work around this automatically, but that work isn’t done yet.

**Comment by mtrmac** [comment]
For permanent record, the error body as of today:
```
HTTP/1.1 404 Not Found
Connection: close
Content-Length: 65
Content-Type: application/json; charset=utf-8
Date: Tue, 06 Sep 2022 21:19:02 GMT
Docker-Distribution-Api-Version: registry/2.0

{"errors":[{"code":"NOT_FOUND","message":"404 page not found"}]}
```

**Comment by mtrmac** [comment]
#1522 should fix this … but in the meantime, the server has now added the tag list endpoint.
