### ISSUE TITLE
skopeo snap package outdated (unmaintained?)

### ISSUE THREAD

**Issue by paride** [containers/skopeo#1231]
The skopeo snap package (https://snapcraft.io/skopeo) is outdated and has no version published in the stable channel. The latest published version is dated 2019-04-14. I don't see the snap package mentioned in https://github.com/containers/skopeo/blob/master/install.md, so I guess it's not fully official, but as the snap maintainer is @lsm5 I hope we can still discuss it here :)

Is an update of the snap package planned? More in general, is the snap package still maintained?

Thanks!

**Comment by lsm5** [comment]
> The skopeo snap package (https://snapcraft.io/skopeo) is outdated and has no version published in the stable channel. The latest published version is dated 2019-04-14. I don't see the snap package mentioned in https://github.com/containers/skopeo/blob/master/install.md, so I guess it's not fully official, but as the snap maintainer is @lsm5 I hope we can still discuss it here :)
> 
> Is an update of the snap package planned? More in general, is the snap package still maintained?
> 
> Thanks!


Thanks @paride . I do remember registering the name, but I never pushed anything over there. I think the snap package was actually the work of @abitrolly.

@cevich @abitrolly do you have any current status of the skopeo snap package?

**Comment by cevich** [comment]
Nope, I wonder if it's even used.

**Comment by abitrolly** [comment]
No, its not mine. Mine was https://github.com/abitrolly/podman but because [`snapcraft` is poorly supported on Fedora](https://github.com/canonical/multipass/issues/1448) I do not pack anything to snaps anymore.

**Comment by lsm5** [comment]
Thanks @cevich @abitrolly 

@paride would you like to own this? We'll gladly help you any way we can :)

**Comment by paride** [comment]
@lsm5 I am not really experienced with snap packaging, but this could be the right excuse to start maintaining one. I'll experiment a bit and comment back here once I have something functional.

**Comment by lsm5** [comment]
@paride great, I'll assign this to you. No pressure and no rush :) . Please keep us posted either way. Thanks a lot!

**Comment by cevich** [comment]
@paride please feel free to poke me if you need anything from an automation perspective.

**Comment by lsm5** [comment]
@paride hello, are you working on this issue?

**Comment by paride** [comment]
Hi @lsm5, I still plan to work on this, but I didn't get around to it yet. If you want to reassign this please go ahead :)

**Comment by lsm5** [comment]
> Hi @lsm5, I still plan to work on this, but I didn't get around to it yet. If you want to reassign this please go ahead :)

@paride no worries, that's totally cool. Take your time, thanks :)

**Comment by lsm5** [comment]
@paride i'm closing this issue for now, whenever you have the time to work on this, please let us know and we can reopen this. Thanks.
