### ISSUE TITLE
skopeo copy multiarch docker from Artifactory to ECR issue

### ISSUE THREAD

**Issue by slamd64** [containers/skopeo#1236]
Hello!
I have strange issue with skopeo to ECR multiarch

![artifactory-source](https://user-images.githubusercontent.com/37698552/113023699-940a0400-918e-11eb-9caa-e5318039be55.PNG)

In Artifactory it looks OK:
0.3.11 - contains list.manifest.json
0.3.11-amd64 - AMD64 image
0.3.11-arm64 - ARM64 image

But after

skopeo --override-os --override-arch copy --all --src-creds ${TASK_SOURCE_USER}:${TASK_SOURCE_PASS} --dest-creds ${REGISTRY_USER}:${REGISTRY_PASS} docker://${TASK_SOURCE_REGISTRY}${FINAL_FROM}:${FINAL_TAGS} docker://${TASK_TARGET_REGISTRY}${FINAL_TO}:${FINAL_TAGS}

![ecr-destination](https://user-images.githubusercontent.com/37698552/113023697-93716d80-918e-11eb-99ea-d12ec5936d56.PNG)

0.3.11 - contains something strange. I think list.manifest.json _AND_ AMD64 image (by size)
"untagged" - I think this is ARM64.

**Comment by TomSweeneyRedHat** [comment]
IDK, but a quick offhand guess is you've spotted another issue with ECR.  They are currently having problems with tags (https://github.com/containers/skopeo/issues/1230) and I wouldn't be surprised if this is on their side too.  Have you tried this to DockerHub or another registry?  If it works somewhere else, it points the finger further at ECR.

**Comment by mtrmac** [comment]
@slamd64 Is this still relevant?

FWIW `0.3.11-amd64` / `0.3.11-armd64` is some tag convention that is irrelevant to Skopeo; Skopeo does not have any concept of “related tags” like that.

The quoted command with `${FINAL_TAGS}` does not actually say what you were telling Skopeo to copy. If the command was copying `0.3.11`, I would expect the destination to contain a `0.3.11` tag with a multi-arch image (and pre-existing `0.3.11-amd64`/`0.3.11-arm64` tags, if any, to not be affected at all, and to continue to point to whatever they were pointing to previously).
