### ISSUE TITLE
skopeo copy: problem finding where signatures are stored

### ISSUE THREAD

**Issue by darrenfoong** [containers/skopeo#1250]
I am running skopeo 1.2.2 on Debian testing, and I am trying to sign images, following this [document](https://www.openshift.com/blog/signing-and-verifying-container-images). I ran the following command as non-root:

```
$ skopeo copy --sign-by <my e-mail address> docker-daemon:hello-world:latest containers-storage:hello-world:latest-signed
Getting image source signatures
Copying blob af0b15c8625b done  
Copying config fce289e99e done  
Writing manifest to image destination
Signing manifest
Storing signatures
```

1. The signatures are supposed to be stored in `/var/lib/containers/sigstore`, but this directory did not exist on my machine.
2. The configuration is supposed to be stored in `/etc/containers/registries.d`, but this directory did not exist too.
3. Adding the `--debug` switch did not produce any additional clues.
4. I created [default.yaml](https://github.com/containers/skopeo/blob/master/default.yaml) in `/etc/containers/registries.d` (which I created manually), but it did not help.
5. I created `default.yaml` in `$HOME/.config/containers/registries.d` (which I created manually, referencing [this document](https://github.com/containers/image/blob/master/docs/containers-registries.d.5.md)), but it did not help.
6. A `find` on my machine did not find any `sigstore` directory.
7. Using the `--registries.d` switch to point to `/etc/containers/registries.d` did not work either. In fact, I could indicate a non-existent directory and the command would still run without validating the existence of the directory.

How can I find whether the signatures are stored? What is the default behaviour if there is no configuration? According to this [document](https://github.com/containers/image/blob/master/docs/containers-registries.d.5.md),

> If no docker section can be found for the container image, and no default-docker section is configured, the default directory, /var/lib/containers/sigstore for root and $HOME/.local/share/containers/sigstore for unprivileged user, will be used for reading and writing signatures.

**Comment by mtrmac** [comment]
Thanks for your report.

https://github.com/containers/image/blob/master/docs/containers-registries.d.5.md and https://github.com/containers/image/blob/master/docs/signature-protocols.md describe to storing signatures _in registries_. `containers-storage:` is not a registry, so those documents are not applicable.

The signatures actually exist as metadata recorded along with the image, under `/var/lib/containers` or `~/.local/share/containers` or whatever you have configured c/storage to use. You should be able to verify the signatures exist by using `skopeo copy containers-storage:hello-world:latest-signed dir:some-temp-dir` and examining the signatures there.

Note that the created signature signs the image _as it is present in local `containers-storage:`_, i.e. uncompressed. I’d expect such signatures to cause pushes to registry to preserve the uncompressed form, using unnecessary storage and bandwidth. It usually makes more sense to sign the image only when pushing to a registry (compressing the layers in the process).

**Comment by darrenfoong** [comment]
Thank you for the explanation! It makes sense now. I'll test against registries instead of `containers-storage`.
