### ISSUE TITLE
RFE: copy: add command-line override of containers-storage rootdir

### ISSUE THREAD

**Issue by edsantiago** [containers/skopeo#1254]
The setup: I've got podman running with `--root /some/nonstandard/root`. I would like to:
```console
$ skopeo copy --root /some/nonstandard/root containers-storage:myimage oci-archive:/tmp/foo.tar`
```
I do not see any way to do this other than overriding `containers-storage.conf` (which I also don't see any way to do, but I haven't looked closely).

**Comment by vrothberg** [comment]
The `containers-storage` transport supports that (see `man containers-transports`). The format is `containers-storage:[[storage-specifier]]{image-id|docker-reference[@image-id]}` with `storage-specifier` being `[[driver@]root[+run-root][:options]]` (which allows for overriding the storage.conf defaults).

An example is `[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@6dbb9cc54074106d46d4ccb330f2a40a682d49dda5f4844962b7dce9fe44aaec`
