### ISSUE TITLE
v1.2.3 docker image?

### ISSUE THREAD

**Issue by jess-belliveau** [containers/skopeo#1255]
Hello, I'm wondering when the docker image for the tagged release 1.2.3 will be available?
https://quay.io/repository/skopeo/stable?tab=tags

It seems latest was built/pushed recently but still reports 1.2.2
```
➜ docker run quay.io/skopeo/stable:latest -v
skopeo version 1.2.2
```

**Comment by vrothberg** [comment]
@TomSweeneyRedHat PTAL

**Comment by samdoran** [comment]
It would also be nice to have tags for v1.2.1 and v1.2.2. The latest tag is currently v1.2.0 and I would like to use a newer version of `skopeo` without having to use `latest`.

**Comment by samdoran** [comment]
It actually looks like the v1.2.0 image actually has `skopeo` 1.2.2, though the images do have different hashes.

```
> docker image inspect quay.io/containers/skopeo:v1.2.0 -f '{{join .RepoDigests ", "}}'
quay.io/containers/skopeo@sha256:f13b21b67066d451881f65675ca8b0b55dc69cb1637a0e8a03a4fa5106d7781e

> docker image inspect quay.io/containers/skopeo:latest -f '{{join .RepoDigests ", "}}'
quay.io/containers/skopeo@sha256:0ec6e3bc99478f74c5f2f6b094d65f42580d52276246f91f9bf2ef1df335491f

> docker run --rm quay.io/containers/skopeo:v1.2.0 -v
skopeo version 1.2.2

> docker run --rm quay.io/containers/skopeo:latest -v
skopeo version 1.2.2
```

**Comment by lsm5** [comment]
@TomSweeneyRedHat where are the build scripts or whatever for the image located? Wondering if this can be part of release tagging / CI job?

**Comment by TomSweeneyRedHat** [comment]
Sorry for  the delay on this, I've been looking for a good hour to sit down and work through this, but haven't yet.  Still on the Radar. 
The problem  in the past has been that the Skopeo kits hadn't been promoted to Stable on bodhi, I'm not sure if that's still the case here.  

The images these days are created via the CI and the Dockerfiles that create them can be found [here](https://github.com/containers/skopeo/tree/master/contrib/skopeoimage)

**Comment by lsm5** [comment]
> The problem in the past has been that the Skopeo kits hadn't been promoted to Stable on bodhi, I'm not sure if that's still the case here.

f34 is set to land in stable, I have re-triggered gating tests on f33. I wasn't aware the container images depended on the rpms.

> 
> The images these days are created via the CI and the Dockerfiles that create them can be found [here](https://github.com/containers/skopeo/tree/master/contrib/skopeoimage)

Thanks, is it worth adding maybe another image which gets a statically built skopeo or something which doesn't depend on the skopeo rpm?

**Comment by TomSweeneyRedHat** [comment]
Thanks, is it worth adding maybe another image which gets a statically built skopeo or something which doesn't depend on the skopeo rpm?

We've the upstream and testing repos, but most people want the stable branch with a version.  I don't think we should create a `stable:{version}` container image until it at least gets through the bodhi process.

**Comment by lsm5** [comment]
@TomSweeneyRedHat v1.2.3 is in stable on f34 and set to land in f33 stable in the next 24 hrs (hopefully).

**Comment by samdoran** [comment]
It looks like `skopeo` 1.2.3 is available in an image now... but it's not the one you'd expect. 😉 

And there are still no tags (at least in [Quay](https://quay.io/repository/containers/skopeo?tab=tags)) for v1.2.1 - 1.2.3

```
> docker image inspect quay.io/containers/skopeo:latest -f '{{.RepoDigests}}'
[quay.io/containers/skopeo@sha256:7958f3df4822839eac06966141355b931f1fbc6bb63fced9dd0d34089af37ddc]

> docker image inspect quay.io/containers/skopeo:v1.2.0 -f '{{.RepoDigests}}'
[quay.io/containers/skopeo@sha256:da0c8bb49b5e22419961768a08b5c67534e56a8df1f03d93036d4e4c72cc4035]

> docker run --rm quay.io/containers/skopeo:latest -v
skopeo version 1.2.2

> docker run --rm quay.io/containers/skopeo:v1.2.0 -v
skopeo version 1.2.3
```

**Comment by TomSweeneyRedHat** [comment]
@jess-belliveau I'd like to keep this open and swing the focus onto the ongoing build issue.  Thanks again for the heads up and sorry for the tardy response.

**Comment by cevich** [comment]
Thanks, this is on my radar since I want to port the github-action we use for buildah and podman, over here.  I'll poke at the dockerfiles at that time.
