### ISSUE TITLE
Automating the  gpg  Passphrase for signing images in pipelines

### ISSUE THREAD

**Issue by akshaykumar-vijapur** [containers/skopeo#1261]
Hi team,

I am using this `gpg2 --pinentry-mode=loopback  --passphrase ***  --import private.key`  to automatically load the privatekey into keyring without user intervention for password. 

I am trying to sign the images using the Skopeo 
```
 skopeo copy docker://"${image}" docker://"${image}" --dest-creds iamapikey:"${CLOUD_API_KEY}" --src-creds iamapikey:"${CLOUD_API_KEY}" --sign-by "signer@company.com"
```

This is able to sign my image correctly. But it is asking password in the prompt. Is there any way I can automate this password entering in Skopeo?

**Comment by TomSweeneyRedHat** [comment]
@akshaykumar-vijapur which password is it prompting you for? For the registry server that you're copying to?  If so, can you do a `skopeo login` to there first?  Or is it a credentials getting requested from you gpg2?

**Comment by akshaykumar-vijapur** [comment]
@TomSweeneyRedHat It is not about registry. I'm taking about  GPG password prompt which will be prompted to enter GPG password which was used to create the GPG keys. 

That prompt can be overridden by using this command 
```
gpg2 --pinentry-mode=loopback --passphrase *** 
```

But not sure weather this is supported by `skopeo copy`.

**Comment by TomSweeneyRedHat** [comment]
Thanks, @akshaykumar-vijapur for the info.  I don't believe there's a way to do that yet but sounds like a nice RFE if not.

**Comment by akshaykumar-vijapur** [comment]
@TomSweeneyRedHat  Please let me know if I need to open another issue for this RFE ?

**Comment by rhatdan** [comment]
@akshaykumar-vijapur Interested in opening a PR to make this happen?

**Comment by TomSweeneyRedHat** [comment]
@akshaykumar-vijapur no need for an additional issue, I'll just note RFE in the title for this one and will label it so.

**Comment by akshaykumar-vijapur** [comment]
Any timeline for this feature ?

**Comment by mtcolman** [comment]
Hi, we are hitting this limitation too...

**Comment by mtcolman** [comment]
You can provide it with `skopeo copy <params/flags> | cat /path/to/password.txt` however the password will show on screen.

**Comment by mtcolman** [comment]
Linking to this issue: https://github.com/containers/image/issues/1303

**Comment by mtcolman** [comment]
Hi, a colleague (@SionArtingstall) and I have finally found a way round this issue:

Firstly install these two packages:
```
yum install expect spawn -y
```

Then run the following to use passphrase from file:
```
expect -c "
spawn skopeo copy --debug --sign-by none@fake.com docker://path/to/image:123 docker://path/to/image:456 --authfile auth.json
expect \"Passphrase: \"
sleep 3
send \"$(cat /path/to/password.txt)\n\"
interact
"
```

or provide as ENV variable:
```
expect -c "
spawn skopeo copy --debug --sign-by none@fake.com docker://path/to/image:123 docker://path/to/image:456 --authfile auth.json
expect \"Passphrase: \"
sleep 3
send \"$MY_PASSPHRASE\n\"
interact
"
```

Obviously the cleaner way is if skopeo enabled us to send passphrase through like gpg does...

**Comment by akshayvijapur** [comment]
@TomSweeneyRedHat Any timelines for this issue. Need this badly!

**Comment by TomSweeneyRedHat** [comment]
@akshaykumar-vijapur no current timeline.  Will see if we can someone to take a look see.

**Comment by mtrmac** [comment]
PRs would be welcome, of course.

**Comment by rmallam** [comment]
Any progress on this issue please?

**Comment by TomSweeneyRedHat** [comment]
Thanks for the nudge @rmallam https://github.com/containers/skopeo/pull/1540 WIP PR that will hopefully address the issue.

**Comment by akshayvijapur** [comment]
@TomSweeneyRedHat Pls see https://github.com/containers/skopeo/pull/1540#discussion_r787837813

**Comment by rmallam** [comment]
> Thanks for the nudge @rmallam #1540 WIP PR that will hopefully address the issue.

Thanks for your awesome work @mtrmac @vrothberg . I tested this using the environment variable and it works.

**Comment by vrothberg** [comment]
With https://github.com/containers/skopeo/pull/1540 merged, we can close this issue.

**Comment by Pawanpreetkaur175** [comment]
> Hi, a colleague (@SionArtingstall) and I have finally found a way round this issue:
> 
> Firstly install these two packages:
> 
> ```
> yum install expect spawn -y
> ```
> 
> Then run the following to use passphrase from file:
> 
> ```
> expect -c "
> spawn skopeo copy --debug --sign-by none@fake.com docker://path/to/image:123 docker://path/to/image:456 --authfile auth.json
> expect \"Passphrase: \"
> sleep 3
> send \"$(cat /path/to/password.txt)\n\"
> interact
> "
> ```
> 
> or provide as ENV variable:
> 
> ```
> expect -c "
> spawn skopeo copy --debug --sign-by none@fake.com docker://path/to/image:123 docker://path/to/image:456 --authfile auth.json
> expect \"Passphrase: \"
> sleep 3
> send \"$MY_PASSPHRASE\n\"
> interact
> "
> ```
> 
> Obviously the cleaner way is if skopeo enabled us to send passphrase through like gpg does...

**Comment by Pawanpreetkaur175** [comment]
hey what's that auth Jason file contains and where we need to put whole this command in terminal or somewhere else?

**Comment by Pawanpreetkaur175** [comment]
> > Thanks for the nudge @rmallam #1540 WIP PR that will hopefully address the issue.
> 
> Thanks for your awesome work @mtrmac @vrothberg . I tested this using the environment variable and it works.

**Comment by Pawanpreetkaur175** [comment]
can you please tell how you did for this automating gig passphrase for images signing can you please provide the exact command with explanation @rmallam

**Comment by mtcolman** [comment]
@Pawanpreetkaur175 

```
$ skopeo copy --help
Container "IMAGE-NAME" uses a "transport":"details" format.

Flags:
      --additional-tag strings                additional tags (supports docker-archive)
  -a, --all                                   Copy all images if SOURCE-IMAGE is a list
      --authfile string                       path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json
```

(Alternatively, if source and destinations require different credentials, you can provide `--src-authfile` and `--dest-authfile`).

It contains:
```
{
	"auths": {
		"my-example-repo.com": {
			"auth": "base64-encoded<username-for-repo>:<password-for-repo>"
		}
	}
}
```

As per the "help" it will default to `${XDG_RUNTIME_DIR}/containers/auth.json` if not provided.
