### ISSUE TITLE
Using OCI format for skopeo sync for multi-architecture images

### ISSUE THREAD

**Issue by Freakin** [containers/skopeo#1262]
I have a need to replicate a set of public images to our internal registry, and `skopeo sync` looked like it was working great for this.

However, when I attempted to use multi-arch images with `sync`, my registry (Harbor) only uses the tag on the most recently pushed image and the previously pushed/tagged images have their tags cleared.

When I use 
`skopeo copy docker://docker.io/nginx:stable-perl docker://harbor.my-domain.com/my-project/nginx:stable-perl --format oci --all`
It works perfectly and uploads the OCI manifest to Harbor with all the images included and properly tagged.

But it appears that `skopeo sync` does not have the format parameter.  Is there any plan to implement manifest format for `sync`?

**Comment by rhatdan** [comment]
Interested in opening a PR to add it?

**Comment by Freakin** [comment]
PR submitted @rhatdan

**Comment by mtrmac** [comment]
Per https://github.com/containers/skopeo/pull/1263#issuecomment-827048749 , this seems to work as expected (with `--all`). Please reopen if that’s not the case.
