### ISSUE TITLE
Investigate autogenerating completions/…

### ISSUE THREAD

**Issue by mtrmac** [containers/skopeo#1264]
… per https://github.com/spf13/cobra/blob/master/shell_completions.md .

Manually maintaining the shell script is a pain and too easy to forget about.

**Comment by lsm5** [comment]
assigning to myself. IIUC, paul has done something similar for podman.

**Comment by rhatdan** [comment]
@Luap99 FYI

**Comment by Luap99** [comment]
Yes actually this should be very simple to enable for skopeo. AFAIK there are no custom completion logic for command arguments. So only subcommands and flags are completed. I think all you have to do is to enable the default completion command.

**Comment by mtrmac** [comment]
This was implemented in #1647.
