### ISSUE TITLE
skopeo-copy docs incorrectly state that `--format` only applies to `dir:`

### ISSUE THREAD

**Issue by stephen-dexda** [containers/skopeo#1265]
https://github.com/containers/skopeo/blob/master/docs/skopeo-copy.1.md currently says:

> --format, -f manifest-type Manifest type (oci, v2s1, or v2s2) to use when saving image to directory using the 'dir:' transport (default is manifest type of source)

However, this also works with e.g. `docker:` targets:

```bash
skopeo copy --format=v2s2 oci-archive:<ref> docker://<ref>
```

The above results in a Docker-format image being pushed, vs. an OCI image without the `--format` option.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix this?

**Comment by stephen-dexda** [comment]
I don't know what the full correct scope for the option is so I'm not currently in a good position to do that ;)
