### ISSUE TITLE
CentOS7 package for latest release v1.2.3

### ISSUE THREAD

**Issue by shilpa-0** [containers/skopeo#1277]
Hello,

Could you please provide CentOS7 package for latest release v1.2.3? 

Thanks

**Comment by vrothberg** [comment]
Thanks for reaching out.

As per https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html, we do not provide packages for Podman (and Buildah and Skopeo) on old distributions including CentOS 7.

The support matrix grew very big, eating a lot of time. Especially old distributions complicated the packaging efforts with (too) old kernels and core libraries.

@lsm5, could you add the Podman blog that this also applies to Buildah and Skopeo?
