### ISSUE TITLE
how to copy multiple docker images packaged in .tar.gz to oci repository/directory/archive

### ISSUE THREAD

**Issue by shimish2** [containers/skopeo#1295]
I am trying to use docker-archive transport 
``` skopeo copy docker-archive:./test.tar.gz oci:/tmp/oci-test```

 Unexpected tar manifest.json: expected 1 item, got 56

**Comment by mtrmac** [comment]
On a recent enough version, one by one, e.g. `skopeo copy docker-archive:./test.tar.gz:image1:tag1 oci:/tmp/oci-test:image1:tag1`.

(It’s pretty expensive; Go users can use `containers/image/docker/archive.NewReader` to share the overhead across copies; but not using the `docker-archive:` format at all is almost always more efficient anyway — in the worst case, set up a docker/distribution server in a container, and copy across its backing storage.)

**Comment by shimish2** [comment]
Ok, can you elaborate in steps what needs to be done if i am going  ```containers/image/docker/archive.NewReader``` way

I can get list of images available from List() method but what would be next steps after that

**Comment by rhatdan** [comment]
@mtrmac This is waiting on you, I believe.

**Comment by mtrmac** [comment]
The top-level goal is to use `containers/image/copy.Image`, see the implementation of `skopeo copy` for the basic structure. As for how that integrates with `containers/image/docker/archive`, compare Podman’s use.

**Comment by shimish2** [comment]
Thanks for your help, I am able to copy.
