### ISSUE TITLE
“None of the challenges sent by server (127.0.0.1) are supported”

### ISSUE THREAD

**Issue by thanasisk** [containers/skopeo#1300]
Hi everyone,
I have a V2 docker registry running behind an OAuth2 reverse proxy (specifically Zalando's skipper: https://github.com/zalando/skipper ). I tried using ` --dest-registry-token` but it fails - I think it expects the OAuth2 challenge to come from the registry. The specific error I am getting is the following:
`INFO[0000] None of the challenges sent by server (127.0.0.1) are supported, trying an unauthenticated request anyway`

How can I extend skopeo to support my use case - in case I am doing something wrong,

**Comment by bikramguha** [comment]
👍

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
@thanasisk 

> `INFO[0000] None of the challenges sent by server (127.0.0.1) are supported, trying an unauthenticated request anyway`

Hum, that 127.0.0.1 is supposed to be a list of server-accepted authentication types. Can you capture the full HTTP response headers of the access to the registry’s `/v2/` URL, please? The output of `curl -iL https://$registry/v2/` , or something like that, might be a start.

**Comment by thanasisk** [comment]
@bikramguha can you please provide the necessary information, as I am OoO ?

**Comment by mtrmac** [comment]
Closing for now, do feel free to reopen with the requested logs.
