### ISSUE TITLE
Dont use symlink in docker archive format

### ISSUE THREAD

**Issue by jonathongardner** [containers/skopeo#1313]
This might not be a bug as much as a request. But when converting to a dock-archive file symlinks are used for the layer tar. I use skopeo for converting different docker image format to docker archive format so i can scan them to find the SBOM and the symlinks are causing the scanner to find bad results. 

For example if i run `skopeo copy docker://hello-world:latest  docker-archive:/tmp/test/hello-world.tar` I get the following file structure:
```
a803ca04f00ecd1c10fb4978f7a963d1461f4225e568901bc6990cb46a3e04be/layer.tar
a803ca04f00ecd1c10fb4978f7a963d1461f4225e568901bc6990cb46a3e04be/json
a803ca04f00ecd1c10fb4978f7a963d1461f4225e568901bc6990cb46a3e04be/VERSION
repositories
manifest.json
d1165f2212346b2bab48cb01c1e39ee8ad1be46b87873d9ca7a4e434980a7726.json
f22b99068db93900abe17f7f5e09ec775c2826ecfe9db961fea68293744144bd.tar
```
For this `a803ca04f00ecd1c10fb4978f7a963d1461f4225e568901bc6990cb46a3e04be/layer.tar` is a symlink to `f22b99068db93900abe17f7f5e09ec775c2826ecfe9db961fea68293744144bd.tar`. 

It would be helpful if symlinks weren't used and the docker-archive was the same format as doing `docker save hello-world:latest > hello-world.tar` which results in something like 
```
a803ca04f00ecd1c10fb4978f7a963d1461f4225e568901bc6990cb46a3e04be/layer.tar
a803ca04f00ecd1c10fb4978f7a963d1461f4225e568901bc6990cb46a3e04be/json
a803ca04f00ecd1c10fb4978f7a963d1461f4225e568901bc6990cb46a3e04be/VERSION
repositories
manifest.json
d1165f2212346b2bab48cb01c1e39ee8ad1be46b87873d9ca7a4e434980a7726.json
```

**Comment by rhatdan** [comment]
@mtrmac PTAL
