### ISSUE TITLE
Fix documentation for --retry-times

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#1322]
Currently the `--retry-times` flag is only documented for `skopeo inspect` in the markdown. https://github.com/containers/skopeo/blob/master/docs/skopeo-inspect.1.md

However, it appears to have also been implemented for `skopeo copy`, `skopeo delete`, `skopeo list-tags`, and `skopeo sync`, as per the help text.

Please update the markdown to reflect this.

**Comment by mtrmac** [comment]
Thanks for your report. Care to prepare a PR?
