### ISSUE TITLE
Unable to run skopeo on Fedora 30 - `libdevmapper.so.1.02.1` dependency

### ISSUE THREAD

**Issue by davidhay1969** [containers/skopeo#1336]
This is similar to #333 which related to Fedora `25` and may well be a self-inflicted problem 🤣 

Having built `skopeo` on an Ubuntu `20.04` box, I've shipped the binary to a VM based upon Fedora `30`.

However, when I run, say, `skopeo --version` I see: -

```text
skopeo: error while loading shared libraries: libdevmapper.so.1.02.1: cannot open shared object file: No such file or directory
```

I do have `libdevmapper.so` albeit an older version: -

`ls -al /usr/lib64/libdev*`

```text
lrwxrwxrwx 1 root root     20 Feb 17  2019 /usr/lib64/libdevmapper.so -> libdevmapper.so.1.02
-r-xr-xr-x 1 root root 401232 Feb 17  2019 /usr/lib64/libdevmapper.so.1.02
```

As per #333 I found that setting `DISABLE_CGO=1` made the difference e.g.

`DISABLE_CGO=1 make bin/skopeo`

resulting  in a slightly larger binary: -

`ls -al bin/skopeo`

```text
-rwxr-xr-x 1 root root 36607904 Jun 25 02:45 bin/skopeo
```

Having pushed the new, larger version of the binary to the Fedora box, things appear to be A-OK : -

`skopeo --version`

```text
skopeo version 1.3.1-dev commit: af550fda48c4f0829dc722e937206abf5fddcccb
```

# Background of Fedora box

`cat /etc/redhat-release`

```text
Fedora release 30 (Thirty)
```

`uname -a`

```text
Linux nginx-kata 5.10.25 #1 SMP Fri Jun 11 20:36:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

`which skopeo`

```text
/usr/local/bin/skopeo
```

```bash
ls -al `which skopeo`
```

```text
-rwxr-xr-x 1 root root 37580456 Jun 25 09:33 /usr/local/bin/skopeo
```

**Comment by vrothberg** [comment]
Thanks for reaching out!

Copying dynamic binaries across different (versions of different) distributions may not always.  Yet I am equally surprised about the error given the library seems to be present.  Could you `strace` to see which path skopeo is looking up?

A word of caution: Fedora 30 ran out of support in 2020-05-26 and is not getting any updates anymore.

**Comment by davidhay1969** [comment]
Thanks @vrothberg very valid point re Fedora `30` - purely for info, we're using that version as part of [Kata Containers](https://github.com/kata-containers/kata-containers/releases) - it's one of the options for the guest Virtual Machine, aka Pod Sandbox, that Kata spins up when one deploys a K8s pod.

Will get a `strace` back here shortly ....

**Comment by mtrmac** [comment]
It seems the `soname` (shared library dependency) is the full `libdevmapper.so.1.02`**`.1`**  (check with `ldd /path/to/skopeo`); the `soname` values are compared as strings, with no major/minor/patch semantics, so just sharing `1.02` isn’t enough.

**Comment by davidhay1969** [comment]
For the record, whilst Kata does "default" to Fedora `30` which, as you rightly say, is EOL: -

<img width="486" alt="image" src="https://user-images.githubusercontent.com/18368320/123437707-df825180-d5c7-11eb-8f8a-36f8a8051831.png">

one can choose a later release e.g. `33` or `34` both of which are stilll in support.

Will test both and report back

Meantime, have raised an [issue](https://github.com/kata-containers/kata-containers/issues/2116) over in Kata Containers asking whether we should up the default to something supported 😁

**Comment by vrothberg** [comment]
> It seems the `soname` (shared library dependency) is the full `libdevmapper.so.1.02`**`.1`** (check with `ldd /path/to/skopeo`); the `soname` values are compared as strings, with no major/minor/patch semantics, so just sharing `1.02` isn’t enough.

Good catch, @mtrmac.  Closing the issue.
