### ISSUE TITLE
Copy: OCI - put image name to annotations

### ISSUE THREAD

**Issue by PhilippHomann** [containers/skopeo#1366]
I'm trying to copy multiple images from a docker-registry to a OCI directory and copy them back to another.
I noticed that the source image name is not stored to the OCI dir index file as it could be done (annotation 'org.opencontainers.image.ref.name').
So I'm not able to address a specific image from the OCI directory with skopeo.

```bash
$ skopeo copy docker://centos:7.9.2009 oci:.
$ skopeo copy docker://centos:8.3.2011 oci:.
$ skopeo copy oci:.:centos:8.3.2011 docker://example:test
FATA[0000] Error initializing source oci:.:centos:8.3.2011: no descriptor found for reference "centos:8.3.2011" 
```
This is caued by missing annotations in index.json.
After adding the annotation manually, copying to destination works as expected.

**Comment by mtrmac** [comment]
Thanks for your report.

`skopeo copy` treats the source and destination as completely independent, with no heuristic inference about names. Use the same syntax for writing that you use for reading, e.g. `skopeo copy docker://centos:7.9.2009 oci:.centos:8.3.2011`.

**Comment by PhilippHomann** [comment]
To correct your command:
`skopeo copy docker://centos:7.9.2009 oci:.:centos:8.3.2011`
You missed out the colon between directory name and image name!
