### ISSUE TITLE
Skopeo v1.3.1 not available in Quay.io

### ISSUE THREAD

**Issue by dmaciel** [containers/skopeo#1377]
I noticed that a new version of Skopeo has been available for more than to weeks and tried to update my container tag. It is failing since version v1.3.1 is not available in Quay.io: https://quay.io/repository/containers/skopeo?tab=tags

Is the quay.io repo the official one? anything I can do to help or fix this?

**Comment by TomSweeneyRedHat** [comment]
Yes,
Until a version of Skopeo reaches stable in the latest Fedora, it will not be in the quay.io repo.  Then after it does reach stable in Fedora, there's upwards of a 24-hour wait until the CI job runs again which makes the image on quay.io.

**Comment by lsm5** [comment]
v1.3.1 set to land in stable in 24 hours or less https://bodhi.fedoraproject.org/updates/FEDORA-2021-8f8dbb4440

**Comment by lsm5** [comment]
it's available now. Closing..
