### ISSUE TITLE
Howto copy a container image archive to K8s local storage running on CRI-O

### ISSUE THREAD

**Issue by xcross-ibm** [containers/skopeo#1388]
Hi skopeo dev,
I'm designing an appliance with embedded K8s and investigating how to get container images into the K8s container storage. The appliance can't depend on a remote repository. I'm doing this research with a K8s cluster [installed on a CentOS 8 system with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/).

CentOS 8 comes with `podman` already installed. I installed CRI-O continuing to follow the [K8s instructions for a production environment](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o). It looks like podman and cri-o use different local storage as `podman images` and `crictl images` report different contents. 

I can successfully inspect and copy the podman images with `skopeo` using `containers-storage:` but I haven't found a way to address the CRI-O images:

```
[chris@esx1k8s1 ~]$ podman pull busybox:1.33
[chris@esx1k8s1 ~]$ podman images
REPOSITORY                 TAG     IMAGE ID      CREATED      SIZE
docker.io/library/busybox  1.33    69593048aa3a  7 weeks ago  1.46 MB
[chris@esx1k8s1 ~]$ skopeo inspect containers-storage:docker.io/library/busybox:1.33 
{
    "Name": "docker.io/library/busybox",
    "Digest": "sha256:dca71257cd2e72840a21f0323234bb2e33fea6d949fa0f21c5102146f583486b",
    "RepoTags": [],
    "Created": "2021-06-07T20:20:29.305375985Z",
...

[chris@esx1k8s1 ~]$ sudo crictl pull busybox
[chris@esx1k8s1 ~]$ sudo crictl images
IMAGE                                TAG                 IMAGE ID            SIZE
docker.io/library/busybox            latest              69593048aa3ac       1.46MB
k8s.gcr.io/coredns/coredns           v1.8.0              296a6d5035e2d       42.6MB
k8s.gcr.io/echoserver                1.4                 a90209bb39e3d       145MB
...

[chris@esx1k8s1 ~]$ skopeo inspect containers-storage:docker.io/library/busybox:latest
FATA[0000] Error parsing image name "containers-storage:docker.io/library/busybox:latest": reference "[overlay@/home/chris/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/library/busybox:latest" does not resolve to an image ID: identifier is not an image 
ERRO[0000] exit status 1                                
```

I think what I'm attempting to do is implied by the skopeo doc

> containers-storage:docker-reference An image located in a local containers/storage image store. Both the location and image store are specified in /etc/containers/storage.conf. (This is the backend for Podman, CRI-O, Buildah and friends)

but I obviously have some confusion about the organization of container storage. Can you help with this question?

**Comment by vrothberg** [comment]
Thanks for reaching out, @xcross-ibm!

CRI-O  runs as `root` on your machine while the examples above show that podman and skopeo are executed as user `chris`.  Try re-running the same commands as root which should resolve the issue.

Each user has their own container storage, so a non-root user cannot access the images of root.

**Comment by xcross-ibm** [comment]
@vrothberg Thanks, that done it! Appreciate the quick response.
