### ISSUE TITLE
How to export the local image to docker format

### ISSUE THREAD

**Issue by klvchen** [containers/skopeo#1401]
How to export the local image to docker format

I can see the details with commands
[root@localhost ~]# skopeo inspect containers-storage:xxxxx.xxxxxx.com/xxxxx/provid-spot-server:5

{
    "Name": "xxxxx.xxxxxx.com/xxxxx/provid-spot-server",
    "Digest": "sha256:3adba323bab12171019f1cd98f5962bad9af1f9684796404e45e4621eceed9df",
    "RepoTags": [],
    "Created": "2020-08-19T07:35:20.50010297Z",
    "DockerVersion": "18.06.1-ce",
    "Labels": {},
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:53478ce18e19304e6e57c37c86ec0e7aa0abfe56dff7c6886ebd71684df7da25",
        "sha256:d1c225ed7c34b971d07972665694b54692ae4e5337ec463277c82e408afc62ce",
        "sha256:c6724ba0c09a9abac10a5d84cc53f9843cb7d81a465f9bca280ef300821e7a29",
        "sha256:a93cd1ce2cb2edd5c786b98d5846fd48758bdab9f2f868d74ed1d2c8d3c43ad0",
        "sha256:3db15decd4aa05c67e6b7aa4b703e4d8b024fe5b1760e2896a3a3f9875b99204",
        "sha256:997bfacab656edce9e88cfb36ed8e2ff538a55a6b3a29610e24ae0fc8ef54d3f",
        "sha256:bffa923ffd6452efe54063a632b60d737a93bb1e24978b54d889ac109176d486",
        "sha256:0fb47bee640a26da0ba5d0dfc42b4e90636bdc75dbf5316b240508ae952331cf"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin",
        "LANG=C.UTF-8",
        "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
        "JAVA_VERSION=8u111",
        "JAVA_ALPINE_VERSION=8.111.14-r0"
    ]
}

But I cannot export with command:
[root@localhost ~]# skopeo copy containers-storage:xxxxx.xxxxxx.com/xxxxx/provid-spot-server:5 docker-archive:/tmp/provid-spot-server.tar
Getting image source signatures
FATA[0001] Error reading blob sha256:9f8566ee5135862dd980160c27bd7721448a6f7f385bbb81f7f001f1b78a5fbf: stat /var/lib/containers/storage/overlay/9f8566ee5135862dd980160c27bd7721448a6f7f385bbb81f7f001f1b78a5fbf: no such file or directory

How can i solve it, thank you!

**Comment by vrothberg** [comment]
> Error reading blob sha256:9f8566ee5135862dd980160c27bd7721448a6f7f385bbb81f7f001f1b78a5fbf: stat /var/lib/containers/storage/overlay/9f8566ee5135862dd980160c27bd7721448a6f7f385bbb81f7f001f1b78a5fbf: no such file or directory

This indicates that a layer is missing in the local storage. Did some previous copy operation to the containers-storage fail or got killed?

**Comment by klvchen** [comment]
I found the missing layer is in this place( /var/lib/containers/storage/overlay2 ), not in /var/lib/containers/storage/overlay/
`
[root@localhost overlay2]# cd /var/lib/containers/storage/overlay2
[root@localhost overlay2]# ls 9f8566ee5135862dd980160c27bd7721448a6f7f385bbb81f7f001f1b78a5fbf
diff  empty  link  merged  work
`
What should i do？thank

**Comment by mtrmac** [comment]
This might require a much more specific c/storage reference, or accessing the right configuration files, e.g. in some Podman logs:
```DEBU[0000] parsed reference into "[vfs@/home/cicd/.local/share/containers/storage+/run/user/1000/containers]myregistry.local/ubuntu:20.04-amd64"
```
(very likely your configuration will require a different […] part.) Skopeo does not read all of the configuration that Podman does.

**Comment by rhatdan** [comment]
Did you convert from overlay2 to overlay?  You might need to reset storage and start again.  Do not use overlay2 at all, it is the same as overlay.

**Comment by klvchen** [comment]
Thank you all, I will try
