### ISSUE TITLE
Misleading unauthorized error while copying

### ISSUE THREAD

**Issue by davidmogar** [containers/skopeo#1416]
I'm using Skopeo to copy images to a different register. This is part of a pipeline that has been more active lately. One thing I noticed is that if the destination image already existed (or at least the repo did when copying to quay.io), the copy was generally successful. In the case of the image not existing, an error like the following one was quite frequent (although not happening every time):

```
Command: /usr/bin/skopeo copy --authfile /mnt/docker/.dockerconfigjson docker://source_image docker://destination_image Failed

STDOUT: Getting image source signatures
Copying blob sha256:1e01d767f57
Copying blob sha256:869101f0eb4
Copying blob sha256:83bb052421

STDERR: time="2021-08-12T11:10:58Z" level=fatal msg="Error writing blob: Error initiating layer upload to /v2/my_organization/destination_image_name/blobs/uploads/ in quay.io: unauthorized: access to the requested resource is not authorized"
```

I tried to reproduce the error both, running the pipeline and running the command locally with different skopeo versions but the same credentials. I actually didn't manage to reproduce it, what lead me to think that this wasn't a real permissions problem as shown. The error didn't happen either in all the copies in the same pipeline, so this was another reason to think the credentials were just fine.

I added a retry mechanism to the pipeline to rerun the skopeo command in case it failed. This is the result:
```
Command: /usr/bin/skopeo copy --authfile /mnt/docker/.dockerconfigjson docker://source_image docker://destination_image Failed

STDOUT: Getting image source signatures
Copying blob sha256:1e01d767f57
Copying blob sha256:869101f0eb4
Copying blob sha256:83bb052421

STDERR: time="2021-08-12T11:21:22Z" level=fatal msg="Error writing blob: Error initiating layer upload to /v2/my_organization/destination_image_name/blobs/uploads/ in quay.io: unauthorized: access to the requested resource is not authorized"

Command: /usr/bin/skopeo copy --authfile /mnt/docker/.dockerconfigjson docker://source_image docker://destination_image

STDOUT: Getting image source signatures
Copying blob sha256:1e01d767f57
Copying blob sha256:869101f0eb4
Copying blob sha256:83bb052421
Copying config sha256:1b43abc950
Writing manifest to image destination
Storing signatures
```

So, the copy worked in the first retry of the command. At this point it looks more like a timeout with a not that good error logged to the terminal.

Have you seen this before? What would be the best way to debug it and to address it?

```
Skopeo versions tried: 1.2.3-dev and 1.3.1
OS: Fedora 34 and Red Hat UBI 8
```

**Comment by rhatdan** [comment]
Since we never got any feedback, I am going to close.  Reopen if you can provide the feedback.
