### ISSUE TITLE
Skopeo v1.0 + on RHEL 7?

### ISSUE THREAD

**Issue by pkddacoliat** [containers/skopeo#1424]
Hi all, I am trying to install a version of skopeo with the `list-tags` flag available. Is there any repository where I can pull a skopeo with newer versions? This is the version I currently have installed:
```bash
==============================================================================================================================================================================================================================================================================================================================
 Package                                                               Arch                                                                  Version                                                                           Repository                                                                                Size
==============================================================================================================================================================================================================================================================================================================================
Installing:
 skopeo                                                                x86_64                                                                1:0.1.40-12.el7_9                                                                 rhel-7-server-extras-rpms                                                                5.8 M

Transaction Summary
==============================================================================================================================================================================================================================================================================================================================
```

**Comment by mtrmac** [comment]
Thanks for your report.

For Red Hat officially-supported versions included in/around RHEL, if any, please contact official Red Hat support through access.redhat.com

As for unsupported upstream or third-party builds, I’m not sure. @lsm5 , do you know? The Kubic libcontainers repo seems to have RHEL 7 disabled, by now at least.

**Comment by lsm5** [comment]
@pkddacoliat hi, rhel7 isn't going to get any official package updates anymore. Also, the Kubic packages were disabled for CentOS7 and other older distros because of really outdated dependencies. See: https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html . I don't know if there are any third parties building newer skopeo for el7.

So, you could either install from source, or switch to a newer rhel/centos. Sorry about the inconvenience. 

Closing this..
