### ISSUE TITLE
Why does skopeo copy not copy the entire contents of a layer?

### ISSUE THREAD

**Issue by TheTTimeLives** [containers/skopeo#1434]
New to skopeo and trying to figure something out.

Just messing with stuff and ran 
`skopeo copy --src-tls-verify=false docker://melnikprod/ubi-8-thing:1 (relativepathtolocaldirectory) 
`
to copy basically ubi8:8.4 and evaluate its contents.

But when I add the tar.gz extension to open and check the contents, I don't see anything inside the sys, dev or proc directories, even though they have contents when I look within that container when it's running. Why aren't these contents copied in this command?

**Comment by mtrmac** [comment]
Thanks for your report.

Skopeo is not interpreting the `tar` format _at all_ in that case. What you see is exactly all there is in the image.

If a running container sees different contents in `/sys`, `/dev` or `/proc`, they presumably don’t come from the image. Inspect the list of mounts applicable to a running container.
