### ISSUE TITLE
Does skopeo copy --dest-compress accept/require boolean value?

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/skopeo#1435]
https://github.com/containers/skopeo/blob/main/docs/skopeo-copy.1.md says, that the `--dest-compress ` parameter accepts a boolean value.  `skopeo copy --help` says nothing about the boolen value.

Likewise for `--dest-decompress`.

**Comment by mtrmac** [comment]
Thanks for your report. These are bugs in the man page, and we should get them fixed.

(For the record, the Go behavior of boolean flags: accepted values are `--dest-compress`, which is the same as `--dest-compress=true`, and `--dest-compress=false`, which is the default. `--dest-compress {false,true}` is parsed as `--dest-compress=true` with a non-option `{false,true}` argument.)
