### ISSUE TITLE
unable to copy layer wasm oci image by tag

### ISSUE THREAD

**Issue by cortex93** [containers/skopeo#1438]
Hi,

I'm trying to promote an oci image builded with either [wasm-to-oci](https://github.com/engineerd/wasm-to-oci) or [wasme](https://github.com/solo-io/wasm).
Both have similar mime type layers.

```json
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.wasm.config.v1+json",
    "digest": "sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a",
    "size": 2
  },
  "layers": [
    {
      "mediaType": "application/vnd.wasm.content.layer.v1+wasm",
      "digest": "sha256:4c7915b4c1f9b0c13f962998e4199ceb00db39a4a7fa4554f40ae0bed83d9510",
      "size": 1624962
    }
  ]
}
```

`skopeo copy docker://localhost:5000/oneimage:develop docker://localhost:5001/oneimage:master` or
`skopeo copy docker://localhost:5000/oneimage@sha256:digest docker://localhost:5001/oneimage:master` fails with 

`FATA[0000] Error creating an updated image manifest: Error preparing updated manifest, layer "sha256:2cb8fac4d856630394c26811383a36001fdb234671df758013715d071662f54d": unsupported MIME type for compression: application/vnd.wasm.content.layer.v1+wasm`

I didn't find any working options to disable compression (`--dest-compress=false`).

I would expect the image to be raw copied without trying to compress (especially if not supported).

One workaround is to first copy by digest  and then copy dest@digest to dest:master.
```
skopeo copy docker://localhost:5000/oneimage@sha256:digest docker://localhost:5001/oneimage@sha256:digest
skopeo copy docker://localhost:5001/oneimage@sha256:digest docker://localhost:5001/oneimage:master
```

**Comment by mtrmac** [comment]
Thanks for your report.

> ```
>   "mediaType": "application/vnd.wasm.config.v1+json",
> ```

This doesn’t look like a container image, rather like a generic OCI artifact, and the current implementation is not ready to handle such formats in general; that’s tracked in https://github.com/containers/image/issues/1370 .

**Comment by mtrmac** [comment]
Closing — OCI artifact support needs to be added to c/image, and then Skopeo will automatically inherit it.
