### ISSUE TITLE
`skopeo copy oci-image:….tar containers-storage:…` does not import implicitly the org.opencontainers.image.ref.name annotation

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/skopeo#1442]
Imagine, ldap-2021-09-14.tar:index.json contains
```json
{"schemaVersion":2,
  "manifests":[
    {
      "mediaType":"application/vnd.oci.image.manifest.v1+json",
      "digest":"sha256:0fa7ea05f92a968c52975b127383aedbc677fa4e17f3fa25e4255f391859dd24",
      "size":349,
      "annotations":{"org.opencontainers.image.ref.name":"openldap:2021-09-14"}
    }
  ]
}
```

To import the file into `containers-storage:`, and preserve the REPOSITORY:openldap, TAG:2021-09-14 annotation, one has to write the tedious:
```
skopeo copy oci-archive:ldap-2021-09-14.tar:openldap:2021-09-14 containers-storage:localhost/openldap:2021-09-14
```
or the simpler (removing reference/repository/tag from the source)
```
skopeo copy oci-archive:ldap-2021-09-14.tar containers-storage:localhost/openldap:2021-09-14
```
However, just typing:
```
$ skopeo copy oci-archive:ldap-2021-09-14.tar containers-storage:localhost
Getting image source signatures
Copying blob 72cd3998238f done  
Copying config 0d44d7a447 done  
Writing manifest to image destination
Storing signatures
$ podman images 
REPOSITORY                   TAG         IMAGE ID      CREATED         SIZE
docker.io/library/localhost  latest      0d44d7a447ee  24 minutes ago  6.35 MB
```

strips the reference/repository/tag.

I propose to import the reference/repository/tag by default by `skopeo copy` & co. , when it is available in the image source, but is not explicitly given in the copy destination.

I use skopeo 1.4.1.

**Comment by mtrmac** [comment]
Thanks for your report.

Skopeo is a thin wrapper over c/image, with `skopeo copy` more or less directly exposing the `c/image/copy.Image` function. Such heuristics are not in the current scope of Skopeo; however Podman does implement many such features.

E.g. `podman pull oci-archive:…`, or maybe just `podman load ldap-$date.tar`, are AFAIK existing features of Podman.
