### ISSUE TITLE
Does list-tags guarantee an order on the returned tags?

### ISSUE THREAD

**Issue by jaikiran** [containers/skopeo#1465]
I've been using the `skopeo list-tags` command to peek into what tags have been published for a certain docker image. The returned list _appears_ to be order as "oldest tags first". Looking at the docs, I don't see an explicit specification on whether external tools which work on top of the output returned by this command can rely on this order.

Is there any specific ordering guarantee of this command output? Right now, is it ordered by tag timestamp or is the output that I'm seeing just coincidental?

P.S: Creating this as an issue because looking around, I didn't see any other place where I could ask this.

**Comment by lsm5** [comment]
@jaikiran if you try `skopeo list-tags docker://docker.io/debian` it shows newer tags first, and it looks like alphabetical order to me than tag date.

@mtrmac @vrothberg probably have more insight into this.

**Comment by lsm5** [comment]
> @jaikiran if you try `skopeo list-tags docker://docker.io/debian` it shows newer tags first, and it looks like alphabetical order to me than tag date.

same with fedora and ubuntu images.

**Comment by jaikiran** [comment]
> > @jaikiran if you try `skopeo list-tags docker://docker.io/debian` it looks like alphabetical order to me
> 
> same with fedora and ubuntu images.

Hello @lsm5, you are right the output against these registry images is alphabetical, when I run that command against these registry images from the same setup that I'm currently using. That is interesting because when I run that command against one of our internal registries the output is definitely based on timestamp (as far as I can see) and not alphabetical. I can't post the output here because the tags/images aren't for public consumption. So I wonder if the output somehow depends on the target docker registry? Let me see if I can find more details.

While we are at it, the reason why I started looking into the ordering of this output is for one of the use cases we are dealing with. We currently has a docker registry that is internal to our company and that docker images get published to it very frequently. We then have a separate docker registry where we want to replicate certain images and only "recent X tags" for those images. Imagine something like "Keep last 10 builds" that's present in the Jenkins CI jobs. To be able to do that  I was planning to do a `skopeo copy` after identifying the last X tags for a particular image. I wonder if the `list-tags` command can be enhanced to provide some such feature or maybe come up with a way to print out the tags in some specific deterministic (time based?) order.

**Comment by jaikiran** [comment]
> So I wonder if the output somehow depends on the target docker registry? Let me see if I can find more details.

Looking at the implementation of this command, it looks like all it does is fires a HTTP request against the registry[1] and doesn't do anything specific with the output. So it looks like it all depends on the registry instances on what order it sends. I'll check our setup to see where this difference of order comes from.

[1] https://github.com/containers/skopeo/blob/86fa758ad85c05484a4ba26e046abc437d90964d/vendor/github.com/containers/image/v5/docker/docker_image.go#L56

**Comment by vrothberg** [comment]
That is correct.  Skopeo is just returning the results from the registry

**Comment by rhatdan** [comment]
Yes there is nothing in the registry protocol, I believe to get you what you want. Skopeo can return everything and potentially sort it in different orders.  Or you could pipe the output of Skopeo to sort, to handle it yourself.

**Comment by jaikiran** [comment]
> Yes there is nothing in the registry protocol, I believe to get you what you want. 

Yes, that looks like the case. 

Thank you all for the inputs. I'll close this one now.
