### ISSUE TITLE
Error:/usr/bin/skopeo: 3: Syntax error: word unexpected (expecting ")"), when run skopeo copy in arm arch builder

### ISSUE THREAD

**Issue by langjianke** [containers/skopeo#1469]
we use skopoe command to copy docker image from local archive to gcr repository
below is the sample of the command
```
skopeo --debug copy --all docker-archive:/containers/abusedecision.tar docker://gcr.io/machamp-prod/abusedecision:807cc4de-7a51-4b57-9235-67ea86819089]
```

when update the skopeo to 1.4.1
verison v1.4.1 https://github.com/containers/skopeo/commit/130f32f047b7bf9b1fb4f95c4c5b1da6255e4829

we start to see this error in arm arch builder in aws as below, we also run this in the amd host in gcp, which does not have this issue
```
/usr/bin/skopeo: 3: Syntax error: word unexpected (expecting ")") 
Exit value: 2 
```

since this is only happens on arm arch builder, also based on some online search, I suspect this is binary arch issue

how I build the binary for aws is, I create the binary by running "make bin/skopeo" in arm builder
I suppose the binary generated in arm host should be compatible with arm, but this is assumption

want to get some help on this issue
would "make bin/skopeo" create the correct arch binary? or I have to run "make local-cross", and copy correct version myself?

**Comment by mtrmac** [comment]
Thanks for your report. `Syntax error: word unexpected` is not a Skopeo message, see e.g. https://stackoverflow.com/questions/36725864/syntax-error-word-unexpected-expecting . This looks like a bug in a script that invokes Skopeo.

**Comment by langjianke** [comment]
this is our run log, I think this error is what skopeo binary throwed
```
2021-10-01T15:13:33.879961094Z INFO   [15:13:33.879] [pool-3-thread-1] [] c.s.m.s.c.Commands -  Running: [skopeo, --debug, copy, --all, docker-archive:/containers/abusedecision.tar, docker://gcr.io/machamp-prod/abusedecision:622d67d5-d7d9-4efc-88ae-9e1a977c83ae] 
2021-10-01T15:13:33.881264167Z WARN   [15:13:33.881] [pool-3-thread-1] [] c.s.m.s.c.Commands -  /usr/bin/skopeo: 3: Syntax error: word unexpected (expecting ")") 
2021-10-01T15:13:33.881720301Z INFO   [15:13:33.881] [pool-3-thread-1] [] c.s.m.s.c.Commands -  Exit value: 2 
```

**Comment by mtrmac** [comment]
\*shrug\* Does that work when run manually?

(In general, `make bin/skopeo` does generate a binary for the current local architecture; immediately afterwards `bin/skopeo --version` should work. I guess it’s possible that this is caused an architecture mismatch, reported in a confusing way by a shell, but that error message is simply not one that Skopeo itself can, to my knowledge, generate. Perhaps confirm with `strace`.)

**Comment by langjianke** [comment]
*shrug* Does that work when run manually? <-- how do I confirm this?

some input, after genrate skopeo from arm builder, I can run skopeo -version with no issue
we are using --debug option, is there a strace option in skopeo, sorry did not find it

I wonder if I using local-cross and copy the specific arch skopeo would help in this case?

**Comment by langjianke** [comment]
some input when we are using older (much older) version, 0.1.41 there was no issue
when I bump up to skopeo version 1.4.1 commit: 130f32f047b7bf9b1fb4f95c4c5b1da6255e4829, I start to see this error

**Comment by langjianke** [comment]
some more update, I have tried to run the local-cross build and generate bunch of binaries 
```
-rwxr-xr-x 1 root root 26M Oct  2 03:15 skopeo.darwin.amd64
-rwxr-xr-x 1 root root 23M Oct  2 03:15 skopeo.linux.arm
-rwxr-xr-x 1 root root 25M Oct  2 03:16 skopeo.linux.arm64
-rwxr-xr-x 1 root root 25M Oct  2 03:16 skopeo.windows.386.exe
-rwxr-xr-x 1 root root 28M Oct  2 03:16 skopeo.windows.amd64.exe
```

however when I run the binary on the x86_64 machine (my mac)
I can not run amd64 but able to run arm binary, is it suppose to be opposite?

```
root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# uname -m
x86_64
root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# ./skopeo.darwin.amd64 --version
bash: ./skopeo.darwin.amd64: cannot execute binary file: Exec format error
root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# ./skopeo.linux.arm --version
skopeo version 1.4.1 commit: 130f32f047b7bf9b1fb4f95c4c5b1da6255e4829
root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# ./skopeo.linux.arm64 --version
skopeo version 1.4.1 commit: 130f32f047b7bf9b1fb4f95c4c5b1da6255e4829
```

**Comment by langjianke** [comment]
@mtrmac can I get some advise? thank you

**Comment by jaikiran** [comment]
I don't have much experience with skopeo, so this is more of a general advice:

> [15:13:33.881] [pool-3-thread-1] [] c.s.m.s.c.Commands -  /usr/bin/skopeo: 3: Syntax error: word unexpected (expecting ")") 

Going by that log message, it appears to be me that you are perhaps launching this skopeo command from some Java code using Java's `ProcessBuilder` API perhaps. Have you verified that the binary it is picking up - the `/usr/bin/skopeo` is indeed the one that was built for that particular host machine architecture?

**Comment by lynn447742** [comment]
> some more update, I have tried to run the local-cross build and generate bunch of binaries
> 
> ```
> -rwxr-xr-x 1 root root 26M Oct  2 03:15 skopeo.darwin.amd64
> -rwxr-xr-x 1 root root 23M Oct  2 03:15 skopeo.linux.arm
> -rwxr-xr-x 1 root root 25M Oct  2 03:16 skopeo.linux.arm64
> -rwxr-xr-x 1 root root 25M Oct  2 03:16 skopeo.windows.386.exe
> -rwxr-xr-x 1 root root 28M Oct  2 03:16 skopeo.windows.amd64.exe
> ```
> 
> however when I run the binary on the x86_64 machine (my mac) I can not run amd64 but able to run arm binary, is it suppose to be opposite?
> 
> ```
> root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# uname -m
> x86_64
> root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# ./skopeo.darwin.amd64 --version
> bash: ./skopeo.darwin.amd64: cannot execute binary file: Exec format error
> root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# ./skopeo.linux.arm --version
> skopeo version 1.4.1 commit: 130f32f047b7bf9b1fb4f95c4c5b1da6255e4829
> root@14d9413fd9be:/go/src/github.com/containers/skopeo/bin# ./skopeo.linux.arm64 --version
> skopeo version 1.4.1 commit: 130f32f047b7bf9b1fb4f95c4c5b1da6255e4829
> ```

how to build skopeo in arm64 ?
