### ISSUE TITLE
skopeo copy --decryption-key parameter cannot be resolved

### ISSUE THREAD

**Issue by jialez0** [containers/skopeo#1479]
ocicrypt_keyprovider.conf is as follows:

```
{
        "key-providers": {
                "enc": {
                    "grpc": "127.0.0.1:1234"
                },
                "dec": {
                    "grpc": "127.0.0.1:4321"
                }
        }
}
```

The container image was successfully encrypted using the following command:

```
OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf skopeo copy --encryption-key --provider:enc oci:example oci:example-enc
```

When attempting to decrypt the container image with the following command:

```
OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf skopeo copy --decryption-key --provider:dec oci:example-enc oci:example
```

It will fail. After investigation, we found that `dec` in `--decryption-key --provider:dec` is not parsed, skopeo will still look for the keyprovider named "enc" to obtain the key, that is, if we change the ocicrypt_keyprovider.conf to the following:

```
{
        "key-providers": {
                "enc": {
                    "grpc": "127.0.0.1:4321"
                }
        }
}
```

At this time, the decryption can be successful, which means that when skopeo uses keyprovider for encryption and decryption, keyprovider programs with different names are not supported for encryption and decryption, this means that the --decryption-key parameter is not resolved during decryption.

**Comment by jialez0** [comment]
@vrothberg  I'm sorry I wrote the above command wrong. The correct command should be: 
```
OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf skopeo copy --encryption-key provider:enc oci:example oci:example-enc

**Comment by lumjjb** [comment]
I believe the issue has been addressed, waiting on author to try the solution out.

**Comment by vrothberg** [comment]
Thanks everybody!  I am going to close.  Feel free to reopen if needed.
