### ISSUE TITLE
Release 0.5.1?

### ISSUE THREAD

**Issue by cgwalters** [containers/skopeo#1491]
https://github.com/coreos/rpm-ostree/pull/3139 depends on a new skopeo; I can temporarily add overrides where necessary, but it'd be nice to get a release out and in Fedora at least.

**Comment by lsm5** [comment]
@cgwalters bodhis have been sent https://bodhi.fedoraproject.org/updates/?packages=skopeo .

**Comment by jnovy** [comment]
@lsm5 merged: https://gitlab.com/redhat/centos-stream/rpms/skopeo/-/merge_requests/84
