### ISSUE TITLE
Version 1.5.0 on quay.io ?

### ISSUE THREAD

**Issue by dhatrifork** [containers/skopeo#1492]
On the docker registries on quay.io:
* https://quay.io/repository/containers/skopeo?tab=tags
* https://quay.io/repository/skopeo/stable?tab=tags
it seems the latest 1.5.0 build is not triggered to produce newest version 1.5.0 of the images.

**Comment by lsm5** [comment]
@TomSweeneyRedHat quay is probably something you own? ^

**Comment by lsm5** [comment]
> @TomSweeneyRedHat quay is probably something you own? ^

@TomSweeneyRedHat also please remind me how I could get rights to quay image maintenance as well

**Comment by cevich** [comment]
This is probably in my boat-house, as much as I enjoy working with github-actions, I'll take a look...

**Comment by cevich** [comment]
...[The latest logs show builds for 1.4.1 being pushed](https://github.com/containers/skopeo/actions/runs/1433783264), so something is broken.

**Comment by cevich** [comment]
Oh, [looks like the images are based on F33](https://github.com/containers/skopeo/runs/4136128814?check_suite_focus=true), that's probably why.

**Comment by cevich** [comment]
@lsm5 is going to fix the Dockerfiles, they'll get automatically picked up in the daily build subsequent to the fix-merge.
