### ISSUE TITLE
When to use --dest-precompute-digests?

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#1506]
I see that in v1.5.1, the `--dest-precompute-digests` flag was added to `skopeo copy`. However, the description of this flag doesn't really make it clear when you should or should not use it. It would be helpful if there were an explanation of what exactly skopeo does by default (without the flag), and how exactly adding the flag changes the behavior.

**Comment by mtrmac** [comment]
See https://github.com/containers/image/issues/1392 for more discussion about the motivation. In short: do you specifically care about the effect “to ensure layers are not uploaded that already exist on the destination registry”? If not, leave this in the default-disabled state.


Can you suggest a change to make the description clearer?

**Comment by rittneje** [comment]
From what I've observed, `skopeo copy` already did not copy existing layers. (Although it does seem to copy the manifest every time.) My assumption was it was doing some sort of HEAD request to enable this. Consequently, it wasn't clear what the purpose of this flag was. Is it just for cases in which skopeo has to do some conversion, and so consequently the source's digest cannot be reused?

**Comment by mtrmac** [comment]
Yes.

**Comment by mtrmac** [comment]
… or rather, it’s not only when it _has_ to do a blob conversion, it’s also when it prefers to. The typical case is sending an uncompressed image to a registry, when the cheap reuse fails (Skopeo could in that case use the uncompressed version on the registry, if it existed — but assume it doesn’t, as is usually the case); in that case Skopeo is compressing the image and streaming the compressed data to the registry, and only when the compression+streaming is done, will the registry be able to tell that the data already exists there.

Apparently that’s costly enough for some users to worry about, enough to take extra time and disk space to avoid that situation. Most users, AFAIK, haven’t been worrying about this, so the existing default (faster, and negligible disk space) suits them better.
