### ISSUE TITLE
How to restore an oci file containing multiple images to a harbor?

### ISSUE THREAD

**Issue by lynn447742** [containers/skopeo#1513]
Use "skopeo copy" to copy some images from harbor A (harbor.test.com) to the local:
$ skopeo docker://harbor.test.com/kube-apiserver:v1.20.7 oci:images -a --insecure-policy
$ skopeo docker://harbor.test.com/coredns:1.7.0 oci:images -a --insecure-policy
$ skopeo docker://harbor.test.com/metrics-server:v0.3.6 oci:images -a --insecure-policy

when copy to harbor B (harbor.zy.com) , It has the following error：
$ skopeo copy oci:images docker://harbor.zy.com/library/kube-apiserver:v1.20.7 -a --insecure-policy
FATA[0000] Error initializing source oci:images:: more than one image in oci, choose an image
$ skopeo copy oci:images:kube-apiserver docker://harbor.zy.com/library/kube-apiserver:v1.20.7 -a --insecure-policy
FATA[0000] Error initializing source oci:images:kube-apiserver: no descriptor found for reference "kube-apiserver"

**Comment by lynn447742** [comment]
how to choose an image?

**Comment by lsm5** [comment]
> Use "skopeo copy" to copy some images from harbor A (harbor.test.com) to the local: $ skopeo docker://harbor.test.com/kube-apiserver:v1.20.7 oci:images -a --insecure-policy $ skopeo docker://harbor.test.com/coredns:1.7.0 oci:images -a --insecure-policy $ skopeo docker://harbor.test.com/metrics-server:v0.3.6 oci:images -a --insecure-policy

The image refs must be mentioned at the time of copying. If you only mention `oci:images` it will not preserve the reference.

So you could try: 
` skopeo copy docker://harbor.test.com/kube-apiserver:v1.20.7 oci:images:kube-apiserver:v1.20.7 -a --insecure-policy`  and likewise ... then you can send to harbor B with this:

`skopeo copy oci:images:kube-apiserver:v1.20.7 $HARBOR_B_URL`

@vrothberg @mtrmac please correct me if i'm wrong.

**Comment by lynn447742** [comment]
> 

i just tried,it works,thanks a lot
