### ISSUE TITLE
Support dockercfg authfile

### ISSUE THREAD

**Issue by lcarva** [containers/skopeo#1514]
There are two distinct formats for the docker registry authentication file:

`dockercfg`, example:
```
{
  "registry.example.com": {
    "username": "spam",
    "password": "super-secret",
    "email": "spam@example.com",
    "auth": "also-super-secret"
  }
}
``` 

`dockerconfigjson`, example:
```
{
  "auths": {
    "registry.example.com": {
      "username": "spam",
      "password": "super-secret",
      "email": "spam@example.com",
      "auth": "also-super-secret"
    }
  }
}
```

`dockerconfigjson` is basically `{ "auths": <dockercfg> }`

Kubernetes [supports](https://kubernetes.io/docs/concepts/configuration/secret/#secret-types) both formats. Although `dockercfg` is referred to as the older format, it seems to still be widely used. On a recent OpenShift cluster (Kubernetes v1.21.1), the registry secrets created by the cluster are all of type `kubernetes.io/dockercfg`.

Skopeo does not find the credentials when using an authfile in the `dockercfg` format:
```
DEBU[0000] No credentials for registry.example.com found 
```

When the file is changed to the `dockerconfigjson` format, everything works as expected:
```
DEBU[0000] Found credentials for registry.example.com in credential helper containers-auth.json in file /tmp/authfile.json
```

System Info:
```
$  skopeo --version
skopeo version 1.5.1
$  cat /etc/system-release
Fedora release 34 (Thirty Four)
```

My use case is that I want to use skopeo to interact with a registry from a Pod within OpenShift/Kubernetes. The credentials to the registry are provided in the form of an OpenShift/Kubernetes Secret of type `kubernetes.io/dockercfg`. This is provided by the platform itself and cannot be easily adjusted to be provided in a different format. 

The workaround is to convert the file to the `dockerconfigjson` format at run time. This is error prone and far from ideal. Can we add support for the dockercfg file format in skopeo?

**Comment by mtrmac** [comment]
Thanks for your report.

(I would generally caution against using K8s secrets directly as credential files; K8s doesn’t interpret the formats exactly in the same way, https://github.com/kubernetes/kubernetes/issues/102472 is an extreme example. So some kind of conversion/filtering is necessary either way, to be 100% correct.)

The legacy format is implemented, and used to read `~/.dockercfg` (if no other credential file is defined). The underlying implementation also allows using other paths via `types.SystemContext.LegacyFormatAuthFilePath`, but that’s not exposed in the CLI. Would you care to contribute a PR to expose that, maybe as a `--legacy-auth-file` option?

**Comment by lcarva** [comment]
> Thanks for your report.
> 
> (I would generally caution against using K8s secrets directly as credential files; K8s doesn’t interpret the formats exactly in the same way, [kubernetes/kubernetes#102472](https://github.com/kubernetes/kubernetes/issues/102472) is an extreme example. So some kind of conversion/filtering is necessary either way, to be 100% correct.)
Noted :)
> 
> The legacy format is implemented, and used to read `~/.dockercfg` (if no other credential file is defined). The underlying implementation also allows using other paths via `types.SystemContext.LegacyFormatAuthFilePath`, but that’s not exposed in the CLI. Would you care to contribute a PR to expose that, maybe as a `--legacy-auth-file` option?

+1 I think that would be a nice way to handle this. I would like to do this, but it may be a while before I can dedicate some time.

**Comment by lcarva** [comment]
Following up on this. For my particular use case, I am not able to mount the k8s secret on my container due to unrelated issues. I need to make a copy of the authfile which I'm using as an opportunity to convert between the different formats.

I still think that it would be good to have some support in skopeo in general, but it's not something that would be useful to me right now or in the near future.

From my perspective this issue can be closed, but I'll leave it up to the skopeo maintainers to make that decision.

**Comment by mtrmac** [comment]
Thanks for the update.

This is not something I’m planning to work on, so closing. But if anyone else needs it, a PR _would_ be welcome.
