### ISSUE TITLE
skopeo copy generates such an error "does not resolve to an image ID: identifier is not an image"

### ISSUE THREAD

**Issue by cmoulliard** [containers/skopeo#1515]
## Issue

The following `skopeo copy` command 
```
[vagrant@centos7 buildah]$ IMAGE_ID="ba42db863d2b"
[vagrant@centos7 buildah]$ sudo skopeo --debug copy containers-storage:$IMAGE_ID oci:$(pwd)/$IMAGE_ID:1637781561859189730-1
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] cached value indicated that overlay is supported 
DEBU[0000] cached value indicated that metacopy is not being used 
DEBU[0000] cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/ba42db863d2b:latest" 
```

generates such an error 
```
DEBU[0000] reference "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/ba42db863d2b:latest" does not resolve to an image ID 
FATA[0000] Error initializing source containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/ba42db863d2b:latest: reference "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/ba42db863d2b:latest" does not resolve to an image ID: identifier is not an image 
```

The problem seems to be related to the fact that `overlay` driver is used while the image has been created under `vfs`

```
sudo buildah --storage-driver vfs images | awk -v r="$REPO" '$0 ~ r {print $3;}'
ba42db863d2b
fc5a911fab0c
4350afae9732
...

and
sudo buildah --storage-driver vfs images | awk -v r="$REPO" '$0 ~ r {print $2;}'
1637781561859189730-1
1637781360202720896-1
...
 sudo buildah --storage-driver vfs images 
REPOSITORY                        TAG                     IMAGE ID       CREATED        SIZE
localhost/buildpack-buildah       1637781561859189730-1   ba42db863d2b   2 hours ago    327 MB
localhost/buildpack-buildah       1637781360202720896-1   fc5a911fab0c   2 hours ago    327 MB
```

WDYT ? @mtrmac

**Comment by vrothberg** [comment]
> The problem seems to be related to the fact that overlay driver is used while the image has been created under vfs

That is correct.  I am not sure what the request is but I assume you are looking for a way to access the VFS-driver storage via skopeo.  In order to change the default storage in skopeo, you need to embed the new driver, location etc. in the reference (see `man containers-transports`).

For a rootless user with uid 1000, it may look as follows: `containers-storage:[vfs@$HOME/.local/share/containers/storage+/run/user/1000/containers]@ba42db863d2b`

Looking at the reference from your debug logs, you need to `s/overlay/vfs/` and specify the ID at the end:
> DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage]docker.io/library/ba42db863d2b:latest"

**Comment by cmoulliard** [comment]
Many thanks @vrothberg. I was able to fix my problem after passing as request
```
sudo skopeo --debug copy \
     containers-storage:[vfs@/var/lib/containers/storage+/run/containers/storage]ba42db863d2b \
     oci:$(pwd)/ba42db863d2b:1.0
```
Question:
- Is there a skopeo, ... utility go function that I could use to generate such a syntax `[vfs@/var/lib/containers/storage+/run/containers/storage]` ?
- How can I discover the `graph driver` like the `root path` or `run path` if we can ?

**Comment by cmoulliard** [comment]
> (see `man containers-transports`).

Where can I find such a documentation on github as my centos7 vagrant vm do not display using `man` the `containers-transports` doc @vrothberg

**Comment by cmoulliard** [comment]
> you need to embed the new driver, location etc

The only way to do that is to pass between the `[xxxxxx]` the needed information such as `graph-driver and `storage-paths` ?

**Comment by vrothberg** [comment]
> Where can I find such a documentation on github as my centos7 vagrant vm do not display using `man` the `containers-transports` doc @vrothberg

The upstream docs live in containers/image: https://github.com/containers/image/blob/main/docs/containers-transports.5.md

>     * Is there a skopeo, ... utility go function that I could use to generate such a syntax `[vfs@/var/lib/containers/storage+/run/containers/storage]` ?

https://github.com/containers/image/blob/main/storage/storage_transport.go#L118 will take care of that but you need to create containers/storage.Store object before.

>     * How can I discover the `graph driver` like the `root path` or `run path` if we can ?

If you create a containers/storage.Store object, it will take care of setting the default values.

> The only way to do that is to pass between the [xxxxxx] the needed information such as graph-driver and storage-paths` ?

Alternatively you could create custom storage.conf that sets the specific driver you want.  You point to a non-default storage.conf via an environment variable `CONTAINERS_STORAGE_CONF=/path/to/custom/storage.conf skopeo ...`.

But I do not know whether the skopeo in CentOS 7 supports that already.
