### ISSUE TITLE
what registries does skope support?

### ISSUE THREAD

**Issue by amokkara** [containers/skopeo#1524]
Does skopeo support fetching image digest from gcr and aws?

**Comment by vrothberg** [comment]
Yes, it supports these registries.

**Comment by amokkara** [comment]
@vrothberg is there a version available where i can import the project as go module? i dont want a cli. Is there any way to this?

**Comment by vrothberg** [comment]
@amokkara, Skopeo is a CLI tool only and is not meant to be imported as a Go module.  Skopeo builds around the github.com/containers/image library. Feel free to have a look at the Skopeo code on how to use it.

**Comment by amokkara** [comment]
@vrothberg  in github.com/containers/image, how to get bearer token for a registry? is there a method that i can call or it should be manually provided by user

**Comment by vrothberg** [comment]
@amokkara all registry-related code is in https://github.com/containers/image/blob/main/docker/docker_client.go but bearer tokens are not something the API exposes to the user.

**Comment by amokkara** [comment]
@vrothberg sorry, didnt quite get it.. bearer tokens should be provided by the user explicitly?

**Comment by vrothberg** [comment]
No, bearer tokens are not something the user has to worry about at all.  Can you elaborate what you want to do?

**Comment by amokkara** [comment]
@vrothberg  How can we provide login credentials?

currently this is how im running it 

`ref, err := docker.ParseReference("//registry-1.docker.io/library/ubuntu:latest")
		if err != nil {
			panic(err)
		}
		ctx := context.Background()
	dig,err := docker.GetDigest(ctx,&types.SystemContext{OSChoice: "linux", **DockerBearerRegistryToken**: "**<some token>**"},ref)
`

AS you see here, im providing bearer token..How else can we do this with me providing bearer token. Is there a method to call this?

And this code is for dockerhub.. is it same for google container registry?

**Comment by vrothberg** [comment]
> AS you see here, im providing bearer token..How else can we do this with me providing bearer token. Is there a method to call this?

If you have the bearer token, you can specify it there. You can also specify credentials via https://github.com/containers/image/blob/main/types/types.go#L615.
 
> And this code is for dockerhub.. is it same for google container registry?

Yes.

**Comment by amokkara** [comment]
Just one last thing

what will be the reference for gcr if i have to use it

for dockerhub im using this -> docker.ParseReference("//registry-1.docker.io/library/ubuntu:latest")

**Comment by vrothberg** [comment]
> docker.ParseReference("//registry-1.docker.io/library/ubuntu:latest")

This should `docker.io/library/ubuntu:latest`.  c/image will take care of the rest.

The reference to GCR is the same as you would pass when doing a `podman pull` or `docker pull`.

**Comment by amokkara** [comment]
I tired with `docker.io/library/ubuntu:latest`
but its throwing this error -- panic: docker: image reference docker.io/amokkara/amokkara:2 does not start with // [recovered]

thats why i had to start with //

**Comment by amokkara** [comment]
@vrothberg in case of gcr
what credentials do we provide? username and serviceaccount?
and where to add service account in auth info

**Comment by vrothberg** [comment]
Please have a look at the link above and read the code. The data can be set via https://github.com/containers/image/blob/6f3c8453e1a7d8096e4536512bf883a47e68e9e0/types/types.go#L473.

An example would be:
```golang
sys := types.SystemContext{}
sys.DockerAuthConfig = types.DockerAuthConfig{Username: ..., Password: ...} // also supports identity tokens
```

**Comment by vrothberg** [comment]
>  or is it possible to get username and password from gcr?

Sorry, I don't know enough about GCR internals. Did you have a look at https://cloud.google.com/container-registry/docs/advanced-authentication?

containers/image supports credential helpers and GCR one is known to work.
