### ISSUE TITLE
Building skopeo binary in a container report an error: "/bin/sh: 1: /go/bin/go-md2man: not found"

### ISSUE THREAD

**Issue by lynn447742** [containers/skopeo#1525]
build skopeo binary in a container, when finished return `"/bin/sh: 1: /go/bin/go-md2man: not found".`
![image](https://user-images.githubusercontent.com/87010472/145706844-a937101b-b63f-40fd-ac4c-b495b2b2311d.png)

i git the source code 1.5.2,but the skopeo version is 1.3.0.
![image](https://user-images.githubusercontent.com/87010472/145706906-480353e9-c60f-45e9-9472-5e243c5f803e.png)

**Comment by mtrmac** [comment]
Thanks for your report.

That `docker run …` command doesn’t look like something we maintain; it will probably meed to be adjusted manually.  The need for, and alternatives to, `go-md2man` is documented in `install.md`.

---

WRT the version number discrepancy, are you really running the built version? `PATH` typically doesn’t contain `.`, and the built binary is placed in `bin/skopeo` per the command above. Compare `which skopeo` or `command -v skopeo`.

**Comment by TomSweeneyRedHat** [comment]
@cevich WDYT?

**Comment by cevich** [comment]
This appears like a missing dependencies issue like @mtrmac said.

**Comment by lynn447742** [comment]
> Thanks for your report.
> 
> That `docker run …` command doesn’t look like something we maintain; it will probably meed to be adjusted manually. The need for, and alternatives to, `go-md2man` is documented in `install.md`.
> 
> WRT the version number discrepancy, are you really running the built version? `PATH` typically doesn’t contain `.`, and the built binary is placed in `bin/skopeo` per the command above. Compare `which skopeo` or `command -v skopeo`.


Thank you for your answer.
After I copied the compile command of install.md and add `DISABLE_DOCS=1` to skip building of documentation , the binary  skopeo can be builded normally.
```
docker run -v $PWD:/src -w /src -e CGO_ENABLED=0 golang \
make BUILDTAGS=containers_image_openpgp GO_DYN_FLAGS= DISABLE_DOCS=1
```
![image](https://user-images.githubusercontent.com/87010472/145924447-7f642a68-0cfc-4ca8-9f7e-2e32199bb7a1.png)

**Comment by mtrmac** [comment]
Thanks for the confirmation.
