### ISSUE TITLE
Please update the version in the opensuse repository

### ISSUE THREAD

**Issue by lework** [containers/skopeo#1528]
The version in the opensuse repository is still 1.3.0。Please update the version in the opensuse repository！

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/skopeo_1.3.0-1_amd64.deb

**Comment by rhatdan** [comment]
@lsm5 PTAL
Although I think skopeo is available via yum for OpenSuse.

@vrothberg WDYT?

**Comment by vrothberg** [comment]
The link points to the Ubuntu packages (https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/skopeo_1.3.0-1_amd64.deb).

openSUSE has Skopeo in it's repositories. Ubuntu does not.

I leave it up to @lsm5 to decide whether Skopeo should be updated for 20.04.

**Comment by lework** [comment]
When will this new version be added? Is it possible?

**Comment by TomSweeneyRedHat** [comment]
@lework I think it's possible to be added, but @lsm5 will have to answer next week after he returns from a well-deserved and extended PTO.  Thanks for the patience.

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
apologies all about the late response. Ubuntu 22.04 should be out in about 2 months or less which IIUC should have at least v1.4.1 (https://github.com/containers/skopeo/issues/1535#issuecomment-1030452087). Users should switch to the official ubuntu repos once 22.04 is released and I prefer not to send any further updates to the Kubic repos.

Until 22.04 is released, I would recommend building from source if you would like a newer version.

Closing..
