### ISSUE TITLE
how to cache  layer file when  `skopeo`  copy from docker reigstry to local dir?

### ISSUE THREAD

**Issue by tanguofu** [containers/skopeo#1530]
it is very expensive and time consuming to download many big docker images to local dir; 

as the base image of diff docker image may be same such as  build from `golang` or `java`, and  the sha256 of each layer  will be unique.

is it possible to cache the same sha256 layer accelerate the docker image copy process ?

**Comment by rhatdan** [comment]
Why not copy it to container/storage?

**Comment by tanguofu** [comment]
> Why not copy it to container/storage?

~, i want docker save the images from public docker registry to a tar.gz file,  and dispatch this file to private docker registry which has no interenet access.

and i see the options ` --dest-shared-blob-dir` can cache the blob?

**Comment by mtrmac** [comment]
`dir:` will not download a blob if it already exists in the destination directory.

> and i see the options `--dest-shared-blob-dir` can cache the blob?

As documented, that applies only to the OCI transports.

----

`dir:` is primarily a debugging mechanism; for transporting a large number of images, I’d generally recommend setting up a temporary registry (perhaps running in a container, and almost certainly `localhost`-only), copying images there (benefiting from all the within-repo and cross-repo sharing mechanisms that already exist), copying images to that registry; then transferring the backing storage of that registry to the destination, and again setting up a temporary registry to copy images from.

**Comment by tanguofu** [comment]
As there are Hundreds of images; it is very time cost copy images at every build time~

And why `dir:` is not recommend for use as cache when  transporting a large number of images?  

many thanks!

**Comment by mtrmac** [comment]
Basically the code to reuse blobs across repos, and especially to reuse different but equivalent blobs — and to do all of that in parallel with multiple concurrent writers, is non-trivial, and already exists in `docker://`; so it’s not _that_ attractive to reimplement something similar for `dir`.

Meanwhile, the simplicity of `dir` is valuable in itself, for debugging.

**Comment by tanguofu** [comment]
> especially to reuse different but equivalent blobs

is there possible the  blobs name(sha256) is same but the content is differenet ?  ie  when multiple writer write same blob may corrupt ?

**Comment by tanguofu** [comment]
i get. thanks very much for your detailed explains !
