### ISSUE TITLE
Authenticating with Azure via az acr login seems broken?

### ISSUE THREAD

**Issue by danking** [containers/skopeo#1534]
I executed:
```
az acr login
skopeo copy docker://xyz.azurecr.io/... docker://xyz.azurecr.io/...
```
and I expected Skopeo to successfully copy from the source to the destination. Instead I got this output:
```
Getting image source signatures
FATA[0001] trying to reuse blob sha256:339de151aab4bc06eed8409daae147c408478cb538dacb90cc63f19ad4eba80b at destination: unable to retrieve auth token: invalid username/password: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 
```

The only way I can seem to get skopeo to use credentials with Azure is:
```
az acr login -n xyz --expose-token \
    | jq -r '.accessToken' \
    | skopeo login haildev.azurecr.io \
      --username 00000000-0000-0000-0000-000000000000 \
      --password-stdin
skopeo copy docker://xyz.azurecr.io/... docker://xyz.azurecr.io/...
```
Is this the expected behavior?

I'm on Mac OS X 11.6
```
(base) # skopeo --version
skopeo version 1.5.1
(base) # az --version
azure-cli                         2.30.0 *

core                              2.30.0 *
telemetry                          1.0.6

Python location '/usr/local/Cellar/azure-cli/2.30.0_1/libexec/bin/python'
Extensions directory '/Users/dking/.azure/cliextensions'

Python (Darwin) 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
```

**Comment by mtrmac** [comment]
Thanks for your report.

At least #533 suggests az ` acr login`, _in general_, should work, although it’s not something we explicitly test for. (OTOH the the `--password-stdin` example is surprising to me, and the zero-UUID username, is something else than #533 discusses.)

Can you confirm what file is `az acr login` updating? Does the created entry in that file, for the registry in question, contain an `auth` field, an `identity token` field, or perhaps something else?

Also please provide the output of `skopeo --debug copy …`.

**Comment by danking** [comment]
FWIW, I'm doing this on my work laptop with my human user credentials rather than the credentials of an Azure Service Principal. In my experience, Azure treats human users very differently from SPs. The zero-UUID is specifically for user accounts, I found it [here](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#individual-login-with-azure-ad).

Sure, so, after logging out of my azure registry, my ~/.docker/config.json looks like this:
```
(base) # cat ~/.docker/config.json
{
	"auths": {},
	"credsStore": "desktop",
	"credHelpers": {
		"asia.gcr.io": "gcloud",
		"eu.gcr.io": "gcloud",
		"gcr.io": "gcloud",
		"marketplace.gcr.io": "gcloud",
		"staging-k8s.gcr.io": "gcloud",
		"us.gcr.io": "gcloud"
	},
	"experimental": "disabled",
	"stackOrchestrator": "swarm"
}
```
Then after logging in:
```
(base) # az acr login -n haildev
Login Succeeded
(base) # cat ~/.docker/config.json
{
	"auths": {
		"haildev.azurecr.io": {}
	},
	"credsStore": "desktop",
	"credHelpers": {
		"asia.gcr.io": "gcloud",
		"eu.gcr.io": "gcloud",
		"gcr.io": "gcloud",
		"marketplace.gcr.io": "gcloud",
		"staging-k8s.gcr.io": "gcloud",
		"us.gcr.io": "gcloud"
	},
	"experimental": "disabled",
	"stackOrchestrator": "swarm"
}
```
Which, to be honest, looks suspicious to me. I'm not sure what good adding an entry here without a credential helper would do.

I can successfully use Docker to pull an image:
```
(base) # docker pull haildev.azurecr.io/alpine:3.8
3.8: Pulling from alpine
Digest: sha256:954b378c375d852eb3c63ab88978f640b4348b01c1b3456a024a81536dafbbf4
Status: Downloaded newer image for haildev.azurecr.io/alpine:3.8
haildev.azurecr.io/alpine:3.8
```
But `skopeo inspect` fails:
```
(base) # skopeo --debug inspect docker://haildev.azurecr.io/alpine:3.8
DEBU[0000] Loading registries configuration "/usr/local/etc/containers/registries.conf" 
DEBU[0000] Trying to access "haildev.azurecr.io/alpine:3.8" 
DEBU[0000] No credentials for haildev.azurecr.io found  
DEBU[0000] Using registries.d directory /usr/local/etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for haildev.azurecr.io/alpine:3.8, using built-in default file:///Users/dking/.local/share/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/haildev.azurecr.io 
DEBU[0000] GET https://haildev.azurecr.io/v2/           
DEBU[0000] Ping https://haildev.azurecr.io/v2/ status 401 
DEBU[0000] GET https://haildev.azurecr.io/oauth2/token?scope=repository%3Aalpine%3Apull&service=haildev.azurecr.io 
DEBU[0000] Accessing "haildev.azurecr.io/alpine:3.8" failed: unable to retrieve auth token: invalid username/password: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 
FATA[0000] Error parsing image name "docker://haildev.azurecr.io/alpine:3.8": unable to retrieve auth token: invalid username/password: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information. 
```

It sure seems like Azure is doing something unusual here.

Unfortunately, due to SIP, I can't seem to use dtrace with az, so I'm not sure if its modifying any other files. I'm happy to file a bug against azure-cli, but I'd need some help drafting the right ticket because I'm not familiar with how auth is expected to work in skopeo (or docker, for that matter)

**Comment by mtrmac** [comment]
Thanks, that’s informative.

I’ll only be able to look into the details tomorrow at the earliest — for now just a half-substantiated guess: The credentials have been stored in the `desktop` helper, but Skopeo doesn’t implement `credsStore`.

Does Skopeo work if you add a `"haildev.azurecr.io": "desktop"` entry to the `"credHelpers"` object? That’s not a sustainable fix of course, that would require deeper thought — if it is even the cause.

**Comment by mtrmac** [comment]
@danking 
> Does Skopeo work if you add a `"haildev.azurecr.io": "desktop"` entry to the `"credHelpers"` object? That’s not a sustainable fix of course, that would require deeper thought — if it is even the cause.

**Comment by danking** [comment]
@mtrmac , if I understood you correctly, I tried this and it had no effect. Sorry about the delay in response, thanks for pinging me.
```
(base) # cat ~/.docker/config.json 
{
	"credsStore": "desktop",
	"credHelpers": {
		"haildev.azurecr.io": "desktop",
		"asia.gcr.io": "gcloud",
		"eu.gcr.io": "gcloud",
		"gcr.io": "gcloud",
		"marketplace.gcr.io": "gcloud",
		"staging-k8s.gcr.io": "gcloud",
		"us.gcr.io": "gcloud"
	},
	"experimental": "disabled",
	"stackOrchestrator": "swarm"
}
(base) # skopeo --debug inspect docker://haildev.azurecr.io/alpine:3.8
DEBU[0000] Loading registries configuration "/usr/local/etc/containers/registries.conf" 
DEBU[0000] Trying to access "haildev.azurecr.io/alpine:3.8" 
DEBU[0000] Found credentials for haildev.azurecr.io in credential helper containers-auth.json in file /Users/dking/.docker/config.json 
DEBU[0000] Using registries.d directory /usr/local/etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for haildev.azurecr.io/alpine:3.8, using built-in default file:///Users/dking/.local/share/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/haildev.azurecr.io 
DEBU[0000] GET https://haildev.azurecr.io/v2/           
DEBU[0000] Ping https://haildev.azurecr.io/v2/ status 401 
DEBU[0000] POST https://haildev.azurecr.io/oauth2/token 
DEBU[0000] Accessing "haildev.azurecr.io/alpine:3.8" failed: unable to retrieve auth token: invalid username/password: unauthorized: authentication required 
FATA[0000] Error parsing image name "docker://haildev.azurecr.io/alpine:3.8": unable to retrieve auth token: invalid username/password: unauthorized: authentication required 

```

**Comment by danking** [comment]
I also tried with the `auths` block I had above in addition to the new `credHelpers` entry and that had no effect.

**Comment by mtrmac** [comment]
> ```
> DEBU[0000] Found credentials for haildev.azurecr.io in credential helper containers-auth.json in file /Users/dking/.docker/config.json 
> ```

OK, looks like that one part worked. (It does not explicitly say that it used a credential helper, but those messages were only added in c952f6cf0 ; and anyway the listed `config.json` has no there entries, so if something was found, it must have come from the credential helper.)

---

Does `printf haildev.azurecr.io | docker-credential-helper-desktop get` print a plausible value? It should either contain an `Username`/`Secret` field, or an username `<token>`+ a `Secret` field.

**Comment by mtrmac** [comment]
> When I add debug info in the src code, the error message of Azure registry is:

It’s not clear what this is a response to (no request headers, no URL); assuming this logs the data from a registry response, the actual issue is fairly likely to manifest earlier, in `getBearerToken`/`getBearerTokenOAuth2`.

> The only difference i noted with legitimate call is the content of the Bearer Token which has no Role in the the invalid call

That value comes, unmodified, from the authentication call (one of the two functions above). So if the authentication server is not _rejecting_ the credentials, but returns credentials that are not acceptable, it’s either that the credentials just don’t have access (e.g. are not assigned that role), or possibly we are not asking for the right values ( https://github.com/containers/image/issues/1478 — but if the issue is really with a Role field, not scopes, that is a bit likely to be unrelated ).

**Comment by danking** [comment]
Sorry for the latency on my end. I had to use a slightly different credential command, but, yeah, I do get a plausible value 

```
printf haildev.azurecr.io | docker-credential-desktop get
```
```
{
  "ServerURL": "haildev.azurecr.io",
  "Username": "<token>",
  "Secret": ...
}
```

**Comment by mtrmac** [comment]
Thanks @danking . That looks fine, and along with @amine-khemissi ’s report suggests that something is wrong, or behaving differently from Docker at least, in or around `dockerClient.getBearerTokenOAuth2` ; just by reading that code, I’m not sure what the difference is.

**Comment by rhatdan** [comment]
@mtrmac Any further thoughts?

**Comment by skycaptain** [comment]
> Does Skopeo work if you add a `"haildev.azurecr.io": "desktop"` entry to the `"credHelpers"` object? That’s not a sustainable fix of course, that would require deeper thought — if it is even the cause.

Had the same issue, however adding an entry as suggested above works for me. My `config.json` now looks like this:
```json
...
"credsStore": "desktop",
"credHelpers": {
	"[REDACTED].azurecr.io": "desktop"
},
...
```

```bash
$ az acr login -n [REDACTED]
Login Succeeded
$ skopeo --debug inspect docker://[REDACTED].azurecr.io/my-azure-image
...
DEBU[0012] Found credentials for [REDACTED].azurecr.io/my-azure-image in credential helper containers-auth.json in file /Users/[REDACTED]/.docker/config.json
...
```

**Comment by SantoshG-Derivco** [comment]
> > Does Skopeo work if you add a `"haildev.azurecr.io": "desktop"` entry to the `"credHelpers"` object? That’s not a sustainable fix of course, that would require deeper thought — if it is even the cause.
> 
> Had the same issue, however adding an entry as suggested above works for me. My `config.json` now looks like this:
> 
> ```json
> ...
> "credsStore": "desktop",
> "credHelpers": {
> 	"[REDACTED].azurecr.io": "desktop"
> },
> ...
> ```
> 
> ```shell
> $ az acr login -n [REDACTED]
> Login Succeeded
> $ skopeo --debug inspect docker://[REDACTED].azurecr.io/my-azure-image
> ...
> DEBU[0012] Found credentials for [REDACTED].azurecr.io/my-azure-image in credential helper containers-auth.json in file /Users/[REDACTED]/.docker/config.json
> ...
> ```

This worked for me also.

**Comment by mtrmac** [comment]
@danking Is this still outstanding? Given the multiple reports above that adding a `credHelpers` entry makes a difference, I’m not sure what’s the current situation.

**Comment by danking** [comment]
I haven't tried recently and I don't have to use azure from my laptop these days. I'll reopen if I discover the issue again. thanks all!

**Comment by danking** [comment]
I cleared all the azure instances from my docker config, updated `az`, and tried to get this to work from a clean slate and it still didn't produce that critical `credHelpers` entry:
```
(base) dking@wm28c-761 hail % az version  
{
  "azure-cli": "2.48.1",
  "azure-cli-core": "2.48.1",
  "azure-cli-telemetry": "1.0.8",
  "extensions": {}
}
(base) dking@wm28c-761 hail % az acr login -n haildev.azurecr.io
The login server endpoint suffix '.azurecr.io' is automatically omitted.
Login Succeeded
(base) dking@wm28c-761 hail % cat ~/.docker/config.json
{
	"auths": {
		"haildev.azurecr.io": {},
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "desktop",
	"credHelpers": {
		"asia.gcr.io": "gcloud",
		"eu.gcr.io": "gcloud",
		"gcr.io": "gcloud",
		"marketplace.gcr.io": "gcloud",
		"staging-k8s.gcr.io": "gcloud",
		"us-docker.pkg.dev": "gcloud",
		"us.gcr.io": "gcloud"
	}
}
(base) dking@wm28c-761 hail %
````

**Comment by mtrmac** [comment]
@danking Thanks. The code of the config file processing did change a bit between Skopeo 1.5.2 and 1.12., but I can’t see anything that would explain the previous behavior of `credHelpers` not working if it works now.

---

Given that, I think the gist of the situation is that Skopeo et al. don’t support `credsStore`; so, I guess (without reading that code) that `az acr login` finds the `credsStore` entry and writes the credential there, but Skopeo needs a `credHelpers` entry.

Adding support for `credsStore` is tracked as half-finished PRs in the containers/image repository; the difficulty there is that the the primary read-write location for Podman and Skopeo is a non-persistent `/run/user/…auth.json`, and storing credential helper configurations in a non-persistent file does not make much sense.

A possible one-time workaround is to set `credential-helpers` in `registries.conf` to include the helper set in `credsStore` (maybe to `["containers-auth.json", "desktop"]`); that would cause Docker and Podman/Skopeo to more closely match the searched locations.
