### ISSUE TITLE
Official Ubuntu Repos only install 1.1

### ISSUE THREAD

**Issue by ldanielw1** [containers/skopeo#1535]
Latest installs with `apt-get` on ubuntu only install 1.1 - is there any chance we can get an update up to 1.5?

**Comment by mtrmac** [comment]
@lsm5 is that something we manage?

**Comment by lsm5** [comment]
apologies, seeing this just now. @ldanielw1 If this is still an issue, I suggest you file a bug on ubuntu's launchpad because it's best handled there. I'm gonna close this but also copy @siretart , the official debian and ubuntu package maintainer so it's on his radar.

**Comment by siretart** [comment]
versions currently available in Debian:

```
skopeo     | 1.2.2+dfsg1-1+b6 | stable         | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
skopeo     | 1.4.1+ds1-1      | testing        | source, amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
skopeo     | 1.4.1+ds1-1      | unstable       | source, amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
```

versions available in ubuntu:

```
 skopeo | 1.2.2+dfsg1-1 | impish/universe | source, amd64, arm64, armhf, ppc64el, riscv64, s390x
 skopeo | 1.4.1+ds1-1   | jammy/universe  | source, amd64, arm64, armhf, ppc64el, riscv64, s390x
```

I'm not sure where the version 1.1 is coming from
