### ISSUE TITLE
Library support

### ISSUE THREAD

**Issue by 030** [containers/skopeo#1539]
I would like to use the copy skopeo functionality in other go code, but I do not see a pkg folder. Would it be possible to move some code to the pkg folder and release a library so it could be called in other Golang projects?

**Comment by mtrmac** [comment]
Thanks for your report.

See https://github.com/containers/image ; most of Skopeo is a pretty thin wrapper around it. (And in turn, Skopeo can be used as a source of examples of how to use the library.)
