### ISSUE TITLE
Does skopeo-copy copy multiarch images?

### ISSUE THREAD

**Issue by Noksa** [containers/skopeo#1552]
If I have an image for arm/amd arch as one tag (backed by different manifests), will skopeo copy all of them if it copies only the same arch as a host has?

**Comment by mtrmac** [comment]
Thanks for your report. See the `--all` option, or perhaps the `--multi-arch` option, of `skopeo copy`.

**Comment by Noksa** [comment]
Thanks

**Comment by leon0306** [comment]
> Thanks for your report. See the `--all` option, or perhaps the `--multi-arch` option, of `skopeo copy`.

there's any example for `--multi-arch` ? 
i wanna copy arch of amd64, arm64 image to private registry

**Comment by mtrmac** [comment]
`--multi-arch` doesn’t allow picking up an _arbitrary_ subset right now, although it’s designed to allow adding such a feature ion the future.

**Comment by slhck** [comment]
For those coming here via a web search, the actual command to run is:

```
skopeo copy --multi-arch all docker://registry1.example.com/image docker://registry2.example.com/image
```

This will show something like:

```
Getting image list signatures
Copying 3 of 3 images in list
Copying image sha256:eb0eefcefceb0761aa79ec2046be640fc9f755e72c9d4fba1d1d9959e5415d8d (1/3)
Getting image source signatures
...
```
