### ISSUE TITLE
Copy command doesn't work if a proxy requires a specific user-agent value

### ISSUE THREAD

**Issue by Noksa** [containers/skopeo#1553]
Hello.

We use a docker registry in Nexus OSS. To be able to use it as DNS name without full url of registry we use nginx as reverse-proxy.

Config is like this:
```
  location /
  {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;

    if ($http_user_agent ~ docker|Docker|cri-o|containerd) {
      proxy_pass http://127.0.0.1:10081;
    }
    # Use IPv4 upstream address instead of DNS name to avoid attempts by nginx to use IPv6 DNS lookup
    proxy_pass http://127.0.0.1:8081/;
```

So if `http_user_agent` is docker or similar - we go directly to the docker registry.

But it looks like `skopeo` doesn't use this header.

So I'm getting the following error:

```
➜ ~ skopeo copy --all docker://rabbitmq:3.9.13 docker://blabla.com/3rdparty/rabbitmq:3.9.13
Getting image list signatures
Copying 6 of 6 images in list
Copying image sha256:9d5ee37c1f61bd31bda3b697e81881d59ce235bab59f5bb1b8ae750b4ce66d4a (1/6)
Getting image source signatures
FATA[0003] trying to reuse blob sha256:ea362f368469f909a95f9a6e54ebe0121ce0a8e3c30583dd9c5fb35b14544dec at destination: pinging container registry blabla.com: invalid status code from registry 404 (Not Found)
```

**Comment by Noksa** [comment]
Can I set custom `User-Agent` header somehow?

**Comment by mtrmac** [comment]
Thanks for your report.

I mean … change the server configuration? It makes no sense for Skopeo, by default, to pretend to be Docker or CRI-O, and there’s only so far it makes sense to add workarounds for any custom configuration anyone could ever create.

There isn’t currently a CLI option to change the user-agent header, and I’m not sure adding that feature is net beneficial (compare https://github.com/containers/skopeo/issues/1212 ).
