### ISSUE TITLE
Is skopeo efficient to copy several images of the same remote repository?

### ISSUE THREAD

**Issue by ioanvapi** [containers/skopeo#1563]
I want to copy several images of the same remote repository to another remote repository. 
Ex:
skopeo copy docker://some-remote-server/myrepo:0.1 docker://another-remote-server/myrepo:0.1
skopeo copy docker://some-remote-server/myrepo:0.2 docker://another-remote-server/myrepo:0.2
skopeo copy docker://some-remote-server/myrepo:0.3 docker://another-remote-server/myrepo:0.3
skopeo copy docker://some-remote-server/myrepo:0.4 docker://another-remote-server/myrepo:0.4

Is this sequence efficient? I mean, If I would use docker pull, tag, push then docker pull will fetch just the new image layers for tags  0.2, 0.3 and 0.4.

Question: Will skopeo copy for tag 0.4 fetchs the entire 0.4 image and not reuse layer from previous tags?
Is there a way to specify just the repo and skopeo does the copy just pulling new layes of tags?  
How to use efficiently skopeo to copy and entire remote repository to another remote repository?
Thanks.

**Comment by mtrmac** [comment]
I’d expect `skopeo copy` to reuse the same layers as Docker in this situation (and to be _significantly_ more efficient for the actual copy of a layer).

WRT copying entire repositories, see `skopeo sync`.

#1498 discusses efficiency of copying _very large_ numbers of images, and ways to possibly improve it, in more detail.

**Comment by ioanvapi** [comment]
Is't _skopeo sync_ used to syncrhonize local repositories to remote repositories? I need to use skopeo to sync two remote repositories, ex: a GCR repo with a ECR repo. What would be the best approach to do that?

**Comment by mtrmac** [comment]
> Is't _skopeo sync_ used to syncrhonize local repositories to remote repositories? I need to use skopeo to sync two remote repositories

It does both.
