### ISSUE TITLE
skopeo copy only the manifest.json file?

### ISSUE THREAD

**Issue by ldanielw1** [containers/skopeo#1571]
I was wondering if there'd be any way for us to download a container's manifest.json file (and only that file)? This is primarily for verification purposes, and we were thinking that it'd be especially nice to not have to download EVERYTHING of the container just to verify a signature, if that'd be ok?

**Comment by vrothberg** [comment]
Thanks for reaching out, @ldanielw1!

> I was wondering if there'd be any way for us to download a container's manifest.json file (and only that file)? 

`skopeo inspect --raw` does that.

> This is primarily for verification purposes, and we were thinking that it'd be especially nice to not have to download EVERYTHING of the container just to verify a signature, if that'd be ok?

I don't think that would be sufficient. There is everlasting risk of a time-of-check-time-of-use issue. To verify the signature, we should recompute the manifest and for that we need the entire image (including layers).

@mtrmac WDYT?

**Comment by mtrmac** [comment]
Yes; “verify a signature, and if it is OK, it is safe to use the image” is _usually_ not true.

The **only recommended** way to verify signatures is to verify them *at pull by the **actual end user***, using a configured `policy.json`.

It is possible to design other safe workflows, but that requires changing more components than just a single config file, requires some attention detail, deep understanding, and most importantly the ability to enforce that no-one without that attention to detail or deep understanding will be in a position to “simplify” the process.

“Have `root` edit `/etc/containers/policy.json` on all relevant computers” is much easier to explain, follow, and audit.

**Comment by ldanielw1** [comment]
ok - but what if we already downloaded the image for use to the docker-daemon - then it'd be ok to just just do a
`skopeo inspect --raw docker-daemon://IMAGE_NAME`, right?

Also, is there a way to inspect for only the signature...?

**Comment by mtrmac** [comment]
The signature is lost when pushing to `docker-daemon`, so no, that’s impossible.

Enforce the signature during the pull to `docker-daemon`.

**Comment by ldanielw1** [comment]
Got it, that's good enough for me then! Thank you!
