### ISSUE TITLE
skopeo copy doesn't copy image signature into local directory

### ISSUE THREAD

**Issue by shenqinb-star** [containers/skopeo#1580]
I'm trying to use skopeo to sign the container image. JFrog Artifactoy is the container registry. below steps are we have done

**Sign Container Image from within a RHEL8 container**
`skopeo copy docker://https://artifactory-registry/image:unsiged  docker://https://artifactory-registry/image:signed  --sign-by ${gpgfingerprint} `  ## Sign a Image
`skopeo copy docker://https://artifactory-registry/image:signed  dir:/imagesigned`  ## Pull Signed Image to local directory
I can find signature in the local directory via `ls :/imagesigned `
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/79623318/156190701-e6edc0ef-beb7-4a3c-9cf2-6b5ad8aa90cf.png">

**Copy Signed Image into Local Directory on my MacOS, But signature doesn't appear**
skopeo copy docker://https://artifactory-registry/image:signed  dir:/imagesigned` 
I can't find the signature in the local directory of my MacOS
<img width="924" alt="image" src="https://user-images.githubusercontent.com/79623318/156191006-371f8d8b-843a-4f71-8de8-e1f9bbea05f4.png">

I didn't find skopeo sign docs. Need someone's help to find what's the problem. many thanks!

**Comment by mtrmac** [comment]
Thanks for your report.

> `docker://https:`

(That is, or should be, invalid syntax that is rejected. Assuming a copy-paste error while writing the report.)

---

Is the macOS system configured to access the same sigstore? See `registries.d/*.yaml`. `skopeo --debug` shows where it reads these config files, and what “signature storage configuration” is used.

**Comment by mtrmac** [comment]
>```
>No signature storage configuration found for tools.boomerangplatform.net:8500/boomerangcicdteam/springboot-checkout:master-4-1, using built-in default file: ///var/lib/containers/sigstore
>```

Signatures are not stored in registries (unless the registry specifically supports X-Registry-Supports-Signatures, like the OpenShift integrated registry; I don’t know if any other registry supports that).

You need to set up a process to publish the signatures created locally when signing, and to configure clients to access those published signatures. Compare maybe https://gist.github.com/saschagrunert/1d0b3cc40ce0418558d7c2a5a8fe8a1c .

**Comment by mtrmac** [comment]
(The description now says something about copying files; was that edited later?) For local files, note that the debug log shows the exact location where it is looking for signatures , see the line ending with `/signature-1`.

The “Reading …-1” line means that file does not exist.

**Comment by shenqinb-star** [comment]
Thanks for all your reply, now I understand it, close this issue.
