### ISSUE TITLE
(make docs) and (make binary) commands fail on Ubuntu

### ISSUE THREAD

**Issue by jameskim0987** [containers/skopeo#1584]
I'm trying to do a clean install skopeo, Building from Source (**in** a container), but at `make docs` and `make binary` step seems to fail.

- Environment: `Ubuntu 18.04`
- Installed Go Version: `go version go1.17.7 linux/amd64`
- root@ubuntu1804:~# make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- root@ubuntu1804:~# podman --version
podman version 3.0.1

Some issues:
- root@ubuntu1804:~# go-md2man version
    **Output hangs**
- root@ubuntu1804:~# podman info
**Error: failed to mount overlay for metacopy check with "nodev,metacopy=off" options: invalid argument**

```
root@ubuntu1804:~/workspace/skopeo# make docs
make: command: Command not found
sed -e 's/\((skopeo.*\.md)\)//' -e 's/\[\(skopeo.*\)\]/\1/' docs/skopeo.1.md  | /bin/go-md2man -in /dev/stdin -out docs/skopeo.1
make: command: Command not found
/bin/sh: 1: /bin/go-md2man: not found
Makefile:147: recipe for target 'docs/skopeo.1' failed
make: *** [docs/skopeo.1] Error 127
```
and

```
root@ubuntu1804:~/workspace/skopeo# make binary
make: command: Command not found
Error: failed to mount overlay for metacopy check with "nodev,metacopy=off" options: invalid argument
docker run --rm -i -e TESTFLAGS="-v -check.v -test.timeout=15m" -e CI= -e SKOPEO_CONTAINER_TESTS=1 -t --security-opt label=disable -v /root/workspace/skopeo:/src/github.com/containers/skopeo -w /src/github.com/containers/skopeo  make bin/skopeo  BUILDTAGS='  libdm_no_deferred_remove '
make: command: Command not found
Unable to find image 'make:latest' locally
docker: Error response from daemon: pull access denied for make, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Makefile:135: recipe for target 'binary' failed
make: *** [binary] Error 125
```

I'm not completely sure why the make command is not found when running the make command in the skopeo directory. 
Could I get some pointers on how to start debugging this issue?

**Comment by mtrmac** [comment]
Thanks for your report.

`command` is a POSIX-defined utility, usually a shell builtin. Are you using some obscure weird shell?

**Comment by jameskim0987** [comment]
I'm using a clean bash that comes with Ubuntu 18.04. I haven't changed anything regarding the bash shell.

**Comment by vrothberg** [comment]
Please use the `-local` make targets when already running inside a container.  Running nested containers can be tricky as it outside the scope. `make binary` will otherwise setup a container automatically.

For the remainder, please refer to the install instructions: https://github.com/containers/skopeo/blob/main/install.md

**Comment by mtrmac** [comment]
> This issue should not be closed. There is no nested container here, `make binary` is what OP refers to as `(in a container)`. The problem is that the build does not work on Ubuntu 18.04 and 20.04 (LTS).

```console
# podman run -it --rm ubuntu:latest
…
root@8d9e21426d94:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
root@8d9e21426d94:/# command -v go-md2man
```
no failure
```console
…
root@8d9e21426d94:/# apt-get update
…
root@8d9e21426d94:/# apt-get install git make
…
root@8d9e21426d94:/# git clone https://github.com/containers/skopeo
…
root@8d9e21426d94:/# cd ./skopeo/
root@8d9e21426d94:/# make docs
make: go: Command not found
make: go: Command not found
make: command: Command not found
sed -e 's/\((skopeo.*\.md)\)//' -e 's/\[\(skopeo.*\)\]/\1/' docs/skopeo.1.md  | /bin/go-md2man -in /dev/stdin -out docs/skopeo.1
make: command: Command not found
/bin/sh: 1: /bin/go-md2man: not found
```
OK, so that does fail on `command` not being found…
```console
root@8d9e21426d94:/skopeo# dash -c 'command -v go-md2man'
root@8d9e21426d94:/skopeo# sh -c 'command -v go-md2man'
root@8d9e21426d94:/skopeo# echo $SHELL
/bin/bash
root@8d9e21426d94:/skopeo# bash -c 'command -v go-md2man'
```
… but none of this fails.

> 
> Other issues like `awk: not an option: -e` (from `hack/get_fqin.sh`) also happen for me on 20.04.
```console
root@8d9e21426d94:/skopeo# awk -F "=" -e '{print $2}' < /dev/null
awk: not an option: -e
root@8d9e21426d94:/skopeo# dpkg -S /bin/sh
diversion by dash from: /bin/sh
diversion by dash to: /bin/sh.distrib
dash: /bin/sh
root@8d9e21426d94:/skopeo# ls -la /usr/bin/awk*
lrwxrwxrwx. 1 root root 21 Mar 16 17:07 /usr/bin/awk -> /etc/alternatives/awk
root@8d9e21426d94:/skopeo# ls -la /etc/alternatives/awk 
lrwxrwxrwx. 1 root root 13 Mar 16 17:09 /etc/alternatives/awk -> /usr/bin/mawk
```

---

So, yes, those issues are real.

But navigating compatibility between standard GNU tools (bash, gawk) and macOS is non-trivial enough, and I’m afraid this is not something I can personally spend time on. A clean PR fixing this, and not breaking the primary development platforms, would be welcome.

**Comment by lewisdiamond** [comment]
> and not breaking the primary development platforms
Are those listed somewhere?

**Comment by rhatdan** [comment]
Should we care about a 4 year old OS?  I don't see anyone interested in fixing this, so the issue will just languish.

**Comment by mtrmac** [comment]
There is a report of this affecting 20.04, so not just a 4-year old system. Still, this is only likely to be fixed if an Ubuntu user contributes a fix.

**Comment by rhatdan** [comment]
Since no one has touched, I am closing.
