### ISSUE TITLE
no image found in manifest list for architecture amd64, variant "", OS darwin FAIL

### ISSUE THREAD

**Issue by finalcreator** [containers/skopeo#1586]
$ skopeo copy docker://docker.io/alpine:latest docker-daemon:docker.io/alpine:latest                                             [18:16:36]
FATA[0005] choosing an image from manifest list docker://alpine:latest: no image found in manifest list for architecture amd64, variant "", OS darwin
FAIL

**Comment by mtrmac** [comment]
Thanks for your report.

The default value of `--multi-arch` is `system` (matching the environment where Skopeo is run), and there is no macOS variant for the `alpine` image. If you want to copy some other variant, see `--override-{os,arch,variant}`.

**Comment by finalcreator** [comment]
> Thanks for your report.
> 
> The default value of `--multi-arch` is `system` (matching the environment where Skopeo is run), and there is no macOS variant for the `alpine` image. If you want to copy some other variant, see `--override-{os,arch,variant}`.
I have two quesitons:

1. Is there a way to find all supported arc/os for a image?
2. How to get the url (docker://docker.io/alpine) of an image, when I use docker hub , there is no such imformation.


Thanks anyway. I can run with following.
$ skopeo inspect docker://docker.io/alpine --override-os linux --override-arch amd64                                                                                                                   
{
    "Name": "docker.io/library/alpine",
    "Digest": "sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300",
    "RepoTags": [
        "2.6",

**Comment by mtrmac** [comment]
> * Is there a way to find all supported arc/os for a image?

What are you actually trying to achieve, at a higher level? This is not an _unreasonable_ question to ask, but it’s a surprising question to start with.
