### ISSUE TITLE
Skopeo not using rate limit free call to compare digest

### ISSUE THREAD

**Issue by sanderc85** [containers/skopeo#1587]
I'm using Skopeo to sync images from Docker hub to ECR. Currenty, I'm running against the rate limit of Docker, while the images are the same on our destination repository. Currently the digest is compare inside https://github.com/containers/image/blob/ebf47f4/copy/copy.go, but it's using GET requests. I saw that can be bypassed by getting the digest from https://github.com/containers/image/blob/2d0e142/docker/docker_image.go#L116? Would this be possible?

**Comment by mtrmac** [comment]
Thanks for your report.

It’s not easily possible with the public c/image transport API as it currently exists. We are now building, for other reasons, infrastructure to extend the API (`containers/image/internal/private` and the like), and that would make adding that a bit easier, in the order of about a month.

Still, if the _source_ is Docker, that would be at best an opt-in behavior: GET and HEAD are very likely to take just about the same amount of time, and _actually copying_ the data would require a GET request. So starting with a HEAD is always more expensive than just doing a GET when having to do a copy, _and_ we would have to worry about the registry returning different data in the two (e.g. when the source tag moves concurrently to the copy).

**Comment by sanderc85** [comment]
I'll get it. That way it would be better to only do a GET-request indeed.
