### ISSUE TITLE
How to install the latest version 1.6.1 of skopeo on CentOS7/SLES15/RHEL8 Operating systems?

### ISSUE THREAD

**Issue by mehulgogri** [containers/skopeo#1598]
How to install the latest version of skopeo on CentOS7/SLES15/RHEL8 Operating systems?

CentOS7: yum install -y skopeo
In this case skopeo version 0.1.40 is installed

SLES:  zypper in -y skopeo
In this case, skopeo version 0.1.41 is installed

How do I install skopeo version 1.6.1 on these Operating Systems?

**Comment by mtrmac** [comment]
Thanks for your report.

Stable distributions generally don’t update to latest versions of software. Compare also https://github.com/containers/skopeo/issues/1277 .

Assuming a new enough Go tooling, you can build Skopeo from source, using something like https://github.com/containers/skopeo/blob/main/install.md#building-without-a-container , or perhaps make your own packages.

**Comment by mehulgogri** [comment]
@mtrmac I want to use the skopeo login and skopeo logout feature which is only available in v1.0.0 and above. Any possibility that any skopeo package version between v1.0.0 and v1.6.1 will be made available for RHEL and SLES OS distriution?

**Comment by mtrmac** [comment]
What RHEL and SLES provide is decided by RHEL and SLES.

As for the upstream Skopeo project providing third-party packages for these distributions, my reading of #1277 is that we are no longer doing that for these distributions; I’ll let @lsm5 confirm.

**Comment by vrothberg** [comment]
An alternative may be using the container images we provide on `quay.io/skopeo/stable`.  The images includes skopeo and can be used as `podman run quay.io/skopeo/stable $command`.

**Comment by mehulgogri** [comment]
@lsm5 @vrothberg @mtrmac Thanks for your responses.
For time being I will manually create the skopeo bin and unblock myself, till we find some better solution to install new version of skopeo in the operating systems that we support for my project.

Question: Once I have created a skopeo bin file in SLES15 operating system, can I use this same bin file in any other operating system to install skopeo? or should I create skopeo bin files separately for each operating system?

**Comment by mtrmac** [comment]
In general, different Linux distributions are not binary-compatible, at the very least due to version differences. Some specific pairs may be.
