### ISSUE TITLE
FEAT: having skopeo show repotags with the same digest

### ISSUE THREAD

**Issue by georgettica** [containers/skopeo#1601]
I know websites have in their UI's "the latest tag is also where other tags live" (see https://hub.docker.com/_/ubuntu?tab=description) in the line with `"20.04, focal-20220316, focal, latest"`

I would like `skopeo inspect` or `skopeo list-tags` (or anther endpoint)  to show me what are the matching tags with the same digest.

I want this so I can rely most of the time on digest in my codebase, but see if I drifted from a tag (it has been retagged and the digest is pointing to an old commit) or just to help devs get the tag names for the digest I pushed

**Comment by mtrmac** [comment]
Thanks for your report.

This feature is not natively available in the API; Skopeo would have to enumerate all the tags, and query the registry one by one to discover the manifest digest and see if the digest matches.

That can, of course, be done, but it’s a fair number of operations for repositories with many tags. I’m not quite sure it is desirable for Skopeo to provide this as an automated feature, where users could be causing non-trivial registry load without being aware of that cost.

Of course a determined user can always implement that loop, e.g. in a shell script that calls `skopeo list-tags` + `skopeo inspect`, but the unavailability of this operation might serve as a nudge to consider other options.

For example, a tag convention that allows reliably sorting the version numbers would allow figuring out which tag is the latest just from the tag name.

**Comment by georgettica** [comment]
I see and I am sad that this is not exposed by the registries API.

I will close it and add a script to do that, so at maybe the API devs will add that function to reduce their load

**Comment by georgettica** [comment]
(I'll close when I have that script ready)

**Comment by georgettica** [comment]
https://github.com/georgettica/check-image-digest
and closing the issue (sadly)
