### ISSUE TITLE
repositories file inside tar file is empty after skopeo copy with docker-archive

### ISSUE THREAD

**Issue by mehulgogri** [containers/skopeo#1609]
I am running the skopeo command as follow:
(Example command)
`skopeo copy --src-tls-verify=false  docker://marketplace.io/busybox:latest docker-archive:tmp1/busybox_latest.tar`

This will download the docker image `busybox:latest` and save it in the tar file `busybox_latest.tar`. We are downloading the image from Harbor registry.

Now when I do `docker load < busybox_latest.tar` it loads the image with name and tag as `<none>` (Checked it using docker command `docker images -a`)

Am I missing passing any parameter to skopeo copy command?

**Comment by mtrmac** [comment]
Thanks for your report.

Yes; `skopeo copy` creates the source and destination as completely independent, it does not transfer anything from the source name to the destination. Try something like `docker-archive:path.tar:marketplace.io/busybox:latest`.

**Comment by mehulgogri** [comment]
@mtrmac Thanks for the response. I already figured out how to use docker-archive in the copy command from one of your unit tests. We should add this in the `skopeo copy` documentation on how to use skopeo copy command with docker-archive.

**Comment by mehulgogri** [comment]
Another example would be very helpful. Also, docker-archive example would be more helpful.
