### ISSUE TITLE
fea: `skopeo sync` support use src or dest  use oci format

### ISSUE THREAD

**Issue by tanguofu** [containers/skopeo#1619]
oci format did support the `dest_shared_blobs` which can reduce the images size when there are lots of images.

oci format also support the `src_shared_blobs` which can reduce the unnecessary downloads.

**Comment by mtrmac** [comment]
(There’s more discussion about the tradeoffs in #1620; sharing blobs does sound desirable, but using the OCI format is probably not the right way todo it.)
