### ISSUE TITLE
regarding the incompatibility of Skopeo and docker together.

### ISSUE THREAD

**Issue by Pawanpreetkaur175** [containers/skopeo#1622]
I had a query that while using the command : sudo dnf -y install skopeo and we get latest version 1.6.0 . But as requirement we need skopeo 1.6.0  - but if we install 1.6, it is uninstall docker..
We are on CentOS8 which have Docker  Version:  20.10.1 is bring skopeo 1.4.0. so with skopeo 1.6.0 which version of docker will be compatible as we require the skopeo copy --sign-passphrase-file path command which is available on skopeo 1.6.0 not on 1.4.0. Kindly solve the issue as early . thanks in advance.

**Comment by rhatdan** [comment]
Skopeo requires containers-common which require the latest runc.  Docker has a hard requirement for a particular version of runc, so these conflict.  Open an issue with Docker to make the version of runc that it ships private to docker and store it somewhere like /usr/libexec/docker/runc.  Docker should not be conflicting with standard distro packages.

Have you looked at Podman.

If you need docker and the latest skopeo, then you could attempt to run skopeo in a privileged container launched by Docker, or just use Podman.  :%)

**Comment by Pawanpreetkaur175** [comment]
@rhatdan can you please send the way how to approach to sign and push the image to container registry with the approach of podman tool. so please help us out.

**Comment by rhatdan** [comment]
Are you talking about signing it with Docker Notary?  If yes, then this is not supported with Podman or Skopeo for that matter.
Podman and Skopeo support simple signing.
