### ISSUE TITLE
Does it change the md5 of a image's layers when use skopeo copy with oci args

### ISSUE THREAD

**Issue by lynn447742** [containers/skopeo#1623]
Hello:

i have a docker image named `demo:v1` in registry A,  I use `skopeo copy docker://registryA/demo:v1 oci:local:registryA/demo:v1` to copy to local, then use `skopeo copy oci:local:registryA/demo:v1 docker://registryB/demo:v1 ` to copy to registry B.

**my question is**：
the image `demo:v1` whether in registry A and in registry B have the same md5.

**Comment by vrothberg** [comment]
Thank you for reaching out!  Are you referring to the sha256 sum / the digest of the image or an individual layer?

**Comment by lynn447742** [comment]
> Are you referring to the sha256 sum / the digest of the image or an individual layer?
the digest of the image

**Comment by vrothberg** [comment]
@lynn447742, the layers should remain untouched, so their digests won't change.  The digest of the image _may_ change.

For the _manifest_ it depends whether the initial image was in the OCI or Docker format.  If it remains in the OCI, nothing should change. If the initial image was in the Docker format, it will certainly change.

**Comment by lynn447742** [comment]
> @lynn447742, the layers should remain untouched, so their digests won't change. The digest of the image _may_ change.
> 
> For the _manifest_ it depends whether the initial image was in the OCI or Docker format. If it remains in the OCI, nothing should change. If the initial image was in the Docker format, it will certainly change.


 thanks very much
