### ISSUE TITLE
Publish latest versions?

### ISSUE THREAD

**Issue by rbren** [containers/skopeo#1625]
The latest version available for alpine via `apk add` is 1.5.2, which contains a lot of vulnerabilities. Can we get a release for 1.7.0?

https://pkgs.org/download/skopeo

**Comment by TomSweeneyRedHat** [comment]
@lsm5 do you by chance know how or who updates Skopeo on Alpine?

**Comment by mtrmac** [comment]
https://pkgs.alpinelinux.org/packages?name=skopeo&branch=edge has a maintainer contact — and also shows 1.7.0.

I have also found https://git.alpinelinux.org/aports/log/community/skopeo/APKBUILD ; apparently the package is maintained by the Alpine community, so any requests to update specific branches need to be directed at them. I don’t use Alpine, so I’m not sure what the right place is, maybe https://gitlab.alpinelinux.org/alpine/aports/-/issues .

**Comment by rhatdan** [comment]
Since this is a downstream version, I am closing.  You can continue the conversation here, but not something the upstream can fix.

**Comment by lsm5** [comment]
Would it be worthwhile to update our docs to also include links to downstream package info (maintainer / link to source etc.) so that people know where to go when they get here?

**Comment by mtrmac** [comment]
Good idea, that would definitely be valuable — both for users, and for us to as a quick way to find the authoritative information about what version any particular distribution ships, where to find a packager contact, and the like.

**Comment by lsm5** [comment]
@mtrmac ack, is it best listed in install.md along with the installation info for each distro? Or do you prefer README.md or a separate doc?

**Comment by lsm5** [comment]
i can do the PR for this.

**Comment by mtrmac** [comment]
I was thinking some kind of … tasteful? link in `install.md` in each distribution’s paragraph. That’s where the users would be looking for it, if anywhere.

It will need a _bit_ of tact so that it doesn’t unintentionally end up looking like “do not report bugs to us, always blame those people for breaking our perfect software”; I’m sure we can manage that :)
