### ISSUE TITLE
A digest form of a docker reference is not supported for docker-daemon destination

### ISSUE THREAD

**Issue by mike-sul** [containers/skopeo#1638]
```
skopeo --version
skopeo version 1.7.0 commit: f45ae950aacb7b61ec13223fc22269f2fe270eab
```

1. An image is copied from the docker registry to a local OCI store. The image reference is represented in a digest form.
```
skopeo copy -f v2s2 docker://alpine@sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4 oci:oci
```

2. Now, let's try to copy the image from a local OCI store to the docker daemon's store.
```
skopeo copy -f v2s2 oci:oci docker-daemon:alpine@sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4
FATA[0000] initializing destination docker-daemon:alpine@sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4: Invalid destination docker-daemon:alpine@sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4: a destination must be a name:tag
```

It fails saying that the destination reference cannot be represented in a digest form.
An attempt to copy the image if a reference is represented as a tag works.
```
skopeo copy -f v2s2 oci:oci docker-daemon:foo/bar/alpine:51103b3f
Getting image source signatures
Copying blob 73b28a5955ec done  
Copying config 28ca6b2fc0 done  
Writing manifest to image destination
Storing signatures
```

```
docker images
REPOSITORY       TAG        IMAGE ID       CREATED       SIZE
foo/bar/alpine   51103b3f   28ca6b2fc070   4 weeks ago   5.44MB
```

Expected behavior - the copy command succeeds if a destination is referenced as a digest.

**Comment by mike-sul** [comment]
I understand, and it makes sense for the `docker save | load` tar format.
However, in this particular case, the source is an OCI store which contains an overall Merkle tree of an image, including an image manifest.
```
cat oci/blobs/sha256/51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1470,
      "digest": "sha256:28ca6b2fc07057618ad749d6f6403afde056ed534ba14271d6c9ead8cd1ea136"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2818974,
         "digest": "sha256:73b28a5955ec7fb46f2cf0434e4901a889f7dda3f8c9ec496300feb256c7eda8"
      }
   ]
}
```

```
sha256sum oci/blobs/sha256/51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4
51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4  oci/blobs/sha256/51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4
```

Therefore, the copy from `oci` to `docker-daemon`, IMHO, could inject the overall image tree starting from a top level manifest and check its hash against the specified destination represented as a digest reference. Maybe it should work similar to `docker pull` command.

**Comment by mike-sul** [comment]
Somehow the destination of `docker pull alpine@sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4` command knows that the image can be represented as `sha256:51103b3f2993cbc1b45ff9d941b5d461484002792e02aa29580ec5282de719d4`...

**Comment by mtrmac** [comment]
Sure, and so does `podman pull`. That’s irrelevant to the capabilities of the `docker load` format.

Can you show me a shell script that does that using `docker load`? (Maybe the capability is there now; it definitely wasn’t there last time I looked.)

**Comment by mike-sul** [comment]
I agree that it has nothing to do with the `docker load | save` format.
I just thought or expected that `skopeo copy oci:<> docker-daemon:` would behave like `docker pull` :).
If the command mimics `docker load | save` then it works as expected.

Thanks for you help :).
