### ISSUE TITLE
skopeo copy

### ISSUE THREAD

**Issue by arvindraju** [containers/skopeo#1639]
Hi,

When trying to copy an image from one registry to another, i get the below error .

<img width="1312" alt="Screenshot 2022-05-06 at 1 09 45 PM" src="https://user-images.githubusercontent.com/5938014/167088704-7f655b8b-aed8-4714-b2ca-9c6e64893070.png">

**LM0002358:~ xxxxxx$ skopeo copy docker://nexus.xyz.com:5550/svc:20220418.2 docker://nexus.rjil.ril.com:5500/svc:20220418.2 --registries-conf ~/.docker/registries.conf
Getting image source signatures
Copying blob 121319d3ac51 skipped: already exists  
Copying blob cd32ce0efa70 skipped: already exists  
Copying blob 0c6b8ff8c37e skipped: already exists  
Copying blob 412caad352a3 skipped: already exists  
Copying blob 82233e85f8fb skipped: already exists  
Copying blob e6d3e61f7a50 skipped: already exists  
FATA[0036] trying to reuse blob sha256:e00faeb297c57cc28ff7b00c43717a90eb26ab725c577b02c2bfdb6c3ffe2eee at destination: failed to read from destination repository svc: 500 (Internal Server Error)** 

Instead of reusing this blob - "trying to reuse blob sha256:e00faeb297c57cc28ff7b00c43717a90eb26ab725c577b02c2bfdb6c3ffe2eee " can we forcefully push it . This blob seems to be missing in the destination registry. 

Thanks

**Comment by vrothberg** [comment]
Thank you for reaching out, @arvindraju.

> Instead of reusing this blob - "trying to reuse blob sha256:e00faeb297c57cc28ff7b00c43717a90eb26ab725c577b02c2bfdb6c3ffe2eee " can we forcefully push it . This blob seems to be missing in the destination registry.

Any chance you can access the logs of the registry?  It ultimately looks like an error of the registry.

@mtrmac WDYT?

**Comment by mtrmac** [comment]
Closing; please reopen if more information becomes available.
