### ISSUE TITLE
install latest version of skopeo in ubuntu 22.04

### ISSUE THREAD

**Issue by willzhang** [containers/skopeo#1646]
os: ubuntu 22.04
```
apt update
apt install -y skopeo

root@ubuntu:~# skopeo --version
skopeo version 1.4.1
```

now skopeo latest version is 1.8.0 , but the latest ubuntu version 22.04 use 1.4.1 ,There are huge differences between them in four versions， and there no way to install latest 1.8.0 version in skopeo, but why?

**Comment by mtrmac** [comment]
Thanks for your report.

It’s generally up to the individual distributions (and their support/stability policies) to update repository packages. Failing that, building from source might be an option.

**Comment by lsm5** [comment]
@willzhang hello, this project doesn't maintain the Ubuntu 22.04 LTS package and also from what I gather, 22.04 itself will most likely not update packages. In addition to building from source as @mtrmac mentioned, you have some other options:

- use the skopeo container image
- use packages from the debian experimental repo which *may* have newer packages
- UNRELIABLE METHOD: I have some work-in-progress to build skopeo for the latest ubuntu and debian at https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable, but there's zero guarantee that they will ever be fully supported, so please consider one of the other three options.

Hope that helps.

Closing...
