### ISSUE TITLE
Unable to locate package skopeo on Ubuntu 18.04 & 20.04

### ISSUE THREAD

**Issue by Hans-J-Klose** [containers/skopeo#1648]
Starting having issues pulling Skopeo into my Ubuntu 18.04 images starting last night.  How can we get `skopeo` to install?

```
# apt-get install -y skopeo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package skopeo
```

**Comment by felipecrs** [comment]
I have the same issue. Also, unable to install `podman`, although the error is a little different:

```console
❯ sudo apt install podman -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  catatonit conmon containernetworking-plugins containers-common criu crun dns-root-data dnsmasq-base fuse-overlayfs
  libidn11 libnet1 libnl-3-200 libprotobuf-c1 libprotobuf17 libyajl2 podman-machine-cni podman-plugins python3-protobuf
  uidmap
The following NEW packages will be installed:
  catatonit conmon containernetworking-plugins containers-common criu crun dns-root-data dnsmasq-base fuse-overlayfs
  libidn11 libnet1 libnl-3-200 libprotobuf-c1 libprotobuf17 libyajl2 podman podman-machine-cni podman-plugins
  python3-protobuf uidmap
0 upgraded, 20 newly installed, 0 to remove and 0 not upgraded.
Need to get 18.0 MB/29.8 MB of archives.
After this operation, 151 MB of additional disk space will be used.
Get:1 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  crun 100:1.2-2 [252 kB]
Err:1 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  crun 100:1.2-2
  File has unexpected size (251724 != 251684). Mirror sync in progress? [IP: 190.64.49.124 443]
  Hashes of expected file:
   - SHA256:1c2a3e0d19b27765b7067500bf22bfe0cff2eeefc6a9d2a42150b348b802faba
   - SHA1:c7bab007b17a547540293ba8ad2c63e734d38e6d [weak]
   - MD5Sum:43a01bf8b518728b1981bb9c388144dc [weak]
   - Filesize:251684 [weak]
Get:2 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  podman 100:3.4.2-1 [17.7 MB]
Err:2 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  podman 100:3.4.2-1
  File has unexpected size (17679080 != 17706544). Mirror sync in progress? [IP: 190.64.49.124 443]
  Hashes of expected file:
   - SHA256:4eb9b58413f602cf18ec21a742acd99ae10e71df467e7b9a63c3b1f7e8229f16
   - SHA1:cf1fefe5c85321fe9b562339a79494c9eda9dd60 [weak]
   - MD5Sum:58fa232055dff2700aa55e13c7932536 [weak]
   - Filesize:17706544 [weak]
E: Failed to fetch https://espejito.fder.edu.uy/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/crun_1.2-2_amd64.deb  File has unexpected size (251724 != 251684). Mirror sync in progress? [IP: 190.64.49.124 443]
   Hashes of expected file:
    - SHA256:1c2a3e0d19b27765b7067500bf22bfe0cff2eeefc6a9d2a42150b348b802faba
    - SHA1:c7bab007b17a547540293ba8ad2c63e734d38e6d [weak]
    - MD5Sum:43a01bf8b518728b1981bb9c388144dc [weak]
    - Filesize:251684 [weak]
E: Failed to fetch https://espejito.fder.edu.uy/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/podman_3.4.2-1_amd64.deb  File has unexpected size (17679080 != 17706544). Mirror sync in progress? [IP: 190.64.49.124 443]
   Hashes of expected file:
    - SHA256:4eb9b58413f602cf18ec21a742acd99ae10e71df467e7b9a63c3b1f7e8229f16
    - SHA1:cf1fefe5c85321fe9b562339a79494c9eda9dd60 [weak]
    - MD5Sum:58fa232055dff2700aa55e13c7932536 [weak]
    - Filesize:17706544 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by felipecrs** [comment]
PS: Of course, when using the Kubic APT repo. Issue happens not only on 18.04 but also on 20.04.

**Comment by felipecrs** [comment]
Skopeo seems to be entirely gone from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/

**Comment by mtrmac** [comment]
For now, just to link the reports together: https://github.com/containers/skopeo/pull/1632 is where the installation instructions were removed, and at least https://github.com/containers/skopeo/issues/1528#issuecomment-1041556461 records that the Kubic packages are no longer being updated.

Per https://github.com/containers/skopeo/blob/main/install.md , Skopeo is now available in the official Ubuntu repositories.

At this point I’m not sure what that means for older Ubuntu releases, and completely removing the older packages does look a little unintuitive. @lsm5 PTAL.

**Comment by felipecrs** [comment]
Especially considering that the number of people using Ubuntu 18.04 and 20.04 completely overwhelms the number of people using 22.04 currently.

**Comment by felipecrs** [comment]
For those using skopeo in a docker image, you can statically build it from source like this:

```dockerfile
FROM golang:1.18 AS skopeo-build

WORKDIR /usr/src/skopeo

ARG SKOPEO_VERSION="1.8.0"
RUN git clone https://github.com/containers/skopeo . \
  && git checkout "v${SKOPEO_VERSION}"

RUN CGO_ENABLED=0 DISABLE_DOCS=1 make BUILDTAGS=containers_image_openpgp GO_DYN_FLAGS=

RUN ./bin/skopeo --version


FROM ubuntu:20.04

COPY --from=skopeo-build /usr/src/skopeo/bin/skopeo /usr/local/bin/

RUN skopeo --version
```

And the binary can be exported to the local system, if wish:

```dockerfile
# same build as above

FROM scratch AS bin

COPY --from=skopeo-build /usr/src/skopeo/bin/skopeo /
```

```console
$ docker buildx build . --output=. --target=bin
$ ./skopeo --version
```

**Comment by jdockter** [comment]
I understand it's not being updated for 18.04 but why was it completely removed?

**Comment by felipecrs** [comment]
I think the title of the PR could be changed to include 20.04 as well.

**Comment by jdockter** [comment]
@mtrmac so what is the suggested workaround to download older versions of skopeo moving forward?

**Comment by felipecrs** [comment]
PS: You can use my `Dockerfile` above to also install `skopeo` with the following command:

```console
sudo docker build . --target skopeo-rootfs --output=/
```

It will write two files to your system: `/usr/local/bin/skopeo` and `/etc/containers/policy.json`

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
Hi all, RE: 18.04, skopeo seems to have been enabled mistakenly because of cri-o sharing the project. The kubic packages (at least in the form they were) were causing more trouble than they were solving. Lack of maintenance + issues on the Kubic infra side such as the hash mismatches were why I removed them. Please build skopeo from source or use the [skopeo container image](https://github.com/containers/skopeo/blob/main/install.md#container-images)

**Comment by lsm5** [comment]
Follow-up, the packages have now been restored after lots of pushback. I'd like to reiterate that there will be no further updates and maintenance, not even security fixes. So, I encourage everyone to switch to other ways for fetching skopeo.  The builds should be available now, let me know if anything. 

Sorry about the hassle.

**Comment by robin-wayve** [comment]
A small addition to @felipecrs comments: you need [BuildKit enabled](https://docs.docker.com/build/buildkit/#getting-started) to use the `--output` flag.

**Comment by felipecrs** [comment]
Is there any chance we can have the `default-policy.json` bundled in the binary to avoid having to install two files to the system?
