### ISSUE TITLE
reading manifest v1.7.0 in quay.io/XXX unauthorized: access to the requested resource is not authorized"

### ISSUE THREAD

**Issue by peterlai-roboops** [containers/skopeo#1665]
Hi 

We're getting a weird error when doing a copy. 

 skopeo login --authfile=quay_auth.json quay.io
16:29:34  Authenticating with existing credentials for quay.io
16:29:37  Existing credentials are valid. Already logged in to quay.io
[Pipeline] echo
16:29:37  Logging in to ECR registry
[Pipeline] sh
16:29:37  + skopeo login -u AWS -p XXXXX
16:29:38  Login Succeeded!

copying quay.ioimage -> 237579344283.dkr.ecr.eu-west-1.amazonaws.com/image
[Pipeline] sh
16:29:39  + skopeo copy docker://image
16:29:41  time="2022-06-06T12:29:41Z" level=fatal msg="initializing source docker://quay.io/image reading manifest v1.7.0 in quay.io/image: unauthorized: access to the requested resource is not authorized"

*replaced the real image url with image.

**Comment by peterlai-roboops** [comment]
nevermind, adding tls-verify=false fixed it. itish.

**Comment by vrothberg** [comment]
Thanks for reaching out.  I just want to highlight that turning off TLS verification has a big negative impact on security.
