### ISSUE TITLE
how to copy to local containerd daemon

### ISSUE THREAD

**Issue by willzhang** [containers/skopeo#1683]
how to copy to local containerd daemon, not docker daemon

the follow not work
```
skopeo copy oci:nginx --src-shared-blob-dir ./share docker://localhost:5000/nginx --dest-tls-verify=false

skopeo copy oci:nginx --src-shared-blob-dir ./share docker-daemon:nginx:latest --dest-daemon-host unix:///var/run/containerd/containerd.sock
```

**Comment by vrothberg** [comment]
Thanks for reaching out. The issue is already tracked in https://github.com/containers/image/issues/1572 so I am going to close.

In short: `containerd` is not supported at the moment.
