### ISSUE TITLE
`copy` doesn't skip existing images

### ISSUE THREAD

**Issue by nrdxp** [containers/skopeo#1685]
I noticed that skopeo is always copying all the layers of the image to our registry even when they already exist. This is fairly suboptimal for CI environments especially. In order to mitigate this behavior in our own CI system, I opened nlewo/nix2container#29, but it would be much nicer if skopeo could just check for existing layers beforehand and skip those that exist already.

x-ref: https://github.com/containers/skopeo/issues/214#issuecomment-427577732

**Comment by mtrmac** [comment]
Thanks for your report. This is supposed to work _in general_, and https://github.com/nlewo/nix2container/pull/29#issuecomment-1159371210 confirms that it can work. There are certainly corner cases and situations where reuse isn’t possible or isn’t implemented.

Please determine an exact command that is not working as expected, add the `--debug` flag, and provide both the command and the full output.
