### ISSUE TITLE
Introduce `digest` subcommand

### ISSUE THREAD

**Issue by Dentrax** [containers/skopeo#1689]
Introduce a new `digest` subcommand to get digest directly as crane did[^1]:

```
$ skopeo digest docker://golang:1.18.3
```

Current workaround:

```
$ skopeo inspect docker://golang:1.18.3 --raw | sha256sum | cut -d" " -f1
```

We'd (@developer-guy) like to get into it!

[^1]: https://github.com/google/go-containerregistry/blob/f1fa40b162a1601a863364e8a2f63bbb9e4ff36e/pkg/crane/digest.go

**Comment by mtrmac** [comment]
Thanks for your report.
- The `skopeo inspect` output already contains a digest value, so an extra `sha256sum` should not be necessary. Is there some non-obvious reason why the workaround uses it anyway?
- There already is `--format`, e.g. `skopeo inspect inspect --format '{{.Digest}}'`.
- Compare #1554 : it’s not _trivially_ obvious which of the values would be returned by the new `skopeo digest`; so if we, in the future, add support for all of those values, it seems simpler to only document the values and their semantics in a single place (`skopeo inspect`), and then let users use `--format` referring to those fields. Having both `skopeo inspect` and `skopeo digest` deal with the various digest values, and document two different syntaxes to obtain those values, seems to me to introduce unnecessary complexity.

**Comment by Dentrax** [comment]
> The skopeo inspect output already contains a digest value

Just noticed that, thanks!

> Having both skopeo inspect and skopeo digest deal with the various digest values, and document two different syntaxes to obtain those values, seems to me to introduce unnecessary complexity.

Actually, I was thinking the opposite of this statement. Wouldn't it be more complex for the end user who want to simply get a digest from an image, have to write some complicated CLI command: `skopeo inspect --format '{{.Digest}}'`. But `skopeo digest <IMG>` would be much easier.

Also comparing `inspect` and `digest` would not be good approach since `inspect` is more special purpose whereas `inspect` more general purposes.

I also completely understand your concern here. "A value we can get from the inspect command, it does not make sense to make a completely new sub command to get it directly." But _digest_ is something different. It's important as listing tags. For me, as an end-user, I'm using `crane digest <IMG>` and also thought we would be nice to have similar UX here.

**Comment by mtrmac** [comment]
I don’t know yet.

One very reasonable argument is that we are not that easily going to run out of words, and that `skopeo digest` is unlikely to ever be needed for any other purpose, so adding that command doesn’t hurt (except possibly for making the help output longer, which is not _nothing_ but it’s fairly trivial). Sure, we would need to think about the design WRT #1554 _a bit_.

At a far higher level,
- Most users just shouldn’t need to manually work with digests. They are unwieldy and carry no user-understandable meaning. Talk about applications, software versions, automating a complex deployment using a tool.
- _Machines_ should, OTOH fairly frequently use digests, e.g. to guarantee a complex deployment deploys exactly the right versions of components. But machines don’t care about nice UIs that much.
- Ideally, signatures that contain a signed name combine both: They guarantee image integrity while letting users use convenient semantic names.
- If some process relies on the properties of the digest, those properties should are almost certainly worth preserving throughout the lifetime of the image. I.e. don’t build an image to a tag, copy it around a few systems, and _later_ decide to freeze an immutable digest: I think _most_ users of that kind should capture the digest _at build time_, not from the registry but from the building process directly, and then carry it around all the processes that involve the image as an immutable identifier (probably embedding it into some deployment configuration). So, a “get digest value from the registry” operation exposed to users feels mildly suspect — it suggests a build process that cares about image immutability enough to do _some_ work for it but doesn’t quite achieve it.

The last point is why I’m intuitively reluctant to expose that operation — but it’s also a point of ignorance, so let me finally ask: What are you using the “get digest from registry” operation for?

**Comment by Dentrax** [comment]
Thanks for detailed explanations!

> we would need to think about the design WRT https://github.com/containers/skopeo/issues/1554

If we combine these both issues together, I would expect something the following eventually:

```
$ skopeo --override-os=linux --override-arch=amd64 digest <IMG>
```

> What are you using the “get digest from registry” operation for?

As you mention in the third statement, a "secure in mind" dev do mostly work with digests instead of tags. Because just using tags, for example in Dockerfiles to pull the images, is a mistake and a security issue. This is where we headed “get digest value from the registry”. I generally want to pin the digest after I find the tag that I want to use.

**Comment by mtrmac** [comment]
> I generally want to pin the digest after I find the tag that I want to use.

Oh… that’s a very good point, for third-party dependencies a tag → digest lookup is unavoidable. (Signatures would be better, but that’s not currently very widely-supported.)

Given that, I think adding `skopeo digest` makes sense. (@vrothberg WDYT?)

**Comment by mtrmac** [comment]
> If we combine these both issues together, I would expect something the following eventually:
> 
> ```
> $ skopeo --override-os=linux --override-arch=amd64 digest <IMG>
> ```

Typically `--override-*` don’t change the nature of the operation, i.e. `skopeo digest` and `skopeo --override-arch=amd64` should, on `amd64`, do the same thing.

I’d imagine something like `skopeo digest --top-level`, `skopeo digest --current-variant`, or something like that (almost certainly defaulting to `--top-level`). We don’t immediately _need_ those options, if you are interested in only the top-level digest, implementing that case alone would be perfectly fine.

**Comment by vrothberg** [comment]
Back from PTO.

I am supportive of adding a new command. Before somebody starts working on it, we should decide on the behavior and the CLI options.  What I want is `skopeo digest` to be able to resolve to 1) a manifest list/image index, 2) individual "ordinary" images.

Not sure how to tackle 1).  For 2) I am gravitating toward the `--override-*` flags for the sake of consistency.
