### ISSUE TITLE
Copy /var/lib/containers/storage to other VM

### ISSUE THREAD

**Issue by geertpingen** [containers/skopeo#1702]
Im spinning up a number of VMs on my local workstation and want to provision those with an image registry ready to go (mostly Kubernetes images and CNI plugin). In my current setup Im using skopeo to fetch those from a Docker registry I have running somewhere else.

This works, but takes quite some time however, due to having to download all the images on every VM.

I wondered if instead I could simply mount/copy the `/var/lib/containers/storage` dir.

Ive tried mounting that directory into another VM and adding the path to the `storage.conf`'s `additionalimagestores`. That worked, however, these are read-only and I quickly run into an error of a Calico Pod that wants to start writing stuff.

Then I tried copying the entire `/var/lib/containers/storage` directory from a VM with a working Kubernetes cluster up and running (deleted `overlay-containers` because think that is only for running containers), and that works for some containers but not all. Im wondering if this should work theoretically, or if there are other things to be cautious about?

**Comment by vrothberg** [comment]
Thanks for reaching out @geertpingen.

> Ive tried mounting that directory into another VM and adding the path to the storage.conf's additionalimagestores. That worked, however, these are read-only and I quickly run into an error of a Calico Pod that wants to start writing stuff

Can you elaborate on the error?  The images should not be writable but once mounted in a container, things should just work. Cc: @giuseppe @rhatdan

**Comment by geertpingen** [comment]
It's the Canal CNI initContainer:

```shell
❯ kubectl get po -A        
NAMESPACE     NAME                                         READY   STATUS       RESTARTS      AGE
kube-system   calico-kube-controllers-6fb9bbf6f7-llgzs     0/1     Pending      0             50s
kube-system   canal-slndr                                  0/2     Init:Error   3 (32s ago)   51s
kube-system   coredns-86bfdd759c-fj94p                     0/1     Pending      0             50s
kube-system   coredns-86bfdd759c-sdrsj                     0/1     Pending      0             50s
kube-system   etcd-cluster-0-master-0                      1/1     Running      0             59s
kube-system   kube-apiserver-cluster-0-master-0            1/1     Running      0             59s
kube-system   kube-controller-manager-cluster-0-master-0   1/1     Running      0             59s
kube-system   kube-proxy-k426p                             1/1     Running      0             51s
kube-system   kube-scheduler-cluster-0-master-0            1/1     Running      0             59s
```

```shell
❯ kubectl logs -n kube-system canal-slndr -c install-cni           
time="2022-07-11T08:25:48Z" level=info msg="Running as a Kubernetes pod" source="install.go:139"
2022-07-11 08:25:48.667 [INFO][1] cni-installer/<nil> <nil>: File is already up to date, skipping file="/host/opt/cni/bin/bandwidth"
2022-07-11 08:25:48.667 [INFO][1] cni-installer/<nil> <nil>: Installed /host/opt/cni/bin/bandwidth
2022-07-11 08:25:48.668 [ERROR][1] cni-installer/<nil> <nil>: Failed to install /host/opt/cni/bin/calico error=failed to copy file: write /host/opt/cni/bin/calico.tmp: copy_file_range: protocol error
```

**Comment by giuseppe** [comment]
Please mount the existing storage directory to a different path inside the VMs and add it to `additionalimagestores`.

`/var/lib/containers/storage` is the default path and it is expected to be writeable and not shared among different hosts.

**Comment by geertpingen** [comment]
Hi @giuseppe Tried this already, but no success unfortunately, I still get the above error in `kube-proxy`. Any idea on why `kube-proxy` would not be able to load the kernel modules? (again I have no issues when doing a `skopeo copy ...` instead).

**Comment by geertpingen** [comment]
I made a mistake with copying and dropped symlinks. Cluster is up. Thanks for the nudge in the right direction.
