### ISSUE TITLE
quay.io does not have tagged v1.9.x skopeo image

### ISSUE THREAD

**Issue by eperdeme** [containers/skopeo#1718]
Looks like builds not pushing to quay the image.

**Comment by vrothberg** [comment]
Thank you for reaching out.

Publishing the images usually takes a couple of days. @TomSweeneyRedHat will know for sure.

**Comment by eperdeme** [comment]
[v1.9.0](https://github.com/containers/skopeo/releases/tag/v1.9.0) never appeared and its 14 days old ;)

**Comment by mtrmac** [comment]
I’m afraid the image build automation has been broken for a bit over a week (search for `Cron build 'multiarch' Failed` on `Podman-monitor`). It’s being worked on, I think #1711 is the work to follow.

**Comment by cevich** [comment]
Next scheduled invocation of the build is at 6:22pm EST today, which will have the #1711 fix.  I'll check on Monday to make sure it ran smoothly.

**Comment by mtrmac** [comment]
The scheduled builds did succeed. Thanks @cevich !

Matching https://bodhi.fedoraproject.org/updates/?search=skopeo&releases=__current__ , 1.9.0 is currently available in the `skopeo/testing` repo; the stable Skopeo containers match Fedora 36 at 1.8.0, and it seems that the build should be released in Fedora within a day or so.

**Comment by cevich** [comment]
```
$ podman run -it --rm quay.io/skopeo/upstream:latest --version
skopeo version 1.9.2-dev commit: 61c28f5d477f64b5ca8fbef6692381e85d2d92d1
```

61c28f5d477f64b5ca was from Friday.  I also checked the `testing` and `stable` images to confirm they all report a `1.9.x` version, so this issue is confirmed resolved.

**Comment by cevich** [comment]
Oh woops, missed Miloslav's comment :blush:

**Comment by mtrmac** [comment]
@cevich Thanks for confirming this.
