### ISSUE TITLE
make failed about skopeo@1.9.x  on centos8_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [containers/skopeo#1721]
hello,I meet a problem:make failed about skopeo@1.9.x  on centos8_aarch64
### Steps to reproduce the issue

```console
[root@localhost skopeo-1.9.0]# go version
go version go1.17 linux/arm64
[root@localhost skopeo-1.9.0]# make
GO111MODULE=on go build -mod=vendor "-buildmode=pie" -ldflags '-X main.gitCommit= ' -gcflags "" -tags "btrfs_noversion exclude_graphdriver_btrfs  " -o bin/skopeo ./cmd/skopeo
# pkg-config --cflags  -- gpgme
Package gpgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpgme.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gpgme', required by 'virtual:world', not found
pkg-config: exit status 1
make: *** [Makefile:139: bin/skopeo] Error 2
[root@localhost skopeo-1.9.0]# make bin/skopeo
GO111MODULE=on go build -mod=vendor "-buildmode=pie" -ldflags '-X main.gitCommit= ' -gcflags "" -tags "btrfs_noversion exclude_graphdriver_btrfs  " -o bin/skopeo ./cmd/skopeo
# pkg-config --cflags  -- gpgme
Package gpgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpgme.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gpgme', required by 'virtual:world', not found
pkg-config: exit status 1
make: *** [Makefile:139: bin/skopeo] Error 2
```
I have installed gpgme, but it always reports this problem, saying that gpgme.pc cannot be found in the PKG_CONFIG_PATH search path. How can I solve this problem?

**Comment by Tom-python0121** [comment]
Is there a requirement for the gpgme version?

**Comment by Tom-python0121** [comment]
Skopeo depends on the version, causing an error. Upgrade the Go version and the gpgme version to match Skopeo@1.9.x.
![image](https://user-images.githubusercontent.com/77763324/182121355-5e0981a0-757c-45e2-a3b5-e9dabd3fbe8e.png)

**Comment by TomSweeneyRedHat** [comment]
Thanks a bunch for noting the solution you found @Tom-python0121 !

**Comment by mtrmac** [comment]
FWIW this is caused by https://github.com/containers/skopeo/commit/ebc5573e83fc97d2896a619af6a19d2981c8de74 , which says GPGME ≥ 1.13.0 is required.

I did intend that to be prominent in the 1.9.0 release notes, but somehow missed that, I apologize.
