### ISSUE TITLE
quay.io doesn't have 1.9.1 or 1.9.2 images

### ISSUE THREAD

**Issue by olfway** [containers/skopeo#1726]
https://quay.io/repository/skopeo/stable?tab=tags&tag=latest

There is only v1.9.0 tag modified 10 hours ago

**Comment by TomSweeneyRedHat** [comment]
@cevich?

**Comment by cevich** [comment]
Hmmm, we were having some problems with the build jobs the other week, but those appear fixed.  I see the 1.9.1 tag was created 10 days ago, it's possible the packages simply haven't rolled out to the Fedora repos yet, checking...

...ya, not available yet:
```
$ podman run -it --rm --entrypoint=/usr/bin/dnf quay.io/skopeo/stable:latest update -y skopeo
Trying to pull quay.io/skopeo/stable:latest...
Getting image source signatures
...cut...
Fedora 36 - x86_64 - Updates                          9.0 MB/s |  25 MB     00:02
Fedora Modular 36 - x86_64 - Updates                  1.9 MB/s | 2.4 MB     00:01
Dependencies resolved.
Nothing to do.
Complete!
```

and

```
$ podman run -it --rm --entrypoint=/usr/bin/dnf quay.io/skopeo/testing:latest update -y --enablerepo updates-testing skopeo
...cut...
Fedora 36 - x86_64 - Test Updates                     1.9 MB/s | 9.9 MB     00:05
Dependencies resolved.
Nothing to do.
Complete!
```

@TomSweeneyRedHat do you know how to look this up on Koji or who to ask?

**Comment by cevich** [comment]
Looks like it's this page: https://koji.fedoraproject.org/koji/packageinfo?packageID=21883

But I'm not sure how to interpret that.

**Comment by cevich** [comment]
@lsm5 sorry to always bug you with packaging questions -  do you know how/where/why we don't see newer skopeo packages in the Fedora repos yet?

**Comment by rhatdan** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2022-76cbf5837f

I just put skopeo 1.9.1 for f36 into updates-testing.

**Comment by rhatdan** [comment]
skopeo-1.9.2-1 does not exist for Fedora 36

**Comment by cevich** [comment]
Thanks @rhatdan

**Comment by cevich** [comment]
@olfway so from my limited knowledge, 1.9.1 should show up in the "testing:latest" image anywhere between 1-8 days from now.  Some time (1-2 weeks) after that it should show up in the regular repos.  At most a day after it's released, you should see both "stable:latest" and the version-tagged images get pushed.

I have no problem keeping this issue open as well, so we can confirm all that happens.  Thanks again for letting us know.

**Comment by lsm5** [comment]
submitted 1.9.2 just now https://bodhi.fedoraproject.org/updates/FEDORA-2022-e5ee2423d0

We had to hold off builds because of CVE fixes in golang which needed a mass rebuild in fedora, at least that's my recollection. Anyway, this should be fixed soon.

**Comment by olfway** [comment]
I just thought that containers should be available shortly after the source release, didn't expected it could take 1-2 weeks

Thank you for help!

**Comment by TomSweeneyRedHat** [comment]
@olfway Yep, as others have noted, the images show up on the "testing" repo on quay.io pretty quickly, usually within a day of the release in GitHub.  That's at:  https://quay.io/repository/skopeo/testing.  The "stable" repo takes longer.  Once a Podman release is created on GitHub, the newly created package gets pushed to Fedora for testing and consideration for being "stable".  The process of crowning a package as "stable" can take a day to a couple of weeks.  After it is crowned as "stable" in Fedora, then it takes up to 24 hours to create and push an image to the quay.io repo: https://quay.io/repository/skopeo/stable.

**Comment by cevich** [comment]
I think you intended `https://quay.io/repository/skopeo/upstream` as "pretty quickly...within a day".

The `testing` image also takes a while, but is typically a week or two faster than the `stable` image.

**Comment by TomSweeneyRedHat** [comment]
oops, yep, thanks @cevich.  Once again typing while looking at 3 windows at once, never good.

**Comment by cevich** [comment]
Just checked, `1`, `1.9` and `1.9.2` have all been pushed to `quay.io/repository/skopeo/stable` as well as `quay.io/repository/skopeo/testing:latest` is showing `1.9.2` as well.
