### ISSUE TITLE
"skopeo copy" does not preserve labels, annotations and tags of copied ImageStreams

### ISSUE THREAD

**Issue by elmazzun** [containers/skopeo#1727]
As the title says.
Currently using quay.io/skopeo/stable:v1.8.0: I am successfully copying images from my cluster to DR cluster of mine but in DR cluster the labels, annotations and tags are not preserved.
Only "latest" tag, if present in source cluster, is preserved: otherwise, no tag is applied to copied images in DR cluster.
Do I have to use some particular flags or what?

Thanks for giving us such an amazing tool!

**Comment by mtrmac** [comment]
Thanks for your report.

Please provide a specific reproducer and demonstrate what exactly is the expected/actual behavior.

**Comment by mtrmac** [comment]
Please reopen if more information is available.
