### ISSUE TITLE
Why is Dockerfile.build using Ubuntu?

### ISSUE THREAD

**Issue by rhatdan** [containers/skopeo#174]

**Comment by mtrmac** [comment]
https://github.com/projectatomic/skopeo/pull/123#discussion_r68456683

Personally I am using `make binary-local` exclusively, I really care very little.

**Comment by runcom** [comment]
Same here, I build locally and integration tests are being run in Fedora, so no big deal to me either

**Comment by rhatdan** [comment]
Well lets add it to the todo list to set this up to build on Fedora.  What environment variables need to be set to build locally?

**Comment by runcom** [comment]
@rhatdan it's just `make binary-local`

**Comment by runcom** [comment]
> Well lets add it to the todo list to set this up to build on Fedora.

we could make something like the patch we carry for docker to build using whatever base distro you're using

**Comment by rhatdan** [comment]
Sounds good to me.  And default to a Red Hat based Distro...

**Comment by mikebrow** [comment]
For ubuntu xenial you just need to run: 
sudo apt-get update && sudo apt-get install -y golang git-core libgpgme11-dev
Then you can use make binary-local no container needed.

**Comment by duglin** [comment]
Is it possible to run skopeo from an image w/o a linux distro? If so, I'd actually prefer for the resulting image to just the exe.

**Comment by mtrmac** [comment]
It would be possible to create a container image containing a (subset of) a Linux distribution + the skopeo binary, but it wouldn't be trivially convenient to run (e.g. it uses the docker and OpenShift login status in $HOME, so those would have to be e.g. mounted in as volumes).

The current `Makefile` doesn’t do that, though.

**Comment by rhatdan** [comment]
No one has converted this to a Fedora image.  I will assign to a Intern.
