### ISSUE TITLE
The image uploaded by skopeo-copy cannot be obtained by docker-manifest.

### ISSUE THREAD

**Issue by kycheng** [containers/skopeo#1741]
I used buildkit to build image files of different architectures, and then uploaded them to the regsitry using skopeo-copy, but when using docker-menifest to merge multi-architecture images, I cannot get the manifest.

these steps are ok

```bash
# arm64
$ buildctl-daemonless.sh build --progress auto --frontend=dockerfile.v0 \
  --opt filename=Dockerfile --local context=. --local dockerfile=. \
  --output type=oci,dest=oci-image.tar

$ skopeo inspect tarball:oci-image.tar | jq .Digest | xargs echo
sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0

$ skopeo copy --dest-tls-verify=false tarball:oci-image.tar \
 docker://registry.com/image@sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0 --all

# amd64
$ buildctl-daemonless.sh build --progress auto --frontend=dockerfile.v0 \
  --opt filename=Dockerfile --local context=. --local dockerfile=. \
  --output type=oci,dest=oci-image.tar

$ skopeo inspect tarball:oci-image.tar | jq .Digest | xargs echo
sha256:f9e6e595406b86a2bcb7cf88f684222120ecbdb398e2334700e81f5122831087

$ skopeo copy --dest-tls-verify=false tarball:oci-image.tar \
  docker://registry.com/image@sha256:f9e6e595406b86a2bcb7cf88f684222120ecbdb398e2334700e81f5122831087 --all

```
when I use dockermanifest to build a multi-arch image

```sh
$ docker manifest create --insecure --amend registry.com/image:v1 \
  registry.com/image@sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0 \
  registry.com/image@sha256:f9e6e595406b86a2bcb7cf88f684222120ecbdb398e2334700e81f5122831087 
no such manifest: registry.com/image@sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0

$ docker manifest inspect registry.com/image@sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0
no such manifest: registry.com/image@sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0
```
why can't docker-manifest get the manifest ?

**Comment by mtrmac** [comment]
Thanks for your report.

I‘m afraid I can’t help much with debugging the `docker` command.

As for Skopeo, please provide the `skopeo --debug …` output of the upload step (skopeo copy --dest-tls-verify=false tarball:oci-image.tar \
 docker://registry.com/image@sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0 --all`, and of `skopeo --debug inspect docker://registry.com/image@sha256:1a1f3fa29c898fce9d87f6df9f0e29a6972d0e6385f2f16be614fb38f4badbd0`.

---

Also note that the `tarball` transport is not intended to consume OCI-formatted images. Consider `oci-archive`.

**Comment by mtrmac** [comment]
Closing for now; please reopen if more information is available.
