### ISSUE TITLE
signature revokation support or approach

### ISSUE THREAD

**Issue by Rajpratik71** [containers/skopeo#1742]
**Question**

Is signature revocation supported in "skopeo"?

if yes, how to achieve that?

**Comment by mtrmac** [comment]
The only signature revocation method supported is to completely replace the trusted public key, and re-sign any past images previously signed with that key pair, if any.

The basic thinking is that dealing with a key compromise is much more involved than just dealing with the signature (e.g. the already-pulled and already-running images need to be found and replaced), and the complexity of revocation and the inherent tradeoffs of quick revocation vs. system availability, along with need to support running containers on systems disconnected from the internet, make it not worth it — it’s perhaps more likely to be a source of vulnerabilities than a viable recovery feature.

**Comment by Rajpratik71** [comment]
A similar approach which the "Notary v1" or "docker trust" command does to sign and revoke the signature of an artifact tag, can be used/implemented to achieve a bit level of signature revokation.

**Comment by mtrmac** [comment]
That’s exactly what I was referring to with the “complexity” reference.

IIRC, at some point in the past when I was examining this, if you signed an image and did nothing more in the repo, the signatures would just start to be rejected after 3 years of doing nothing. How many of the Notary users even knew that? It was somewhat practical as a hosted service, but only viable as an internally-managed system for a _very_ limited set of highly-motivated specialist users.
