### ISSUE TITLE
No way to specify the storage root dir 

### ISSUE THREAD

**Issue by tarun360** [containers/skopeo#1746]
For podman and buildah, there's a [--root](https://www.mankier.com/1/podman#Global_Options---root=value) flag available, which allows us to specify where images are stored. However, for skopeo there's no such flag available.

This creates problem when you wish to use skopeo-inspect.

`skopeo inspect containers-storage:image-name` fails if the image `image-name` is not stored in the default location.

The only way to make this work seems to me by changing the config file `/etc/containers/storage.conf`. 

Is there a better way to solve this problem?

**Comment by mtrmac** [comment]
Thanks for your report.

The `containers-storage` transport has a syntax for providing such parameters. The syntax shows up in `podman --log-level=debug` logs from time to time, something of the form `containers-storage:[overlay@path]@image-name`. Look for `containers-storage:[`.  The part in brackets should be the same for all images, and can be used as `containers-storage:[…]$yourImageName`.

Note that not all parameters are available like this, so it might be possible that some Podman environments cannot be used like this.

In the worst case, it should be possible to use https://github.com/containers/storage/blob/ca4b82525eb3261a6cae4f87637acbbdfa0c3781/docs/containers-storage.md#environment-overrides without needing to edit the global `/etc/containers/…` file.

**Comment by tarun360** [comment]
Thanks, that works. For me the syntax was:
`containers-storage:[vfs@/var/tmp/$USER/run/user/UID/containers]image-name`
