### ISSUE TITLE
Q: auth file mounted into Skopeo container ignored?

### ISSUE THREAD

**Issue by marcelstoer** [containers/skopeo#1749]
Using the copy command in a Skopeo container fails with "unauthorized: authentication required" even though I

- am authenticated against docker.io/hub.docker.com (i.e. I can push images there)
- mount `.docker/config.json` into the Skopeo container
- set `--authfile` to the mounted file

I am out of ideas what I'm doing wrong here.

## Error 

```
...
Writing manifest to image destination
time="2022-09-11T10:35:19Z" level=fatal msg="copying system image from manifest list: writing manifest: uploading manifest 2.0.0 to docker.io/marcelstoer/my-image: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
```

## Evidence

**Command**

`docker run --rm -v $HOME/.docker/config.json:/config.json quay.io/skopeo/stable:latest copy --authfile /config.json docker://marcelstoer/my-image:latest docker://marcelstoer/my-image:2.0.0`

**Docker config.json**

```json
{
	"auths": {
		"https://index.docker.io/v1/": {},
		"registry-1.docker.io": {}
	},
	"credsStore": "desktop",
	"experimental": "disabled",
	"stackOrchestrator": "swarm",
	"currentContext": "default"
}
```

**Comment by vrothberg** [comment]
Thanks for reaching out, @marcelstoer!

Can you run skopeo with `--debug` and check whether the auth file is mentioned in the logs?

**Comment by marcelstoer** [comment]
Good catch, didn't think of the debug switch, thanks! It indeed reveals something unexpected

```
time="2022-09-12T09:25:55Z" level=debug msg="Using registries.d directory /etc/containers/registries.d"
time="2022-09-12T09:25:55Z" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2022-09-12T09:25:55Z" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf.d/000-shortnames.conf\""
time="2022-09-12T09:25:55Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.config/containers/auth.json"
time="2022-09-12T09:25:55Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.docker/config.json"
time="2022-09-12T09:25:55Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.dockercfg"
time="2022-09-12T09:25:55Z" level=debug msg="No credentials for docker.io/marcelstoer/my-image found"
time="2022-09-12T09:25:55Z" level=debug msg=" Lookaside configuration: using \"default-docker\" configuration"
time="2022-09-12T09:25:55Z" level=debug msg="  Using \"lookaside-staging\" file:///var/lib/containers/sigstore"
time="2022-09-12T09:25:55Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io"
time="2022-09-12T09:25:55Z" level=debug msg=" Sigstore attachments: using \"default-docker\" configuration"
time="2022-09-12T09:25:55Z" level=debug msg="Using registries.d directory /etc/containers/registries.d"
time="2022-09-12T09:25:55Z" level=debug msg="Trying to access \"docker.io/marcelstoer/my-image:latest\""
time="2022-09-12T09:25:55Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.config/containers/auth.json"
time="2022-09-12T09:25:55Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.docker/config.json"
time="2022-09-12T09:25:55Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.dockercfg"
time="2022-09-12T09:25:55Z" level=debug msg="No credentials for docker.io/marcelstoer/my-image found"
```

1. The "No credentials matching..." messages only point to locations I didn't specify.
2. Why is Skopeo even looking in all those places when I explicitly point it to the one auth file I'd like to use (through the `--authfile` argument)?

Since I saw that Skopeo is indeed checking at `/root/.docker/config.json` I then mounted my `config.json` to that path and omitted the `--authfile` argument. That was a step forward as I don't get the "No credentials matching..." message for _that_ location

```
time="2022-09-12T09:37:35Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /tmp/auth.json"
time="2022-09-12T09:37:35Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.config/containers/auth.json"
// message for location /root/.docker/config.json is now missing here
time="2022-09-12T09:37:35Z" level=debug msg="No credentials matching docker.io/marcelstoer/my-image found in /root/.dockercfg"
time="2022-09-12T09:37:35Z" level=debug msg="No credentials for docker.io/marcelstoer/my-image found"
```

Yet, even though the file I mounted seems to be taken into account, Skopeo still concludes "No credentials for docker.io/marcelstoer/my-image found". Looking at my `config.json` I posted above I see

```json
"registry-1.docker.io": {}
```
and I wonder: since the actual auth information appears to be missing (signified by `{}`?) where is the auth information _actually_ stored on my macOS Docker Desktop and how do I carry it over into the Skopeo container?

**Comment by vrothberg** [comment]
> and I wonder: since the actual auth information appears to be missing (signified by {}?) A) where is the auth information actually stored on my macOS Docker Desktop and B) how do I carry it over into the Skopeo container?

Nice catch!  One way to approach it is doing a `skopeo login --authfile ...` on your desktop and inject that file into the container.

@mtrmac WDYT?

**Comment by marcelstoer** [comment]
Thanks Valentin. I tweaked this a bit.

* `skopeo login --authfile ... --username ... docker.io` into a dedicated file.
* Copy the `"docker.io": { "auth": "base64-string" }` from that new file into the existing `config.json`.
* Mount that one into the Skopeo container at `/root/.docker/config.json`.

**Comment by mtrmac** [comment]
>  1. The "No credentials matching..." messages only point to locations I didn't specify.

Uh. So the `{}` entries caused by `credsStore` are treated as “no data, let’s try the next file“ but do not cause any debug log entry to be printed about that file at all. We should fix that.

> 2. Why is Skopeo even looking in all those places when I explicitly point it to the one auth file I'd like to use (through the `--authfile` argument)?

I think Skopeo _was_ looking at that explicitly configured file (but not logging anything about it, per 1.) and `--authfile` does not prevent looking in the various compatibility fallback locations.

---

Fundamentally, credential helpers like `"desktop"` work by executing commands _in some environment_. The inside of a container just can’t run a command outside of that container to get credentials the same way other out-of-containers command interact with the helper.

In _some_ cases (e.g. if the credential helper is fetching secrets from a remote server) it might make sense to copy the credential helper inside the container), but there are limits to that.

Ultimately, sometimes the choice is between not using the credential helper at all (and you have figured out a working version) — or running Skopeo directly on the host system, not inside a container.

---

Then there’s a whole another thing, where Skopeo et al. don’t support the `credsStore` directive at all (but they do support individual `credHelpers` entries), and where the interaction between `~/.docker/config.json` pointing at a helper, and `auth.json` being updated, works out badly.

So, yes, right now the easiest path is to create a non-credential-helper-dependent `auth.json`, and mount that into the container.

**Comment by mtrmac** [comment]
> So the `{}` entries caused by `credsStore` are treated as “no data, let’s try the next file“ but do not cause any debug log entry to be printed about that file at all. We should fix that.

#1653 .

**Comment by marcelstoer** [comment]
Thanks Miloslav for the additional comments and the MR. I am glad I opened this issue; I learned something 😄
