### ISSUE TITLE
Does skopeo sync command - synchronizes the delete (untagged) image from the source to the target docker repo

### ISSUE THREAD

**Issue by kumaravanish** [containers/skopeo#1752]
I have two docker container registries. Source is the `registry1` and Target is `registry2`. 

1. If a deletion/untagging performed on the registry1.
   `docker image rm registry1/image-repo:1.0` 
   
2. run skopeo sync to synchronize the target registry - registry2.
    `skope sync registry1/image-repo:1.0 registry2/image-repo:1.0`

3. Does the `"untagging"` is reflected in the target registry `registry2`

Please let us know if this feature is supported?

**Comment by mtrmac** [comment]
Thanks for reaching out.

No, `skopeo sync` does not currently maintain a persistent record of state, so it can not detect deletion.

(Besides the persistent state, see other issues in this repo about the inability to only delete a tag on older registries.)
