### ISSUE TITLE
skopeo inspect docs not updated in v1.10.0

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#1766]
The 1.10.0 release notes say the following:
> skopeo inspect now provides more information about individual layers.

However, the changeset does not include any updates to [skopeo-inspect.1.md](https://github.com/containers/skopeo/blob/main/docs/skopeo-inspect.1.md). From the other changes it seems a new field `LayersData` was added to the output, but it is not mentioned in the examples.

**Comment by mtrmac** [comment]
Thanks for the report. This is definitely worth doing.
