### ISSUE TITLE
Skopeo copy inserts a "docker.io/" prefix instead of "localhost/" in RepoTags

### ISSUE THREAD

**Issue by jjenne-cisco** [containers/skopeo#1768]
For a locally built archive, not associated with any registry, a `skopeo copy` operation specifying an additional short-name tag results in the default registry domain `docker.io/` being added as a prefix instead of the non-registry prefix `localhost/`.

(This follows discussion from [this podman issue](https://github.com/containers/podman/issues/15974))

---

1. I have saved a basic image to an archive, simply building "FROM scratch".
1. This image has no `RepoTags`:
```
root@ubuntu:~# tar -xOf img.tar manifest.json | jq '.[] | .RepoTags'
[]
```
1. Using `skopeo copy` I create a new archive, naming it `foo`:
```
root@ubuntu:~# skopeo copy docker-archive:img.tar docker-archive:new-img.tar:foo
Getting image source signatures
Copying blob 5f70bf18a086 done
Copying config 1db986249a done
Writing manifest to image destination
Storing signatures
```
1. This new image has the following unexpected `RepoTags`:
```
root@ubuntu:~# tar -xOf new-img.tar manifest.json | jq '.[] | .RepoTags'
[
  "docker.io/library/foo:latest"
]
```
I expected `"localhost/foo:latest"` for this registry-less local archive.
1. (Note that currently, I'm not sure if on purpose or not, `skopeo inspect` always shows empty `RepoTags` for docker archives)
```
root@ubuntu:~# skopeo inspect docker-archive:new-img.tar -f{{.RepoTags}}
[]
```
1. Loading the image with `podman load -i` confirms that `docker.io` is the domain chosen to prefix the image 
```
root@ubuntu:~# podman load -i new-img.tar
Getting image source signatures
Copying blob 5f70bf18a086 done
Copying config 1db986249a done
Writing manifest to image destination
Storing signatures
Loaded image(s): docker.io/library/foo:latest
```

(I have checked this using skopeo 1.5)

**Comment by mtrmac** [comment]
Yes, this is _exactly_ what https://github.com/containers/podman/issues/15974#issuecomment-1262509161 discussed.

---

Also, Skopeo in general makes a different trade-off than Podman. Skopeo prefers unambiguity, and if short names need expanding, they are expanded to `docker.io/[library]`. Podman prefers user convenience, and if short names need expanding, they may, depending on the exact use, trigger a search over a registry list, search over similarly-named images (https://github.com/containers/podman/issues/13383 ).

So, I’m afraid the two are not going to always use the same defaults.

**Comment by mtrmac** [comment]
> Skopeo prefers unambiguity

Or rather, Skopeo is a _very_ thin wrapper over the underlying c/image library, and the library‘s API prefers unambiguity. Heuristics can be built on top of that, and that’s what happens in c/common/libimage and Podman proper.

**Comment by jjenne-cisco** [comment]
Yes, I understand that there must be a trade-off between convenience and implicitness, for the sake of image ambiguity. I just wanted to check whether or not there is a way to use `skopeo copy` to set `RepoTags` that looked like `abc/def:ghi` (without normalisation) via one of the `$options`:
> you can have control over the destination name

But it looks like, to prevent the "docker.io" prefix from being added, the user will need to prefix the tag with "localhost" or some string that looks like a domain to pass as a registry.
```
root@ubuntu:~# skopeo copy docker-archive:img.tar docker-archive:new-img.tar:abc/def:ghi
Getting image source signatures
Copying blob 5f70bf18a086 done
Copying config 3aeae8b972 done
Writing manifest to image destination
Storing signatures
root@ubuntu:~# tar -xOf new-img.tar manifest.json | jq '.[] | .RepoTags'
[
  "docker.io/abc/def:ghi"
]
root@ubuntu:~# skopeo copy docker-archive:img.tar docker-archive:new-img.tar:ab.c/def:ghi
Getting image source signatures
Copying blob 5f70bf18a086 done
Copying config 3aeae8b972 done
Writing manifest to image destination
Storing signatures
root@ubuntu:~# tar -xOf new-img.tar manifest.json | jq '.[] | .RepoTags'
[
  "ab.c/def:ghi"
]
```

---

> Yes, this is exactly what https://github.com/containers/podman/issues/15974#issuecomment-1262509161 discussed.

Sorry, from that previous comment I thought you suggested that `localhost/` was the expanded prefix, but I may have misinterpreted you talking about podman instead :) 

> That’s basically why we have the localhost/ prefix for names where a registry is not implied.

**Comment by mtrmac** [comment]
> But it looks like, to prevent the "docker.io" prefix from being assumed, the user will need to prefix the tag with "localhost" or some string that looks like a domain to pass as a registry.

Yes. Especially because the file can be consumed by `docker load`, which would add `docker.io[/library]` to short names without a domain.
