### ISSUE TITLE
Check existing image layers when copying to docker daemon

### ISSUE THREAD

**Issue by ottowao** [containers/skopeo#1773]
When running skopeo to copy from the local docker daemon to a registry, it copies only the image layers that aren't already present in the registry, this is working as expected. However when copying from the registry to the docker daemon it will send through all of the image layers regardless if they are already present.

docker daemon -> registry: 
`skopeo copy --dest-tls-verify=false docker-daemon:alpine:latest docker://localhost:5000/alpine:latest`

```
Getting image source signatures
Copying blob 52c45c2e2b12 skipped: already exists
Copying config 9c6f072447 done
Writing manifest to image destination
Storing signatures
```

registry -> docker daemon:
`skopeo copy --src-tls-verify=false docker://localhost:5000/alpine:latest docker-daemon:alpine:latest`

```
Getting image source signatures
Copying blob 52c45c2e2b12 done
Copying config 9c6f072447 done
Writing manifest to image destination
Storing signatures
```

Testing using a local docker registry instance and an alpine image. Monitoring network IO on the registry I find that the docker daemon -> registry run uses almost no network resources, whereas the registry -> docker daemon run uses the same as when I push the image for the first time.

I expected that the registry -> docker daemon copy would include similar checks to the docker daemon -> registry copy.

**Comment by mtrmac** [comment]
Thanks for your report.

I’m afraid that’s just how it works: writes to `docker-daemon` are just generating an archive that is essentially passed to `docker load`. There is no interactivity in there that would allow skipping some layers; the file format does not allow partial archives. (Well, it _happens to work_ in some implementations, but it’s against the spec and actually Skopeo is rejecting such archives.)

Overall, the primary recommendation must be to avoid workflows that use `docker-archive` or `docker-daemon`: It is _very_ inefficient both in disk space and time (involving multiple on-disk copies of the uncompressed data, and the like). These features are transition mechanisms, not something for high-performance production. E.g. just using a `docker pull` is always going to be much faster.

**Comment by ottowao** [comment]
Thanks for the info! I'll close this issue and think of another approach
