### ISSUE TITLE
/var/lib/containers/sigstore not being populated for skopeo versions > v1.2.0

### ISSUE THREAD

**Issue by ocofaigh** [containers/skopeo#1774]
We are using skopeo to sign and publish our docker images. Below is an overview of the approach taken. This approach works fine when using skopeo version `v1.2.0` on Ubuntu however it does not work on `v1.2.1` and higher ...

1. Add our PFX (which is in a PKCS#12 format, contains the SSL certificate (public keys) and the corresponding private keys) to `/etc/ekm`

2. Create a file called `/etc/containers/registries.d/icr.yaml` with the details of our container registry sigstore:
```
docker:
  us.icr.io/cpre:
    sigstore: https://****:****@artifactory.ibm.com/artifactory/myteam-generic-local
    sigstore-staging: file:///var/lib/containers/sigstore
```

3. Create a file called `/etc/containers/policy.json` with the following contents:

```
{
  "default": [
    {
      "type": "insecureAcceptAnything"
    }
  ],
  "transports": {
    "docker-daemon": {
      "": [
        {
          "type": "insecureAcceptAnything"
        }
      ]
    },
    "docker": {
      "us.icr.io/cpre": [
        {
          "type": "signedBy",
          "keyType": "GPGKeys",
          "keyPath": "/tmp/myapp.pub"
        }
      ]
    }
  }
}
```

4. Configure local PGP keys for use in signing:
```
# Download local 'pointer keys' referencing the actual private and public keys stored in the HSM (Hardware Security Module)
sudo ucl pgp-key -n ${CERTIFICATE_ALIAS}
# Export our public key to be used for image verification
sudo gpg2 --armor --output /tmp/myapp.pub --export ${CERTIFICATE_ALIAS}
```

5. Sign and Publish the Image
```
FINGERPRINT=$(sudo gpg2 --no-tty --batch --fingerprint --with-colons "${CERTIFICATE_ALIAS}" | grep '^fpr' | cut -d : -f 10 | head -n 1)
LOCAL_DAEMON=`echo ${DOCKER_HOST} | sed s/tcp/http/`
sudo skopeo copy \
  --dest-creds "${DOCKER_CREDS_USR}:${DOCKER_CREDS_PSW}" \
  --remove-signatures \
  --sign-by ${FINGERPRINT} \
  --src-daemon-host "$LOCAL_DAEMON" \
  docker-daemon:${IMAGE_BUILD_TAG} \
  docker://${IMAGE_RELEASE_TAG}
```

After running this command using skopeo 1.2.0 I see the following contents in `/var/lib/containers/sigstore`:
```
drwxr-xr-x 1 root root 4096 Oct 11 10:32 .
drwxr-xr-x 1 root root 4096 Oct 11 10:32 ..
drwxr-xr-x 3 root root 4096 Oct 11 10:32 cpre
```

On skopeo 1.2.1 I see this:
```
drwxr-xr-x 2 root root 4096 Oct 10 16:37 .
drwxr-xr-x 1 root root 4096 Oct 11 10:25 ..
```

So as you can see, something has changed in 1.2.1 which is resulting in `cpre` not being added to `/var/lib/containers/sigstore`. 
I took a stab at comparing 1.2.0 <-> 1.2.1 in github (https://github.com/containers/skopeo/compare/v1.2.0...v1.2.1) but nothing stands out here (although I am not very familiar with this project). 

Any help here is greatly appreciated.

**Comment by ocofaigh** [comment]
Incase it helps, I added the `--debug` flag to the skopeo command and have attached the output from 1.2.0 and 1.2.1.
I can see that both print the following:
`time="2022-10-11T14:41:38Z" level=debug msg="  Using file:///var/lib/containers/sigstore"`

but I can see that in `1.2.0` the following lines are printed at the end of the log that are not seen in 1.2.1...

```
time="2022-10-11T14:42:18Z" level=debug msg="Writing to /var/lib/containers/sigstore/cpre/cie-notifier@sha256=aeea1465d141e7a3d6953c2fcac5b1de0f409555e40f36c663ad5b2f6a055f9a/signature-1"
time="2022-10-11T14:42:18Z" level=debug msg="Deleting /var/lib/containers/sigstore/cpre/cie-notifier@sha256=aeea1465d141e7a3d6953c2fcac5b1de0f409555e40f36c663ad5b2f6a055f9a/signature-2"
```

**Comment by mtrmac** [comment]
Yes; as of 1.2.1, if the registry _natively_ supports storing signatures, that is always used in preference to sigstore. It is no longer necessary to configure a sigstore to work with signatures on such registries — but it’s also not _possible_.

**Comment by mtrmac** [comment]
BTW the way to interoperate between 1.2.0 and 1.2.1 is to not have a sigstore configured (incl. possibly any global `sigstore-staging` in `default.yaml`; those should be removed or be made registry-specific); then both versions should use the native support.

**Comment by mtrmac** [comment]
It’s a fair point that this could have benefitted from a much better announcement — but it’s happened over a year ago, so we can’t quite fix that now.
