### ISSUE TITLE
getting the latest version on centos 7 in WSL

### ISSUE THREAD

**Issue by chb0github** [containers/skopeo#1778]
I have a centos 7 distro installed in wsl and I get that it's not a legit distro. However, when I do a `sudo yum install skopeo` I get version 
```
[cbongior@soho-cbongio-l1 skopeo]$ skopeo -v
skopeo version 0.1.40
```

Obviously that's much too old. I am trying to compile it in wsl and running into dependency errors

```
[cbongior@soho-cbongio-l1 skopeo]$ make install
GO111MODULE=on go build -mod=vendor "-buildmode=pie" -ldflags '-X main.gitCommit=08c290170db67c22a54e072eab2ca8c9c6af77ae ' -gcflags "" -tags "btrfs_noversion exclude_graphdriver_btrfs libdm_no_deferred_remove " -o bin/skopeo ./cmd/skopeo
# pkg-config --cflags  -- gpgme
Package gpgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpgme.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gpgme' found
pkg-config: exit status 1
# pkg-config --cflags  -- devmapper
Package devmapper was not found in the pkg-config search path.
Perhaps you should add the directory containing `devmapper.pc'
to the PKG_CONFIG_PATH environment variable
No package 'devmapper' found
pkg-config: exit status 1
make: *** [bin/skopeo] Error 2
[cbongior@soho-cbongio-l1 skopeo]$ 
```
I don't know where this package it's missing is to be found.

So, either some help with where the correct centos repo is or some instructions on how to compile would be awesome

**Comment by mtrmac** [comment]
Thanks for reaching out.

https://github.com/containers/skopeo/blob/main/install.md#building-from-source should be correct in the general outlines. But I think you’ll find that both the GPGME build environment (presence of `pkg-config` metadata) and feature set (https://github.com/containers/podman/issues/7705#issuecomment-702870476 , and we now do call that new code) makes use of the _latest_ Skopeo together with GPGME impossible without modification.

There might be some earlier version of Skopeo that can still be built.

Alternatively, search for `BUILDTAGS=containers_image_openpgp` (and read https://github.com/containers/image#supported-build-tags for what that means).

**Comment by chb0github** [comment]
I'll confess that I don't understand why the code won't compile as-is from checkout. However, that was an alternative.

Can you point me to the latest centos repo? The WSL image I have apparently has something really out-of-date and I can simply update my repo list and this should get me what I need

**Comment by mtrmac** [comment]
We are not publishing _recent_ Skopeo builds for RHEL 7 any more. Some older artifacts probably stay around, e.g. https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/ . @lsm5 would know more.

At some point, it might be easier to run one of the Skopeo containers: https://github.com/containers/skopeo/blob/main/contrib/skopeoimage/README.md

**Comment by chb0github** [comment]
I just ran repoquery, and unfortunately it didn't give any insight

```
[root@soho-cbongio-l1 yum.repos.d]# repoquery -i skopeo

Name        : skopeo
Version     : 0.1.40
Release     : 11.el7_8
Architecture: x86_64
Size        : 23018307
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Group       : Unspecified
URL         : https://github.com/containers/skopeo
Repository  : extras
Summary     : Inspect container images and repositories on registries
Source      : skopeo-0.1.40-11.el7_8.src.rpm
Description :
Command line utility to inspect images and repositories directly on Docker
registries without the need to pull them
```

**Comment by chb0github** [comment]
I am pretty sure running a containerized version is going to be more (politically) difficult for me than a straight install. To run a container I would need either docker (paid) or podman installed first, which might be a challenge. The whole reason skopeo was chosen was to skip the need for docker to simply move around images

**Comment by mtrmac** [comment]
\*shrug\* The desire to run old software (CentOS 7) and new software (recent Skopeo) together, is ultimately, to an extent, contradictory, and there’s only so much that is easily possible and immediately available.

It is, probably, possible to backport features, or to create custom builds that exactly match your desires, but that’s someone doing specialized (paid) work. Red Hat, for instance, has a product like that (but even that might be limited for RHEL 7 at this point in the lifecycle, I wouldn’t be the authoritative source for that.)

**Comment by chb0github** [comment]
I get ya, an don't blame ya. I will pass details on

**Comment by lsm5** [comment]
> We are not publishing _recent_ Skopeo builds for RHEL 7 any more. Some older artifacts probably stay around, e.g. https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/ . @lsm5 would know more.

That's right. We aren't doing centos7 anymore on the kubic repos. Just way too much work to make anything recent work on it.
See: https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html .

There also won't be any official podman/buildah/skopeo updates for RHEL7 (apart from security I think).


> 
> At some point, it might be easier to run one of the Skopeo containers: https://github.com/containers/skopeo/blob/main/contrib/skopeoimage/README.md

Agreed.

**Comment by Maple1401** [comment]
why not provide binary , centos or ubuntu both can use .

**Comment by vrothberg** [comment]
> why not provide binary , centos or ubuntu both can use .

See https://github.com/containers/skopeo/issues/1478.

**Comment by lsm5** [comment]
we aren't doing any centos7 binaries anymore. Closing..
