### ISSUE TITLE
Rootless, Automated Skopeo workflow returns non-zero for signed images when writing to the Sigstore is denied. 

### ISSUE THREAD

**Issue by jnach** [containers/skopeo#1795]
Summary: 
When automating a rootless, cache-less sync of images from one registry to another as part of a multi-registry sync workflow, Skopeo returns a non-zero, despite successfully pushing an image, due to permissions issues opening the system sigstore. 

Actual: 
Any wrapped automation tends to choke, and any workaround is less than ideal.. eg ignoring the error for the whole batch of images, or reducing the permissions of the signature store. 

Expected: 
It would be nice to emulate the podman --remove-signatures, or the ability to ignore them, for this particular edge case, where the signatures can be verified, the image re-signed, and then subsequently pushed, without taking the computational hit of pulling images down and storing them on the controller filesystem. 

-- OR  --

Documentation or capability for performing rootless signature verification, without privileged access to the system sigstore, instead being able to verify the chain from a restricted user account. 

Notes: 
N/A

**Comment by mtrmac** [comment]
Thanks for reaching out.

It’s rather unclear to me what is actually failing here. Could you perhaps provide specific steps to reproduce, with all details, and a record of the reported failure?

- Skopeo does have the `--remove-signatures` option.
- The current default is for the sigstore locations to be built in (not specified in a global config file), which means unprivileged users have use a sigstore-staging in the home directory.
- If the global config file set ups sigstores for pulling images, they really should be readable by anyone; having them globally set up but not readable is a configuration error.
- Ultimately, there’s a `--registries.d` option which allows unprivileged users to use a private configuration, ignoring the administrator’s system default, entirely.
