### ISSUE TITLE
Dynamically replicate/sync/copy all additional tags of a specific imagename:tagname - is that possible? 

### ISSUE THREAD

**Issue by pandel** [containers/skopeo#1796]
Hi!

My problem is somewhat special... I need to copy images between registries, but have to preserve all of their individual tags (which are dynamically changing over time).

I.e. if I do

`skopeo copy docker://A.priv.reg/repo/imagename:latest docker://B.priv.reg/repo/imagename:latest`

and `repo/imagename` has additional tags, like `:v1_step1_pre`, `:v1_step1_cust` while executing `skopeo copy` for the first time and `:master_post`, `:master_final` when executing `skopeo copy` on another day a second time, how can I force skopeo to

a) copy the image and all of the additional tags (`:v1_step1_pre`, `:v1_step1_cust`) on the first run automatically
b) _change_ the tags (only!) on the next run, if they changed like in the example above(remove: `:v1_step1_pre`, `:v1_step1_cust`, add: `:master_post`, `:master_final`)?

(Tags can contain any kind of information and their structure can change. The examples above are only to make it more clear what I am trying to explain and do not represent a fixed structure or layout.)

I know, it sounds weird, but...

Regards,
Holger

**Comment by mtrmac** [comment]
Thanks for reaching out.

Does this _need_ to be limited to only the same tags of the `:latest` image, or is it basically all of the tags in the repo? `skopeo sync` can copy an arbitrary set of tags (and with `--preserve-digests`, should preserve the tag relationships, i.e. two tags pointing at the same image, _assuming that doesn’t change during the copy). If the tags keep pointing at the same image, there is _some_ overhead but the full binaries should not be copied again.

Or do you mean something much more specific?

**Comment by pandel** [comment]
Thanks for writing back so quickly :-) No, it has to be limited to only the tags of the `:latest` image.

**Comment by mtrmac** [comment]
That doesn’t exist as a native feature, primarily because “see all tags with the same digest” is not a native feature of the registry API and it’s rather expensive.

I think a script doing that could be built using a combination of `skopeo list-tags` + `skopeo inspect` (to determine the relevant tags) + `skopeo copy` (to do the tag propagation).
