### ISSUE TITLE
how to copy from repository to docker daemon on another host?

### ISSUE THREAD

**Issue by horacimacias** [containers/skopeo#1799]
I've been trying to use `dest-daemon-host` to no avail. 
If anybody has any good working examples I'd appreciate.

I'm trying to do the following:

Mount docker socket of remote host as a tcp socket:

```bash
ssh -L localhost:2375:/var/run/docker.sock  myhost.com
```

Read from repository (I need to access through an HTTP proxy) and copy to the mounted localhost:2375

```bash
env HTTPS_PROXY=http://127.0.0.1:8888 skopeo copy docker://remote_repository/image:tag --dest-daemon-host http://localhost:2375 oci:image
```

this creates a local directory with the downloaded image/layers, but I don't want it local I want it on the docker daemon reachable at `localhost:2375`

Tried with `tcp://localhost:2375` instead of `http://localhost:2375` but that makes no difference; the image/layers are downloaded locally.

Does anybody have a suggestion for this scenario?

**Comment by mtrmac** [comment]
`--dest-daemon-host` only applies to `docker-daemon:` destinations; the example above uses `oci:`, not `docker-daemon:`, so that has no chance of working.

After that, `--dest-daemon-host http…` is designed to directly connect to a network socket on which the daemon listens; not to a unix socket forwarded using `ssh`. I’m not saying that it won’t work, just that it’s not designed and tested that way. Worth trying, I suppose.

**Comment by horacimacias** [comment]
indeed worth trying, thanks!

The following worked for me:

```bash
env HTTPS_PROXY=http://127.0.0.1:8888 skopeo copy docker://remote_repository/image:tag --dest-daemon-host http://localhost:2375 docker-daemon:image:tag
```
after that, running `docker images` on the remote docker engine showed the image was there (and it wasn't before).

So, thanks again, that did the trick.
Is there any doc/code listing the various destinations/sources supported and their format? oci/docker/docker-daemon/etc?

**Comment by mtrmac** [comment]
(In general, I’d expect the Docker-targeted tips about using `DOCKER_HOST` for forwarding over `ssh` to work similarly. But we don’t have comprehensive tests of such situations.)

The Skopeo man page points at `containers-transports(5)`, which should be ideally installed in the same place. Alternatively, you can read it on https://github.com/containers/image/blob/main/docs/containers-transports.5.md .

**Comment by horacimacias** [comment]
awesome, thanks!

**Comment by horacimacias** [comment]
from my point of view this can be closed now. 
thanks for the help @mtrmac
