### ISSUE TITLE
Check image existence in `docker.io` consumed request limit

### ISSUE THREAD

**Issue by helobinvn** [containers/skopeo#1801]
Currently, we are using `skopeo sync` to sync many images from `docker.io`, it seems that when skopeo compares the image in src (`docker.io`) will consume the rate limit because almost our images will be skipped as it already existed in the destination, but it still reaches rate limit

```
Skipping: image already present at destination
```

According to the dockerhub document (https://docs.docker.com/docker-hub/download-rate-limit/#definition-of-limits) , the `HEAD` request is not counted into the limit, so it seems skopeo doesn't use the `HEAD` request to check for image existence, is that correct?

I didn't find anything in skopeo mention this, so I would like to ask to be sure.

Thank you!

**Comment by mtrmac** [comment]
It doesn’t.

Using `HEAD` to check if the source changed would be one extra round-trip if it _did_ change, and it would mean a completely new code path in the copy code. It’s not _impossible_ to do, but there’s only so far it makes sense to contort the codebase to avoid a business model. I’m not sure where the line is but my first impression is that this case is very likely on the “not worth it” side of that line.

Something like configuration to assume that (some) tags are immutable and doesn’t need copying, like https://github.com/containers/skopeo/issues/1498 , seems like a more generally useful approach.

**Comment by helobinvn** [comment]
> Something like configuration to assume that (some) tags are immutable and doesn’t need copying, like https://github.com/containers/skopeo/issues/1498 , seems like a more generally useful approach.

Thank you for checking this. I think ^ approach makes sense to me and would help to speed up the synchronizing. Any chance that feature will be implemented in the near future?

We didn't run into the slowness issues like others mentioned in https://github.com/containers/skopeo/issues/1498, I guess because we're only syncing the largest references (introduced by https://github.com/containers/skopeo/pull/1779), but still hitting the rate limit for `docker.io` and from the beginning, we aim to reply on the feature of `skopeo sync` with source is `yaml` instead of building some wrapper around it

I'm closing this issue in favor of https://github.com/containers/skopeo/issues/1498
