### ISSUE TITLE
make binary permitted error

### ISSUE THREAD

**Issue by ZCM111** [containers/skopeo#1814]
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/39475342/203526371-0753ab44-3f41-4233-ae81-710cc06b6e68.png">

**Comment by mtrmac** [comment]
Thanks for your report.

The system, and/or Podman on it, is very likely too old (https://github.com/containers/podman/issues/11862 ). Modifying the `podman run` command to include `--security-opt seccomp=unconfined` would probably help.

Or, preferably, update your system.

**Comment by mtrmac** [comment]
Please reopen if the above did not make a difference.
