### ISSUE TITLE
Skopeo --scoped remove domains

### ISSUE THREAD

**Issue by wrender** [containers/skopeo#1823]
With the skopeo sync is it possible to remove domains from the --scoped, but still keep the sub folder.  For example, we want:

ourregistry.domain/rancher/aks-operator:v1.0.7   not  ourregistry.domain/docker.io/rancher/rancher/aks-operator:v1.0.7

**Comment by mtrmac** [comment]
No, but you can modify the destination parameter to hard-code the parent of the repo you want, and use it without `--scoped`. Compare the “Synchronizing to a container registry keeping the repository” example in the man page.

**Comment by mtrmac** [comment]
Closing; please reopen if the above doesn’t work.
