### ISSUE TITLE
Consider an ecosystem-wide, software-agnostic registry configuration file

### ISSUE THREAD

**Issue by mtrmac** [containers/skopeo#183]
Various registry configuration items are stored in tool-specific configuration locations:
- “this registry can be accessed over HTTP” via docker-daemon’s `--insecure-registry` (which can be in `/etc/sysconfig/docker`’s `INSECURE_REGISTRY`, or `OPTIONS`, or overridden in `docker.service`); altogether quite difficult to parse; `skopeo` does not read any of this, adds its own command-line option.
- The TLS certificate & key supported in `skopeo` (but not `docker`?!) also can be only specified on the command line.
- The `sigstore`\* options considered in #170 , configured in `atomic.conf` (which makes it awkward to include the parsing and semantics in `containers/image`).

Would it make sense to introduce a system-wide configuration file, perhaps `/etc/containers/docker-registries.yaml`, which allows per-registry and per-repository configuration, to be used by all of the tools if possible?
- The configuration would be shared across various tools (we could even generate `--insecure-registry` automatically, no need to patch Docker)
- Well-defined format instead of plain-text `OPTIONS` would make it easier to manipulate with tools.
- Consolidates similar information into one place
- Vendor/project-neutral (but of course supporting vendor extensions, e.g. via `x-reverse.domain.name` or whatever)

@runcom , @rhatdan  ?

**Comment by mtrmac** [comment]
cc @baude

**Comment by runcom** [comment]
> Would it make sense to introduce a system-wide configuration file, perhaps /etc/containers/docker-registries.yaml, which allows per-registry and per-repository configuration, to be used by all of the tools if possible?

I would have loved Docker to have registries conf (ala git remote maybe) but that never happened and maybe it'll never happen..... sadly...

I'm all for this though and what you've highlighted sounds good to me :+1:

**Comment by rhatdan** [comment]
I like the idea.
@cgwalters WDYT?

**Comment by rhatdan** [comment]
Docker not having a configuration file at this point is just nuts.  Perhaps this was Solomon's idea to prevent other tools from easily understanding the configuration.

**Comment by runcom** [comment]
That's probably it yeah..

**Comment by cgwalters** [comment]
https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file or am I missing something?

**Comment by runcom** [comment]
That's intended mainly for configurations that can be live reloaded. They do not intend (as the last time I talked to them) to store registries configuration options there and the configuration isn't widely used though.

**Comment by rhatdan** [comment]
I did not realize that that was added.  We really should start to move towards using this configuration file.  Having docker-storage-setup edit this file and setting things like selinux-enabled/log-driver in here would be nice.
@rhvgoyal WDYT

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by runcom** [comment]
Please note that there are pitfalls with the config file when for instance a flag is both defined in the the config and via flag to dockerd. I never considered the config file for this and other reasons..

**Comment by rhatdan** [comment]
Yes it looks like the dockerd will refuse to start, but we really want to start to minimize the use of /etc/sysconfig/docker, since we were really abusing this just because dockerd did not have a config file.

**Comment by mtrmac** [comment]
`/etc/containers/registries.d` from #170 ( https://github.com/containers/image/blob/master/docs/registries.d.md ) is a start.

**Comment by rhatdan** [comment]
:+1:

**Comment by mtrmac** [comment]
> Seems like this is done.

Not to the _full_ extent, but https://github.com/containers/image/tree/master/pkg/sysregistriesv2 is basically it, yes.
