### ISSUE TITLE
skopeo copy multi-arch manifest from local containers-storage to private registry not working

### ISSUE THREAD

**Issue by prashant0810** [containers/skopeo#1830]
$ podman images nodeimage

REPOSITORY                                                                          TAG                IMAGE ID      CREATED       SIZE
localhost/nodeimage                                                            9.arm64            95d9fe375ed3  17 hours ago  888 MB
localhost/nodeimage                                                            9.amd64            a523734ebdb1  17 hours ago  864 MB
localhost/nodeimage                                                            9                  410c25c08493  17 hours ago  1.09 kB  

$ podman inspect  localhost/nodeimage:9.arm64|grep Digest

          "Digest": "sha256:6db6e95b26c56459ffd63539e8f7b1418d15a8ba35e979bd61374779c20b80d3",

$ podman inspect localhost/nodeimage:9.amd64|grep Digest

          "Digest": "sha256:e4cb67eb7189c6d7e02d7f394f3d28ea50af723ea853b984618b57d96aba4940",

$ podman manifest inspect localhost/nodeimage:9|grep sha256

            "digest": "sha256:e4cb67eb7189c6d7e02d7f394f3d28ea50af723ea853b984618b57d96aba4940",

            "digest": "sha256:6db6e95b26c56459ffd63539e8f7b1418d15a8ba35e979bd61374779c20b80d3",

$ podman manifest inspect localhost/nodeimage:9

{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 1682,
            "digest": "sha256:e4cb67eb7189c6d7e02d7f394f3d28ea50af723ea853b984618b57d96aba4940",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 1682,
            "digest": "sha256:6db6e95b26c56459ffd63539e8f7b1418d15a8ba35e979bd61374779c20b80d3",
            "platform": {
                "architecture": "arm64",
                "os": "linux",
                "variant": "v8"
            }
        }
    ]
}

$ skopeo --debug copy --dest-registry-token $gcr_auth_token  containers-storage:localhost/nodeimage:9  docker://us.gcr.io/localhost/nodeimage:9 --multi-arch all

DEBU[0000] [graphdriver] trying provided driver "overlay" 

DEBU[0000] Cached value indicated that overlay is supported 

DEBU[0000] Cached value indicated that overlay is supported 

DEBU[0000] Cached value indicated that metacopy is being used 

DEBU[0000] Cached value indicated that native-diff is not being used 

INFO[0000] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 

DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true 

DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]localhost/nodeimage:9" 

DEBU[0000] Using registries.d directory /etc/containers/registries.d 

DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 

DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf" 

DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/001-rhel-shortnames.conf" 

DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/002-rhel-shortnames-overrides.conf" 

DEBU[0000] Found credentials for us.gcr.io/localhost/nodeimage  in credential helper containers-auth.json in file /run/user/0/containers/auth.json 

DEBU[0000]  Lookaside configuration: using "default-docker" configuration 

DEBU[0000]   Using "sigstore-staging" file:///var/lib/containers/sigstore 

DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/us.gcr.io 

DEBU[0000]  Sigstore attachments: using "default-docker" configuration 

DEBU[0000] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb 

DEBU[0000] Source is a manifest list; copying all instances 

Getting image list signatures

DEBU[0000] Manifest list has MIME type application/vnd.oci.image.index.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.docker.distribution.manifest.v1+json] 

DEBU[0000] ... will use the original manifest list type, and then try [application/vnd.docker.distribution.manifest.list.v2+json] 

Copying 2 of 2 images in list

DEBU[0000] Copying instance sha256:e4cb67eb7189c6d7e02d7f394f3d28ea50af723ea853b984618b57d96aba4940 (1/2) 
Copying image sha256:e4cb67eb7189c6d7e02d7f394f3d28ea50af723ea853b984618b57d96aba4940 (1/2)

FATA[0000] copying image 1/2 from manifest list: determining manifest MIME type for containers-storage:[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]localhost/nodeimage:9@410c25c084931697396bd851fb1c726d1d7d8cfb7de98c91ed1bd10e8b3226ea: reading manifest for image instance "sha256:e4cb67eb7189c6d7e02d7f394f3d28ea50af723ea853b984618b57d96aba4940": locating item named "manifest-sha256:e4cb67eb7189c6d7e02d7f394f3d28ea50af723ea853b984618b57d96aba4940" for image with ID "410c25c084931697396bd851fb1c726d1d7d8cfb7de98c91ed1bd10e8b3226ea" (consider removing the image to resolve the issue): file does not exist

**Comment by mtrmac** [comment]
Thanks for your report.

Yes, the `podman manifest` commands are manipulating Podman-specific structures. That set of commands includes `podman manifest push`, which is the intended way to export the result; why are you not using that one, and manually running `skopeo` instead?

(I’m not very familiar with how `podman manifest` works, but my first impression is that it’s just not currently possible to use with `skopeo`.)

**Comment by mtrmac** [comment]
Assuming this works as (currently) designed; please reopen if that’s not the case or if doesn’t provide a necessary functionality.
