### ISSUE TITLE
Integration test bucket needs:

### ISSUE THREAD

**Issue by mikebrow** [containers/skopeo#184]
1) More test cases a) push & pull images using local docker registry b) see @runcom todo notes
2) OCI test cases need to be added (OCI enabled local registry) a) using modified registry fork that enables OCI push pull.

I'm doing some work on the above.  Comments & questions?

**Comment by runcom** [comment]
I know @mtrmac was working on at least speed up the whole CI. 

Anyway, 1) is still probably needed while 2) I'm not sure how ok would be to work/test against something not upstreamed (fork)

**Comment by mikebrow** [comment]
Can just leave the OCI tests in skip mode till there's an upstream fork.

**Comment by mtrmac** [comment]
I wasn’t really working on the speed up much; so far I have experimented with a Docker Hub automated build, but that runs out of memory when compiling OpenShift :smiling_imp:  So my best plan ATM is to add `make upload-test-base-images` to `Makefile`, manually build them locally and upload them to a personal repository.  (Or is there another hosted, automated service to rebuild Docker images on either a commit or a base image change, and to publish them into a registry, which we could easily use?)

Re: 1), you may find #177 useful or at least inspirational, although it doesn’t work that way at the moment.

I don’t have a strong opinion on 2) beyond thinking that our default setup should not refuse to work with an upstream unpatched server. Supporting a fork if we autodetect it or if we are configured to do so is in principle fine with me.

**Comment by mikebrow** [comment]
I'd rather see a docker/distribution registry PR that fixes the hardcoded manifest tags like https://github.com/docker/distribution/blob/master/manifest/manifestlist/manifestlist.go#L14 to enable /s/.docker./.oci. Any chance one of you guys or maybe @stevvooe are working on that?

**Comment by mikebrow** [comment]
Re #177 yes that helps.. but I was a bit perplexed by the two separate registry testing paths one for docker registry and another for the open shift (based on docker registry) registry?

**Comment by mtrmac** [comment]
For OpenShift, we use the native API to store/retrieve signatures (and actually for uploading the manifest as well).

**Comment by mikebrow** [comment]
Talked to stevvooe.. so I'll get started on a docker/distribution PR for the tag support. Won't have to do a fork :-)

**Comment by cgwalters** [comment]
@mtrmac see https://wiki.centos.org/ContainerPipeline

**Comment by runcom** [comment]
@mikebrow are you talking about having docker/distribution to support OCI media types? If so, probably my mistake of not telling it before, there's already a pseudo-effort to achieve this (there are some WIP branches around).

**Comment by mikebrow** [comment]
@runcom Yes. If a branch exists / someone is working on it, just need a pointer.

**Comment by runcom** [comment]
@mikebrow there are also @mfojtik @miminar that are going to investigate those OCI patches - could you sync up with them?

**Comment by mikebrow** [comment]
Sure, thx.

**Comment by rhatdan** [comment]
I believe this is fixed, closing.  Reopen if I am mistaken.

**Comment by mtrmac** [comment]
We don’t have any integration tests against an OCI-supporting registry AFAIK.

The way I read this issue, it was @mikebrow announcing what he plans to work on, though, so closing this seems reasonable. (And for the record, the support did land upstream in https://github.com/docker/distribution/pull/2076 thanks to @mikebrow ).
