### ISSUE TITLE
How to get image manifest

### ISSUE THREAD

**Issue by akshayvijapur** [containers/skopeo#1856]
I was trying to [verify signatures](https://github.com/containers/skopeo/blob/main/docs/skopeo-standalone-verify.1.md) of the docker image using this command 

```
$ skopeo standalone-verify busybox-manifest.json registry.example.com/example/busybox 1D8230F6CDB6A06716E414C1DB72F2188BB46CC8  busybox.signature
Signature verified, digest sha256:20bf21ed457b390829cdbeec8795a7bea1626991fda603e0d01b4e7f60427e55
```

How to get the `busybox-manifest.json` file for the image? I mean image manifest using skopeo command?

**Comment by akshayvijapur** [comment]
got it

**Comment by mtrmac** [comment]
FWIW you should basically never use `standalone-verify`; set up `policy.json` instead.

**Comment by akshayvijapur** [comment]
@mtrmac thanks,  pls explain `policy.json` or point to document.

**Comment by mtrmac** [comment]
https://github.com/containers/image/blob/main/docs/containers-policy.json.5.md . I’d really expect any documentation that pointed you at the “simple signing” feature set to include that.
