### ISSUE TITLE
Filter layers while using skopeo copy

### ISSUE THREAD

**Issue by k-e-r-n-e-l-p-a-n-i-c** [containers/skopeo#1872]
Hello,

I have a need to copy images from docker registry (transport as docker) to the local file system (transport as dir) under a dedicated directory. This directory will already contain previously copied image digests/layers. I want to replicate the behavior of a docker pull command which will skip downloading the existing layers, using skopeo. I would like to know if below is possible:

1. Allow skopeo to copy files using transport as 'dir' even if the directory is not empty. At the moment skopeo complains if this is  a non-empty directory.
2.  Filter/skip layers which are already available in the target directory.

Note: I want to use the target transport as 'dir' only.

Thanks and Regards

**Comment by mtrmac** [comment]
Thanks for reaching out.

`dir` is really a debugging tool, intentionally with not much complexity to it.

What are you _ultimately_ trying to do? The `dir:` state is certainly only a means to some end.

In many cases, using a temporary local registry (e.g. in a container, listening only on `localhost`) is a more efficient way to copy a large number of images.

For truly specialized situations (e.g. some kind of image scanning), calling GitHub.com/containers/image directly from a custom Go program is probably better than tryin to bend Skopeo to an unusual purpose.

**Comment by k-e-r-n-e-l-p-a-n-i-c** [comment]
Thank you @mtrmac .  Your answer clarifies my question. I will look into image module (and the go docs) to see how can I use it as a library in my code.

Regards
