### ISSUE TITLE
RFE: Install shell completions in Homebrew

### ISSUE THREAD

**Issue by foolioo** [containers/skopeo#1873]
Firstly, **thank you** for Skopeo!

Skopeo has a support for [shell completion](https://github.com/TomWright/dasel#completion) and has a [Homebrew formula for installation](https://github.com/containers/skopeo/blob/main/install.md#macos).

What do you think of adding another formula for installing the shell completion (such as [brew-cask-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/brew-cask-completion.rb), [rake-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/rake-completion.rb), [bundler-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/bundler-completion.rb), [ruby-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ruby-completion.rb), [vagrant-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/vagrant-completion.rb), [packer-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/packer-completion.rb), [gem-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gem-completion.rb), [pip-completion](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pip-completion.rb), ... just to name a few), or utilize the current formula for installing the shell completion?

**Comment by mtrmac** [comment]
Thanks for the proposal.

Coming from a Linux world, I would expect completion to be included in the main package, but I’m not very certain about the customs of Homebrew.

@ashley-cui what’s the right thing to do here, please?

**Comment by ashley-cui** [comment]
Will get it done soon!

**Comment by ashley-cui** [comment]
Skopeo's Homebrew formula already has shell completions installed by default! You may have to configure your shell to recognize homebrew completions: https://docs.brew.sh/Shell-Completion
