### ISSUE TITLE
Skopeo copy fails when image contains attestation manifest

### ISSUE THREAD

**Issue by sjauld** [containers/skopeo#1874]
When images are built with buildx >= v0.10.0, an [SLSA Provenance](https://slsa.dev/provenance/) attestation is added. This causes skopeo copy to fail with the error

```
Error creating an updated image manifest: Error preparing updated manifest, layer \"sha256:<sha>\": unsupported MIME type for compression: application/vnd.in-toto+json
```

See https://github.com/docker/buildx/releases/tag/v0.10.0

**Comment by tyranron** [comment]
Have the same issue with my workflows: https://github.com/instrumentisto/rust-docker-image/actions/runs/3984656840/jobs/6831114769#step:6:50

**Comment by mtrmac** [comment]
Thanks for your report. What version of Skopeo is this? That’s not expected with ≥ 1.9.0 AFAICS.

If it happens with a recent version, please attach the complete output of `skopeo --debug copy …`

**Comment by sjauld** [comment]
Thanks @mtrmac. I was using the latest version in the Debian Bullseye repo, which is horrendously out of date. It works fine when I build the latest version myself.

@tyranron as another workaround I added `--sbom=false --provenance=false` to my docker build step - this enables me to still use Debain version of skopeo to copy the containers.

**Comment by tyranron** [comment]
@sjauld thanks for the workarounds!

**Comment by snowmanstark** [comment]
I use the quay.io/skopeo:latest image and I am also facing this issue. Is there any other image which fixes this issue?

**Comment by mtrmac** [comment]
@snowmanstark Please file a separate issue, include the specific version number of Skopeo, and the debug output per https://github.com/containers/skopeo/issues/1874#issuecomment-1400508324 .
