### ISSUE TITLE
copy from docker-archive to quay not preserving image tag

### ISSUE THREAD

**Issue by GCHQDeveloper926** [containers/skopeo#1878]
I'm trying to do a `skopeo copy` from a docker archive to a redhat quay instance but I am seeing it only get tagged with latest as opposed to my image tag. I am wondering if this is a problem with skopeo or redhat quay so I can try and narrow down a solution. 

I can see that my tag does exist when I do `list-tags`, and I know this works when I push to other registry types. 

`[{xyx:1.2.3}]` etc

I've tried using `--additional-tag` as well to try and force a tag with no avail. 

I am interested if anyone else has seen this issue, will be investigating with Quay as well if I can.

Quay v3.8
Skopeo v1.1.0

**Comment by mtrmac** [comment]
Thanks for your report. Please provide a complete reproducer, at the very least the full command in question, and expected/actual results.

Also note this part of the `skopeo copy` man page:
> _source-image_ and _destination-image_ are interpreted completely independently; e.g. the destination name does not
automatically inherit any parts of the source name.

**Comment by mtrmac** [comment]
I’m assuming this works as documented; please reopen if that’s not the case.
