### ISSUE TITLE
Cannot delete Docker images from ghcr.io

### ISSUE THREAD

**Issue by duhow** [containers/skopeo#1880]
```sh
skopeo delete docker://ghcr.io/organization/my-application@sha256:DOCKER-HASH-SHA256-IMAGE

FATA[0001] Failed to delete /v2/organization/my-application/manifests/sha256:DOCKER-HASH-SHA256-IMAGE:
{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
 (405 Method Not Allowed) 
```

I'd like to remove some old images from GitHub Container Registry.

**Comment by mtrmac** [comment]
Please reopen if there’s more to this.

**Comment by felipecrs** [comment]
I still have the same issue:

```
skopeo delete docker://ghcr.io/felipecrs/alpine
FATA[0000] Failed to delete /v2/felipecrs/alpine/manifests/sha256:c0669ef34cdc14332c0f1ab0c2c01acb91d96014b172f1a76f3a39e63d1f0bda: {"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
 (405 Method Not Allowed)
```

> The client can’t very well substitute for a server just not providing a feature. (https://github.com/containers/image/issues/1616 suggests that this was actually possible, in principle some time ago.)

The issue you referred to mentioned GCR, not ghcr.io.

I understand that this is server related feature. However, GitHub has allegedly implemented it:

https://github.com/orgs/community/discussions/24974#discussioncomment-3246040

But it still doesn't work.

**Comment by mtrmac** [comment]
> However, GitHub has allegedly implemented it:

By my very brief attempt to follow the links, that’s some GitHub Packages REST API, not the registry API.

**Comment by felipecrs** [comment]
That would make sense. I'll try to ping them for implementing the feature in the registry API side.
