### ISSUE TITLE
Add option to `skopeo copy from-img oci-archive:destination.tar` to skip some layers in the destination

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/skopeo#1889]
I create two images, one is called A:
```
FROM scratch
…
```
the other is called B:
```
FROM A
…
```
To transport the image B on another system I call
```
skopeo copy containers-storage:localhost/ABC:123 oci-archive:ABC-123.tar
```
and on the other system I call
```
skopeo copy oci-archive:ABC-123.tar containers-storage:localhost/ABC:123
```
This works as expected.

As next I rebuild only image B, keeping A unmodified.  Image A is present on the destination system as blob, not displayed by `podman images`.  Thus I want to copy only the last layer of image B.  The above copy-to-oci-archive copies all layers.

`skopeo copy` has to means to copy to an oci-archive-tar file only specific images (blobs, layers) from an image.

**Comment by mtrmac** [comment]
… and a registry also notably allows multi-threaded copies, with multi-threaded compression and O(1) access to individual layers; whereas `oci-archive` is structurally a linear file that must be copied as a whole, compressed as a whole, and decompressed as a whole.

**Comment by dilyanpalauzov** [comment]
For trivial setups/workflows/needs registries are overengineering.

**Comment by mtrmac** [comment]
Well, the engineering to avoid duplicates and parallelize and the like exists for registries. `podman run registry:2 -p … -v /some/temporary/directory/to/copy` might not be _that_ much of a hurdle.

The “trivial” format of `oci-archive` is not over-engineered that way, and therefore can’t do things like that. (Besides the thing with `tar` making some of the over-engineering fundamentally impossible or at least unprofitable.)

**Comment by dilyanpalauzov** [comment]
This ticket is not about advantages or disadvantages of registries.

**Comment by mtrmac** [comment]
The very first response was that the OCI image format does not allow partial images, so _exactly_ what you ask is impossible.

Skopeo could, plausibly, generate files in some non-standard extension / new file format to allow that feature; but we already have that feature, _and more_, some of which is fundamentally impossible to do with `oci-archive:` by using (possibly very temporary) registries.

So we are very unlikely to work on adding that non-standard extension / new file format.
