### ISSUE TITLE
Is skopeo has any packages that can be imported?

### ISSUE THREAD

**Issue by jsparter** [containers/skopeo#1891]
I want to import skopeo to my project so as to use skopeo abilities, but I can't find an elegent way to import skopeo
Does skopeo have plans to export packages for use like buildah?

**Comment by vrothberg** [comment]
> I want to import skopeo to my project so as to use skopeo abilities, but I can't find an elegent way to import skopeo Does skopeo have plans to export packages for use like buildah?

Thanks for reaching out.  Skopeo is not intended to be used a Go library.  Instead it suggest to use `github.com/containers/image`. Skopeo is really just a (comparatively thin) layer around the image library.

**Comment by jsparter** [comment]
> 

Oh, thanks a lot., I'll turn to use `github.com/containers/image` directly as you said

**Comment by vrothberg** [comment]
Excellent!  The Skopeo code can serve as a nice example of how to use c/image.
