### ISSUE TITLE
skopeo copy to v2s2 format fails on application/octet-stream config

### ISSUE THREAD

**Issue by mattclay** [containers/skopeo#1910]
Using `skopeo copy` with the `--format v2s2` option is unable to copy images with a config media type of `application/octet-stream`. Attempting to do so (at least when copying to quay.io) results in a `manifest invalid` error:

```
$ bin/skopeo --version
skopeo version 1.11.1-dev commit: e0893efc48544c13048d3506ece9899ae54ba339
$ bin/skopeo copy docker://docker.io/ubuntu:15.10 docker://quay.io/mattclay/quay-test:ubuntu-15.10 --format v2s2
Getting image source signatures
Copying blob 7dcf5a444392 skipped: already exists  
Copying blob 759aa75f3cee skipped: already exists  
Copying blob 224c42ae46e7 skipped: already exists  
Copying blob 3fa871dc8a2b skipped: already exists  
Copying config 9b9cb95443 done  
Writing manifest to image destination
FATA[0003] writing manifest: uploading manifest ubuntu-15.10 to quay.io/mattclay/quay-test: manifest invalid 
```

The config media type for the image being copied is `application/octet-stream`:

```
$ docker manifest inspect ubuntu:15.10 | head -n 5
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/octet-stream",
```

The full error body returned by quay.io is:

```
{"errors":[{"code":"MANIFEST_INVALID","detail":{"message":"failed to parse manifest: manifest data does not match schema: 'application/octet-stream' is not one of ['application/vnd.docker.container.image.v1+json']\n\nFailed validating 'enum' in schema['properties']['config']['properties']['mediaType']:\n    {'description': 'The MIME type of the referenced object. This should '\n                    'generally be '\n                    'application/vnd.docker.container.image.v1+json',\n     'enum': ['application/vnd.docker.container.image.v1+json'],\n     'type': 'string'}\n\nOn instance['config']['mediaType']:\n    'application/octet-stream'"},"message":"manifest invalid"}]}
```

If I modify skopeo to replace the config media type with `application/vnd.docker.container.image.v1+json` then the upload is accepted by quay.io.

I realize I could simply omit the `--format` option when using `copy` to work around the issue. However, when using `sync` that is problematic, as specifying `--format v2s2` resolves issues copying other images (which I plan on investigating further).

**Comment by mtrmac** [comment]
Thanks for your report.

I mean, that image is invalid at the source, per https://github.com/distribution/distribution/blob/main/docs/spec/manifest-v2-2.md#image-manifest-field-descriptions. Skopeo does not, in general, try to fix up images to mean what Skopeo _thinks_ they mean; in general the copy process should preserve the original form (and the original digest in particular).

Quay has fairly strong validation, and so it rejects this invalid image.

---

A possible workaround seems to be to use `--format oci` to create an OCI formatted image (which, in the current c/image implementation, _happens_ not to validate the MIME type and creates a correct image, and perhaps then to convert back to `v2s2`.

(This is also why not using `--format` works: without `--format`, Skopeo is allowed to try converting, so it tries `v2s1`, and for the same reason the implementation _happens_ to turn the invalid image into a valid one.)

Also, https://hub.docker.com/layers/library/ubuntu/15.10/images/sha256-9b9cb95443b5f846cd3c8cfa3f64e63b6ba68de2618a08875a119c81a8f96698?context=explore says that image was pushed 7 years ago, and per https://hub.docker.com/_/ubuntu it is not a supported tag.

Given that,
- Should that image be used at all, for _any_ purpose? It’s fairly certain to be a security risk
- It might be practical enough to sync that image once, perhaps manually and with the above workaround, and then exclude it from any future regular syncs, when the image is not expected to be updated.

**Comment by mattclay** [comment]
@mtrmac Thanks for the detailed explanation. I'm going with the manual sync once and skip approach -- which is a bit inconvenient, since it seems `skopeo sync` doesn't provide a way to skip specific tags, unless I missed something. I'm having to fetch the list of tags, filter it, and request a sync of what's left.

**Comment by mtrmac** [comment]
As it happens, there might be some improvement in this area: https://github.com/containers/skopeo/issues/852#issuecomment-1430795586 .

**Comment by mattclay** [comment]
@mtrmac Thanks for that. Feel free to close this issue, I don't think there's anything else to be done here.

**Comment by mtrmac** [comment]
Thanks!
