### ISSUE TITLE
Support `arch` `os` `platform` flags for `inspect` command.

### ISSUE THREAD

**Issue by kaovilai** [containers/skopeo#1914]
related to https://github.com/containers/skopeo/issues/634

--raw does not support format option.
I want to look at formatted output of a specific arch.

I am on darwin/arm64 and would like to use skopeo like a normal human being too on manifests containing only linux/amd64 image.

**Comment by mtrmac** [comment]
Thanks for your report.

What are you ultimately trying to do?

`--raw` is inherently somewhat in conflict with a formatting option, it’s more a tool to use when the native features fail or a re missing (though piping to something like `jq` is possible, of course, and re-formatting the raw output is not _completely implausible_).

For non-raw output, I routinely use `skopeo --override-os linux inspect …`, and that seems to work for me. (These options are listed in the global `skopeo --help`, not in the subcommand, but the man page does point out their existence.)

Ultimately, there is an outstanding #1283, but so far it’s unclear whether that’s what you are actually looking for.

**Comment by kaovilai** [comment]
@mtrmac TL;DR

```sh
❯ skopeo inspect -f '{{.Labels.version}}-{{.Labels.release}}' docker://xxx.registry.redhat.io/some/image@sha256:<manifest>      
FATA[0000] Error parsing manifest for image: choosing image instance: no image found in manifest list for architecture arm64, variant "", OS darwin
```

I should be able to just pass arch + os via flags above and be done with.

**Comment by kaovilai** [comment]
The help printout do not tell me about the override option. In any case I think it wouldn't hurt to have more than one flags that does the same thing especially if it can align skopeo with user of podman/docker somewhat.
```
 skopeo inspect --help                                                                                                                                                                            
Return low-level information about "IMAGE-NAME" in a registry/transport
Supported transports:
containers-storage, dir, docker, docker-archive, docker-daemon, oci, oci-archive, ostree, sif, tarball

See skopeo(1) section "IMAGE NAMES" for the expected format

Usage:
skopeo inspect [command options] IMAGE-NAME

Examples:
skopeo inspect docker://registry.fedoraproject.org/fedora
  skopeo inspect --config docker://docker.io/alpine
  skopeo inspect  --format "Name: {{.Name}} Digest: {{.Digest}}" docker://registry.access.redhat.com/ubi8

Flags:
      --authfile string             path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json
      --cert-dir PATH               use certificates at PATH (*.crt, *.cert, *.key) to connect to the registry or daemon
      --config                      output configuration
      --creds USERNAME[:PASSWORD]   Use USERNAME[:PASSWORD] for accessing the registry
      --daemon-host HOST            use docker daemon host at HOST (docker-daemon: only)
  -f, --format string               Format the output to a Go template
  -h, --help                        help for inspect
      --no-creds                    Access the registry anonymously
  -n, --no-tags                     Do not list the available tags from the repository in the output
      --password string             Password for accessing the registry
      --raw                         output raw manifest or configuration
      --registry-token string       Provide a Bearer token for accessing the registry
      --retry-times int             the number of times to possibly retry
      --shared-blob-dir DIRECTORY   DIRECTORY to use to share blobs across OCI repositories
      --tls-verify                  require HTTPS and verify certificates when talking to the container registry or daemon
      --username string             Username for accessing the registry


```

**Comment by mtrmac** [comment]
Dealing with the different `--help` scopes for main command / subcommands is admittedly a pain, but not easily fixed given other constraints we have (namely the need to differentiate between `skopeo --tls-verify… copy` and `skopeo copy --tls-verify…` and the like).

I’m not too much a fan of adding option aliases, _especially_ if they should show up in the `--help` output. A hidden alias is somewhat more plausible… but also less useful…

**Comment by kaovilai** [comment]
Then subcommand --help should suggest that more options maybe available in top level help

**Comment by mtrmac** [comment]
The `--help` output can never fully substitute a man page; in fact the `skopeo inspect` man page explicitly emphasizes the `--override-*` options in the description section.

Still, those man pages _should_ more consistently point at the two sets of options; #1944 should help with that.

**Comment by kaovilai** [comment]
Not every cli has a manpage. If you're running in a container you might not have man. If manpage exists, help shall point there as well.

**Comment by mikepurvis** [comment]
I think there's more than a documentation issue here. IMO the following should give me the raw manifest of Alpine's am64/linux image, but instead I get the listing of Alpine images for all platforms:

```
skopeo inspect docker://library/alpine --override-arch amd64 --override-os linux --raw | jq
```

**Comment by mtrmac** [comment]
No, `--override-`… are explicitly documented as “Use … for choosing images”; it does not impact the _kind of operation_ the command does, only which of the per-platform alternatives is chosen.

There are other possible designs, and it might well make sense to provide something like `skopeo inspect --platform-entry linux/amd64 …`. That’s not what the current options are.

**Comment by mikepurvis** [comment]
My issue is that `skopeo inspect <image>:latest --raw` is ambiguous— for a single-arch image, it will give you that one, but for a multi-arch image, it will give you the multi-manifest response. So you have to have logic that's basically "if I got the multi-manifest response, pick X out of the list and get the SHA of it so that I can request the actual image, but if I got the actual image, then use that, first confirming that it matches my expect platform."

**Comment by mtrmac** [comment]
Sure, that’s #1283 .
