### ISSUE TITLE
Image cleanup/slimming options when copying

### ISSUE THREAD

**Issue by glennswest** [containers/skopeo#1915]
Facing a situation where a large set of apps(containers), where not developed with good practice on image layer control.
While I know there is other upstream tools, is there any intention of adding image layer reduction as part of skopeo.
Something like --squash

**Comment by mtrmac** [comment]
Thanks for reaching out.

Skopeo, and the underlying c/image library, does not really deal with the _contents_ of the layer tarballs.

That’s the domain of Buildah, and I guess a short shell script could be written to pull the image, and create a new squashed one, using Buildah and its `--squash` option (or `podman build --squash-all`).
