### ISSUE TITLE
Syncing and inspecting helm charts into docker registries

### ISSUE THREAD

**Issue by martencassel** [containers/skopeo#1922]
Sometimes i need to download all images references in helm charts.
This is solved usually with helm template|grep image and then docker pull/tag/push.

Could possible skopeo include such capabilities ? Syncing images from a particular chart into a private registry ? 

For example so sync images references in a helm chart:

skopeo sync --src helm bitnami/redis --dest docker registry.example.com/myrepo

Inspecting images in a chart

skopeo inspect helm://bitnami/redis
...
image1
image2
...

**Comment by mtrmac** [comment]
Thanks for reaching out.

> This is solved usually with helm template|grep image 

I’m not familiar with Helm; does that show some on-registry image location that could be copied?

---

> `skopeo inspect helm://bitnami/redis`

A `helm:` transport would need to be implemented as a new feature in the https://github.com/containers/image library, so that that syntax works universally. (Assuming it is read-only, it could mostly just redirect to the existing `docker://` implementation.)

> `skopeo sync --src helm bitnami/redis --dest docker registry.example.com/myrepo`

Is this intended to aways be a single-image sync, although possibly with many different Helm charts, one at a time? Or some kind of inherently multi-image sync operation?

---

Right now, it seems to me that a small helper (possibly just a small shell script) that turns a helm reference into a `docker://` reference, outside of the Skopeo implementation, would be easier to write and maintain than some kind of native integration:

```sh
skopeo inspect docker://$(helm-to-image-ref bitnami/redis)
```
and the like.

But that very much depends on the details, and I guess on whether the c/image transport would need to do something noticeably different or more complex than just extracting up an image name from a command output.

**Comment by martencassel** [comment]
Thanks for your input...

```bash
helm-to-image-ref() {
HELM_CHART_REF=$1
helm template $HELM_CHART_REF|grep image|grep image:|xargs|sed --expression 's/image://g' - |xargs
}

$ helm-to-image-ref jetstack/cert-manager

quay.io/jetstack/cert-manager-cainjector:v1.11.0 quay.io/jetstack/cert-manager-controller:v1.11.0 quay.io/jetstack/cert-manager-webhook:v1.11.0 quay.io/jetstack/cert-manager-ctl:v1.11.0
```

In many cases a helm chart might reference images from multiple docker registries.

**Comment by mtrmac** [comment]
Oh, thanks for clarifying. That’s rather different than I thought.

> `skopeo inspect helm://bitnami/redis`

this just wouldn’t fit the model; the “image name” used for `skopeo inspect` is supposed to designate exactly one image.

---

OTOH this does make the case for some kind of native support in `skopeo sync` a bit stronger.

How would the source → destination repo mapping work, though? Can the helm template reference images from multiple repositories, namespaces, or even multiple different registries?

**Comment by martencassel** [comment]
Here is an actual real world situation:

You have a platform team in a enterprise that hosts the internal k8s.
They want to ship a particular helm chart from a vendor (mirantis) and all its related charts and images needed internally.
They host all images in a single private registry in a platform team specific repository like private-registry.internal/platform-tools.
The helm charts in question consists of the core helm chart and two dependencies (postgres-operator, and cert-manager).
All the images in the three charts come from various public image registries. 
But they like to push all images into a single private repository from the internet (possible through artifactory remote proxy).
After figuring out image references, the persona installing all charts, has to rewrite the found images into the target images
that will eventually be available in the onprem private registry repository, ie. private-registry.internal/platform-tools/cert-manager-controller:v1.11.0

So here is the steps needed:

helm repo add postgres-operator \
        https://opensource.zalando.com/postgres-operator/charts/postgres-operator/
helm repo update
helm template postgres-operator postgres-operator/postgres-operator|grep image:

image: "registry.opensource.zalan.do/acid/postgres-operator:v1.9.0"
  docker_image: ghcr.io/zalando/spilo-15:2.1-p9
    logical_backup_docker_image: registry.opensource.zalan.do/acid/logical-backup:v1.8.0
    connection_pooler_image: registry.opensource.zalan.do/acid/pgbouncer:master-26

helm repo add jetstack https://charts.jetstack.io
helm repo update
helm template certmanager jetstack/cert-manager|grep image:

   image: "quay.io/jetstack/cert-manager-cainjector:v1.11.0"
          image: "quay.io/jetstack/cert-manager-controller:v1.11.0"
          image: "quay.io/jetstack/cert-manager-webhook:v1.11.0"
          image: "quay.io/jetstack/cert-manager-ctl:v1.11.0"



helm template  msr msrofficial/msr --version 1.0.0 \
	--api-versions=acid.zalan.do/v1 \
	--api-versions=cert-manager.io/v1|grep Image:

image: "registry.mirantis.com/msr/enzi:1.0.0"
image: "mirantis/rethinkdb:2.3.6-mirantis-35-7d29e61"
image: "registry.mirantis.com/msr/msr-api:3.0.0"
image: "registry.mirantis.com/msr/msr-garant:3.0.0"
image: "registry.mirantis.com/msr/msr-jobrunner:3.0.0"
image: "registry.mirantis.com/msr/msr-nginx:3.0.0"
image: "registry.mirantis.com/msr/msr-notary-server:3.0.0"
image: "registry.mirantis.com/msr/msr-notary-signer:3.0.0"
image: "registry.mirantis.com/msr/msr-registry:3.0.0"
image: "registry.mirantis.com/msr/enzi:1.0.0"
image: "mirantis/rethinkdb:2.3.6-mirantis-35-7d29e61"
image: "registry.mirantis.com/msr/msr-api:3.0.0"

---
Something to consider:

1. In the above case, for convenience because the platform team hosts all their internal
tools like the msr related images are stored  in a single repository.

2. Helm chart can reference images from a multitude of public registries.

3. There is no standard "image:" key for image references. 
I've seen images being referenced in pod deployment config variables,
because the software launch containers on demand using this config.

4. Docker image references should possible be identifiable and findable (possible) their syntax using a string search.

5. The above chart msr, have depenency checks for the dependant charts (cert-manager, and postgres-operator). 
To do a helm template --api-versions arguments has to be given, so our helm image ref macro breaks in that case.

**Comment by mtrmac** [comment]
> 3. There is no standard "image:" key for image references.
>    I've seen images being referenced in pod deployment config variables,
>    because the software launch containers on demand using this config.

That’s not great for a reliable feature.

> 4. Docker image references should possible be identifiable and findable (possible) their syntax using a string search.

… even worse.

(And if the image references can be in arbitrary config variables, I wouldn’t be surprised to see a `product_repo = quay.io/product` + `individual_image = server:123`, combined in code to point at `quay.io/product/server:123` — actually to make mirroring and redirection easier :).)

---

There’s also the consumption side to consider.
- If `skopeo sync` is solely responsible for defining and determining the source → destination mapping, presumably the mapping would be determined by parsing the output of `skopeo sync`… fair enough, it _is_ using some kind of structured logging (although the output format is, strictly speaking, undocumented and not committed to be stable)
- Then, that mapping needs to somehow be _applied_ to trigger uses of the mirror registry. There are features like `registries.conf` that allow defining it on a system (or on systems managed by a cluster). But if it is possible to not pull images directly, but the Helm chart can launch containers that pull other containers, it’s not obvious that `registries.conf` on a host would apply to those in-container pulls. If the source reference were found in the Helm template using a “string search”, would then the deployment try to do a naive search&replace on the Helm template, then?

My first impression is that determining the set of images to be mirrored, and the ways to point at those images in a mirror-based deployment, might be way too application-specific to be usefully hidden behind an abstraction.
