### ISSUE TITLE
Renovate’s update PRs filed too frequently for digest dependencies

### ISSUE THREAD

**Issue by mtrmac** [containers/skopeo#1926]
https://github.com/containers/skopeo/pull/1904 was filed on 2023-02-11; merged on 2023-02-23.
Just three hours later, https://github.com/containers/skopeo/pull/1924 was filed.

https://github.com/containers/automation/blob/fada0fa488981a2b1ddd9d3f1debf71571143cba/renovate/defaults.json5#L112-L117 suggests that a new PR should be filed on the first day of the month (only), and IIRC that used to work.

@cevich do you know what is happening? (This is low-priority, the PRs are easy to ignore.)

**Comment by cevich** [comment]
I don't recall changing this config but I'll look into it.  Thanks for the references.

**Comment by cevich** [comment]
Curiously both mentioned PRs say in their description: "Schedule: Branch creation - At any time".  So definitely the mentioned rule is not being used for some reason.

**Comment by cevich** [comment]
Debug log entry:

```json
          {
            "currentDigest": "5e25df0256eb",
            "currentValue": "v0.0.0-20230213192124-5e25df0256eb",
            "currentVersion": "v0.0.0-20230213192124-5e25df0256eb",
            "datasource": "go",
            "depIndex": 14,
            "depName": "golang.org/x/exp",
            "depType": "require",
            "digestOneAndOnly": true,
            "fixedVersion": "v0.0.0-20230213192124-5e25df0256eb",
            "managerData": {
              "lineNumber": 18,
              "multiLine": true
            },
            "sourceUrl": "https://github.com/golang/exp",
            "versioning": "semver",
            "warnings": [],
            "updates": [
              {
                "updateType": "digest",
                "newValue": "v0.0.0-20230213192124-5e25df0256eb",
                "newDigest": "c95f2b4c22f226b18030fd3b7d5cd47e0d12395a",
                "branchName": "renovate/golang.org-x-exp-digest"
              }
            ]
          },
```

**Comment by cevich** [comment]
After merging https://github.com/containers/automation/pull/130 I ticked the "rebase" box on https://github.com/containers/skopeo/pull/1924  In a moment, renovate should re-run on that PR and (hopefully) update the schedule.

**Comment by cevich** [comment]
The update happened and changed the description to read:

"date Schedule: Branch creation - "after 1am and before 11am on the first day of the month" in timezone UTC, Automerge - At any time (no schedule defined)."

So my guess at a fix seems to have worked :tada:

**Comment by mtrmac** [comment]
Thanks!
