### ISSUE TITLE
`skopeo copy` fails with "requested access to resource is denied"

### ISSUE THREAD

**Issue by rnjudge** [containers/skopeo#1929]
I am trying to copy an image built locally using docker (`docker build -t tagless:test .`) to a directory using skopeo but keep getting an access denied error:

```
[rose@fedora home]$ skopeo copy docker://tagless:test dir:/home/rose/.tern/temp
FATA[0001] initializing source docker://tagless:test: reading manifest test in docker.io/library/tagless: requested access to the resource is denied
```

I am logged in to docker. How do I authenticate the copy?

Thanks in advance.

**Comment by mtrmac** [comment]
Thanks for your report.

Run `skopeo --debug copy …`, see where it is reading credentials from, if anywhere.

**Comment by mtrmac** [comment]
Oh… a _locally-built image_.

That’s not `docker://tagless:test` (an image uploaded to `docker.io/library/tagless:test`. Try using `docker-daemon:tagless:test`.

**Comment by rnjudge** [comment]
A-ha! That's what I was missing. Sorry about that. Thanks for your time and the solution :)
