### ISSUE TITLE
skopeo copy local file to harbor error

### ISSUE THREAD

**Issue by freemankevin** [containers/skopeo#1934]
```shell
$ skopeo copy --dest-tls-verify=false --all --dest-creds "admin:Harbor12345" dir:"/root/tmp/multi/" docker://harbor.dockerregistry.com/multi-arch/kkfileview:multi
Getting image source signatures
FATA[0000] Error trying to reuse blob sha256:a39c84e173f038958d338f55a9e8ee64bb6643e8ac6ae98e08ca65146e668d86 at destination: error pinging docker registry harbor.dockerregistry.com: Get http://harbor.dockerregistry.com/v2/: EOF
```

**Comment by freemankevin** [comment]
```shell
$ skopeo copy --all --dest-creds "admin:Harbor12345" dir:"/root/busybox/" docker://harbor.dockerregistry.com/multi-arch/busybox:latest                                                                                                                                    1
Getting image list signatures
Copying 10 of 10 images in list
Copying image sha256:2c8ed5408179ff4f53242a4bdd2706110ce000be239fe37a61be9c52f704c437 (1/10)
Getting image source signatures
FATA[0000] Error trying to reuse blob sha256:1487bff95222881565c7c063129c2c2ce3d6fc4d14796ac7627bd1f167bc5621 at destination: error pinging docker registry harbor.dockerregistry.com: Get https://harbor.dockerregistry.com/v2/: EOF
```

**Comment by mtrmac** [comment]
Thanks for your report.

A `harbor.dockerregistry.com` does not exist on the public internet; are you substituting some internal host name?

Compare the output of `skopeo debug copy …`, to confirm, but basically this is the very first request to the registry, and the registry seems to just not respond with any data, if there is a registry at all.

Compare maybe `curl -iv 'http://harbor.dockerregistry.com/v2/'` . There should be _some_ output, not just nothing. If you see no response, that needs to be investigated at the server side, or in the relevant network infrastructure.

---

(BTW the Skopeo version seems to be somewhat old, with c/image before 1f79791095ef56f86931c52bf9e44e892d484fb7 . That’s fairly unlikely to be the cause.)

**Comment by freemankevin** [comment]
The reason has been found because of the version problem, v1.11 everything is normal, thank you, please close this issue.

**Comment by mtrmac** [comment]
Thanks for the confirmation.
