### ISSUE TITLE
Partial skopeo copy

### ISSUE THREAD

**Issue by snowmanstark** [containers/skopeo#1937]
Is there a way that I can copy only certain multi-arch images from the source image

eg: the source image supports following archs:
```
linux/amd64
linux/arm64
linux/arm/v8
linux/s390x
linux/ppc64le
```

But I want to copy only the following archs to my private registry:
```
linux/amd64
linux/arm64
linux/arm/v8
```

Currently `skopeo copy` only supports aither one arch or all the archs.

**Comment by mtrmac** [comment]
Thanks for reaching out.

That’s not currently possible; follow #1694 .
