### ISSUE TITLE
How to install project ... or better yet provide prebuilt binaries

### ISSUE THREAD

**Issue by verdverm** [containers/skopeo#1940]
There are no instructions, running `go install github.com/containers/skopeo/cmd/skopeo@latest` fails with 

```
../go/pkg/mod/github.com/containers/storage@v1.45.3/drivers/btrfs/btrfs.go:12:10: fatal error: btrfs/ioctl.h: No such file or directory
   12 | #include <btrfs/ioctl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

Ideally I would just download a binary, but some instructions would be appreciated in their absence

**Comment by mtrmac** [comment]
Thanks for reaching out. https://github.com/containers/skopeo/blob/main/install.md should help.

**Comment by verdverm** [comment]
I already solved my problem, I would just recommend pointing to installation instructions from the README.

GitHub now collapses the code view, so finding where the setup / install can be found is not as straight forward. Anyway, always good policy to put installation instructions in the main README, even if it's just a link to another doc

**Comment by mtrmac** [comment]
That document _is_ linked in the main README, but in a hard-to find place. #1943 should help with that for future readers.

Thanks again!
