### ISSUE TITLE
skopeo copy  ram usage

### ISSUE THREAD

**Issue by paneda1998** [containers/skopeo#1941]
hi
i have same problem as #714 
after reading this issue i check my grafana and this is some example:
![11](https://user-images.githubusercontent.com/52179148/226101863-761bfd95-5cf5-4bf1-9a14-b3fe28141eea.png)

its about 500MB of RSS memory and 0 to 600 Mb of cache memory.
and it seems RSS value is about half of ram limit of pod
for example this result is for 1Gb ram limit
if i set it to 2Gb everything is multiple by 2.

and another problem is RSS+cache is causing oom kill not only RSS

**Comment by paneda1998** [comment]
Hello, yes, you are right, I generally meant the memory oom kill problem.
i use this command:
skopeo copy [some image form different registeries] docker-archive:/dev/null

This is because I don't really need the image to be downloaded to the pod, so I drop it in this destination.
I'm using a proxy that this command causes the image to start pulling on a specific node...

**Comment by mtrmac** [comment]
That code triggers decompression; that does allocate a few MB, but from a naive look it should be about 4 MB, not 500. In my testing, the maximum RSS on macOS is 27 MB, by no means 500.

Is `/var/tmp` on a swap-based filesystem like `tmpfs`, by any chance? That’s the most likely explanation I can think of.

Failing that, I suppose it would be necessary to add a Go memory profiling code to Skopeo, something like https://pkg.go.dev/runtime/pprof#hdr-Profiling_a_Go_program .

**Comment by paneda1998** [comment]
Hey
I finally managed to solve this problem. The main issue was due to the fact that when I executed the Scopeo Copy command in a for loop structure, it was not done in a blocking manner, and the execution of the commands overlapped, causing a significant increase in RAM consumption. To solve this problem, I executed the commands in a blocking form, and the issue was resolved.

**Comment by TomSweeneyRedHat** [comment]
@paneda1998 nice sleuthing and TYVM for the update!
