### ISSUE TITLE
skopeo copy to Google Artifact registry fails with error

### ISSUE THREAD

**Issue by prakashlbg** [containers/skopeo#1954]
I am trying to copy my oci registry to gcp artificial registry but it fails and asks for credentials -
Error that I get - **Requesting bearer token: invalid status code from registry 403 (Forbidden)**

code I use - **skopeo copy oci-archive://xxxx.tar docker://registry_name/filename:tag**

Please can anyone help me how can I generate the bearer token for this operation?

**Comment by mtrmac** [comment]
Thanks for reaching out.

The bearer token is more or less a protocol detail of using credentials to access the repository. So my first guess is that the credentials (user name / password / …) just don’t allow writing to that specific destination, or perhaps the credentials might be incorrect.

**Comment by TheWiresharkGuy** [comment]
Same problem when copying a local image to a self hosted GitLab instance.
It worked perfectly with skopeo v1.10 but fails with the same error with v1.11 and later

**Comment by mtrmac** [comment]
@TheWiresharkGuy Is this reproducible? I can’t see any clearly relevant code changes in this area between Skopeo 1.10.0 and 1.11.0 (there are some changes in error handling, but we shouldn’t get to that part.)

**Comment by mtrmac** [comment]
Closing for lack of data; if this shows up again, please collect the output of `skopeo --debug copy …` when the failure is happening.

**Comment by TheWiresharkGuy** [comment]
@mtrmac 

Thanks to your `--debug` flag instruction, I've managed to find what was causing the issue in my case.

I'm using skopeo in a bash script like this: 

```
docker run -v "$HOME/.docker:/root/.docker:ro" --rm quay.io/skopeo/stable:v1.10 copy docker://... docker://...
```

> Does not work with skopeo v1.11 and later

I've changed the volume part and now It's working perfectly with v1.11 and later

```
docker run -v "$HOME/.docker:/tmp/auth.json:ro" --rm quay.io/skopeo/stable:v1.12 copy docker://... docker://...
```

So the debug message that helped me was:

```
time="2023-06-19T14:10:13Z" level=debug msg="Found credentials for ... in credential helper containers-auth.json in file /root/.docker/config.json"
```

Which did not appear with skopeo v1.11 and later.

Thanks again !
