### ISSUE TITLE
skopeo inspect --config docker://alpine   ;How to get all the different OS/ARCH with one command

### ISSUE THREAD

**Issue by JayLeonX** [containers/skopeo#1974]
For example, when I want to get the configuration of apline for the linux/arm/v6 architecture
`skopeo --override-os linux --override-arch arm --override-variant v6 inspect --config docker://alpine`

But I want to get the configuration of all architectures of the apline with just one command, I can't find the relevant command

The official docker commands are for example
`docker manifest inspect -v library/alpine@<sha256>`
Here the -v,  output additional info including all platform

Does skopeo have a similar command for exporting to all platforms?

**Comment by vrothberg** [comment]
Thanks for reaching out, @JayLeonX!

By default, Skopeo attempts to resolve to an individual image when hitting a manifest list/OCI image index.  You can change that by using the `--raw` flag. This will print the initial manifest (list) as is without any pretty-printing.

I usually do `skopeo inspect --raw docker://alpine | jq .`.  Then we can play with `jq` to process the JSON.  To list all architectures, you may use something similar to `jq ".manifests[].platform`.

**Comment by mtrmac** [comment]
`--raw` is not ideal because it forces the consumer to understand the specific manifest format; improving this is tracked in #1283 .
