### ISSUE TITLE
Skopeo default cert path

### ISSUE THREAD

**Issue by dcdh** [containers/skopeo#1976]
When I am doing a skopeo copy I've got this in my debug log:

```
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/container-registry.lab.stack:5000 
```

How can I setup my env to make skopeo using this directory by default: /etc/**containers**/certs.d/container-registry.lab.stack:5000

It should be already the case but I do not know why it is not :(

I guess /etc/docker/cert.d is the default path.

Who is in charge to defined and so how to define it ? 

I am using a Rocky Linux 9 with only podman (for creating a private registry), skopeo and httpd-tools

**Comment by dcdh** [comment]
I reply to myself. By default it will look on /etc/containers/cert.d/ ... if it could not find the registry it will not log and look forward into /etc/docker/cert.d ... on my side I make a mistake in directory naming. No log about the registry not found inside /etc/containers/cert.d ... maybe it should be nice to add a log about it .

**Comment by mtrmac** [comment]
Thanks for the update.

Care to propose a PR improving the debug logs? We might not want an individual debug log entry for all attempted directories, but maybe a single line showing what was tried and failed, and what was selected, would make sense.

**Comment by mtrmac** [comment]
(That would be a PR in the https://github.com/containers/image repo.)
