### ISSUE TITLE
OCI Zstd → schema2 uncompressed manifest conversion fails

### ISSUE THREAD

**Issue by lizelive** [containers/skopeo#1977]
i tried copying an image to my daemon. a few of the layers use `"mediaType": "application/vnd.oci.image.layer.v1.tar+zstd"`

`skopeo copy docker://registry.hf.space/project-baize-baize-7b:latest --dest-compress-format=gzip --format=v2s2 docker-daemon:registry.hf.space/project-baize-baize-7b:latest`
but that fails with
`FATA[0186] creating an updated image manifest: Error during manifest conversion: "application/vnd.oci.image.layer.v1.tar+zstd": zstd compression is not supported for docker images `

weird, i told you to use gzip. to try and fix i do

`skopeo copy docker://registry.hf.space/project-baize-baize-7b:latest --dest-compress-format=gzip --format=v2s2 dir:project-baize-baize-7b`

but the output dir still has zstd compressed layers :(

(to check manifest of image pulling)
```
curl https://registry.hf.space/v2/project-baize-baize-7b/manifests/latest -H "Accept: application/vnd.oci.image.manifest.v1+json"
```

how do i fix this?

**Comment by mtrmac** [comment]
This was fixed in Skopeo 1.14.0.
