### ISSUE TITLE
inspect failing on some ghcr images

### ISSUE THREAD

**Issue by revolunet** [containers/skopeo#2004]
Hi,

i'm using skopeo to check my images availability; for some reason, sometimes, `inspect` command dont work while the image is available :

`docker run quay.io/skopeo/stable inspect --retry-times 3 docker://ghcr.io/socialgouv/mon-psy-sante/app:1.69.4`

> time="2023-05-24T15:50:22Z" level=fatal msg="Error parsing manifest for image: fetching target platform image selected from image index: reading manifest sha256:f3840ef0a57f1467d7f126d1a64098333ad3eefeb7c18913298a5eb5454fe211 in ghcr.io/socialgouv/mon-psy-sante/app: manifest unknown"

Looks ok with `docker pull` though 

`docker pull ghcr.io/socialgouv/mon-psy-sante/app:1.69.4`

> 1.69.4: Pulling from socialgouv/mon-psy-sante/app
f56be85fc22e: Pull complete
8f665685b215: Pull complete
e5fca6c395a6: Pull complete
561cb69653d5: Pull complete
c5462cf75285: Pull complete
a4c0051e022b: Pull complete
265758bb4001: Pull complete
2805df4f0995: Pull complete
c528a6323221: Pull complete
5303f02a1256: Pull complete
a523bf56a68e: Pull complete
83fdfe89b3f9: Pull complete
3d49726c5211: Pull complete
480f655a2932: Pull complete
8da7a8e246da: Pull complete
Digest: sha256:7552f42192eabb7b3cf97d7cc1f0fa5750ede39a1ff531dc361b4c2ebee8ac78
Status: Downloaded newer image for ghcr.io/socialgouv/mon-psy-sante/app:1.69.4
ghcr.io/socialgouv/mon-psy-sante/app:1.69.4

What's wrong with this image ?

**Comment by mtrmac** [comment]
Thanks for your report.

The registry says the the per-architecture manifest is not available; AFAICt that‘s not something that can be fixed client-side. The server-returned error message also does not provide any more details:

```
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown"}]}
```

**Comment by mtrmac** [comment]
At least some very old Docker I have around fails similarly:
```console
# docker pull ghcr.io/socialgouv/mon-psy-sante/app:1.69.4
Trying to pull repository ghcr.io/socialgouv/mon-psy-sante/app ... 
manifest for ghcr.io/socialgouv/mon-psy-sante/app:1.69.4 not found
```

**Comment by revolunet** [comment]
which version do you use ? i have `Docker version 20.10.21, build baeda1f`

**Comment by mtrmac** [comment]
`moby-engine-20.10.23-1.fc38.x86_64.rpm` fails exactly the same for me.

**Comment by mtrmac** [comment]
Assuming this works correctly and the image is really missing on the registry, please reopen if there are indications that’s not the case.
