### ISSUE TITLE
Support for other registries

### ISSUE THREAD

**Issue by bharat-srinivasan** [containers/skopeo#2013]
Is there a plan to introduce support for other registries like Nvidia NGC, GHCR?

**Comment by mtrmac** [comment]
Thanks for reaching out.

What kind of functionality are you looking for, exactly? (And did you mean GHCR?)

From a quick check, reading `docker://nvcr.io/nvidia/tensorflow` seems to work fine for me.

**Comment by bharat-srinivasan** [comment]
We are looking at pulling images from different container registries and save them for faster usage. E.g. GHCR, NGC, etc
I tried out only the docker hub hosted image and didn't try NGC ones as it wasn't clear from documentation. I will give it a try now. Thanks for checking on that.

**Comment by mtrmac** [comment]
I’m assuming using other registries works, please reopen with a specific reproducer if that’s not the case.
