### ISSUE TITLE
Silently fails to copy to directory with special characters

### ISSUE THREAD

**Issue by xeor** [containers/skopeo#2019]
Example explains it all.. skopeo fails to copy without any form of notification if folder contains a `:` (might be other characters as well). This is very easy to reproduce

Making a symlink to the special folder and downloading from inside the symlinked folder works..

```sh
docker run -it --rm redhat/ubi9 bash
dnf install -y skopeo

# Making our test-folders
mkdir "/a" "/b:1"

# Downloading to a
[root@7bd17c88bc57 /]# skopeo copy docker://alpine:latest oci-archive://a/alpine.tar
Getting image source signatures
Copying blob 8c6d1654570f done
Copying config b4788059cc done
Writing manifest to image destination
Storing signatures

# Trying to download to b:1
[root@7bd17c88bc57 /]# skopeo copy docker://alpine:latest oci-archive://b:1/alpine.tar
Getting image source signatures
Copying blob 8c6d1654570f done
Copying config b4788059cc done
Writing manifest to image destination
Storing signatures

# See that the b:1 file is missing
[root@7bd17c88bc57 /]# ls -l "/a" "/b:1"
/a:
total 3260
-rw-r--r-- 1 root root 3336704 Jun 20 12:43 alpine.tar

'/b:1':
total 0

# symlinking the directory works
[root@7bd17c88bc57 /]# ln -s "/b:1" /c

# After downloading to the symlink c, that pointed to b:1, we got content in b:1
[root@7bd17c88bc57 /]# ls -l "/a" "/b:1"
/a:
total 3260
-rw-r--r-- 1 root root 3336704 Jun 20 12:43 alpine.tar

'/b:1':
total 3260
-rw-r--r-- 1 root root 3336704 Jun 20 12:48 alpine.tar

[root@7bd17c88bc57 /]# skopeo --version
skopeo version 1.11.2-dev
```

**Comment by mtrmac** [comment]
Thanks for your report.

Yes; the `:` character has a specific meaning in `oci-archive`, per https://github.com/containers/image/blob/main/docs/containers-transports.5.md . You’ll find that the data was written to a directory named `b`.

And we’ve painted ourselves into rather a corner: there is no very good way to allow including `:` in the syntax any more.

As you have found, using a symlink is a possible workaround.

**Comment by xeor** [comment]
Thanks for the info! It's not in a directory called `b`, but the tar-ball itself is going to be named `b`. I didn't notice that..
I guess it doesnt make sense to add a warning either then, if this is really a "supported format" that should in theory do something else. Or maybe it should be a headsup in the doc? At least other people can find this issue now to figure out what happened :)

**Comment by mtrmac** [comment]
I have filed https://github.com/containers/skopeo/issues/2019 to clarify that a bit.

**Comment by mtrmac** [comment]
https://github.com/containers/image/pull/2007 was merged, that should eventually propagate to distribution packages.
