### ISSUE TITLE
Skopeo copy does not copy the image and does not generate an error when the target image contains a digest

### ISSUE THREAD

**Issue by tkrishtop** [containers/skopeo#2023]
# How to reproduce

The following command is executed without any errors, but it does not copy the image to the local Quay registry:

```
skopeo copy 
--debug 
--all --preserve-digests 
--remove-signatures 
--authfile /path/to/config.json 
--dest-tls-verify=false 
docker://quay.io/operator-framework/scorecard-test@sha256:2598524c79f094b385fb01e89434956536da4c8ab54796dd21ccdbae127e4821 
docker://registry.dfwt5g.lab:4443/operator-framework/scorecard-test@sha256:2598524c79f094b385fb01e89434956536da4c8ab54796dd21ccdbae127e4821
```

If I remove the digest from the target image, everything works fine:

```
skopeo copy 
--debug 
--all 
--preserve-digests 
--remove-signatures 
--authfile /path/to/config.json 
--dest-tls-verify=false 
docker://quay.io/operator-framework/scorecard-test@sha256:2598524c79f094b385fb01e89434956536da4c8ab54796dd21ccdbae127e4821 
docker://registry.dfwt5g.lab:4443/operator-framework/scorecard-test
```

# Expected behavior

The command should not fail silently. It should either successfully copy the image, or it should fail and display an appropriate error message explaining the reason for the failure.

**Comment by mtrmac** [comment]
Thanks for your report.

How did you determine that the image was not copied? To my knowledge, this works fine:
```console
% skopeo copy --override-os linuxdocker://quay.io/libpod/alpine@sha256:634a8f35b5f16dcf4aaa0822adc0b1964bb786fca12f6831de8ddc45e5986a00 docker://quay.io/mitr/test-digest@sha256:634a8f35b5f16dcf4aaa0822adc0b1964bb786fca12f6831de8ddc45e5986a00        
…
% bin/skopeo inspect --authfile auth.json docker://quay.io/mitr/test-digest@sha256:634a8f35b5f16dcf4aaa0822adc0b1964bb786fca12f6831de8ddc45e5986a00 
{
    "Name": "quay.io/mitr/test-digest",
    "Digest": "sha256:634a8f35b5f16dcf4aaa0822adc0b1964bb786fca12f6831de8ddc45e5986a00",
…
```

Now, it is true that it does not show up on the web site.

And registries may have various policies about preserving, or not, images with no tag attached — I seem to remember Quay is on the aggressive side of removing them fairly soon.

But the upload almost certainly really did succeed. If you don’t think that’s the case, please provide steps how to determine that’s not the case, and the full `--debug` output of the copy.

**Comment by mtrmac** [comment]
Assuming this works as intended, please comment or reopen if that’s not the case.
