### ISSUE TITLE
Request for Feedback: OCI image-spec 1.1.0

### ISSUE THREAD

**Issue by sudo-bmitch** [containers/skopeo#2040]
OCI is approaching a 1.1.0 release on the image-spec and distribution-spec, so we are reaching out to implementations to see if you have any concerns implementing support for those changes that we should address before a GA release.

A full diff of the changes can be viewed at:

- image-spec: https://github.com/opencontainers/image-spec/compare/v1.0.2...opencontainers:image-spec:main
- distribution-spec: https://github.com/opencontainers/distribution-spec/compare/v1.0.1...main

I'm happy to take feedback here, you can raise an issue in OCI, or respond in our tracking issue at https://github.com/opencontainers/image-spec/issues/1093.

**Comment by mtrmac** [comment]
Hello @sudo-bmitch , thanks for reaching out. It’s great to hear from you again.

From what I’ve briefly seen in the RC phases, the new features are definitely interesting and look good in broad strokes.

I’m afraid I am a bit swamped with other work at this moment; https://github.com/opencontainers/image-spec/issues/1093 talks about a “six-week timeframe”, I’d like to review the details of the changes more carefully, and see what implementation changes are needed in c/image, by then.

**Comment by mtrmac** [comment]
I have reviewed those spec changes; much more detail / a to-do list is in https://github.com/containers/image/issues/2030 .

The code affected by the spec updates is, AFAICT, all in c/image, so I’ll leave that issue open to track implementation.

There’s nothing specific to do in Skopeo, so I’m closing this one.

@sudo-bmitch Thanks again for the heads-up!
