### ISSUE TITLE
Need latest version of skopeo on centos 7

### ISSUE THREAD

**Issue by akshayvijapur** [containers/skopeo#2051]
I am unable to find the latest version on centos 7, can you pls guide me to get latest version

**Comment by vrothberg** [comment]
Thanks for reaching out, @akshayvijapur !

CentOS 7 does not receive such updates anymore.  You need to build Skopeo yourself but I am pretty sure the version of go is too on CentOS 7.  Alternatively, you could use the `quay.io/skopeo/stable` container image and run Skopeo in a container.
