### ISSUE TITLE
mediaType in manifest is altered during sync

### ISSUE THREAD

**Issue by wrender** [containers/skopeo#2057]
I'm using Skopeo 1.10.0.

When I do a skopeo sync from a public repository, to a local dir (using --preserve-digests) and then use skopeo to sync images to a Harbor repository (also using --preserve-digests).   For some reason, only for certain images, it appears to alter the mediaType and results in errors (Below)

For example this happens for the image:  ghcr.io/dexidp/dex:v2.36.0

Then when the image is run in a Kubernetes cluster, with docker as the container runtime. We get the error:  
`ErrImagePull (rpc error: code = Unknown desc = Error response from daemon: mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json') `

If I just do a "docker save" and then "docker load" to copy the image to Harbor it then works.

**Comment by mtrmac** [comment]
Thanks for your report.

MIME types are not included in the data preserved by `--preserve-digests`, they are stored by registries separately. Historically, there have been registries that don’t really support OCI images, accept OCI content, but hard-code returning a Docker (non-OCI) MIME type.

At this point I definitely wouldn’t rule out a Skopeo bug, but a registry with that behavior, or something similar, would be my first hypothesis.

You can use e.g. `skopeo inspect --debug` to see what the registry reports:
```console
% skopeo inspect --debug --raw docker://ghcr.io/dexidp/dex:v2.36.0
…
DEBU[0000] GET https://ghcr.io/v2/dexidp/dex/manifests/v2.36.0 
DEBU[0000] Content-Type from manifest GET is "application/vnd.oci.image.index.v1+json" 
```

So, please check each registry to see what the MIME type is on each one. (The same information can also be seen in the logs of `skopeo --debug sync`.)

---

> If I just do a "docker save" and then "docker load" to copy the image to Harbor it then works.

Yeah but that, to my knowledge, doesn’t do the equivalent of `--preserve-digests`, let alone preserve all of the per-architecture instances.

If you don’t care about `--preserve-digests`, and the registry really doesn’t support OCI, `--format v2s2` would trigger an actual conversion to schema2. That might be necessary if upgrading the registry weren’t an option.

**Comment by wrender** [comment]
Ok. Appreciate the help. I will try running inspect --debug --raw shortly for more detail.

As far as I know Harbor supports OCI. I'm running a fairly recent version 2.7.1. I don't know that it is a problem that Harbor does not support OCI. Because it seems to hold the image fine, and their documentation says it supports OCI. It's when we go to pull the image later by a docker/kubernetes host, that it fails complaining that the mediaType is incorrect/altered (Error above). 

So it appears more to be, that:
1. Skopeo alters the mediaType during sync to OCI from docker v2.
2. When docker engine goes to pull the image, it errors on this.

I could try forcing --format v2s2, but I am also curious if we migrate to a newer docker engine, or to containerd, would the error just go away.

It seems more for compatibility that Skopeo shouldn't be altering the mediaType in the manifest from the original? Or their should be at least an option to disable altering of the mediaType?

**Comment by mtrmac** [comment]
There’s _some_ possibility that Skopeo does not preserve the original MIME type (the data is not carried through the whole process, it is autodetected from contents on upload), but it seems _quite_ unlikely to me (the autodetection looks at the top-level `mediaType` field in the JSON, and that exists in this image, so the there really is no ambiguity). Locally testing that autodetection code, the result on the image in question is `"application/vnd.oci.image.index.v1+json"`, so I‘m pretty confident that that’s what is being uploaded.

I think the first thing we need to _positively confirm_ is that the destination registry is in fact serving a v2s2 MIME type; at this point that’s a hypothesis.

And _then_, assuming that’s indeed the case, we need to figure out how that happened. I’m afraid the debug log does not currently record the autodetected type (that would need to happen around https://github.com/containers/image/blob/8c387a14f4ac95fb4aa0569e8e31439f988bc941/docker/docker_image_dest.go#L473 ); so that can be confirmed either by adding a debug log, or by dumping the HTTP traffic (something like https://github.com/containers/image/pull/201, or an intercepting proxy), or possibly from server-side logs.

**Comment by wrender** [comment]
Ok.  I tested using debug and raw like you suggested.

-  If I skopeo sync images to Harbor . And then query them, the "application/vnd.oci.image.index.v1+json" mediaType matches that of what you see from the public ghcr.io/dexidp/dex:v2.36.0  . This in turn seems to error out wit the original error I reported with our docker/kubernetes version.

- If I do a manual "docker save" and then "docker load", "docker tag", and "docker push" of this image to Harbor. Docker commands appear to be what is actually altering the mediaType and changing it to "application/vnd.docker.distribution.manifest.v2+json"  . In turn making it work with our docker version in the kubernetes clusters.

I think this shows that Docker is the issue in this scenario, as well as the industry transition for containers moving to OCI format?

I think most of our clusters are going to be migrating to containerd soon anyway, so I would imagine this will become a non-issue.

**Comment by mtrmac** [comment]
What version of Docker is that, actually? There are things like https://github.com/moby/moby/pull/40070 , but that’s _years_ old.

**Comment by wrender** [comment]
docker-ce-19.03.3-3.el7.x86_64
docker-ce-cli-19.03.3-3.el7.x86_64

**Comment by mtrmac** [comment]
Thanks. AFAICT that version does not support OCI at all, so running the original `ghcr.io/dexidp/dex:v2.36.0` image without mirroring wouldn’t work either.

A conversion using `--format v2s2` should help.

**Comment by wrender** [comment]
Thanks!

**Comment by mtrmac** [comment]
Assuming this now works as well as it can, please reopen if that’s not the case.

**Comment by wrender** [comment]
Yes. Issue ended up just being an outdated Docker version in our kubernetes cluster.  Updating to new docker version resolved the issue. Thanks again for your help!
