### ISSUE TITLE
image annotations only show up in raw view

### ISSUE THREAD

**Issue by rittneje** [containers/skopeo#2070]
I'm not sure if this constitutes a bug or a feature request.

We have an image with annotations on it. If I just do `skopeo inspect`, the annotations do not show up at all. If I do `skopeo inspect --raw` then I see an `annotations` property in the raw JSON that is a sibling of the `layers` property.

This image was built using buildctl with manifest annotations applied as per [the documentation](https://github.com/moby/buildkit/blob/master/docs/annotations.md).

I don't know of any public images that use annotations so I cannot provide a reproducer or tell if this is particular to the way buildctl sets annotations.

**Comment by mtrmac** [comment]
Closing in favor of #1583, then.
