### ISSUE TITLE
How can I use SOURCE-IMAGE as a list?

### ISSUE THREAD

**Issue by sdemura** [containers/skopeo#2072]
I want to do the equivalent of `docker save foo:bar biz:bang  | pzstd > output.tar.zst`, but I can't seem to figure out how to do this with skopeo

```
❯ skopeo copy --dest-compress-format zstd --override-os linux --override-arch arm64 --all 'docker://docker.io/rancher/rke2-runtime:v1.27.3-rke2r1,docker://docker.io/rancher/klipper-lb:v0.4.4'  docker-archive:skopeo-test-arm64.tar.zst
FATA[0000] Invalid source name docker://docker.io/rancher/rke2-runtime:v1.27.3-rke2r1,docker://docker.io/rancher/klipper-lb:v0.4.4: invalid reference format
```

What is the syntax for a source images list?

**Comment by mtrmac** [comment]
Thanks for reaching out.

That feature does not exist in the CLI; `skopeo copy` works one (possibly multi-arch) image at a time, and the `docker-archive:` syntax does not allow referring to multiple images.

It exists in the underlying containers/image library (`archive.NewWriter`), and that is IIRC available though `podman save`.

But, really, the `docker-archive:` format is a very inefficient way to store/transfer images as files. Almost any other alternative is better; typically I recommend using a temporary registry server, using `skopeo sync`, and then archiving/transporting the backing storage of that registry.

**Comment by sdemura** [comment]
`docker-archive` format may be less efficient to store/transfer, but it is vastly simpler for us to consume given what we're doing.

I appreciate the feedback nonetheless @mtrmac. Thanks!
