### ISSUE TITLE
All images in quay.io show deleted

### ISSUE THREAD

**Issue by shakeelosmani** [containers/skopeo#2095]
What is happening?

![image](https://github.com/containers/skopeo/assets/9120484/61b0128a-8bb1-4195-b3e7-a66e2ec19f3b)

**Comment by katlol** [comment]
Any workaround? for example ghcr?

**Comment by TomSweeneyRedHat** [comment]
@katlol There is no workaround at the moment.  We are working as fast as possible to get at least `:latest` images up there today, others as we can.  For updates, please follow the discussion on Podman's GitHub site: https://github.com/containers/podman/discussions/19796

Closing here.

**Comment by katlol** [comment]
Had success building my own image via GitHub Actions... for what it is worth.

https://github.com/katlol/containers
