### ISSUE TITLE
skopeo copies images/layers that are already present (docker-daemon -> docker-daemon)

### ISSUE THREAD

**Issue by swarren** [containers/skopeo#2107]
I'm using Skopeo to copy from the local docker-daemon to a docker-daemon on another machine, which is accessed via an ssh-forwarded unix socket. I believe skopeo should skip copying the images/layers that are already present on the destination, but it does not appear to.

I've tried both the version of Skopeo that's packaged in Ubuntu 22.04, and git HEAD (I compiled it on Ubuntu 23.04, but ran it on Ubuntu 22.04). The results were the same. The debug log below is from git HEAD.

I can see that some large images/layers/... are copied during this process, even if I simply re-run the exact same command over and over without changing the Docker image at all. This shows up in both skopeo's output (gives a progress bar and a bandwidth readout) and via `iotop` on the destination machine (shows high bandwidth use).

Machine A (destination):

```
ssh -R /swarren-data/machinea.docker.sock:/run/docker.sock machineb
```

Machine B (source):

```
skopeo copy \
    --debug \  # log is below
    --dest-precompute-digests \ # same issue with or without this with git HEAD; option doesn't exist on Ubuntu 22.04's version
    --dest-daemon-host unix:///swarren-data/machinea.docker.sock \
    docker-daemon:srcimage:srctag \
    docker-daemon:dstimage:dsttag
```

--debug Log:
```
DEBU[0016] No compression detected                      
DEBU[0019] Using blob info cache at /home/swarren/.local/share/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0019] No compression detected                      
DEBU[0019] No compression detected                      
DEBU[0019] No compression detected                      
DEBU[0019] No compression detected                      
DEBU[0019] No compression detected                      
DEBU[0019] No compression detected                      
DEBU[0019] IsRunningImageAllowed for image docker-daemon:docker.io/library/srcimage:srctag
DEBU[0019]  Using default policy section                
DEBU[0019]  Requirement 0: allowed                      
DEBU[0019] Overall: allowed                             
Getting image source signatures
DEBU[0019] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json] 
DEBU[0019] ... will first try using the original manifest unmodified 
DEBU[0019] Checking if we can reuse blob sha256:954c82bdeb5fcc80094317528fa3fcbb1026aeff64f872527d35ec9b4343b84d: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0019] No compression detected                      
DEBU[0019] No compression detected                      
DEBU[0019] Using original blob without modification     
DEBU[0019] Sending as tar file 954c82bdeb5fcc80094317528fa3fcbb1026aeff64f872527d35ec9b4343b84d.tar 
Copying blob 954c82bdeb5f done   | 
DEBU[0019] Checking if we can reuse blob sha256:721b7a38f2fc294aa841670a061947f2cca419689e935e1433dc3a27b8785db9: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0019] No compression detected                      
DEBU[0019] No compression detected                      
DEBU[0019] Using original blob without modification     
Copying blob 954c82bdeb5f done   | 
Copying blob 721b7a38f2fc done   | 
DEBU[0030] Checking if we can reuse blob sha256:7a32123898ef8da460509f637b34bc2766fd7f553f4fab44a27b95097d36edc9: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0030] No compression detected                      
DEBU[0030] No compression detected                      
Copying blob 954c82bdeb5f done   | 
Copying blob 721b7a38f2fc done   | 
Copying blob 7a32123898ef done   | 
DEBU[0030] Checking if we can reuse blob sha256:1899086c49745ff3c79ca7a6f2e6d16007fd95766103889478afe34148a94be2: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
DEBU[0030] No compression detected                      
Copying blob 954c82bdeb5f done   | 
Copying blob 721b7a38f2fc done   | 
Copying blob 7a32123898ef done   | 
Copying blob 1899086c4974 done   | 
DEBU[0030] Checking if we can reuse blob sha256:efce02de769b4fd95ad04cbec2117534b9074c9d22694f56008e28fcdb589ba9: general substitution = true, compression for MIME type "application/vnd.docker.image.rootfs.diff.tar.gzip" = true 
Copying blob 954c82bdeb5f done   | 
Copying blob 721b7a38f2fc done   | 
Copying blob 7a32123898ef done   | 
Copying blob 1899086c4974 done   | 
Copying blob efce02de769b done   | 
DEBU[0030] Checking if we can reuse blob sha256:7809ce0fd6bf705804e2db4fbfa3816dd1e91f488c57ce95890a319b3ba6053e: general substitution = true, compression fo
Copying blob 954c82bdeb5f done   | 
Copying blob 721b7a38f2fc done   | 
Copying blob 7a32123898ef done   | 
Copying blob 1899086c4974 done   | 
Copying blob efce02de769b done   | 
Copying blob 7809ce0fd6bf done   | 
DEBU[0030] No compression detected                      
DEBU[0030] Compression change for blob sha256:4e14b693ccb1d026fa17cd8a3310e3bed792d97ea125d452b1ce813a327049bb ("application/vnd.docker.container.image.v1+json") not supported 
DEBU[0030] Using original blob without modification     
DEBU[0030] Sending as tar file 4e14b693ccb1d026fa17cd8a3310e3bed792d97ea125d452b1ce813a327049bb.json 
Copying config 4e14b693cc done   | 
Writing manifest to image destination
DEBU[0030] Sending as tar link 6bf2f6983b3e979826be0d8a2475e7071dc9048792119af4886d47a4dce1680c/layer.tar -> ../954c82bdeb5fcc80094317528fa3fcbb1026aeff64f872527d35ec9b4343b84d.tar 
DEBU[0030] Sending as tar file 6bf2f6983b3e979826be0d8a2475e7071dc9048792119af4886d47a4dce1680c/VERSION 
DEBU[0030] Sending as tar file 6bf2f6983b3e979826be0d8a2475e7071dc9048792119af4886d47a4dce1680c/json 
DEBU[0030] Sending as tar link cbad4cb79bc45c65ad3abfaa611247fe66d1f3d1fc3649e99609c48bbeecde25/layer.tar -> ../721b7a38f2fc294aa841670a061947f2cca419689e935e1433dc3a27b8785db9.tar 
DEBU[0030] Sending as tar file cbad4cb79bc45c65ad3abfaa611247fe66d1f3d1fc3649e99609c48bbeecde25/VERSION 
DEBU[0030] Sending as tar file cbad4cb79bc45c65ad3abfaa611247fe66d1f3d1fc3649e99609c48bbeecde25/json 
DEBU[0030] Sending as tar link a1accb520ed346cc90fda717909feaa2ae0176af9e955ec58a86f2d109d24f64/layer.tar -> ../7a32123898ef8da460509f637b34bc2766fd7f553f4fab44a27b95097d36edc9.tar 
DEBU[0030] Sending as tar file a1accb520ed346cc90fda717909feaa2ae0176af9e955ec58a86f2d109d24f64/VERSION 
DEBU[0030] Sending as tar file a1accb520ed346cc90fda717909feaa2ae0176af9e955ec58a86f2d109d24f64/json 
DEBU[0030] Sending as tar link 06f96389097fbe988d50d36171fa05025598aae63cdfb58b0e7703b490b0750c/layer.tar -> ../1899086c49745ff3c79ca7a6f2e6d16007fd95766103889478afe34148a94be2.tar 
DEBU[0030] Sending as tar file 06f96389097fbe988d50d36171fa05025598aae63cdfb58b0e7703b490b0750c/VERSION 
DEBU[0030] Sending as tar file 06f96389097fbe988d50d36171fa05025598aae63cdfb58b0e7703b490b0750c/json 
DEBU[0030] Sending as tar link a0ccd1eb61757841211768481c750ab515f69697ea51f113a93ddb622416cdf2/layer.tar -> ../efce02de769b4fd95ad04cbec2117534b9074c9d22694f56008e28fcdb589ba9.tar 
DEBU[0030] Sending as tar file a0ccd1eb61757841211768481c750ab515f69697ea51f113a93ddb622416cdf2/VERSION 
DEBU[0030] Sending as tar file a0ccd1eb61757841211768481c750ab515f69697ea51f113a93ddb622416cdf2/json 
DEBU[0030] Sending as tar link 5cc1b93aa50495e29a3231cab6f149f84420978eb24c8f88cfec166d5922ca78/layer.tar -> ../7809ce0fd6bf705804e2db4fbfa3816dd1e91f488c57ce95890a319b3ba6053e.tar 
DEBU[0030] Sending as tar file 5cc1b93aa50495e29a3231cab6f149f84420978eb24c8f88cfec166d5922ca78/VERSION 
DEBU[0030] Sending as tar file 5cc1b93aa50495e29a3231cab6f149f84420978eb24c8f88cfec166d5922ca78/json 
DEBU[0030] docker-daemon: Closing tar stream            
DEBU[0030] Sending as tar file manifest.json            
DEBU[0030] Sending as tar file repositories             
DEBU[0030] docker-daemon: Waiting for status            
DEBU[0030] docker-daemon: sending done, status <nil>    
```

**Comment by mtrmac** [comment]
Thanks for reaching out.

Yes; the `docker-daemon` transport is a wrapper around one-shot `docker save`/`docker load`, it is not interactive in a way that would allow detecting that layers already exist. It is an interoperability/transition mechanism, so significant changes to add new features are not very likely.

I would rather strongly recommend not using `docker-daemon` in workflows, _especially not_ two of them: creating/consuming the `docker-daemon` tarballs, one uncompressed file at a time, is always going to be _much_ slower, CPU and IO-intensive, than doing registry-to-registry copies (`docker://`→`docker://`) of compressed data.

**Comment by swarren** [comment]
> Even if we wanted to, this is also just impossible:
> The Docker Engine API does not provide any way to export a single layer, nor a way to import a single layer

I was worried you were going to say that.

> I have heard of someone building such invalid archives, but that‘s a hack that can break at any time if the
> docker load implementation ever changes.

Interesting. I was vaguely thinking of trying that before finding Skopeo... I don't suppose this was in a published script/tool anywhere?

I don't suppose there are any Docker implementations (or container systems in general) that use some custom daemon that shares storage between a Docker daemon and Docker register implementation, to avoid the duplicate-disk-space usage of a push/pull model?

Feel free to close this bug since there isn't anything Skopeo can do about this. Thanks.

**Comment by mtrmac** [comment]
> > I have heard of someone building such invalid archives, but that‘s a hack that can break at any time if the
> > docker load implementation ever changes.
> 
> Interesting. I was vaguely thinking of trying that before finding Skopeo... I don't suppose this was in a published script/tool anywhere?

I vaguely remember a GitHub Issue discussing that somewhere in the c/image or Skopeo repo, or possibly elsewhere in GitHub.com/containers, but I’m afraid I can’t find this now.

> I don't suppose there are any Docker implementations (or container systems in general) that use some custom daemon that shares storage between a Docker daemon and Docker register implementation

That’s just not possible; the daemon must contain uncompressed filesystems that can be executed against, while the registry contains a linear tarball, and preferably a compressed one.

**Comment by swarren** [comment]
FWIW, the "invalid archive" approach seems to work for now...

https://github.com/swarren/misc-public-scripts/blob/main/docker-push-to-remote-daemon.sh

> That’s just not possible

I'm not entirely sure yet:-) Not that it really matters; this is just some idle thoughts:-)

> the daemon must contain uncompressed filesystems that can be executed against,

Certainly.

> while the registry contains a linear tarball, and preferably a compressed one.

Is the registry protocol defined so that that the registry server _must_ store linear/compressed tarballs, or only that it is able to send/receive these over the network? I.e. could the registry server untar on RX and tar on TX? While this would be inefficient for a regular registry server, if this was a special registry server with the sole use-case of interfacing with the pool of images used by the docker daemon for local development, that would probably be OK, since the registry protocol wouldn't be the primary access mechanism.

**Comment by rhatdan** [comment]
Rootful podman might be able to work with such a registry  via a network file system protocol like NFS without needing to pull the images using Additional Image Stores.

**Comment by mtrmac** [comment]
What @rhatdan says — I think the design would benefit from being discussed at a higher level of abstraction than “we know we are going to use Docker, and we know we are going to use the unpackaged data underlying the graph driver as the primary storage”. Either using a registry, like most other users, or using a network filesystem to share the unpackaged images, could be on the table.

---

(It doesn’t necessarily have to _store_ tarballs but it must know and compute SHA256 digests of those tarballs, i.e. they must be byte-for-byte exactly reproducible. The storage underlying Docker and/or Podman can do that _for uncompressed tarballs_; compressed tarballs can only be reproduced by storing them, never by reproducing them.)
