### ISSUE TITLE
Skipping present tags for faster sync

### ISSUE THREAD

**Issue by zlobober** [containers/skopeo#2111]
Hi,

We are thinking about using skopeo for syncing quite large repositories containing lots of images (more precisely, tens of images with hundreds of tags, a couple of thousands of images-tag pairs in total). This case is close to maintaining what is mentioned as "air-gapped environments" in skopeo sync documentation. 

Ideally, I would like to set up a periodic `skopeo sync` run and specify a number of desired images in yaml (like `images: <imageName>: []`, or using images-by-tag-regex with quite broad regexps). Most often, this run should not push any new images to the destination registry, as source and target repositories are in sync and contain same images.

It turns out that skopeo iterates over all admitted images and performs some sort of signature or mainfest check, comparing original and target images even if the image with the same name and tag is present in the destination repository.

```
time="2023-09-13T20:25:04Z" level=info msg="Copying image ref 1/9" from="docker://registry.hub.docker.com/...:1.16.0" to="docker://myrepo/...:1.16.0"
Getting image source signatures
Skipping: image already present at destination
time="2023-09-13T20:25:05Z" level=info msg="Copying image ref 2/9" from="docker://registry.hub.docker.com/...:1.16.1" to="docker://myrepo/...:1.16.1"
Getting image source signatures
Skipping: image already present at destination
time="2023-09-13T20:25:07Z" level=info msg="Copying image ref 3/9" from="docker://registry.hub.docker.com/...:1.16.2" to="docker://myrepo/...:1.16.2"
Getting image source signatures
Skipping: image already present at destination
time="2023-09-13T20:25:08Z" level=info msg="Copying image ref 4/9" from="docker://registry.hub.docker.com/...:1.16.3" to="docker://myrepo/...:1.69.0"
Getting image source signatures
Skipping: image already present at destination
```

In my case this check takes around 1 second per image, so even a no-op run of skopeo would take hours to complete. At the same time, --dry-run runs quite fast, as it is enough to just query the set of available tags for each original image.

By design of this synchronization, I can be sure that images with coinciding names and tags in source and target repositories are actually the same, because there are no other processes populating the destination repository. This leads to an idea of an option for skipping image signature comparison in order to not spend any time on already present images. What do you think about that?

**Comment by mtrmac** [comment]
Thanks for reaching out. This is already tracked in #1498 .

> By design of this synchronization, I can be sure that images with coinciding names and tags in source and target repositories are actually the same, because there are no other processes populating the destination repository. 

Some tags can change on the source; `:latest` is the typical example, and _very_ common. So the feature would need to let the user configure which tags are / are not immutable, and I’m afraid right now the `yaml` configuration format used by `skopeo sync` does not reasonably allow adding that option. So a new config format will need to be implemented first, in order to get this fairly small feature.
