### ISSUE TITLE
release: publish binaries

### ISSUE THREAD

**Issue by katexochen** [containers/skopeo#2121]
Would be cool if there were binaries for common architectures attached to the release for easier consumption in places without package manger.

**Comment by hurzelpurzel** [comment]
Totally agree. I think this can be done via GitHub Action.  Their is a Implementation availaible for windows @ https://github.com/passcod/winskopeo/tree/main if we use that as a template, I think this would be easy to extend it.

**Comment by hurzelpurzel** [comment]
Did the work. should be availaible as soon as PR 
Update install documentation & add Build pipeline #2124  has been merged

**Comment by katexochen** [comment]
Thanks @hurzelpurzel !

**Comment by mtrmac** [comment]
Thanks for reaching out. Linux distributions are not compatible enough to be able to provide a single full-featured binary, see e.g. #1545  and past reports.
