### ISSUE TITLE
Official skopeo docker image and official Dockerfile

### ISSUE THREAD

**Issue by gabrimonfa** [containers/skopeo#2126]
Hi, is quay.io docker image the official skopeo image?
Reading some issues it seems so, but I don't see a clear statement in project Readme.

Moreover I can't find an official Dockerfile, is it on purpose? 
It would be useful to have reproducible builds with respect of quay.io ones.
Thank you.

**Comment by mtrmac** [comment]
Thanks for reaching out.

The images in https://github.com/containers/skopeo/blob/main/install.md#container-images are as official as it gets, for a no-commercial-support-promises made project freely available on GitHub; they are built and maintained by the same team. That links to https://github.com/containers/skopeo/blob/main/contrib/skopeoimage/README.md , and the build sources are nearby.

Reproducible builds would, indeed, be great, but it’s not something Fedora can currently do, AFAIK.

**Comment by gabrimonfa** [comment]
ok, thank you for your answer
