### ISSUE TITLE
Bandwidth limit option on copy

### ISSUE THREAD

**Issue by OlafvdSpek** [containers/skopeo#2127]
Could a bandwidth limit option be added to the copy command for cases where one doesn't want to interfere with other traffic is upload bandwidth is limited.

**Comment by mtrmac** [comment]
Thanks for reaching out.

I agree that limiting bandwidth is useful in many situations; but I don’t think it’s all that user-friendly or productive for every single binary that could ever reach the internet to grow its own (necessarily tool-specific) bandwidth limiting option; and I’m not very convinced that even doing that for the major users, like `skopeo sync` might well be, is the best approach.

Enforcing some kind of more global limit, based on a route or possibly on a cgroup (maybe at the container boundary, like https://github.com/containers/podman/issues/17414 ), seems to me to be a far more general and safe approach.
