### ISSUE TITLE
misleading ENTRYPOINT info in README

### ISSUE THREAD

**Issue by schewara** [containers/skopeo#2134]
I just stumbled on the [README](https://github.com/containers/skopeo/blob/main/contrib/skopeoimage/README.md), where it states:

> Also, the ENTRYPOINT and the WORKDIR variables are not set within these container images, as such they default to /.

While https://github.com/containers/skopeo/blob/ca00d96b6bae830b9b19b222597871ae1727dbe8/contrib/skopeoimage/stable/Containerfile#L47

explicitly defines one, which is very confusing when someone tries to pull the container image and want's to test it out.

Therefore either the README or the Containerfile should be updated that the information is correct again.

**Comment by mtrmac** [comment]
Thanks for your report, #2138 should help.
