### ISSUE TITLE
Is there a command for docker content trust

### ISSUE THREAD

**Issue by meghnasiingh** [containers/skopeo#2135]
This issue is regarding missing api for docker trust inspect. I was trying to find a commad alternative to `docker trust inspect` like skopeo trust inspect which can give me image signer information, I see it is not there. I need to get the signed Tags of an image to know who signed the image. If its there can someone point me out and if not what is the alternative?
I can also see that while copying an image with `RemoveSignatures` as false copy options, the signatures not getting stored in destination directory.
I don't want the signatures or verification of signatures. I just meed signedTags for who signed this image like
```
Linux:~/gows/src/github.com/meghna/images$ docker trust inspect alpine:latest
[
    {
        "Name": "alpine:latest",
        "SignedTags": [
            {
                "SignedTag": "latest",
                "Digest": "eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978",
                "Signers": [
                    "Repo Admin"
                ]
            }
        ],
        "Signers": [],
        "AdministrativeKeys": [
            {
                "Name": "Root",
                "Keys": [
                    {
                        "ID": "a2489bcac7a79aa67b19b96c4a3bf0c675ffdf00c6d2fabe1a5df1115e80adce"
                    }
                ]
            },
            {
                "Name": "Repository",
                "Keys": [
                    {
                        "ID": "5a46c9aaa82ff150bb7305a2d17d0c521c2d784246807b2dc611f436a69041fd"
                    }
                ]
            }
        ]
    }
]
```
How can I get this from skopeo?

**Comment by mtrmac** [comment]
Thanks for reaching out.

Skopeo has no integration with `docker trust` (Notary v1) at all, and given the existence of Sigstore (and even Notary v2), it’s very unlikely it would ever be added.
