### ISSUE TITLE
Allow copying without pulling images before when image exists on destination registry

### ISSUE THREAD

**Issue by ibotty** [containers/skopeo#2154]
I'd like to tag an image already on a remote registry to a new name, i.e.

```
skopeo copy docker://my-registry/my-image:tag docker://my-registry/other-image:tag
```

ATM this pulls the image and then decides (correctly) that it does not have to push blobs but only `write manifest to image destination`.

It would be great to allow not pulling the image first.

**Comment by mtrmac** [comment]
Thanks for your report.

This sounds like be https://github.com/containers/image/issues/312 , except for this part:
> and then decides (correctly) that it does not have to push blobs 

Please collect the logs from `skopeo copy --log-level=debug`.

**Comment by ibotty** [comment]
Yes, that looks like it!  I can collect logs, but I doubt they tell more of a story.  Should I really collect logs?

**Comment by mtrmac** [comment]
Up to you.

AFAICT it should not happen that the code _initiates_ a download (there is actually a `GET` happening) and then decides not to use the data, so I am a bit curious, but if you think the linked issue actually describes the situation accurately, that’s good enough for me.
