### ISSUE TITLE
Unable to pull large layer

### ISSUE THREAD

**Issue by samdish7** [containers/skopeo#2164]
Take a look at [this image](https://hub.docker.com/r/cykgaudi/norm-triton/tags). The image in question is under the tag 0.0.0. I want to stress that I did not create the image, I only wanted to pull it via skopeo copy. However, there is a layer within this image that is 34 GB. When attempting to pull the layer, skopeo spins for a while, then appears to skip it, then pull the next layer, which results in a failure to create the tarball. Docker pulling this image works, but skopeo does not like it. Unsure if it is a bug or this is by design. Upon removal of the layer (tag 0.0.1), skopeo takes some time but is able to pull the 15 GB sized artifact.

**Comment by mtrmac** [comment]
Thanks for reaching out.

Reading that image seems to work for me.

Please provide an _exact_ reproducing command, and collect the logs of `skopeo --debug …` (possibly through `|& cat` or something similar to make sure to capture everything, without the progress bars interfering) when running that command.

**Comment by samdish7** [comment]
`skopeo copy --preserve-digests docker://cykgaudi/norm-triton:0.0.0 oci-archive:large.tar`

This seems to work on my mac as I was able to test it there, but here are the logs that I got regarding the output. I'm confused as to why this happens because docker pull works fine. Note, this is on an Amazon Linux EC2 instance using skopeo 1.13.3

`DEBU[0401] Error deleting temporary directory: <nil>`
`FATA[0401] reading blob sha256:91ac28f153b3810fe144fb1e881e6883461f5ea972737a5259768214df9abe30: fetching blob: name invalid: The requested artifact is larger than our max limit of 9.9 GiB `
