### ISSUE TITLE
Add support for getting digest for image indexes / lists

### ISSUE THREAD

**Issue by tnozicka** [containers/skopeo#2180]
I'd like to resolve the sha of an image index (multi-arch) using skopeo.

For single architecture I was using `skopeo inspect --format "{{.Name}}@{{.Digest}}" docker://quay.io/<org>/<repo>` but that doesn't work with image indexes containing multiple architectures.

Here is an example of the sha on quay.io:
![quay_image_index_sha](https://github.com/containers/skopeo/assets/11869554/ab23b8b5-ed10-4b93-ab63-30f43101e143)

Note that I specifically don't want to resolve the image for any specific platform, because I don't know the platform this will be used on. One of the use cases are third party images that my Kubernetes operator deploys, but I don't know the platform this lands on but I still need to use sha references to be sure it's always the same image it was tested with + security concers.

**Comment by mtrmac** [comment]
Thanks for your report.

This is probably a subset of #1283 .

For now, there are two ways to do this:
- `skopeo inspect --raw docker://… | bin/skopeo manifest-digest /dev/stdin` (on operating systems where `/dev/stdin` exist, alternatively use a temporary file)
- _Guess_ a supported OS/architecture `amd64/linux`) and use the command you quoted, with `--override-os … --override-arch …` . The `.Digest` field in `skopeo inspect` _does_, always, refer to the top-level image index (if it didn’t, that would be a bug); but the way `skopeo inspect` currently mixes top-level and per-arch data, the command might fail if the current runtime platform is not supported by the image.

**Comment by tnozicka** [comment]
thanks @mtrmac 


> Guess a supported OS/architecture amd64/linux) and use the command you quoted

You are correct, the digest is for the manifest list. In the json it is slightly confusing to see these along side (although probably a better choice in the end)
```json
{
    "Name": "quay.io/scylladb/scylla-operator",
    "Digest": "sha256:<multiarch-digest>",
    "Architecture": "amd64",
    "Os": "linux",
}
```

I was using `sha256sum` but the `skopeo manifest-digest` is more handy, so I ended up with this (in case anyone needs it as well for the interim)
```bash
function resolve-image {
(
        set -euEo pipefail
        local digest
        digest=$( skopeo inspect --raw docker://"${1}" | skopeo manifest-digest /dev/stdin )
        echo "${1}@${digest}"
)
}

```

**Comment by mtrmac** [comment]
>  In the json it is slightly confusing 

It is definitely confusing. We ended up in this situation for historical reasons, and it would probably break far too much to change it now.

**Comment by mtrmac** [comment]
The RFE is tracked in #1283 .
