### ISSUE TITLE
Why can't I perform security scanning on the image I copied with skopeo copy cli

### ISSUE THREAD

**Issue by fatzhang** [containers/skopeo#2181]
I used skopeo to copy MySQL images into my private Harbor library, like this：
skopeo copy docker://docker.io/mysql:latest docker://192.168.1.xx/library/mysql:latest --dest-tls-verify=false --src-tls-verify=false

but it prompted that scanning is not possible. 
However, when I used Docker to pull MySQL, modify tags, and then push the images into my private library, like this:
docker pull mysql:latest
docker tag mysql:latest 192.188.1.xx/library/mysql:latest
docker push 192.188.1.xx/library/mysql:latest

the images scanning vulnerabilities is allowed。

**Comment by rhatdan** [comment]
Could it be that nothing has changed so no scan is activated?

**Comment by fatzhang** [comment]
The MySQL images downloaded using the Docker pull/push method have been scanned for 1 serious vulnerability and 1 intermediate vulnerabilities, with the following information:
[ELSA-2022-9564] libgcrypt 1.8.5-7.el8_6
[ELSA-2022-9221]gnutls 3.6.16-7.el8

**Comment by mtrmac** [comment]
> but it prompted that scanning is not possible.

I’m afraid I have no idea what this means; which “it”, with what error, etc.

**Comment by fatzhang** [comment]
sorry，I am a non-native English speaker， it mean the docker images scaner ,like this
the docker images sha256:28a116e31 is use skopeo copy command like this :skopeo copy docker://docker.io/mysql:latest docker://192.168.1.xx/library/mysql:latest --dest-tls-verify=false --src-tls-verify=falsethe docker images sha256:44afff47 is use docker pull and docker push command, this image can be scanned my  private library is Harbor
Best wishes
----- 原始邮件 -----
发件人：Miloslav Trmač ***@***.***>
收件人：containers/skopeo ***@***.***>
抄送人：fatzhang ***@***.***>,  Author ***@***.***>
主题：Re: [containers/skopeo] Why can't I perform security scanning on the image I copied with skopeo copy cli (Issue #2181)
日期：2023年12月20日 21点56分



but it prompted that scanning is not possible.

I’m afraid I have no idea what this means; which “it”, with what error, etc.

**Comment by mtrmac** [comment]
The scanner you use hopefully can report why it can / cannot scan some images.

**Comment by mtrmac** [comment]
Please reopen if more information becomes available.
