### ISSUE TITLE
When multiple skopeo copy commands are executed in parallel, the generated index.json file will lose information.

### ISSUE THREAD

**Issue by Zacama** [containers/skopeo#2184]
Hello

file cmds
```
skopeo copy docker://xxx oci:xxx:xxx
skopeo copy docker://xxx oci:xxx:xxx
skopeo copy docker://xxx oci:xxx:xxx
...
```

[rush](https://github.com/shenwei356/rush) {} -i cmds

the generated index.json file will lose some information of them.

**Comment by mtrmac** [comment]
Thanks for your report. `oci` does not do any locking to make this possible, and doing that (while allowing concurrent deletions, which are nowadays implemented) without making it as slow as completely serial execution would not be quite trivial.

This is tracked in https://github.com/containers/image/issues/1028 , and if it were implemented in c/image, that would be directly inherited by Skopeo.

I’m afraid it’s not something we are likely to work on short-term; so I’d recommend just not running these copies in parallel, or perhaps using a temporary registry as a destination instead, as also detailed in https://github.com/containers/image/issues/1028 .
