### ISSUE TITLE
Local disk usage spikes when using skopeo copy to transfer a large image tarball to a remote registry

### ISSUE THREAD

**Issue by spoonysnail** [containers/skopeo#2185]
I've encountered an issue where my local disk usage increases dramatically when I use skopeo copy to transfer a large image tarball, around 50GB in size, to a remote registry. The local disk usage goes up by approximately 50GB during the process. Could you provide insight into why this happens and if there's a way to mitigate such a large increase in disk usage?

**Comment by mtrmac** [comment]
Please reopen if there is anything unexpected happening.
