### ISSUE TITLE
Error parsing manifest for image

### ISSUE THREAD

**Issue by CeerDecy** [containers/skopeo#2203]
I tried to run the example from the documentation, unable to get data
![image](https://github.com/containers/skopeo/assets/79098669/d3e3345a-5253-416e-8b88-ec1a069892ff)

<img width="1208" alt="image" src="https://github.com/containers/skopeo/assets/79098669/0d90cd9f-2230-4515-889a-56c97c30eb3e">

Then I guessed it might be the architecture, but it still doesn't work

<img width="1216" alt="image" src="https://github.com/containers/skopeo/assets/79098669/c436dd71-1f94-4c04-8830-8b830cd9a9b7">

When I specify the tag of the mirror, it may be fine, but some tags still can't get the data
<img width="428" alt="image" src="https://github.com/containers/skopeo/assets/79098669/512e6ac8-ead5-4e49-bc2e-7b68d3cae962">
<img width="1203" alt="image" src="https://github.com/containers/skopeo/assets/79098669/187e1685-4a1b-4a7c-b2fb-ac87f7e12383">

I tried to use https://github.com/containers/image in golang and it still doesn't solve my problem, why is that?

**Comment by mtrmac** [comment]
> I tried to use https://github.com/containers/image in golang and it still doesn't solve my problem, why is that?

Without specifics it’s impossible to say

---

With the `skopeo inspect` commands, on Mac you probably need `--override-os linux`, in addition to _possibly_ `--override-arch`, depending on your use case. Fedora doesn’t exist as macOS-native containers.

**Comment by CeerDecy** [comment]
> With the `skopeo inspect` commands, on Mac you probably need `--override-os linux`, in addition to _possibly_ `--override-arch`, depending on your use case. Fedora doesn’t exist as macOS-native containers.

oh, my bad. It's working now. tks
