### ISSUE TITLE
Skopeo Copy notation specific signatures

### ISSUE THREAD

**Issue by omkhard** [containers/skopeo#2215]
Hi ,
We are doing container image signing/verifying , we needed to do it using X509 certificates so notation was best suited for it, If i am trying to detach signature using 'skopeo'.

It gives an error , I don't know if skopeo is not compliant or notation's signature type is different.

`root@okhardubuntu:/home/ubuntu# skopeo inspect docker://<ARTIFACT_REPO_URL>debian15@sha256:c12a3cced3b1812feb9f1675a6087ed238e4a0a1ef79c24fe64a4cc3794b3471 FATA[0000] unsupported image-specific operation on artifact with type "application/vnd.cncf.notary.signature"`

**Comment by mtrmac** [comment]
Thanks for reaching out.

Yes, `inspect` only works on images, and a signature is not an image. `skopeo inspect --raw` will probably show something.
