### ISSUE TITLE
Regarding skopeo libraries to be used in golang

### ISSUE THREAD

**Issue by surendrababuravella** [containers/skopeo#2219]
Hi Team,

We would like to write golang code to copy images from registry to local. For this purpose, are there any skopeo libraries available? are these libraries gets updated time to time with identified vulnarabilities? are there any examples how to use that library if exists?

Thanks,
Surendra

**Comment by mtrmac** [comment]
Thanks for reaching out.

Skopeo is not maintained as a library, but it is (apart from `sync`) a very thin wrapper over https://github.com/containers/image/ . That is a library, with a stable API. Skopeo itself is an example of how to use it :)

**Comment by surendrababuravella** [comment]
Thank you @mtrmac for your quick help.. It looks like podman also uses same library internally. So this image library will be always up-to-date.

Thank you..
