### ISSUE TITLE
inspect: Go template not working well on some images

### ISSUE THREAD

**Issue by knacky34** [containers/skopeo#2220]
I'm trying to extract version from images of various services I use on my server. So that I can be notified whether there is an update available.
The way I'm doing it, is by inspecting images on both local and remote, and then comparing the versions.

But I encounter an issue with Go template formatting.
I ran the following commands without trouble (RepoTags and Layers have been truncated to be more legible):

`skopeo inspect docker://library/nextcloud:production-fpm-alpine`
``` json
{
    "Name": "docker.io/library/nextcloud",
    "Digest": "sha256:581dc648fbd39fd5752c683d8598567e476a72a1cd97a2d1b725d87e949846c6",
    "RepoTags": [
        "10",
        "10-apache",
        "10-fpm",
        [...]
        "stable-apache",
        "stable-fpm",
        "stable-fpm-alpine"

		],
    "Created": "2024-02-02T08:18:36.524351129Z",
    "DockerVersion": "20.10.23",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:4abcf20661432fb2d719aaf90656f55c287f8ca915dc1c92ec14ff61e67fbaf8",
        "sha256:9b9ef19a461f9d419fc91c59399a9daa1f3302d30f099065a185a8bfeea3c9a8",
        [...]
        "sha256:5da1bfd5da692910995451de2a6344ed8b1ea8ce739d5ba9c7e17bc06b216df2",
        "sha256:a59aaa13e26ad69af8a52b6b1cd95756dfcbf79d965483e778b8b68370153665"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "PHPIZE_DEPS=autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
        "PHP_INI_DIR=/usr/local/etc/php",
        "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
        "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
        "PHP_LDFLAGS=-Wl,-O1 -pie",
        "GPG_KEYS=39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC",
        "PHP_VERSION=8.2.15",
        "PHP_URL=https://www.php.net/distributions/php-8.2.15.tar.xz",
        "PHP_ASC_URL=https://www.php.net/distributions/php-8.2.15.tar.xz.asc",
        "PHP_SHA256=eca5deac02d77d806838275f8a3024b38b35ac0a5d9853dcc71c6cbe3f1f8765",
        "PHP_MEMORY_LIMIT=512M",
        "PHP_UPLOAD_LIMIT=512M",
        "NEXTCLOUD_VERSION=27.1.6"
    ]
}
```

`skopeo inspect docker://library/mongo:latest --format "{{ .Env }}"`
```
[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin GOSU_VERSION=1.17 JSYAML_VERSION=3.13.1 MONGO_PACKAGE=mongodb-org MONGO_REPO=repo.mongodb.org MONGO_MAJOR=7.0 MONGO_VERSION=7.0.5 HOME=/data/db]
```

But, the problem happens when I run this command:
`skopeo inspect docker://library/nextcloud:production-fpm-alpine --format "{{ .Env }}"`

I shoud except this:
```
[ "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "PHPIZE_DEPS=autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
        "PHP_INI_DIR=/usr/local/etc/php",
        "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
        "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
        "PHP_LDFLAGS=-Wl,-O1 -pie",
        "GPG_KEYS=39B641343D8C104B2B146DC3F9C39DC0B9698544 E60913E4DF209907D8E30D96659A97C9CF2A795A 1198C0117593497A5EC5C199286AF1F9897469DC",
        "PHP_VERSION=8.2.15",
        "PHP_URL=https://www.php.net/distributions/php-8.2.15.tar.xz",
        "PHP_ASC_URL=https://www.php.net/distributions/php-8.2.15.tar.xz.asc",
        "PHP_SHA256=eca5deac02d77d806838275f8a3024b38b35ac0a5d9853dcc71c6cbe3f1f8765",
        "PHP_MEMORY_LIMIT=512M",
        "PHP_UPLOAD_LIMIT=512M",
        "NEXTCLOUD_VERSION=27.1.6" ]
```
but instead nothing returns...
It's also affecting docker://library/php:<tag> with any tag as well

I tested the previous command with about ten services and I could have got `Env` array every time.

Finally, I tried to extract another variable like `Os` and the array `Layers` on nextcloud image. it worked.
I'm runnig Skopeo version `1.9.3` on Debian Bookworm.

By the way, is this method the best for checking image for update ? I seen `containrrr/watchtower` but I'm using podman and I don't want to update automatically (only notify).

**Comment by mtrmac** [comment]
Thanks for your report.

That command (or rather `skopeo --override-os linux inspect -n docker://library/nextcloud:production-fpm-alpine --format "{{ .Env }}"` works fine for me, and returns seemingly reasonable data. I don’t know how that fails, unless maybe your caller is completely ignoring, and throwing away, error messages (maybe exactly because it needs to query the Linux version from a non-Linux host).

---

> By the way, is this method the best for checking image for update ?

That‘s … mostly an invitation to a pedantic debate about what you mean by “update”. If you want to make some kind of a decision based on version numbers, well, container images don’t _inherently_ contain a version number in any specific format, so you are left with repository-specific rules (like parsing the tag value, or maybe a label, or maybe something in `Env`, although I find the latter one rather unexpected).

In other situations, the desired policy may be “I always run the `latest` image”, and in that case version numbers don’t matter (to the point of downgrading if `latest` is moved to a smaller version). In such situations, just checking whether `Digest` has changed would probably be the way to decide whether to pull again.

**Comment by knacky34** [comment]
thank you,
I will check using the `override-os` option even if I don't really understand why it is not behaving the same as with other images.

Okay, then I will consider checking the digest as I want to always run the last image (or at least know that a newer image exists).
Thank you for your answer :)

**Comment by mtrmac** [comment]
@knacky34 please reopen if there are any underlying issues.
