### ISSUE TITLE
Skopeo's ability to retain SHA value when copied from one registry to other

### ISSUE THREAD

**Issue by dnt238** [containers/skopeo#2225]
If I do docker pull/docker tag/dokcer push from one reg to other many times I see SHA changing but I don't see that with skopeo, How is skopeo able to retain SHA values and docker can't?

**Comment by mtrmac** [comment]
`docker push` compresses the underlying data again. There is no guarantee that that recreates the original compressed version bit by bit.

(You might also want to use the `--preserve-digests` option to `skopeo copy`.)

**Comment by dnt238** [comment]
Thanks 
So skopeo using oci format is not the (only) reason, right?

So even if I use oci format of docker, over there, there is no gurantee it will preserve SHA value of image, right?

**Comment by mtrmac** [comment]
Consider that some images are not in OCI format originally; so converting them to OCI would _certainly_ change the digest.

What I said about “no guarantee” about re-compression recreating data is precisely that. Using a push _might work_ for a time, until something somewhere in the implementation changes. Uses who relied on that behavior did get broken in the past.

**Comment by dnt238** [comment]
ok so reason skopeo is able to retain SHA *is not because it uses oci format* but because it does not do compression and copies the data including metadata -- is that correct?

**Comment by mtrmac** [comment]
Close enough.
