### ISSUE TITLE
Please release #2189

### ISSUE THREAD

**Issue by donnyv12** [containers/skopeo#2233]
Hi Folks, 

I have a feeling this is user error, but I'm not able to figure out what I'm doing wrong. 
```sh
skopeo --version
skopeo version 1.14.2
``` 
Given the below yaml file: 
```sh
bitnami:
  images:
    sealed-secrets-controller:
      - "v0.17.1"
    redis-cluster:
      - "7.0.8-debian-11-r0"
    redis-exporter:
      - "1.45.0-debian-11-r26"
  images-by-semver:
    kubectl:
      - ">= 1.26.4"
``` 
I run a dry-run sync and see the first three images would be copied but nothing for the `kubectl` image. I've double checked my syntax against the example but it seems like the `images-by-semver` is just being ignored. Any idea what I'm doing wrong?

**Comment by donnyv12** [comment]
I could be way off here, but I am starting to suspect that #2189 has not been released yet (it may have just missed the cutoff for v1.14.2). I am going to try a nightly build and see if that confirms my hypothesis

**Comment by donnyv12** [comment]
Using `quay.io/skopeo/upstream:latest@sha256:25705ae5c0276fa6dc252356f9c34efeb73a18ef0f9bd4682850acf3a59cd6ca` I've confirmed the functionality does work! It just hasn't been released. Sorry for wasting some time. Would love to know when the next release is.

**Comment by zhangguanzhang** [comment]
https://github.com/containers/skopeo/releases/tag/v1.15.0
/close
