### ISSUE TITLE
How to use skopeo container with credential helpers?

### ISSUE THREAD

**Issue by hellt** [containers/skopeo#2235]
Hi all,
I wanted to use skopeo container with Google Cloud Artifact registry.

Artifact registry's default authentication method is leveraging `gcloud` cli tool that acts as a docker credential helper.
Since `gcloud` is not a single binary it seems not quite possible to bind mount it to the skopeo container.

So I wonder how people use skopeo in a container packaging with registries that make use of credential helpers?

**Comment by mtrmac** [comment]
Thanks for reaching out.

I don’t know that there is a good answer. When the Skopeo binary needs to interact that tightly with the surrounding environment, my first choice would be to use a distribution package, not a container.

**Comment by hellt** [comment]
I think I am fine with closing this issue.
The way I used skopeo container with gcp involved the following:

```
alias skopeo='sudo docker run --rm \
-v ~/.config/gcloud:/root/.config/gcloud:ro \
-v ~/.docker/config.json:/tmp/auth.json:ro \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /usr/bin/docker-credential-gcr:/usr/bin/docker-credential-gcr \
-v $(pwd):/workdir \
-w /workdir \
quay.io/skopeo/stable:v1.14'
```

Basically I had to use the standalone credential helper for the gcp, instead of a proposed monstrous credential helper
