### ISSUE TITLE
Have issue with upgrading skopeo version to 1.8.1 in ubuntu 22.04

### ISSUE THREAD

**Issue by prashant9394** [containers/skopeo#2245]
I have come across issue: sudo OCICRYPT_KEYPROVIDER_CONFIG=$(pwd)/attestation-agent/sample_keyprovider/src/enc_mods/offline_fs_kbs/ocicrypt.conf skopeo copy docker://docker.io/library/alpine:latest oci:alpine-encrypt1 --encryption-key provider:attestation-agent:$(pwd)/keys.json:key_id1

**FATA[0000] Invalid encryption keys: Provided protocol not recognized**

And not able to encrypt using coco attestation service using skopeo

**Comment by mtrmac** [comment]
I’m afraid I don’t know how I could possibly help.
- There is no Skopeo version 1.8.1.
- That form of `provider:…` syntax is parsed correctly for me. My best guess is that `$(pwd)` contains some punctuation that changes the semantics.

**Comment by jojimt** [comment]
I ran into the same issue:
```
OCICRYPT_KEYPROVIDER_CONFIG=./ocicrypt.conf skopeo copy --insecure-policy --encryption-key provider:attestation-agent oci:alpine oci:alpine:encrypted
FATA[0000] Invalid encryption keys: Provided protocol not recognized
``` 
skopeo --version
skopeo version 1.4.1

This is the version that gets installed by apt on ubuntu 22.04. If I build from source, I don't see this issue. HTH.

**Comment by mtrmac** [comment]
Thanks, that is suggestive. I didn’t check the _actual_ Ubuntu build process, but https://packages.ubuntu.com/jammy/golang-github-containers-ocicrypt-dev suggests that the Ubuntu version is built with ocicrypt 1.0.3, while Skopeo 1.4.1 otherwise includes ocicrypt 1.1.2 — and ocicrypt 1.0.3 does not support the `provider` protocol.

**Comment by rhatdan** [comment]
Since this is not something the upstream can fix and is fixed in the upstream closing this issue.  Conversation can continue.
