### ISSUE TITLE
Does skopeo supports loading local docker tar.gz file into remote registry?

### ISSUE THREAD

**Issue by mehulgogri** [containers/skopeo#2247]
Does Skopeo supports loading local docker tar.gz file into remote registry?

We have a bunch of docker images stored locally in the tarfile. Does skopeo supports uploading this local docker images file into remote docker registry?

**Comment by mehulgogri** [comment]
I tried this and it worked
`skopeo copy tarball:images/busybox_1.28.tar docker://remote-registry/test/busybox:1.28`

This works for a single image. I believe we cannot copy multiple images or all the images in a directory via a single command. I'll have to loop through the images in the directory to do that. 

Please suggest if there is any better way to do this.

**Comment by mtrmac** [comment]
Are you _sure_ `tarball:` is producing an image with the right contents? How was that tar file created?

I suspect what you are looking for might be `docker-archive:`. In that case, also, `skopeo copy` only copies one image at a time. If the archive is uncompressed, that’s not significantly more expensive than it could possibly be all in one command.

**Comment by mehulgogri** [comment]
the tar file is created using skopeo 
`skopeo copy docker://{} docker-archive:/{}.tar:{}`

I already have the docker tar files created using above skopeo command. I am trying to upload this local docker images into remote registry. With docker we will have to run docker load, docker tag, and docker push. I am looking for doing this with skopeo.

**Comment by mtrmac** [comment]
Yes. `tarball:` does not _correctly_ consume the output of `docker-archive`.

---

As a general matter, if the ultimate goal is to do a registry-to-registry transfer, `docker-archive` is not a good format; e.g. it can’t represent multi-architecture images at all. I generally recommend
- on the source, run a temporary registry (maybe in a container)
- do a registry-to-registry copy to that temporary registry
- stop the temporary registry, transfer the backing storage of that registry to the destination
- on the destination, run a temporary registry again, with the transferred backing storage
- do a registry-to-registry copy to the ultimate destination

This can do bit-by-bit exact copies, copy shared layers only once, does not need to spend CPU time compressing data, never needs disk space to store uncompressed variants.

**Comment by mehulgogri** [comment]
understood. thanks for the suggestion.

**Comment by hellt** [comment]
I was a little bit buffled by the performance of `docker-archive` transport option.

Given that I already have a `tar.xz` file that was produced by a `docker save | xz` I needed to copy that image to a a remote docker image.

I did

```
skopeo copy docker-archive:image.tar.xz docker://some.registry/image:latest
```

surprisingly, this took the whole 12 minutes (xz fsize is 700MB), which is 2-3 times slower than doing the `docker load -i file.xz & docker tag && docker push`.

I wonder why is that?

**Comment by mtrmac** [comment]
Franky I’m not going to dig into the details of that difference. `docker-archive:` is a compatibility/transition mecahnism and users who care about performance (or features like image preservation and multi-arch-images) will end up not using `docker-archive:`, even if we improved it by some constant factor.

It’s possible there are performance improvements possible (especially with Docker 25 where the archive actually contains another set of metadata), and if someone cares to diagnose that difference, I’d be interested to read it — but using a `docker-archive` is _never_ going to be as efficient as not transferring duplicate layers at all, so I am not going to invest a day into it.
