### ISSUE TITLE
Build upstream man pages from containers/image/docs directory

### ISSUE THREAD

**Issue by aweiteka** [containers/skopeo#225]
Per discussion https://github.com/projectatomic/atomic/issues/616, we want to include the man pages from https://github.com/containers/image and deliver them with skopeo.

@mtrmac I was unable to get this working in the Makefile.

**Comment by rhatdan** [comment]
We deliver man pages now.

**Comment by mtrmac** [comment]
`MANPAGES` in `Makefile` only includes `docs/*.md`; the man pages in `vendor/github.com/containers/image/docs` are included by `make vendor` but not installed.

**Comment by mtrmac** [comment]
Per the conversation around https://github.com/containers/skopeo/pull/645#issuecomment-489127187 , this seems unnecessary for RPM packaging, in the Fedora ecosystem at least.

It would _still_ be useful, for users building Skopeo from source — but that should be a comparatively rare case (contributors to Skopeo or testers of a recent version) and such users presumably know enough about the implementation to read the right version of c/image documentation on-line.
