### ISSUE TITLE
Why does updating skopeo to the latest version remove docker packages?

### ISSUE THREAD

**Issue by mypleasuer** [containers/skopeo#2251]
I'm working on the use of encrypted image.
Reference  #https://confidentialcontainers.org/docs/use-cases/encrypted-images/

Mentioned in the Instructions,
"Please ensure you have a recent version of [Skopeo](https://github.com/containers/skopeo/releases) (v1.14.2+) installed locally".

So I upgraded skopeo by using the command  `sudo yum -y install skopeo`

```
[root@coco ~]# skopeo -v
skopeo version 1.14.3-dev
```

and then,I get an error when I execute this command,

```
[root@coco ~]# docker build -t unencrypted - <<EOF
> FROM nginx:stable
> RUN echo "something confidential" > /secret
> EOF
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

ok,fine~let's check docker

```
[root@coco ~]# docker -v
Docker version 25.0.3, build 4debf41

[root@coco ~]# systemctl start docker
Failed to start docker.service: Unit docker.service not found.
```

The docker package was removed when skopeo was updated to the latest version.
Which is weird, because I can't even take the first step.

**Comment by vrothberg** [comment]
Thanks for reaching out! Which OS/distribution are you running on?
Cc: @lsm5

**Comment by mypleasuer** [comment]
Thanks for your reply! 
I'm running on Centos 8.

Because I just started to study CoCo by the following reference,
#https://www.redhat.com/en/blog/how-use-confidential-containers-without-confidential-hardware

@vrothberg

**Comment by vrothberg** [comment]
Did you use the skopeo shipped with CentOS 8 or from somewhere else?

**Comment by mypleasuer** [comment]
I install skopeo through yum or dnf , by the following command ,
`dnf -y install skopeo` or `yum -y install skopeo`

I guess it's shipped with Centos 8.

**Comment by mtrmac** [comment]
(I didn’t check CentOS.) RHEL 8 does not include `docker`, that must be a third-party package. It does include `podman`, and some helpers to ease migration; and the two probably rely on different versions of similar underlying tools. It’s possible those parts conflict, or maybe require careful coordination; I would expect `yum` to be quite explicit about such constraints.

Doing `yum -y`… will succeed _somehow_.

**Comment by lsm5** [comment]
@mypleasuer could you please run this command: `rpm -q skopeo docker container-tools` and reply with the output ?

**Comment by mypleasuer** [comment]
Thank you for your analysis. I also assume that there are conflicts in some parts of the underlying tools.
@mtrmac

**Comment by mypleasuer** [comment]
I didn't install container-tools, but I'll still show you.
And thanks for your reply!
@lsm5 

```
[root@coco ~]# rpm -q skopeo docker-ce
skopeo-1.4.0-6.module_el8.5.0+890+6b136101.x86_64
docker-ce-24.0.7-1.el8.x86_64
```

**Comment by lsm5** [comment]
> I didn't install container-tools, but I'll still show you. And thanks for your reply! @lsm5
> 
> ```
> [root@coco ~]# rpm -q skopeo docker-ce
> skopeo-1.4.0-6.module_el8.5.0+890+6b136101.x86_64
> docker-ce-24.0.7-1.el8.x86_64
> ```

Thanks @mypleasuer , not sure what's causing the upgrade to remove docker. So, I'm hoping you can give me some more info. With these packages currently installed, would you mind running `dnf update skopeo` (do not actually go through with the upgrade) and paste the entire output you get. The output should show you what packages will be updated and what will be removed (if any).

**Comment by mypleasuer** [comment]
![skopeo和docker不和](https://github.com/containers/skopeo/assets/144890450/cf2a54b8-0ff9-49a8-bfef-13fd02739acb)

It's in Chinese, but you can see which packages have been updated and which have been removed in different colors.
@lsm5

**Comment by mypleasuer** [comment]
> In addition, when I was executing this command, `skopeo copy docker-daemon:unencrypted:latest dir:./oci/input `
> 
> I encountered the following error, which has been bothering me for two days and has not yet found a solution... `FATA[0000] initializing source docker-daemon:unencrypted:latest: loading image from docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version `

Hey, guys, I found a solution to this error!
When Docker Engine was upgraded to v25, the minimum API version was changed to 1.24
So we just downgrade the docker version , making the minimum api version less required.

I tried to install docker for v24 and re-execute the above command, and no error was reported !
`yum -y install docker-ce-24.0.7`

**Comment by lsm5** [comment]
awesome, good to know you have it sorted @mypleasuer . Let me know if we need to look further on our side, though it can be hard to resolve things with packages not outside of the official repos. Closing...
