### ISSUE TITLE
Skopeo copy job creates .kube/config directory structure failing Azure AKS  kubelogin convert-kubeconfig command

### ISSUE THREAD

**Issue by Sarang-Sangram** [containers/skopeo#2253]
Hello, 

We are trying to run some jobs where the first step is to utilise Skopeo to copy some images from container registry, once completed it tries to login into azure environment and then into the AKS. 

Once the first job is completed i.e. image copy using Skopeo, we found out that it creates a directory structure i.e. .kube/config (2 directories).

Now, when the AKS login is executed, and kubelogin convert-kubeconfig command is triggered to login into the AKS cluster and create a config file under .kube directory, it fails as Skopeo have created a directory called "config" and the config file creation fails with error as:

IsADirectoryError: [Errno 21] Is a directory: '/home/test/.kube/config'

Is there a specific reason for the Skopeo to always create this directory structure ? Can I please have some suggestion and knowledge behind it. 

Thanks

**Comment by mtrmac** [comment]
Thanks for reaching out.

There is exactly one instance of the `.kube` string in the Skopeo codebase, and that is used only with the deprecated `atomic:` transport (you are unlikely to be using, although you didn’t provide any reproducer), and that use is, AFAICT, fully is read-only.

So I think it’s very unlikely that Skopeo itself is doing that. _Maybe_ a configured credential helper could be the culprit.

Perhaps using something like `strace -ff -e trace=%file,%process` can point at the code actually creating the directory.

**Comment by mtrmac** [comment]
@Sarang-Sangram please reopen if there are more specific indications pointing at Skopeo as the origin of the behavior.
