### ISSUE TITLE
Skopeo 1.15.0 is not available in alpinelinux packages 

### ISSUE THREAD

**Issue by husseinferas** [containers/skopeo#2263]
I can't find 1.15.0
https://pkgs.alpinelinux.org/packages?name=skopeo&branch=edge&repo=&arch=&maintainer=

and I'm not able to install it with `apk add skopeo=1.15.0-r0`

**Comment by vrothberg** [comment]
Please reach out to the Alpine maintainers.  There is nothing much we can upstream.  Note that the release if just 4 days old and that there was weekend in between.  Give it some more time, and I am sure the package will be updated soon.
