### ISSUE TITLE
`v1.15.0` Container not available on quay.io

### ISSUE THREAD

**Issue by ericgraf** [containers/skopeo#2264]
`v1.15.0` Container tag is not available in the quay repo. 

https://quay.io/repository/skopeo/stable?tab=tags&tag=latest

**Comment by mtrmac** [comment]
Thanks for reaching out. The stable images are built from stable Fedora updates, and the Fedora update packages are still in the testing phase: https://bodhi.fedoraproject.org/updates/?search=skopeo .

**Comment by MShekow** [comment]
v1.15.0 is now listed.
