### ISSUE TITLE
The checks in hack/ directory hardcode `cc'

### ISSUE THREAD

**Issue by graywolf** [containers/skopeo#2278]
The scripts in the hack/ directory assume that `cc' binary is present in the build environment.  That might not always be the case (the C compiler might be present as `gcc' for example).  Podman project does https://github.com/containers/podman/blob/main/hack/btrfs_tag.sh#L2 , would be nice if skopeo started to do the same.

**Comment by rhatdan** [comment]
Interested in making a PR to add support?
