### ISSUE TITLE
The ubuntu version doesn't support --preserve-digests parameter

### ISSUE THREAD

**Issue by Wyifei** [containers/skopeo#2279]
Install skopeo by apt install in ubuntu 22.04, but it doesn't support --preserve-digests  in copy subcommand

![image](https://github.com/containers/skopeo/assets/65744961/4ad0bcb0-5283-4d09-92ee-eedbdcc60acd)

**Comment by mtrmac** [comment]
Thanks for reaching out. That option was added in Skopeo 1.6.0; which version is packaged, and whether it is updated, in Ubuntu, is up to the Ubuntu distribution/package maintainers.
