### ISSUE TITLE
Error while trying to encrypt container image with skopeo

### ISSUE THREAD

**Issue by elouanjef** [containers/skopeo#2288]
Hi, I am following the quickstart tutorial from CoCo (Confidential Containers) project in order to create an encrypted container image an deploy it as a CoCo workload on CC HW (Intel TDX).
# What I want
The image to be encrypted
# What I got
```
$ OCICRYPT_KEYPROVIDER_CONFIG=ocicrypt.conf skopeo copy --insecure-policy --encryption-key provider:attestation-agent docker://library/busybox oci:busybox:encrypted
FATA[0000] Invalid encryption keys: Provided protocol not recognized 
```
Only having errors, I was wondering if it was the OCICRYPT_KEYPROVIDER_CONFIG variable that was undefined so I tried like this:
```
OCICRYPT_KEYPROVIDER_CONFIG="$(cat ocicrypt.conf)" skopeo copy --insecure-policy --encryption-key provider:attestation-agent docker://library/busybox oci:busybox:encrypted
FATA[0000] Invalid encryption keys: Provided protocol not recognized 
```
# What I did
I followed the tutorial on https://github.com/confidential-containers/confidential-containers/blob/main/quickstart.md, from the beginning to "Encrypting an Image"

coco_keyprovider is running (due to the `docker compose up -d` command mentionned in the tutorial):
```
$ ps aux | grep provider
root      100291  0.0  0.0 621968  2688 ?        Ssl  12:59   0:00 coco_keyprovider --socket 0.0.0.0:50000 --kbs http://kbs:8080 --auth-private-key /etc/private.key
```
PS: I was wondering how was set /etc/private.key because I got nothing here:
```
$ ls /etc/private.key
ls: cannot access '/etc/private.key': No such file or directory
```
My ocicrypt.conf file:
```
{
    "key-providers": {
        "attestation-agent": {
            "grpc": "127.0.0.1:50000"
        }
    }
}
```

# Other
- Is anything else to start/setup ?
- Do I need to run the skopeo command in a specific directory ?
Don't hesitate if you need info! Because I'm possibly missing some important information about my config (sorry about this)
Can anyone help me please ?

**Comment by mtrmac** [comment]
Thanks for reaching out. What version of Skopeo is this?

Compare https://github.com/containers/skopeo/issues/2245#issuecomment-1981621029 .

**Comment by elouanjef** [comment]
Hi ! Thank you for responding, my skopeo version is 1.4.1

**Comment by mtrmac** [comment]
That explains it, then, I think.

**Comment by elouanjef** [comment]
Then what is the solution ? Do I need to tell Ubuntu to use another version of ocicrypt ?

**Comment by mtrmac** [comment]
I’d expect that upgrading the Skopeo package as a whole to a newer released version would be the default approach. Whether that happens by changing what Ubuntu distributes, or by some out-of-distribution changes, is up to you and Ubuntu to decide.

**Comment by elouanjef** [comment]
I just installed from source skopeo version 1.16, it works. Thank you, I'm closing this issue
