### ISSUE TITLE
Can't use skopeo 1.15.0

### ISSUE THREAD

**Issue by husseinferas** [containers/skopeo#2303]
I still can't use the release 1.15.0, it isn't available on alpine or ubuntu
I couldn't find a binary hosted in github
https://github.com/containers/skopeo/releases/tag/v1.15.0
 can you please advise how we can download and use Skopeo?
 I need to install it inside a custom docker image in a Dockerfile 
 I raised this a month ago and it didn't change https://github.com/containers/skopeo/issues/2263
I really need to use semver filter, I'm ok to download the binary inside my docker image, please let me know the proper URL

**Comment by mtrmac** [comment]
I’m afraid the situation won’t change: distribution package need to be updated by distributions. We do provide a set of container images.

Alternatively, https://github.com/containers/skopeo/blob/main/install.md#building-from-source .

**Comment by husseinferas** [comment]
> I’m afraid the situation won’t change: distribution package need to be updated by distributions. We do provide a set of container images.
> 
> Alternatively, https://github.com/containers/skopeo/blob/main/install.md#building-from-source .

Is there a reason why you don't publish the binary on github release page?

**Comment by mtrmac** [comment]
That’s been extensively discussed before, and it’s a responsibility we don’t want to take on.
