### ISSUE TITLE
Feature Request/Verification - list tags matching latest

### ISSUE THREAD

**Issue by adamjk-dev** [containers/skopeo#2311]
Would anyone find it useful to have a flag/command/feature that allows on to find "named" tags that match the ":latest" tag for a given image repo? For some use cases, it makes sense to sync the :latest tag and the matching :version tag (by matching SHAsums).

It would be cool if we could query a repo and say which "named tags/versions" match the current :latest tag.

Unless someone has an easier way to do this outside of doing a skopeo inspect, grabbing the SHA for :latest (assuming the :latest tag exists, which I know all repos don't provide), and then looping through other image versions and finding the one(s) that match the SHA for :latest.

**Comment by mtrmac** [comment]
Thanks for reaching out. The “tag list” API does not provide the digest data, so indeed the only way to actually do that is to list the tags, and then loop through all of them one by one, checking the digests of each.

That can be hundreds/thousands of operations, so I’m rather reluctant to make it an easily-available operation; speaking high-level, it would be better to do this using some other data. Maybe the build system can provide the digests/versions natively. Maybe a sync could keep a local record of previously-seen tags, and download the added tags. Something like that.

Of course the loop can be built using `skopeo list-tags` + individual inspect operations. It’s _a bit_ of a hassle, but maybe just the right amount of resistance to motivate towards designing a more efficient workflow.

**Comment by adamjk-dev** [comment]
Thanks for the response, I just wanted to toss the notion out there. 

- Currently, I use skopeo list-tags to see if the image has a latest tag
- If so, I use skopeo inspect to grab the digest
- Then, I loop over the tags list in reverse order trying to find matches to that digest of the latest image up to X tries etc. and work it that way
