### ISSUE TITLE
Can skopeo sync layer the images with the same name but different tags under the same folder in the dir

### ISSUE THREAD

**Issue by anushka-jainn** [containers/skopeo#2349]
Hello team, 
Can skopeo sync with docker as src and dir as dest, layer the images with the same name but different tags under the same folder in the dir. As this will help in drastically reducing the size

**Comment by mtrmac** [comment]
Thanks for reaching out.

That’s not available. Registries already implement all of this, and more, so doing all of that again for `dir:` seems unnecessary.

Use a registry server, perhaps running in a container, with a backing volume mounted in to the container. Then you can transfer the contents of that volume to the other system, and run a registry server with the same volume mounted again.
