### ISSUE TITLE
`skopeo copy` fails copying from a tarball to Docker daemon when using Docker 26.1.3

### ISSUE THREAD

**Issue by phlax** [containers/skopeo#2365]
Our (Envoy proxy) CI uploads some images from a tarball created by other CI

This worked as expected with Docker version 24.0.9.

Recently Github updated its runner images. The newer images use Docker 26.1.3

Since this change our CI reliably fails with:

```console
Copy oci image: oci-archive:/tmp/tmp.TebmJdN0Xs/envoy.tar docker-daemon:envoyproxy/envoy:dev
time="2024-06-22T22:47:03Z" level=fatal msg="writing blob: io: read/write on closed pipe"
```

I have tried to repro the issue locally using the same Docker version/s but it works as expected.

I suspect this is a similar issue to https://github.com/containers/skopeo/issues/1627 where a source resource is producing data too slowly for the daemon

Not sure if this is a skopeo issue as such, but we are hitting it while trying to load using skopeo so reporting here

Any workarounds would be greatly appreciated, I would also be happy to debug further if this is helpful

**Comment by mtrmac** [comment]
@phlax please reopen if more information becomes available.

**Comment by phlax** [comment]
sorry for lack of follow up - our workaround has been working and ive been busy with other things

ill try removing it soon and reopen if necessary - thanks

**Comment by phlax** [comment]
it seems i removed the workaround some time back as a result of some other dev - the problem appears to have resolved itself - thanks again
