### ISSUE TITLE
Docker references with both a tag and digest are currently not supported

### ISSUE THREAD

**Issue by sbp-bvanb** [containers/skopeo#2367]
skopeo copy docker://alpine:3.12.1@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321 dir:/tmp/helloworld
FATA[0000] Invalid source name docker://alpine:3.12.1@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321: Docker references with both a tag and digest are currently not supported

Could this, i.e. pull of image with tag in conjunction with digest, e.g. docker://alpine:3.12.1@sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321 be implemented?

**Comment by mtrmac** [comment]
Thanks for reaching out.

This is, for the most part, intentional: see https://github.com/containers/image/issues/1736 .

Either way, Skopeo is a thin wrapper over the c/image library, so if this would be changed, it would happen in the linked repository and issue.
