### ISSUE TITLE
skopeo "sync" the data structure, can it Diff

### ISSUE THREAD

**Issue by tnubeo1111** [containers/skopeo#2376]
Hello everyone, I've only been using skopeo 2 3 days today, but I'm wondering if skopeo "sync" the data structure, can it Diff, which means it only copies the different layer hash and not the full image. Hope everyone can help me answer this question.

**Comment by mtrmac** [comment]
Thanks for reaching out.

Each layer copy is already checking for presence on the destination; it’s just a metadata check, it should never initiate a copy of a known-present layer. If you see something different, please provide details.

**Comment by tnubeo1111** [comment]
This means that skopeo does not copy the entire layer of the image every time it is copied locally. That is, if I have copied all the images from the beginning, then if I copy the layers of the image later, skopeo will not copy them in full, but will only copy back the other layers, right? Currently, I am commanding skopeo copy.

**Comment by mtrmac** [comment]
I’d recommend measuring whether it does what you need. And if it doesn’t, please provide a specific problem description.

**Comment by tnubeo1111** [comment]
Hello, let me bother you a bit. Currently, I am assuming that I copied an image named app:v1 to local area and I just edited the image based on the image name app:v1 and saved it as app:v2 later. Then I pushed the registry again. Finally, I used command skopeo copy to copy images app:v2, but as I checked, the layers are still fully downloaded like images app:v1 along with some new layers of images app. :v2. So what I'm hoping for is that skopeo only copies other layers from app:v2 which is not very feasible.

![image](https://github.com/user-attachments/assets/bec3f4a5-1c77-4dc1-aee2-cc32fa6f37c2)

**Comment by mtrmac** [comment]
I don’t know what that is showing. Specific steps to reproduce / expected results / actual results, please. And if Skopeo commands are involved, please run with `--debug`.

**Comment by tnubeo1111** [comment]
Maybe my meaning makes you not understand because of it. 

My idea is like this: 

Currently I have a Harbor registry which will save projects/images (my example would be vcr.test.vn/layer/app:v1)

With specific information such as:
- URL: vcr.test.vn
- projects: layers
- images: app:v1

And now I want to save these projects/images locally for storage unless I accidentally delete the images and projects.

So I used the following command:

`skopeo copy --tls-verify=false docker://vcr.test.vn/layer/app:v1 dir:backup/layer/app/v1`

After I use this command, I will save all layers of an image as follows:

```
root@k8s-all-in-one-1:~/harbor-backup/layer/app/v1# ls -al
total 49460
drwxr-xr-x 2 root root     4096 Jul 17 17:55 .
drwxr-xr-x 4 root root     4096 Jul 17 17:52 ..
-rw-r--r-- 1 root root  3138389 Jul 17 17:55 276dfcf5deffff3c5d540a8e0d9a18656a4c03637a8b4f4eec1f4a147799c901
-rw-r--r-- 1 root root      660 Jul 17 17:55 66379c55dabab7339fd72809e43142d6a50acfabe81d3c91b5a0e0d17365f11e
-rw-r--r-- 1 root root  2781342 Jul 17 17:55 824416e234237961c9c5d4f41dfe5b295a3c35a671ee52889bfb08d8e257ec4c
-rw-r--r-- 1 root root     8054 Jul 17 17:55 899b2ee2a2e77ad28ce03eb1242d29432e4b384853105341d970a47105e89eb5
-rw-r--r-- 1 root root 27138450 Jul 17 17:55 8b91b88d557765cd8c6802668755a3f6dc4337b6ce15a17e4857139e5fc964f3
-rw-r--r-- 1 root root 12889395 Jul 17 17:55 8f777578c172d018077d3dc22d6654911fff60066097943fe8c4697ecf8aac35
-rw-r--r-- 1 root root       93 Jul 17 17:55 953d4e06a834f8f0a86dfb739fec45e914a30b951bad66def2c1366e09e488ca
-rw-r--r-- 1 root root  4648362 Jul 17 17:55 c9eba0c7ed748c12feb7c3c44ffbab094c8d02853fb932d4c2cc10925e67d7a8
-rw-r--r-- 1 root root      244 Jul 17 17:55 cbfea27109a8b1136059a7973ccb8243889faf162ebc173a05909dcb0bec03c9
-rw-r--r-- 1 root root      154 Jul 17 17:55 fd7373d5066cc6e0679e9e53c3dbe4c69a3a54e2f3fff2cb9e1bb6d3fd267971
-rw-r--r-- 1 root root     2201 Jul 17 17:55 manifest.json
-rw-r--r-- 1 root root       33 Jul 17 17:55 version
```
Then I used the image app:v1 to add some content and saved it as app:v2 and I pushed it to the registry. 

I used the following command again to save the app:v2 images 
`skopeo copy --tls-verify=false docker://vcr.test.vn/layer/app:v2 dir:backup/layer/app/v2`

**My desire is that after copying the app:v2 images to the backup folder, I only want to save the layers different from app:v1, not the entire layer like app:v1.**

But when I looked again, I saw that app:v2 still had the same layers as app:v1 along with some new layers. You can see the image below.

```
root@k8s-all-in-one-1:~/harbor-backup/layer/app/v2# ls -al
total 49468
drwxr-xr-x 2 root root     4096 Jul 17 17:55 .
drwxr-xr-x 4 root root     4096 Jul 17 17:52 ..
-rw-r--r-- 1 root root  3138389 Jul 17 17:55 276dfcf5deffff3c5d540a8e0d9a18656a4c03637a8b4f4eec1f4a147799c901
-rw-r--r-- 1 root root      167 Jul 17 17:55 5c661d79c421b96f91b7c304c6bb5fc244bc5296c2830be9f9128dc743e501ec
-rw-r--r-- 1 root root      660 Jul 17 17:55 66379c55dabab7339fd72809e43142d6a50acfabe81d3c91b5a0e0d17365f11e
-rw-r--r-- 1 root root  2781342 Jul 17 17:55 824416e234237961c9c5d4f41dfe5b295a3c35a671ee52889bfb08d8e257ec4c
-rw-r--r-- 1 root root 27138450 Jul 17 17:55 8b91b88d557765cd8c6802668755a3f6dc4337b6ce15a17e4857139e5fc964f3
-rw-r--r-- 1 root root 12889395 Jul 17 17:55 8f777578c172d018077d3dc22d6654911fff60066097943fe8c4697ecf8aac35
-rw-r--r-- 1 root root       93 Jul 17 17:55 953d4e06a834f8f0a86dfb739fec45e914a30b951bad66def2c1366e09e488ca
-rw-r--r-- 1 root root     8597 Jul 17 17:55 c15ff18dd6577833b54a6d2e1e2565292c65ab25361def317a067096360724f2
-rw-r--r-- 1 root root  4648362 Jul 17 17:55 c9eba0c7ed748c12feb7c3c44ffbab094c8d02853fb932d4c2cc10925e67d7a8
-rw-r--r-- 1 root root      244 Jul 17 17:55 cbfea27109a8b1136059a7973ccb8243889faf162ebc173a05909dcb0bec03c9
-rw-r--r-- 1 root root      154 Jul 17 17:55 fd7373d5066cc6e0679e9e53c3dbe4c69a3a54e2f3fff2cb9e1bb6d3fd267971
-rw-r--r-- 1 root root     2408 Jul 17 17:55 manifest.json
-rw-r--r-- 1 root root       33 Jul 17 17:55 version
```


In my opinion, when copying to a newly edited image, the original image should only be copied to other layers, not the entire old layer of the original image. Doing so will make copying quite time-consuming.


Thank you for your feedback.

**Comment by mtrmac** [comment]
Yes; `dir` is a very simple destination which stores one image at a time. The path at `…/v2` is completely independent to `…/v1`; you wouldn’t want software to, unprompted, go looking for duplicates all over the computer.

If you want to share blobs across images, I generally recommend running a registry (perhaps `docker.io/library/registry:2`) open only to `localhost`, storing data in an out-of-container volume, and to do a sync/copy to/from that registry, instead of using `dir:`. Registries already implement deduplication and concurrency, and name management.

**Comment by tnubeo1111** [comment]
Thank you for your feedback. Please close this ticket
