### ISSUE TITLE
Can't copy a nerdctl save  images to image registry?

### ISSUE THREAD

**Issue by sober-wang** [containers/skopeo#2378]
untar nerdctl images 
![image](https://github.com/containers/skopeo/assets/35804630/9c26aa71-3a3a-4a7e-83fb-f6b29619ab4b)

untar a docker images
![image](https://github.com/containers/skopeo/assets/35804630/d6ff3a61-6fc5-4c1c-9d5c-31172c6722ad)

[nerdctl_issues_3202](https://github.com/containerd/nerdctl/issues/3202)
error message 
```
 skopeo copy --dest-tls-verify=false dir:/..../tmp docker://myregistry.io/lib/image_name:20240710
FATA[0000] initializing image from source dir:/..../tmp: json: cannot unmarshal array into Go value of type manifest.Schema1
```

**Comment by mtrmac** [comment]
Thanks for reaching out.

`dir:` is expecting a specific format, not that one. You might want `oci:`, `oci-archive:`, or `docker-archive:`.

**Comment by mtrmac** [comment]
Please reopen if there are outstanding questions.
