### ISSUE TITLE
Error writing manifest: can't create an OCI manifest from Docker V2 schema 1 manifest

### ISSUE THREAD

**Issue by dohnto** [containers/skopeo#240]
Hello, I am trying to examine a docker image which was created with older docker (version 1.9.1). I pushed that image to `dohnto/busybox:test` using skopeo. In order to do that, i convert the image to OCI.

```
skopeo version 0.1.17-dev commit: 507d09876d0620d46de7c8c20eb9b58d2dffa482
```

So when I run

```
skopeo copy docker://docker.io/dohnto/busybox:test oci:tmp
```

I got:

```
Getting image source manifest
Getting image source signatures
Getting image source configuration
Uploading blob sha256:56bec22e355981d8ba0878c6c2f23b21f422f30ab0aba188b54f1ffeff59c190
 559.41 KB / ? [---------------------------=----------------------------------] 
Uploading blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
 0 B / ? [--------------------------------------------------------------------=]
Uploading manifest to image destination
FATA[0007] Error writing manifest: can't create an OCI manifest from Docker V2 schema 1 manifest
```

How to solve this issue? Thank you.

**Comment by runcom** [comment]
Sorry but schema1 isn't compatible with OCI images by definition. Only schema2. There are no plans to support this conversion atm also.

**Comment by runcom** [comment]
,

**Comment by mtrmac** [comment]
The schema2→OCI conversion in `oci:` should really be eventually replaced by an OCI manifest support in `containers/image/image`. Then it should be plausible enough to do a s1→OCI conversion by using a temporary s2 `memoryImage`.

**Comment by mtrmac** [comment]
> The schema2→OCI conversion in `oci:` should really be eventually replaced by an OCI manifest support in `containers/image/image`.

This has happened now.

> Then it should be plausible enough to do a s1→OCI conversion by using a temporary s2 `memoryImage`.

Yes; we even have a `manifestSchema1.OCIConfig`, so we are quite close.

**Comment by jonboulle** [comment]
between this and containers/image, I always look at the wrong repo when looking for existing issues...
in any case, this is what I'm working on in containers/image#380

**Comment by rhatdan** [comment]
@dohnto @mtrmac @jonboulle @vrothberg Does this issue still exists or can we close this issue?

**Comment by mtrmac** [comment]
https://github.com/containers/image/pull/380 has implemented this, e.g.

```
$ skopeo copy docker://busybox:1.23 oci:t
```
now works.
