### ISSUE TITLE
Skopeo inspect fails if Image-Repository (Sonatype Nexus) returns 'null' Tag

### ISSUE THREAD

**Issue by timbocau** [containers/skopeo#2409]
We use Sonatype Nexus as Image Repository. When calling the _tags/list_ Endpoint of some images a 'null' Tag is returned:
```
{
    "name": "imagename",
    "tags": [
        null,
        "1.0.0-1",
        "1.0.0-10",
        "1.0.0-11",
        "1.0.0-12",
[...]
```

This causes Skopeo _inspect_ to fail with error "Error determining repository tags: registry returned invalid tag \"\": invalid tag format"

Running the following command produces the output below:

`skopeo --debug inspect docker://my-nexus.mydomain/my-image:1.0.1-3
`
```
...
time="2024-08-27T14:30:44+02:00" level=debug msg="GET https://my-nexus.mydomain/my-image/tags/list"
time="2024-08-27T14:31:04+02:00" level=fatal msg="Error determining repository tags: registry returned invalid tag \"\": invalid tag format"
```

The error occurs with Skopeo versions 1.14.4. and newer. With Skopeo versions 1.14.3 and older (did not test all older versions) the error does not occur.

Is this a bug or a feature?

**Comment by timbocau** [comment]
Thanks for your reply.

I agree that this is mainly caused by a bug in the Server implementation. I was just wondering what's different between 1.14.3 and 1.14.4.

Actually we found a workaround for that problem. As we do not need the Tag list we added Parameter _-n_ to _skopeo inspect_ command to suppress the processing of the Tag list and the command succeeds although the Tag list still contains invalid "null" values.

For others that want to process the Tag list a workaround in the Skopeo implementation to handle "null" values in the Tag list would surely be helpful.

**Comment by mtrmac** [comment]
@timbocau would you be able to confirm that https://github.com/containers/image/pull/2544 fixes the failure?

Also, could you identify the specific version of the server that exhibits this behavior for you, please?

**Comment by timbocau** [comment]
@mtrmac 
Although I am not an expert for the Go programming language, I would confirm that https://github.com/containers/image/pull/2544 fixes the failure.

We are using Nexus 3.58 OSS. We posted a question in the Nexus community, too: https://community.sonatype.com/t/tags-list-yields-null-as-first-tag/13117

**Comment by vrothberg** [comment]
With https://github.com/containers/image/pull/2544 being merged, I think we can close this issue. Thanks!
