### ISSUE TITLE
Impossible to fetch multi-arch image into local archive

### ISSUE THREAD

**Issue by ypnos** [containers/skopeo#2413]
I have a multi-arch image in my registry that includes images for arm64 and amd64.

When I copy using skopeo I only get the amd64 part (according to my system architecture).
> skopeo copy docker://... docker-archive:...

What I need, is the arm64 part. I cannot specify it but I can also not copy the multi-arch image:
> skopeo copy --multi-arch=all docker://... docker-archive:...

This fails with the error message "copying multiple images: destination transport "docker-archive" does not support copying multiple images as a group".

Is there a possibility to download an archive file for a different arch than the host system one?

**Comment by mtrmac** [comment]
Thanks for reaching out.

I would expect --override-arch to work for choosing which one to use.

The format (in its traditional version) just can’t represent a multi-arch image.

(A general reminder: `docker-archive:` is almost always an undesirable part of a workflow, with feature limitations like these, and unavoidably bad performance. Use a registry if at all possible.)

**Comment by WYmindsky** [comment]
same issue

**Comment by mtrmac** [comment]
Note
> The format (in its traditional version) just can’t represent a multi-arch image.

If that’s not the cause: Steps to reproduce / actual results / expected results?

**Comment by ypnos** [comment]
I'm sorry, I had overlooked the --override-arch option as it is in another option tier. This worked fine for me. Thank you for your help!
