### ISSUE TITLE
Skopeo Tag v1.16.0 Manifest errors on pull-through with podman

### ISSUE THREAD

**Issue by CubexsOne** [containers/skopeo#2416]
In our project environment, we use a harbour registry with a pull-through mirror function to clone images to us accordingly.

Now we are in the process of updating our dependencies and one of them is Skopeo.

If we pull the image with docker from a Macbook with --platform linux/amd64 it works perfectly.

If we do this with podman on a Linux machine, we get an error message that something is not found.

According to the operator of our registry it seems to be a problem in the manifest from the original repo.

Image: skopeo/stable:v1.16.0

For further questions, please write.
I am happy about any help

Best regards
CubexsOne
![377f954f-3d2d-40b4-8f12-eb8d2e8fe6ad](https://github.com/user-attachments/assets/47778502-3064-4ece-962c-3e88bb986787)
![479f8d47-402b-4ce9-92cf-24d8cf85d312](https://github.com/user-attachments/assets/1178bb00-c0cd-4d06-950b-5b26a5e77d06)

**Comment by CubexsOne** [comment]
Thanks for the answer, I will try to work on this with the admins of the registry.

**Comment by mtrmac** [comment]
FWIW, for these changing images, you might want to capture
- `skopeo inspect --raw docker://…:v1.16.0 | sha256sum` to identify the image
- `skopeo inspect --raw docker://…:v1.16.0 | jq .` or something like that to identify the per-arch references being used
- Correlate the per-arch references from the above with the `reading manifest sha256:…` messages.

**Comment by CubexsOne** [comment]
Hii,

FYI: The image 1.16.1 is working.
No one knows why this is working, but I guess its not a problem on your side.

Thanks for helping, have a great time.

**Comment by mtrmac** [comment]
Thanks for the update.
