### ISSUE TITLE
skopeo: /lib64/ libb.so. 6: version 'GLIBC_2.33' not found

### ISSUE THREAD

**Issue by yangzhijia1985** [containers/skopeo#2436]
When I use skopeo on cenos-stream8, the system returns an error message: skopeo: /lib64/ libb.so. 6: version 'GLIBC_2.33' not found (required by skopeo),
Does skopeo require the minimum version of libc to be 2.33?
If the libc of the system cannot be upgraded, then skopeo cannot be used

**Comment by mtrmac** [comment]
Thanks for reaching out.

https://github.com/containers/skopeo/blob/main/install.md generally recommends installing packages provided by the distribution. That should provide packages that match the environment.

Alternatively, we provide container images.

**Comment by lsm5** [comment]
@yangzhijia1985 centos-stream8 is no longer being developed. Please consider switching to CentOS Stream 9 or maybe Fedora if it satisfies your use case.

Don't think there's anything we can do here. Closing...
