### ISSUE TITLE
Skopeo commands should return non-0 exit status if called incorrectly

### ISSUE THREAD

**Issue by ChrisSamo632** [containers/skopeo#2468]
If a `skopeo` command is called with invalid flags, e.g. `skopeo copy --dest-tls-verify false docker-archive://... docker://...`, then `skopeo` fails and prints a Usage help message to STDOUT. However, the exit status of the command is `0`, so there is no easy way to programatically detect whether the command has failed.

In this case, the `=` was missed in `--dest-tls-verify=false` and so `false` is seen as the Source for the `copy` command, which is invalid. But the issue is that my script couldn't then detect that the `skopeo` command had failed, and instead reported that the `copy` was successful (which it wasn't, and only became obvious once checking logs).

**Comment by mtrmac** [comment]
Thanks for your report!

#2469 should fix this.
