### ISSUE TITLE
Support managing manifests with foreign URLs

### ISSUE THREAD

**Issue by aweiteka** [containers/skopeo#247]
The [docker manifest schema](https://docs.docker.com/registry/spec/manifest-v2-2/) and [oci schema](https://github.com/opencontainers/image-spec/blob/master/layer.md) provides support for layers to be referenced using a foreign URL. This allows layer content to be stored outside of registry as an alternative [media type](https://github.com/opencontainers/image-spec/blob/master/media-types.md). Skopeo should be extended to generate and push these manifests to a registry.

**Proposed UX**

Pre-populate a registry with images from a foreign source:
```
# skopeo copy docker-daemon:my/image docker://registry.example.com/my/image \
              --layers-url=https://cdn.example.com/containers/
```

The manifest uploaded to the registry would have a foreign URL reference for *all layers*. This would typically be done for base images. Subsequent pushes to the registry would skip uploading these layers to the registry.

cc @runcom

**Comment by runcom** [comment]
I still struggle to accept this concept of a base image though (probably tied to the FROM Dockerfile instruction)  :) a base image can very likely be composed by multiple layers (my own base image based itself of rhel for instance). Anyhow, there will be some issues with digests I guess, since, changing something in a manifest changes its digest thus invalidating signatures for instance (not to mention it could entirely break pull by digest for people doing FROM image@digest). /cc @mtrmac 

UX can tell exactly which layer in a chain should have a given URL though (by index maybe). 
I believe we first need to sort out the digest-change story above also.

**Comment by mtrmac** [comment]
@aweiteka In principle plausible, as a counterpart to the read path in #147.  But then there are details: What is the protocol and auth mechanism used for uploading the layers?

@runcom I am not really worried about manifest changes; this would obviously change the manifest and invalidate existing signatures, but it’s not the first such option; we already do layer compression and manifest schema conversion. The original author of the image can set `url`s and then sign; this would only prevent third parties from changing the URL list.

(OTOH there _have_ been vague suggestions that Fedora would like to do just that, edit the URL list of published manifests to be able to take advantage of their existing network of dumb file-serving mirrors. Too bad, at least for now, I suppose.  _Eventually_ we can think about `config.json`-based signatures, and it may even be necessary for local signature tracking, but I don’t think that should be our first choice.)

**Comment by aweiteka** [comment]
> What is the protocol and auth mechanism used for uploading the layers?

First, let's recognize this is a special case. I am only aware of OS distros who may require such a thing at this point. I was thinking layer upload is async or uses another mechanism to publish the layers. For example, layers could be written to a **dir:** transport type which is rsync'd to a web server.

**Comment by rhatdan** [comment]
@runcom @aweiteka @mtrmac @vrothberg What ever happened with this?  Is this still something we are interested in or can we close?

**Comment by mtrmac** [comment]
So far, the widespread user of foreign layers I’m aware of are the Windows base images, creation of which is not really possible with Buildah. While that does not _directly_ rule out the use of Skopeo to add the external URLs to an already-built image, the Windows images have obviously been built without this feature being present.

Meanwhile, https://github.com/containers/buildah/commit/7b1a87a17 has at least hinted in the direction of Buildah allowing to create such images (although it only adds support for URLs of _manifests_, not of _layers_, there is no caller, and no upload mechanism).

Also, support for OCI encryption now makes the need to host images outside of registries a bit less important.

Most deceive for me is that without a way to host/upload the layers, we can at best build a partial solution (similar to `sigstore-staging` for publishing signatures); if there aren’t many users asking for the feature (and @aweiteka has not returned to ask for it either), it’s probably not really worth it to provide a hard-to-use partial solution. The few users that do need such a functionality can probably use c/image + a custom code to edit the manifest, along with a specific upload mechanism that fits their setup.
