### ISSUE TITLE
client version too old

### ISSUE THREAD

**Issue by ChristalZhao** [containers/skopeo#2470]
my questions： cant use skopeo in ubuntu22.04；
Syncing image: hardened-addon-resizer:1.8.20-build20240410
FATA[0000] initializing source docker-daemon:hardened-addon-resizer:1.8.20-build20240410: loading image from docker engine: Error response from daemon: {"message":"client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version"} 
Failed to sync: hardened-addon-resizer:1.8.20-build20240410. Retrying...

I use skopeo copy；
and my docker info is following：

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 79
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-94-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.717GiB
 Name: ubuntu2204
 ID: d9e61fde-b34b-4fa8-b0ce-d4b8f5bc4ff0

I would  be  grateful  if you  can  solve  the  problem

**Comment by mtrmac** [comment]
Thanks for your report.

What is the version of Skopeo? This was fixed in Skopeo 1.14.2; if the distribution is shipping an earlier version, you need to talk to them to update (if it is consistent with the policies of that release). Or, alternatively, run Skopeo in a container, or maybe compile it yourself.
