### ISSUE TITLE
Can `skopeo copy` *not* copy through the client?

### ISSUE THREAD

**Issue by maze88** [containers/skopeo#2472]
I'll clarify the question/feature request via my use case:
I'd like to use `skopeo copy` to promote images from _Registry A_ to _Registry B_ ("staging" to "production").

Can the data be transferred directly from _Registry A_ to _Registry B_, without needing to go through my [relatively slow] client (where the command was run)?

I've been waiting on this for several minutes which feel redunant...:
```
Getting image source signatures
Copying blob 06c36f5067bb [=========>----------------------------] 36.2MiB / 135.5MiB
Copying blob 01ddefa12565 done
Copying blob e95fa27a2943 [==========================>-----------] 64.5MiB / 89.2MiB
Copying blob 1f4fb700ef53 done
Copying blob 812008e7f761 done
Copying blob 9c52413557ed done
Copying blob 8d847aa46414 done
```

**Comment by mtrmac** [comment]
Thanks for reaching out.

There is no such feature in the protocol, so, no. Some specific registry implementations might offer server-side sync (or, quite possibly, an ongoing mirroring arrangement), but that would need to be triggered/managed in the UI of that specific registry.

**Comment by maze88** [comment]
Thanks for the swift response. Makes sense I guess.... since various registries would probably be implemented differently.
