### ISSUE TITLE
Can not list Tags on Repo when there is no latest tag

### ISSUE THREAD

**Issue by plumcraft** [containers/skopeo#276]
When i'm trying to list tags on specific repo, i got this error message :

- Erreur : manifest unknown: manifest unknown

Thanks

**Comment by runcom** [comment]
@plumcraft could you try with `skopeo inspect yourimage:atagwhichexist`?

**Comment by plumcraft** [comment]
@runcom : Thanks for your reply. 

The issue is i need to list tags on specific repo which does not have a tag named "latest", i have  "manifest unknown: manifest unknown". Do you have a filter where there is no latest tag ?
Next i will rely on that to clean the docker registry.

When i execute skopeo inspect on a specific tag, it's working.

Thanks

**Comment by runcom** [comment]
I see, unfortunately skopeo does work on a specific tag (e.g. latest) when inspecting an image. The tag list it returns it's fetched when inspecting _a_ particular tag. The way it works, if you don't specify a tag it uses latest, if you don't have a latest tag, skopeo is unable show image information, thus it doesn't make sense to retrieve the tag list. 

I feel we should remove the tag list from inspect and have a dedicated command to show the tag list for a given repository.

**Comment by plumcraft** [comment]
That make sense. It would be awesome having a dedicated command for that.

**Comment by runcom** [comment]
> That make sense. It would be awesome having a dedicated command for that.

Great, time to contribute? :) 

I'd like to hear if this makes sense by @mtrmac also

**Comment by mtrmac** [comment]
> I feel we should remove the tag list from inspect and have a dedicated command to show the tag list for a given repository.

I’m not sure about breaking existing users of `skopeo inspect`, but having a recommended command which is clearly Docker-specific and does not need the magic handling of `docker.Image` in `inspect.go` would be nice.

**Comment by rhatdan** [comment]
@runcom @plumcraft @mtrmac @vrothberg What is the latest on this issue?  Is this still something we are interested in?

**Comment by mtrmac** [comment]
At the API level, there is now `c/image/docker.GetRepositoryTags`, which does not require an existing tag.

Adding this as a separate command to `skopeo`, and ideally deprecating the list of tags in `skopeo inspect` (but that would break users) is still worth considering.

**Comment by zhill** [comment]
This hasn't been updated in a while, but I'm interested in providing a command to list tags from a repository. It is implemented as a distinct top-level command, e.g. `skopeo list-tags docker://myregistry.com/myrepo/`.

I think I'd defer the removal of the tag listing from the inspect output to keep things compatible.

Would you all be open to this, @mtrmac @rhatdan ?

**Comment by mtrmac** [comment]
This is definitely something that we would like to have.


> `skopeo list-tags docker://myregistry.com/myrepo/.`

Design of the CLI in a way that is future-proof and could generalize to other transports would be very tricky, though; see the naming discussion around https://github.com/containers/skopeo/pull/682#discussion_r295892434 (although it talks primarily about the catalog, the same concerns apply to tags; also possibly  https://github.com/containers/skopeo/pull/524#issuecomment-469884710 or even most of that PR deal with the same class of issues).

A very constrained subcommand (roughly like `skopeo docker-list-tags my-registry.com/my-repo`) would be much easier to get right (and if we ever figure out how to generalize the facility, it would be easy enough to turn it into a legacy handler redirecting to the more general feature).

**Comment by zhill** [comment]
> This is definitely something that we would like to have.
> 
> > `skopeo list-tags docker://myregistry.com/myrepo/.`
> 
> Design of the CLI in a way that is future-proof and could generalize to other transports would be very tricky, though; see the naming discussion around [#682 (comment)](https://github.com/containers/skopeo/pull/682#discussion_r295892434) (although it talks primarily about the catalog, the same concerns apply to tags; also possibly [#524 (comment)](https://github.com/containers/skopeo/pull/524#issuecomment-469884710) or even most of that PR deal with the same class of issues).
> 
> A very constrained subcommand (roughly like `skopeo docker-list-tags my-registry.com/my-repo`) would be much easier to get right (and if we ever figure out how to generalize the facility, it would be easy enough to turn it into a legacy handler redirecting to the more general feature).

Understood and agreed. Perhaps `registry-list-tags`? Or is registry (meaning OCI or Docker V2) still not general enough? I'm not opinionated on the naming, to be clear, just want to make it as stable as possible for future use.

**Comment by rhatdan** [comment]
Yes I prefer not to include a company name in the CLI, well anymore then we already do.

**Comment by mtrmac** [comment]
> Perhaps `registry-list-tags`? Or is registry (meaning OCI or Docker V2) still not general enough?

IMHO it’s borderline, closer to the risky side, but opinions on that will differ, as already demonstrated:)

**Comment by zhill** [comment]
I'll go ahead and get the code ready, we can discuss the specific name for the command once I open the PR and make any necessary changes then.
