### ISSUE TITLE
Skopeo layers does not enforce signature policy

### ISSUE THREAD

**Issue by aweiteka** [containers/skopeo#287]
I would expect `skopeo layers` command to enforce signature policy. Is this by design?

```
# skopeo --policy  /etc/containers/policy.json copy docker://docker.io/library/busybox:latest dir:/tmp/
FATA[0000] Source image rejected: Running image docker://busybox:latest is rejected by policy.
# skopeo --policy  /etc/containers/policy.json layers docker://docker.io/library/busybox:latest
# ls -1 layers-240369082/
4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c.tar
a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4.tar
manifest.json
```

**Comment by runcom** [comment]
Yeah, there are plans to remove that command altogether and redirect people to use copy instead.

**Comment by aweiteka** [comment]
Ok, good. So far I do not see a purpose or use case for it. We can migrate atomic to use copy.

**Comment by mtrmac** [comment]
See also https://github.com/containers/image/pull/159 , which would provide something close to a signature-verifying equivalent to the “pull a single layer” use case of `skopeo layers`. Though, philosophically, IMHO `skopeo layers` is too low-level and exposing too much of the implementation to be a long-term recommended solution for anything. Debugging can be done with (`skopeo copy … dir:`), which copies everything in the image; getting a single layer assumes code knowing the structure of the image format, and that should not be in shell.
