### ISSUE TITLE
skopeo build system does not work inside a container

### ISSUE THREAD

**Issue by erikh** [containers/skopeo#311]
I typically develop in containers these days, and the `-v` syntax refers to my host which ironically enough had a copy of skopeo installed into the same path and hilarity ensued.

I am too serious a person for hilarity so I would like a solution instead.

I am thinking if we packaged all the source into the image before running everything instead of using a volume, all would be good. It will slow down the build a little bit but not too much.

Host builds can just be `go build` I guess? Is that an issue?

**Comment by mtrmac** [comment]
What is the issue and the failure path exactly?

**Comment by erikh** [comment]
build inside a container with the docker.sock forwarded.

I don't think we're actually getting anything by building in a container
right now because of the vendoring.

**Comment by mtrmac** [comment]
Steps to reproduce / expected results / actual results?

**Comment by erikh** [comment]
Sure, so do something like this:

```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock golang
```

Install the deps you need, etc., And attempt to build containers/storage.

**Comment by rhatdan** [comment]
@erikh Is this still something you are interested in?  Does it work within Podman?

**Comment by mtrmac** [comment]
Nowadays we primarily advertise the non-container `make binary-local` which should have no issues with running inside a container.

If that is not sufficient clear steps to reproduce / expected results / actual results would still help with triaging.
