### ISSUE TITLE
make binary-local for 0.1.21 fails on amd64/linux with go 1.8.3

### ISSUE THREAD

**Issue by williamh** [containers/skopeo#359]
Here is what I get when I run "make binary-local":

```
go build -ldflags "-X main.gitCommit=0b7315460126b8945fd53f9318a65d7cc8796af1" -gcflags "" -tags " " -o skopeo ./cmd/skopeo
# github.com/projectatomic/skopeo/vendor/github.com/ostreedev/ostree-go/pkg/glibobject
vendor/github.com/ostreedev/ostree-go/pkg/glibobject/gobject.go:69: cannot use v.native() (type *C.struct__GObject) as type C.gpointer in argument to func literal
vendor/github.com/ostreedev/ostree-go/pkg/glibobject/gobject.go:73: cannot use v.native() (type *C.struct__GObject) as type C.gpointer in argument to func literal
make: *** [Makefile:60: binary-local] Error 2

```

**Comment by rhatdan** [comment]
This is exactly what I am seeing on Fedora 25.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by runcom** [comment]
Ryan created a PR already in ostree go bindings to fix this.

**Comment by rhatdan** [comment]
Link?

**Comment by runcom** [comment]
https://github.com/ostreedev/ostree-go/pull/6

**Comment by williamh** [comment]
I applied the patch from the previously mentioned p/r and make binary-local fails with a different message:

```
go build -ldflags "-X main.gitCommit=b40a260b1bd1b9334a6aeafbcbdae91921d6e783" -gcflags "" -tags " " -o skopeo ./cmd/skopeo
# pkg-config --cflags ostree-1 ostree-1 ostree-1 ostree-1 ostree-1 ostree-1
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
Package ostree-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `ostree-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'ostree-1' found
pkg-config: exit status 1
make: *** [Makefile:60: binary-local] Error 2

```

**Comment by mtrmac** [comment]
Yeah, the `README.md` need updating for the added dependency.  Can you verify that one of
```sh
Fedora$ dnf install ostree-devel
Debian$ apt-get install -y libostree-dev
```
fixes this, please? (Reportedly the Ubuntu `libostree-dev` is only present in Zesty, not earlier versions.)

**Comment by williamh** [comment]
I'm not on either of those distros (I use Gentoo), so I can't verify this.
I checked and libostree is not present on Gentoo.

**Comment by rhatdan** [comment]
Might need to have a way to compile out the ostree support then.

**Comment by williamh** [comment]
I looked at packaging ostree, and something is unclear to me about it. It's not clear from its README whether it requires systemd, which is what their releases page seems to say. Since systemd is optional for us, and since I'm not sure whether ostree requires systemd, I tend to agree that making ostree optional would probably be a good idea.

**Comment by mtrmac** [comment]
Well, unless you want to use the ostree backend (which is not the case right now), the dependency is on libostree being _compiled_, not on it _working_. So a compile-time dependency on systemd might not be a show-stopper (unless the distribution requires the systemd runtime to be installed in order to have the build environment available).

We do need a way to make this optional, though. I’m almost tempted to put autoconf in there… Only if it didn't require `autoreconf` after a git checkout.

So, we need a build tag in containers/image which replaces `ostree` in `alltransports` with a dummy “this transport is no available” placeholder, and skopeo’s `Makefile` to use pkg-confing and auto-detect whether ostree is available, configuring the build tag as necessary.

**Comment by williamh** [comment]
Yes, the distro does need systemd installed in order to compile against it. Gentoo does have systemd, but it is optional, so if someone wants to use the systemd support, they can.

I recommend giving us a way to control at build time whether the systend support is included. For example, give us a setting to pass to the make command to control it.

**Comment by mtrmac** [comment]
> Might need to have a way to compile out the ostree support then.

https://github.com/containers/image/pull/290 ; if that works, skopeo can be build with a `BUILDTAGS=`…, or `Makefile` could even auto-detect ostree presence if anyone cared to implement that.

**Comment by williamh** [comment]
I would support a BUILDTAGS option; that would make it possible for distros to turn off the requirement for systemd. I prefer this over autodetection.

**Comment by mtrmac** [comment]
OK, that’s even easier. Can you verify that https://github.com/containers/image/pull/290 works for you, please?

**Comment by williamh** [comment]
The recommended pull request to try for this is

https://github.com/containers/image/pull/290

I am unable to get this to apply against scopeo.

**Comment by williamh** [comment]
I skipped the patch I referred to in the prevvious comment, and yes this allows skopeo to be built without systemd.

**Comment by mtrmac** [comment]
After https://github.com/containers/image/pull/290 it will be possible to build with
```sh
make binary-local BUILDTAGS=containers_image_ostree_stub
```

It would probably make sense to teach `Makefile` to detect `libostree` presence and to add this tag tag automatically (with a warning?)

**Comment by rhatdan** [comment]
I believe this is fixed in skopeo.  Closing, Reopen if I am mistaken.
