### ISSUE TITLE
skopeo needs to support containers/storage

### ISSUE THREAD

**Issue by rhatdan** [containers/skopeo#363]
skopeo copy docker:registry.access.redhat.com:rhel7 storage:  
   Should copy rehl7 to /var/lib/containers/storage based on /etc/containers/storage.conf defaults.

skopeo copy docker:registry.access.redhat.com:rhel7 storage:/var/lib/nfs/storage  
    should copy rehl7 to /var/lib/nfs/storage overriding /etc/containers/storage.conf defaults.

Currently there does not seem to be a way to use skopeo and containers/storage at the same time.

**Comment by runcom** [comment]
mmm actually you can use:
```
skopeo copy docker://someimage containers-storage:someimage:latest
```

**Comment by rhatdan** [comment]
Ok great we can close this, but does this allow the specification of path?

**Comment by runcom** [comment]
@rhatdan I don't think so, @nalind wdyt?

**Comment by nalind** [comment]
It doesn't - we'd been stuffing location and driver into the storage image reference, but that's not actually enough information to let arbitrary locations be specified, and the reference parser doesn't provide a way for us to actually provide enough information.  If we want to open an issue for that, I've been meaning to do something about it.

**Comment by rhatdan** [comment]
You want an issue in container/storage? 
Also can we change container-storage to just be storage?  A lot less to type.

**Comment by giuseppe** [comment]
you can specify the path as: `containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]foo:latest`, or is there something more missing?

**Comment by rhatdan** [comment]
Skopeo now supports containers storage.  So closing.
