### ISSUE TITLE
Document blob digest / layer DiffID, (docker inspect) / (skopeo inspect) differences, and schema1 empty layers

### ISSUE THREAD

**Issue by akostadinov** [containers/skopeo#393]
Hi, I've built an image with the `imagebuilder` tool. Base image has 3 layers and one is added by `imagebuilder`. `docker inspect` shows 4 layers as I would expect. But `skopeo` shows 11 layers:
```
$ skopeo inspect docker://docker-registry.example.com/aosqe/cucushift-base:latest
{
    "Name": "docker-registry.example.com/aosqe/cucushift-base",
    "Tag": "latest",
    "Digest": "sha256:57ba0882d5fb5722dbed7344dc7ec623c2a5b215fbc739d612ead990735dc51f",
    "RepoTags": [
        "latest"
    ],
    "Created": "2017-08-04T09:20:30.926379403Z",
    "DockerVersion": "1.13.1",
    "Labels": {
        "build-date": "20170705",
        "io.openshift.builder-version": "21ac267",
        "license": "GPLv2",
        "maintainer": "AOS QE Team",
        "name": "CentOS Base Image",
        "vendor": "Red Hat inc."
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:ff04a77efbee3d708c4ba5c379e00f72130a0477916d876673c7985660644523",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:f6d2db44e367d68f53eb090da638938427884404009636fdbe6d692ef382e410",
        "sha256:df685470456b4f944a37bf5492d610f296324cdfe7ca132e94751e06cdea8765",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4",
        "sha256:15ddd396c8076103e6e61f304d21b54d47bcea914ef566b21850ee85c51463ee"
    ]
}
```

As you can see, there are a number of duplicate layers. But even if I count them as 1, then still layers are more than what `docker` shows.

Here's docker output for a reference:
```
$ sudo docker inspect docker-registry.example.com/aosqe/cucushift-base:latest
[
    {
        "Id": "sha256:8014a3aa6f2c3dbea5e1b74fa1ea0f4eccf9b82e3faa1429eafbc614745beaa3",
        "RepoTags": [
            "docker-registry.example.com/aosqe/cucushift-base:latest"
        ],
        "RepoDigests": [
            "docker-registry.example.com/aosqe/cucushift-base@sha256:57ba0882d5fb5722dbed7344dc7ec623c2a5b215fbc739d612ead990735dc51f"
        ],
        "Parent": "sha256:4e263fe1b294160435d005c0bc75f119fe45bfb76285020c3e52581e6e878a67",
        "Comment": "",
        "Created": "2017-08-04T09:20:30.926379403Z",
        "Container": "7aaed0a4378c5840ad5fc5620960e45936dc99951d690d6799a7607bd16d2b58",
        "ContainerConfig": {
            "Hostname": "7aaed0a4378c",
            "Domainname": "",
            "User": "root",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/home/jenkins"
            ],
            "Cmd": [
                "sleep 86400"
            ],
            "Image": "openshift/jenkins-slave-base-centos7",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/bin/sh",
                "-c"
            ],
            "OnBuild": null,
            "Labels": {
                "build-date": "20170705",
                "io.openshift.builder-version": "21ac267",
                "license": "GPLv2",
                "name": "CentOS Base Image",
                "vendor": "CentOS"
            }
        },
        "DockerVersion": "1.13.1",
        "Author": "",
        "Config": {
            "Hostname": "d1e7c521d3a4",
            "Domainname": "",
            "User": "1001",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/home/jenkins"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/usr/bin/scl",
                "enable",
                "rh-git29",
                "rh-ror42",
                "--",
                "/usr/local/bin/run-jnlp-client"
            ],
            "OnBuild": null,
            "Labels": {
                "build-date": "20170705",
                "io.openshift.builder-version": "21ac267",
                "license": "GPLv2",
                "maintainer": "AOS QE Team",
                "name": "CentOS Base Image",
                "vendor": "Red Hat inc."
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1213411318,
        "VirtualSize": 1213411318,
        "GraphDriver": {
            "Name": "overlay2",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/2d1e874f5e43261a6a5f1e450f56dfb5cfcb343d9177b4177b0acd00dce0a6c0/diff:/var/lib/docker/overlay2/2ba6cbc2faa110b614d3b6c4746fbe65666d3f5e3aa472381335d1d1fdd3c012/diff:/var/lib/docker/overlay2/298feca6acd9aefde2ee3ba60c79a79cc0eb1425c60c57aacd96d33aad95a97a/diff",
                "MergedDir": "/var/lib/docker/overlay2/37087407e600c4da3c45ca4eed9d24b4eb56368e95fa15e60b20fba15ff2aed5/merged",
                "UpperDir": "/var/lib/docker/overlay2/37087407e600c4da3c45ca4eed9d24b4eb56368e95fa15e60b20fba15ff2aed5/diff",
                "WorkDir": "/var/lib/docker/overlay2/37087407e600c4da3c45ca4eed9d24b4eb56368e95fa15e60b20fba15ff2aed5/work"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:99b28d9413e47df267df84318788754dd39d4c8e0dc2c72c9e8922b3a91f21fa",
                "sha256:1420b3bd2231d58083b355d7f2286e901e035b0ccd69d8a68289993e4fb3fad5",
                "sha256:268371c1ff5c4c33086619c3d1e12bf72ede5a919a8e49331cecd5455fd49018",
                "sha256:dc9feeeb1b614a6947e3f004c8a647fbe13959fb2c158d175bd88bcbb4bf9cba"
            ]
        }
    }
]
```

Another interesting issue is that I can't match any of the skopeo layer hashes with those from docker.

**Comment by mtrmac** [comment]
Thanks for your report.

The a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4 layers are ”empty layer” entries, for things like `CMD`, `ENV` and similar `Dockerfile` entries. That layer _is_, though, physically a part of the image (e.g. it needs to be copied along with other layers), so it is not obvious that it should not be listed here.

Is it functionally important to you that skopeo should not be listing the layer, and if so, why? Or is it ”only” confusing? (I do realize that a confusing output may be problematic, just trying to figure out what the right thing to do is here…)

**Comment by mtrmac** [comment]
(If it matters, these empty layers are used only for schema1 images; an upgrade to a schema2 or OCI image generator and registry should make this go away.)

**Comment by akostadinov** [comment]
Hi, docker doesn't show these layers so it i confusing. On the other hand I don't mind having them there given that's documented somewhere.

Given the above explanation, I think the bigger issue is that I can't match layer hashes between `docker` and `skopeo`. How can this be explained and how could one correlate `docker` to `skopeo` inspect output?

**Comment by mtrmac** [comment]
> I think the bigger issue is that I can't match layer hashes between `docker` and `skopeo`. How can this be explained and how could one correlate `docker` to `skopeo` inspect output?

Again, why does that matter? What are you _ultimately_ trying to do? Are you building a content-addressable system of some kind? (Pedantically speaking, the answer is to filter out the a3ed…6d4 layer from the skopeo output; that should handle most, though not necessarily _all_, of the empty layers; but that’s not all that useful for deciding what skopeo should output.)

**Comment by akostadinov** [comment]
wrt empty layers - in my previous comment I said that I'm fine with them. It's good to be documented though for new users. My use case for this was to make sure my image is squashed before I push to repo. The additional layers shown by skopeo made me suspect something went wrong. I initially saw the base image had 4 layers during build and then see my new image has much more layers and I thought probably it was not squashed. Now I know what is the reason for them. Just telling why I was concerned.

wrt layers reported with different hash by `docker` and `skopeo` that is a big mystery for me. I was trying to compare locally running image to what is available in upstream repo. I guess the main image hash does the job as it is reported the same by both programs. I still can't understand though how could the two programs calculate the layer hashes differently. My thinking is that one of the programs should be doing it wrong. And it's better to understand which one, so this is fixed.

**Comment by mtrmac** [comment]
> My use case for this was to make sure my image is squashed before I push to repo. The additional layers shown by skopeo made me suspect something went wrong.

Ah, that makes sense. The flip side is that `atomic` depends (?) on the layer list to know what to download, and it’s at least not immediately obvious to me that we can just skip the empty layers without breaking it.

> wrt layers reported with different hash by docker and skopeo that is a big mystery for me.

`skopeo inspect` reports the digests of the _compressed_ layer tarballs; `docker inspect` in `RootFS.Layers` shows the “DiffID”s, i.e. digests of the _uncompressed_ layer tarballs:

- The two are in general not the same
- One uncompressed digest may map to several different compressed digests (depending on the specific implementation of the compression), so it is not possible to predict the compressed digest from the uncompressed tarball without having exactly the same compression implementation available
- Without having access to the underlying tarball (compressed or uncompressed), knowing only the compressed/uncompressed digest, it is absolutely impossible to compute the corresponding uncompressed/compressed digest.
- `docker pull` does not store the manifest with the compressed digest values locally; i.e. after the image is pulled, the layers are impossible to match against a remote repository, except by fetching the image from the remote repository and uncompressing the layers (in general), or by fetching the config which contains the DiffIDs (if the image is using schema2 or OCI).

Yeah, that makes the layer digests fairly difficult to work with.

https://github.com/containers/image/pull/288 and a few related PRs will allow `skopeo` to save the manifest when pulling the image, so that it is again available for reading using a containers/image, or skopeo, tooling; but that would still work better with a patched docker to save the same information also on `docker pull`. I’m working on that, but it will take a bit more time.

**Comment by akostadinov** [comment]
Thank you for explanation. Based on it I don't think we need to necessary fix anything in `skopeo`. Perhaps a few words in documentation about the data it is showing would suffice to make use aware about the meaning of the different hashes and difference from `docker`.

**Comment by rhatdan** [comment]
@akostadinov @mtrmac @vrothberg @TomSweeneyRedHat Does anyone know if the documentation was ever improved for this issue?

**Comment by TomSweeneyRedHat** [comment]
No doc changes for this that I"m aware of.

**Comment by mtrmac** [comment]
I’m tempted to say that explaining the difference between compressed/uncompressed digests (and manifest/config/manifest list digests) does not quite belong in the primary man pages.  Ordinary users don’t need to care, and explaining this in man pages would only confuse them, and people building specialized tools should know about all of these things… from… well… somewhere… yeah.

So, this should be explained, but I don’t quite know where.

**Comment by rhatdan** [comment]
Should we add a document to skopeo github to explain this then?

**Comment by akostadinov** [comment]
What will be confusing if there is a section in the man page about layers and digest? Especially becaues users may be exposed to the output from different tools about same images, such explanation will be valuable.

**Comment by mtrmac** [comment]
> What will be confusing if there is a section in the man page about layers and digest?

I was basically thinking that either we put it in some appendix of one of the man pages (or to GitHub) where people who need this won’t notice, or we lead with the definitions in every affected subcommand, and all the people who don’t need to deal with this will have to read the document to realize they don’t need to deal with this.

But you’re right, adding a link to the `DESCRIPTION` section of **skopeo-inspect**(1) and **podman-inspect**(1) should work well enough; these are the two that matter the most (or have I missed an important subcommand?)

**Comment by rhatdan** [comment]
@mtrmac If you write up the description, I will add open PRs for podman, buidlah and Skopeo.

**Comment by rhatdan** [comment]
@mtrmac We never followed through on this.  Could you write up a description of the difference and we can add the description to skopeo-inspect and podman-inspect and we can close this issue?
