### ISSUE TITLE
error on macOS: Error loading trust policy: open /etc/containers/policy.json: no such file or directory

### ISSUE THREAD

**Issue by ahmetb** [containers/skopeo#394]
Can this file be loaded from someplace like `$HOME/.skopeo/policy.json` instead of `/etc/containers` which requires sudo permissions to create?

**Comment by rhatdan** [comment]
This seems reasonable, but only if /etc/containers/policy.json does not exist. We would not want the user to easily override the admins security constraints.

**Comment by mtrmac** [comment]
You can also change the built-in path default using `-ldflags '-X github.com/containers/image/signature.systemDefaultPolicyPath=$your_path'` .

**Comment by ndbroadbent** [comment]
I'm still getting this error on macOS, with skopeo version `0.1.40`. (Installed via `brew install skopeo`.)

```
$ skopeo copy docker-daemon:debian:stretch dir:./
FATA[0000] Error loading trust policy: open /etc/containers/policy.json: no such file or directory
```

If anyone else sees this, I was able to get it to work by using the `--insecure-policy` flag:

```
$ skopeo --insecure-policy copy docker-daemon:debian:stretch dir:./
```

But it would be nice if this worked out of the box on macOS.

**Comment by rhatdan** [comment]
If we add skopeo as a brew package, we could automatically install a lenient policy.json file.

**Comment by ndbroadbent** [comment]
That sounds good! I think someone is already maintaining a brew package for skopeo, because this is how I installed it.

* https://formulae.brew.sh/formula/skopeo
* https://github.com/Homebrew/homebrew-core/blob/master/Formula/skopeo.rb

I just saw that [there should already be a default `policy.json`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/skopeo.rb#L44), so maybe the path just needs to be fixed.

**Comment by rhatdan** [comment]
Looks good, but at this point, it is over my head.  I have never done anything with MACs or Brew.
@jwhonce @lsm5 @vrothberg PTAL

**Comment by mtrmac** [comment]
https://github.com/containers/image/pull/922 will allow using a per-user `policy.json`, _if it exists_.

**Comment by mtrmac** [comment]
- Homebrew now does install a default `policy.json`.
- When building from source, AFAICS `make install` installs a default `policy.json`
- https://github.com/containers/skopeo/pull/957 has added https://github.com/containers/image/pull/922 , so as of Skopeo 1.1.0 it is possible to run Skopeo even if `root` did not install a policy.

**Comment by kislow** [comment]
locate policy file --> ```find / -name "policy.json" 2>/dev/null```
copy to $HOME/.skopeo

**Comment by freemankevin** [comment]
> I have the same problem on arm64:
`FATA[0000] Error loading trust policy: open /etc/containers/policy.json: no such file or directory`

> Refer to the [official](https://github.com/containers/skopeo/blob/main/default-policy.json) solution: 
```shell
$ mkdir -p /etc/containers
$ tee > /etc/containers/policy.json <<-EOF
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports":
        {
            "docker-daemon":
                {
                    "": [{"type":"insecureAcceptAnything"}]
                }
        }
}
EOF

**Comment by mtrmac** [comment]
The official solution would be to use `make install`, or a package from something like Homebrew, not to carry around such a long fragment to copy&paste.

**Comment by freemankevin** [comment]
> The official solution would be to use `make install`, or a package from something like Homebrew, not to carry around such a long fragment to copy&paste.

I have used the above method to solve the problem of error reporting in the arm64 environment.
