### ISSUE TITLE
Improve skopeo copy output

### ISSUE THREAD

**Issue by myllynen** [containers/skopeo#396]
When copying an image with something like:

skopeo copy --dest-tls-verify=true --dest-cert-dir=/etc/docker-distribution/registry docker://registry.access.redhat.com/openshift3/ose-pod:v3.6.173.0.5-2 docker://registry.example.com:5000/openshift3/ose-pod:v3.6.173.0.5-2

The output looks like:

Getting image source signatures
Copying blob sha256:d55ab3b04d8b1b93041514fd0cf77b95c52b4c6a51ee3b403d5bbaf1dbc12a1c
 67.78 MB / ? [---------------------------------------------------------------=]
 68.81 MB / ? [-----------------------------=---------------------------------] Copying blob sha256:b94f985aad49d8208054f5627b69dba26556628517313cb30ec620fa9d363787
 0 B / ? [--------------------------------------------------------------------=]
Copying blob sha256:2415f7f88d0df511ded4b1e3f33299823a42e94a1273e1403c48187fe9f9db4b
 70.53 MB / ? [---------------------------------------------------------------=]
Copying blob sha256:bfbf30eb4a820bfa20ddf28fba0ba09cac3d72cb66d0fc6e37da26a6f419132e
 112.52 MB / ? [-----------------------------------------------=--------------]
 113.27 MB / ? [--------=-----------------------------------------------------] Copying blob sha256:9fa798e1095cbbaf650f4bc8c65160108d86b15888b1aee34ab7e51a738afc98
 0 B / ? [--------------------------------------------------------------------=]
Copying config sha256:d013dee513e7cdc7d42a1db9315ef51f04661783cf52e0dd32f4e1fc426595ee
 0 B / 4.59 KB [---------------------------------------------------------------]
Writing manifest to image destination
Storing signatures

Notice the following issues:

- "Copying blob ..." does not start on new line
- No image total size printed (only "?") although alternatives like "docker pull" do that
- Download progress bar does not give any idea how much has been downloaded (perhaps due to previous "?")
- When pulling the same image several time (for example, due to issue [395](https://github.com/projectatomic/skopeo/issues/395)), the reported size of the download varies slightly for the same images

Please consider fixing / improving these. Thanks.

**Comment by mtrmac** [comment]
All good points, thanks.

**Comment by rhatdan** [comment]
Skopeo output has been improved.
