### ISSUE TITLE
RFE: Allow force anonymous inspect

### ISSUE THREAD

**Issue by juanluisvaladas** [containers/skopeo#421]
By default skopeo tries to use ~/.docker/config.json to authenticate to an external registry unless username and password are provided using --creds flag

It would be handy to allow to force no token to use skopeo as a debug tool

**Comment by TomSweeneyRedHat** [comment]
Would doing a 'docker logout' work to get you what you need?  That should clear the token, but obviously you'd need to re-login to re-establish it when you wanted to go live.  A "--nocreds" flag could be added I suppose to just not use any credentials/tokens.

**Comment by juanluisvaladas** [comment]
> Would doing a 'docker logout' work to get you what you need?
Yes, that works.

**Comment by mtrmac** [comment]
Right now, `HOME=/this/does/not/exist skopeo…` should prevent using `~/.docker*`; though that’s quite unintuitive.

Perhaps we could relax `--creds` to allow using `":"` (i.e. empty username and password) to switch of authentication.

Eventually, with https://github.com/containers/image/issues/345 , there would probably have to be an option to choose an authentication method; with that, allowing `none` as an option would be natural. But that will take some time to happen.

**Comment by rhatdan** [comment]
@juanluisvaladas @mtrmac @vrothberg Is this still an issue?  Are we still waiting for --no-creds?

**Comment by vrothberg** [comment]
I find this to be a useful extension. PR over here https://github.com/containers/skopeo/pull/433.
