### ISSUE TITLE
allow specifying credentials via environment variables

### ISSUE THREAD

**Issue by cyphar** [containers/skopeo#434]
At the moment there are only two ways of specifying credentials:

1. Through the command-line, which allows other users to see it through `/proc`.
2. Using the `--*-creds=abc` mode, supplying the credentials through `stdin`. This doesn't work for scenarios where `skopeo` is used as a script.

I propose we add `SKOPEO_SRC_CREDENTIALS=...` and `SKOPEO_DST_CREDENTIALS=...` (or whatever you think the name should be called) which allows you to specify credentials through the process environment.

**Comment by runcom** [comment]
I wouldn't be against this :)

**Comment by mtrmac** [comment]
Yes, we do need _something_ else than the two options above.

I’m a tiny bit worried about making things easy to understand, there are few other credential proposals arriving now and the number of ways to do things may be rising too quickly. Not a blocker by any means, just a reason to look for options :)

Another thing that could work is just to use a `docker login`-like config file.  Assuming, per https://github.com/kubernetes-incubator/cri-o/pull/1015 , that there will be an `--auth-file` or something like that, would that work for you? (To be fair, I don’t know whether the file would be created by `docker login`, `kpod login`, or generated in a new bit of code; either way, this is unlikely to be much easier for a simple shell script. But, just in case it were a better fit in your overall pipeline…)

**Comment by rhatdan** [comment]
I would like to look at this in grander scale.  We need to move beyond simple User Name/Password authentication and support at least Kerberos and SSHKeys.  So as we think about these things, maybe we should look at what ssh/scp does to handle these situations.

**Comment by cyphar** [comment]
`docker login` doesn't really fit for our pipeline (it's inside of OBS). But what could work is an `--auth-file` which could take plaintext passwords (which we could then use for different authentication modes -- such as the ones @rhatdan mentioned). `.ssh/id_*` is a workaround, but I wonder if we had a single file whether that would work better.

**Comment by mtrmac** [comment]
That `--auth-file` suggested above would be formatted like `~/.docker/config.json`, not quite convenient for generation in a script.

**Comment by rhatdan** [comment]
We would need to handle src-auth-file and dst-auth-file.  I would guess.

**Comment by mtrmac** [comment]
Not urgently; the auth file contains a hostname→(username, password) map, so the same file can be used for both source and destination at the same time.  `--*creds` only configure an username:password, so they need to be specific to source/destination.

(In some unlikely situations it could still be convenient to have separate auth files for source/destination, but the caller can always generate a new single-purpose auth file, it would not be strictly required.)

**Comment by rhatdan** [comment]
Excellent, excuse my ignorance.

**Comment by rhatdan** [comment]
@cyphar @mtrmac @vrothberg Is this still an issue?  Is this something we want to work on?

**Comment by vrothberg** [comment]
We don't support env vars yet. However, I am not sure if supporting that would be any better than the CLI options that already exists as another user could still see the credentials via `/proc/$pid/environ`.

Given the age, I am tempted to close but I leave that up to @cyphar and @mtrmac :)

**Comment by mtrmac** [comment]
We do support `podman login --authfile …` and `skopeo copy --authfile …` now. @cyphar is that good enough for your purposes?

**Comment by cyphar** [comment]
`--authfile` is sufficient. You should be able to use process substitution `<()` in order to avoid other users reading your authfile directly.

**Comment by PaulFurtado** [comment]
> We don't support env vars yet. However, I am not sure if supporting that would be any better than the CLI options that already exists as another user could still see the credentials via /proc/$pid/environ

@vrothberg while `/proc/$pid/environ` does allow other processes to read env vars, it's limited to processes that are allowed to ptrace the target process, whereas `/proc/$pid/cmdline` is readable by any other process by any user. So storing something in `/proc/$pid/environ` is about as secure as any file on disk secured via standard file permissions.

Additionally, things like auditd log command line arguments of processes so things that end up on the command line are often persisted forever in audit logs, tracing systems, etc which poses even more of a threat than existing on the command line temporarily.

Anyway, `--authfile` definitely works for me too, but just wanted to clarify that env vars are definitely more secure than command line args.

**Comment by ssbarnea** [comment]
Considering the the only way to add credentials to github-actions is to define environment variables. How are we supposed to to use skopeo to login to one registry or another when running github workflows?

**Comment by TomSweeneyRedHat** [comment]
@ssbarnea I may be too focused on my upcoming holiday, but can't you do `skopeo login --authfile={dir that github-actions sees}` then do `skopeo copy --authfile={dir that github-actions sees} ...`.  Or uglier, `skopeo copy --dest-creds username:password`?

**Comment by ssbarnea** [comment]
Yeah, I found few workarounds with stdin. They appear as ok for now. I will post a link once I have the confirmation.

**Comment by tyranron** [comment]
@ssbarnea actually, the `REGISTRY_AUTH_FILE` works like a charm for GitHub Actions, without a need to mess with CLI flags. See [the example](https://github.com/instrumentisto/rust-docker-image/blob/7ad547248ccd213149625c26d34c319f1c46cfa7/.github/workflows/nightly.yml).
