### ISSUE TITLE
building skopeo with golang go1.8.3 on illumos/OpenIndiana

### ISSUE THREAD

**Issue by olbohlen** [containers/skopeo#488]
Hi,

I was trying to build skopeo outside of a docker container on OpenIndiana hipster (based on illumos, OpenSolaris fork). I have go 1.8.3 here and I get this:

```
$ git clone https://github.com/projectatomic/skopeo $GOPATH/src/github.com/projectatomic/skopeo
Cloning into '/export/home/olbohlen/go/src/github.com/projectatomic/skopeo'...
remote: Counting objects: 10038, done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 10038 (delta 86), reused 131 (delta 55), pack-reused 9785
Receiving objects: 100% (10038/10038), 5.98 MiB | 1.07 MiB/s, done.
Resolving deltas: 100% (4912/4912), done.
$ cd $GOPATH/src/github.com/projectatomic/skopeo
$ PATH=/usr/gnu/bin:$PATH gmake binary-local
go build  -ldflags "-X main.gitCommit=c61482d2cfd29c5774a9373af287ecc6757204ce" -gcflags "" -tags "btrfs_noversion libdm_no_deferred_remove " -o skopeo ./cmd/skopeo
# github.com/projectatomic/skopeo/vendor/github.com/mtrmac/gpgme
could not determine kind of name for C.gpgme_err_set_errno
# github.com/projectatomic/skopeo/vendor/github.com/containers/storage
vendor/github.com/containers/storage/lockfile_unix.go:28: cannot use lockfile literal (type *lockfile) as type Locker in return argument:
        *lockfile does not implement Locker (missing TouchedSince method)
vendor/github.com/containers/storage/lockfile_unix.go:30: cannot use lockfile literal (type *lockfile) as type Locker in return argument:
        *lockfile does not implement Locker (missing TouchedSince method)
gmake: *** [Makefile:78: binary-local] Error 2

```
unfortunately my go skills are quite limited ;) so I do not really get the point what's going on here.
Hopefully you can help.

Cheers,

Olaf

**Comment by mtrmac** [comment]
Thanks for your report.

As for `C.gpgme_err_set_errno`, either install `gpgme` with its development headers (and make it available through `pkg-config`), or opt out using the `containers_image_openpgp` build tag.

The `vendor/github.com/containers/storage/lockfile_unix.go` errors are real bugs (Cc: @nalind ), if you don’t need the storage backend, you can opt out using the `containers_image_storage_stub` build tag.

In both cases, see `Makefile` for how Go build tags can be applied.

(Maybe the `Makefile` could be improved to autodetect the relevant OS variants, like it autodetects macOS.)

But, overall, it’s unlikely that `skopeo` will work, and keep working over time, on any Solaris variant by default unless someone is interested in working on that, and in keeping it working.

**Comment by rhatdan** [comment]
@olbohlen If you are interested in working on this please reopen the issue.
