### ISSUE TITLE
skopeo search command

### ISSUE THREAD

**Issue by thomasmckay** [containers/skopeo#508]
I'd like to see _skopeo search_ command implemented for use against registries that still continue to support the _/v1/search_ route.

**Comment by thomasmckay** [comment]
@mtrmac - From a user point of view I'd prefer to position skopeo as the drop-in replacement for docker command line tool. Is that not the intent of skopeo?

**Comment by mtrmac** [comment]
No, skopeo is a fairly low-level front-end to containers/image.  If you want a drop-in replacement, that’s precisely the intent of `podman`.

**Comment by thomasmckay** [comment]
Well then, let me give podman a spin.

**Comment by thomasmckay** [comment]
I am specifically using the "skopeo copy" functionality to save images to disk (for disconnected setup) as well as from registry-to-registry directly. Is there equivalent of these in podman?

**Comment by thomasmckay** [comment]
Then I'll leave this feature request up to you to open or close. It would be useful when _skopeo copy_ things around to be able to search source and destination registries. I'd be in favor or implementing here.

Thanks for the pointer to _podman_, I'll be using that going forward for my integration testing.

**Comment by mtrmac** [comment]
I do think it makes sense to expose this in `skopeo`; OTOH with `podman search` available, it is not likely to be a priority; a PR would help make this happen.

**Comment by thomasmckay** [comment]
https://github.com/projectatomic/skopeo#todo ;) Funny.

If I ever manage to get a go debug environment set up (breakpoints, etc.), I may try to give this a shot myself. Probably far down my list of priority vs. hours in the day.

**Comment by rhatdan** [comment]
@thomasmckay Are you still interested in this?  Or is podman search good enough?

**Comment by thomasmckay** [comment]
@rhatdan `podman search` is fine with me; closing. Thanks!
