### ISSUE TITLE
Add configuration option for compression level

### ISSUE THREAD

**Issue by jethrogb** [containers/skopeo#517]
Currently, compression during copying uses the default compression level. When pushing to a registry on my LAN I don't need compression, so I'd like to set `gzip.NoCompression` instead (I have a local fork that hardcodes this). Other people might want to set `gzip.BestCompression`.

**Comment by rhatdan** [comment]
Please open a PR to do this, if you have a local patch?

**Comment by rhatdan** [comment]
@runcom @mtrmac What do you guys think of this idea?

**Comment by rhatdan** [comment]
@mtrmac @vrothberg Should we assign this to an intern?

**Comment by vrothberg** [comment]
Sounds good to me :+1:

**Comment by mtrmac** [comment]
There is now `--dest-compress-format` and `--dest-compress-level`.
