### ISSUE TITLE
docker pull fails with unexpected end of JSON input

### ISSUE THREAD

**Issue by ipanova** [containers/skopeo#526]
Output of:
skopeo copy --format v2s1 docker://busybox:glibc dir:existingemptydirectory
was tared uploaded to Pulp, published which enables to serve the content as of from docker registry.

docker pull fails with:
```
$ docker pull localhost:1234/centos3@sha256:783f7f77b803b74c2f4cf0d61cc27ec404b6896f285106ed0a61ddff37e79833
Trying to pull repository localhost:1234/centos3 ... 
unexpected end of JSON input
```

docker pull from output of skopeo copy --format v2s2 works as supposed:
```
$ docker pull localhost:1234/centos3@sha256:8f89c289ef2f88176cacc1f27459e9b9692d4505ccc2de11ecf70cb6ff302ec6
Trying to pull repository localhost:1234/centos3 ... 
sha256:8f89c289ef2f88176cacc1f27459e9b9692d4505ccc2de11ecf70cb6ff302ec6: Pulling from localhost:1234/centos3
ea1582e210d3: Already exists 
Digest: sha256:8f89c289ef2f88176cacc1f27459e9b9692d4505ccc2de11ecf70cb6ff302ec6
Status: Image is up to date for localhost:1234/centos3@sha256:8f89c289ef2f88176cacc1f27459e9b9692d4505ccc2de11ecf70cb6ff302ec6
```

Docker pull from content synced directly from the docker registry also works as expected.

Versions:
$ rpm -qa |grep skopeo
skopeo-0.1.31-5.git0144aa8.fc28.x86_64
[ipanova@ina pulp_docker]$ rpm -qa |grep docker
docker-rhel-push-plugin-1.13.1-60.git9cb56fd.fc28.x86_64
docker-1.13.1-60.git9cb56fd.fc28.x86_64
docker-common-1.13.1-60.git9cb56fd.fc28.x86_64

**Comment by mtrmac** [comment]
Thanks for your report.

It’s not obvious to me that `skopeo` is the cause here when the data is being served by Pulp. (I’m not saying it isn’t `skopeo`’s fault, just that the description above does not say either way.)

At the very least, does `skopeo inspect $registry/$image`, and `skopeo copy docker://$registry/$image dir:temp-dest` work or fail? Is the image in `dir:temp-dest` and the original `dir:existingemptydirectory` exactly the same, or modified, and if modified, how?

Or, perhaps, is there a way I can reproduce this, maybe by running a few containers, without having to understand much of Pulp?

FWIW, this seems to work fine:
```console
$ sudo docker run -d -p 5000:5000 --name registry registry:latest
$  ./skopeo copy --format v2s1 docker://busybox:glibc dir:d1
$  ./skopeo copy --dest-tls-verify=false dir:d1 docker://localhost:5000/v2s1
$  sudo docker pull localhost:5000/v2s1
$  ./skopeo copy --src-tls-verify=false docker://localhost:5000/v2s1 dir:d2
$  diff -urN d1 d2
# Only differs in manifest
$  diff -u <(python -mjson.tool d1/manifest.json ) <(python -mjson.tool d2/manifest.json )
# Manifest differences: "name" and "tag" defined to "v2s1" and "latest", a different signature
```

**Comment by ipanova** [comment]
skopeo inspect and copy commands do work.
I am not sure how to reproduce this outside of pulp env, but couple of things i noticed:
1) docker pull of v2s2 works without problem
2)this is the diff of the manifest v2s2 of busybox:glibc from skopeo copy using dir transport and API response from the registry:
```
diff -u <(python -m json.tool /home/ipanova/myprojects/tips/man-registryv2s2.json) <(python -m json.tool d2/manifest.json)
[ipanova@ina pulp_docker]$ 
```
Meanwhile:

1) the problem with docker pull occurs just with v2s1 ( only from output from skopeo copy)
2) this is the diff of the manifest v2s1 of busybox:glibc from skopeo copy output and API response from the registry:
```
[ipanova@ina pulp_docker]$ diff -u <(python -m json.tool /home/ipanova/myprojects/tips/man-registry.json) <(python -m json.tool d1/manifest.json)
--- /dev/fd/63	2018-07-24 11:25:12.045104331 +0200
+++ /dev/fd/62	2018-07-24 11:25:12.045104331 +0200
@@ -16,7 +16,7 @@
             "v1Compatibility": "{\"id\":\"008bded6a3286e7b75d718c9f5983b1e4e44bf96f3462e1545fdbae180caec51\",\"created\":\"2018-07-16T22:20:09.382008803Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:391cd1ea45bd9af6cf7bee7aace7a1672ec93504fec7f7264f4a3981650c485c in / \"]}}"
         }
     ],
-    "name": "library/busybox",
+    "name": "",
     "schemaVersion": 1,
     "signatures": [
         {
@@ -24,15 +24,15 @@
                 "alg": "ES256",
                 "jwk": {
                     "crv": "P-256",
-                    "kid": "HEFO:JL7C:NOTP:ASFW:RU75:OFXL:HH6K:DHL5:LVUS:TP2M:OMZT:7R25",
+                    "kid": "XW2A:Q4F7:4L5V:53LA:IMBI:ENK2:A5FE:SJV6:VQUT:EAYH:QT46:RN3T",
                     "kty": "EC",
-                    "x": "ZdTjb6IlTTAOK08RAmK6A_DjdiS-ztQBC4l_SOaJT5E",
-                    "y": "XBkjxqsNDjRbMB5yXOIyw3QWfIibs3ZDidxc0EsUGXI"
+                    "x": "t_UtdXh6LRukU7KiygrfXLy4TSdWpDELJGoMKUQI3nc",
+                    "y": "Ezz1JfFARN01hat3-t_jqNo-yWItICT8Sv_ZG4gudok"
                 }
             },
-            "protected": "eyJmb3JtYXRMZW5ndGgiOjIxMzEsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxOC0wNy0yNFQwOToxODowMFoifQ",
-            "signature": "wQq-nWfqHI3Ku3WPy3MJYJ4gZIxfVNl-Xg3o1c-nGY_VVvv03SlT29Vw1Gp8GvivqGgmhy45ipiL2Z2uxqmU4A"
+            "protected": "eyJmb3JtYXRMZW5ndGgiOjE5NzMsImZvcm1hdFRhaWwiOiJmUSIsInRpbWUiOiIyMDE4LTA3LTI0VDA4OjU0OjU4WiJ9",
+            "signature": "AwP3soAQCiKZvPge90zXvbfS-rsvWwFA_0c8PZwz0hesxD9GZccGhEUjjjD6UPT8M1jJRvRux1dPnqvTlg8XWg"
         }
     ],
-    "tag": "glibc"
+    "tag": ""
 }
```
I understand that signature is different, but tag and name from skopeo copy output is set to empty string.
A side note, pulp does not modify the json which it receives whether from skopeo copy or via direct api requests to the registry, it serves the files as they were received.
i found this one maybe it is related https://stackoverflow.com/questions/27994327/golang-json-unmarshal-unexpected-end-of-json-input

Let me know what other information will help you to narrow down the root cause. Thank you.

**Comment by ipanova** [comment]
json files:
```
$ curl file:///d2/manifest.json 
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1497,
      "digest": "sha256:0b09e1ac1503c9be0db96323bb369daabad3b51982975f15eafca4a6c227746d"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 2399919,
         "digest": "sha256:ea1582e210d3ab24de2f23a432e01474752c751a1826952a389800388836e726"
      }
   ]
}
$ curl file:///d1/manifest.json 
{"name":"library/busybox","tag":"glibc","architecture":"amd64","fsLayers":[{"blobSum":"sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"},{"blobSum":"sha256:ea1582e210d3ab24de2f23a432e01474752c751a1826952a389800388836e726"}],"history":[{"v1Compatibility":"{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"ArgsEscaped\":true,\"Image\":\"sha256:3e6b9fe110329ce78e1aa1953e2e61e044e7ecda1e30be51b816e9cd50aeba92\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"54afe8f1fa22470eb366346cd4b57a2f69060c5a03ddab5351c09ef0d8102643\",\"container_config\":{\"Hostname\":\"54afe8f1fa22\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"sh\\\"]\"],\"ArgsEscaped\":true,\"Image\":\"sha256:3e6b9fe110329ce78e1aa1953e2e61e044e7ecda1e30be51b816e9cd50aeba92\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2018-07-16T22:20:09.616344496Z\",\"docker_version\":\"17.06.2-ce\",\"id\":\"123dd400d6de5ed38739fdf3c9563359df7f5b3684411e4d77759a66f7446ed1\",\"os\":\"linux\",\"parent\":\"008bded6a3286e7b75d718c9f5983b1e4e44bf96f3462e1545fdbae180caec51\",\"throwaway\":true}"},{"v1Compatibility":"{\"id\":\"008bded6a3286e7b75d718c9f5983b1e4e44bf96f3462e1545fdbae180caec51\",\"created\":\"2018-07-16T22:20:09.382008803Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:391cd1ea45bd9af6cf7bee7aace7a1672ec93504fec7f7264f4a3981650c485c in / \"]}}"}],"schemaVersion":1,"signatures":[{"header":{"jwk":{"crv":"P-256","kid":"XW2A:Q4F7:4L5V:53LA:IMBI:ENK2:A5FE:SJV6:VQUT:EAYH:QT46:RN3T","kty":"EC","x":"t_UtdXh6LRukU7KiygrfXLy4TSdWpDELJGoMKUQI3nc","y":"Ezz1JfFARN01hat3-t_jqNo-yWItICT8Sv_ZG4gudok"},"alg":"ES256"},"signature":"AwP3soAQCiKZvPge90zXvbfS-rsvWwFA_0c8PZwz0hesxD9GZccGhEUjjjD6UPT8M1jJRvRux1dPnqvTlg8XWg","protected":"eyJmb3JtYXRMZW5ndGgiOjE5NzMsImZvcm1hdFRhaWwiOiJmUSIsInRpbWUiOiIyMDE4LTA3LTI0VDA4OjU0OjU4WiJ9"}]}

$ curl file://manifest-registry.json
{
  "schemaVersion": 1,
  "name": "library/busybox",
  "tag": "glibc",
  "architecture": "amd64",
  "fsLayers": [
    {
      "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
    },
    {
      "blobSum": "sha256:ea1582e210d3ab24de2f23a432e01474752c751a1826952a389800388836e726"
    }
  ],
  "history": [
    {
      "v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"ArgsEscaped\":true,\"Image\":\"sha256:3e6b9fe110329ce78e1aa1953e2e61e044e7ecda1e30be51b816e9cd50aeba92\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"54afe8f1fa22470eb366346cd4b57a2f69060c5a03ddab5351c09ef0d8102643\",\"container_config\":{\"Hostname\":\"54afe8f1fa22\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"sh\\\"]\"],\"ArgsEscaped\":true,\"Image\":\"sha256:3e6b9fe110329ce78e1aa1953e2e61e044e7ecda1e30be51b816e9cd50aeba92\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2018-07-16T22:20:09.616344496Z\",\"docker_version\":\"17.06.2-ce\",\"id\":\"123dd400d6de5ed38739fdf3c9563359df7f5b3684411e4d77759a66f7446ed1\",\"os\":\"linux\",\"parent\":\"008bded6a3286e7b75d718c9f5983b1e4e44bf96f3462e1545fdbae180caec51\",\"throwaway\":true}"
    },
    {
      "v1Compatibility": "{\"id\":\"008bded6a3286e7b75d718c9f5983b1e4e44bf96f3462e1545fdbae180caec51\",\"created\":\"2018-07-16T22:20:09.382008803Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:391cd1ea45bd9af6cf7bee7aace7a1672ec93504fec7f7264f4a3981650c485c in / \"]}}"
    }
  ],
  "signatures": [
    {
      "header": {
        "jwk": {
          "crv": "P-256",
          "kid": "HEFO:JL7C:NOTP:ASFW:RU75:OFXL:HH6K:DHL5:LVUS:TP2M:OMZT:7R25",
          "kty": "EC",
          "x": "ZdTjb6IlTTAOK08RAmK6A_DjdiS-ztQBC4l_SOaJT5E",
          "y": "XBkjxqsNDjRbMB5yXOIyw3QWfIibs3ZDidxc0EsUGXI"
        },
        "alg": "ES256"
      },
      "signature": "wQq-nWfqHI3Ku3WPy3MJYJ4gZIxfVNl-Xg3o1c-nGY_VVvv03SlT29Vw1Gp8GvivqGgmhy45ipiL2Z2uxqmU4A",
      "protected": "eyJmb3JtYXRMZW5ndGgiOjIxMzEsImZvcm1hdFRhaWwiOiJDbjAiLCJ0aW1lIjoiMjAxOC0wNy0yNFQwOToxODowMFoifQ"
    }
  ]
}

```

**Comment by mtrmac** [comment]
> this is the diff of the manifest v2s1 of busybox:glibc from skopeo copy output and API response from the registry:

(Does “API response from the registry” mean Docker Hub or Pulp? The `manifest-registry.json` file is pretty-printed, and `skopeo` does not do that.)

> I understand that signature is different, but tag and name from skopeo copy output is set to empty string.

A “signature” is randomly regenerated by `skopeo` on every update to the manifest, so it is expected to differ.  Do I understand correctly that the first file is from the Pulp registry server (or, maybe, the Docker Hub server?) and the second one is from a `skopeo copy … dir:…`? That seems right — the copy to `dir:` while converting from `v2s2` to `v2s1` sets these fields to empty, because there is no name/tag that corresponds to a `dir:` destination.  The _second_ `skopeo copy dir:… docker://…` into the registry then adds the name/tag values appropriate for the destination.

So, all of that seems about right.

> A side note, pulp does not modify the json which it receives whether from skopeo copy or via direct api requests to the registry, it serves the files as they were received.

To clarify, is Pulp receiving content by copying the files from `skopeo copy $source dir:…` unmodified, (i.e. with _empty_ name/tag), or is there a second `skopeo copy dir:… $pulp` that adds the name/tag values? (Or is there yet another process that updates these values?)

[AFAIK, recent versions of Docker ignore the name/tag values, so that shouldn’t matter. But if the served values were incorrect, it might be a lead to follow.]

---

> Let me know what other information will help you to narrow down the root cause. Thank you.

Without a reproducer, I don’t know that I can help much more.

As a _very wild_ guess, it might be worth verifying the `Content-Type` and `Content-Length` headers returned in the registry’s manifest response. But I don’t have any reason to suspect they are wrong.

The methodical approach to debugging this would be to track down the exact place within `dockerd` where the error originates (anywhere within the call hierarchy starting at `projectatomic/docker/api/server/router/image.imageRouter.postImagesCreate`, if we are lucky, somewhere around `projectatomic/docker/distribution.v2Puller.pullV2Tag`). I can’t very well do that if I don’t have a way to reproduce the failure; could you take a look?

**Comment by thomasmckay** [comment]
I built _projectatomic/docker_ and begin putting in prints (_logrus.Errorf()_) to see what was happening. Unfortunately I couldn't seem to get anything to print at the one match for the error here https://github.com/projectatomic/docker/blob/master/vendor/src/github.com/docker/go/canonical/json/scanner.go#L167 . I don't know where the problem may lie but believe it is probably _docker pull_ expecting some crumb of detail in either the content or the response details. I can't rule out _pulp_ but it would be helpful to be able to debug further down the stack to see what the json that is being parsed actually is.

The debug statements built in look like this:
```
DEBU[0009] Calling POST /v1.25/images/create?fromImage=devel.example.com%3A5000%2Fexamplecorp-builds-jenkins_builds&tag=glibc-v2s1 
DEBU[0009] hostDir: /etc/docker/certs.d/devel.example.com:5000 
DEBU[0009] hostDir: /etc/docker/certs.d/devel.example.com:5000 
DEBU[0009] Trying to pull devel.example.com:5000/examplecorp-builds-jenkins_builds from https://devel.example.com:5000 v2 
ERRO[0009] Error trying v2 registry: unexpected end of JSON input 
ERRO[0009] Attempting next endpoint for pull after error: unexpected end of JSON input 
DEBU[0009] Skipping v1 endpoint https://devel.example.com:5000 because v2 registry was detected 
ERRO[0009] Handler for POST /v1.25/images/create returned error: unexpected end of JSON input 
```

**Comment by mtrmac** [comment]
> Unfortunately I couldn't seem to get anything to print at the one match for the error here https://github.com/projectatomic/docker/blob/master/vendor/src/github.com/docker/go/canonical/json/scanner.go#L167 

The other one is probably in the standard library package `encoding/json`.  Adding a debug print there may be painful — unless there’s some trick to it, it could require patching `golang` itself.

> `ERRO[0009] Error trying v2 registry: unexpected end of JSON input`

OK, that localizes the root cause to `distribution/pull_v2.go:v2Puller.pullV2Repository` and the things it calls, ruling out most of the daemon.  Worst case, you could just sprinkle debug statements on every other line of that and follow the code flow.

**Comment by thomasmckay** [comment]
Sorry, I meant to include the last line I can figure out how to put debug statements around: https://github.com/projectatomic/docker/blob/master/distribution/pull_v2.go#L340 . I don't know how to go any lower than that. Prints around _scanner.go_ link above don't print, as I mentioned.

**Comment by mtrmac** [comment]
> Sorry, I meant to include the last line I can figure out how to put debug statements around: https://github.com/projectatomic/docker/blob/master/distribution/pull_v2.go#L340 . I don't know how to go any lower than that.

That’s probably https://github.com/projectatomic/docker/blob/bc0ab34be933e29e84fa87aecb97b56106c2e4cd/vendor/github.com/docker/distribution/registry/client/repository.go#L418 .

AFAICS either the reported status is a failure, and JSON is parsed in https://github.com/projectatomic/docker/blob/bc0ab34be933e29e84fa87aecb97b56106c2e4cd/vendor/github.com/docker/distribution/registry/client/errors.go#L41 ;

Or, on success, https://github.com/projectatomic/docker/blob/bc0ab34be933e29e84fa87aecb97b56106c2e4cd/vendor/github.com/docker/distribution/manifests.go#L94 , which _should_ end up with https://github.com/projectatomic/docker/blob/bc0ab34be933e29e84fa87aecb97b56106c2e4cd/vendor/github.com/docker/distribution/manifest/schema1/manifest.go#L32 if this is indeed schema1, _and_ the `Content-Type` header is correct (is it?).

**Comment by thomasmckay** [comment]
@mtrmac - I'll debug. I know the Content-Length is correct but need to double check on Content-Type (@ipanova maybe you can confirm and test that separately)

**Comment by mtrmac** [comment]
@thomasmckay Or maybe capture the full request and response by wrapping 	https://github.com/projectatomic/docker/blob/bc0ab34be933e29e84fa87aecb97b56106c2e4cd/vendor/github.com/docker/distribution/registry/client/repository.go#L469 with `httputil.Dump*`, like https://github.com/mtrmac/image/commit/8f753285ef7f1a2defa19a8fd69f54dd4b78a802 does with other code, but with `true` as the `body` parameter to `Dump*`, to let everyone see the same data.

**Comment by thomasmckay** [comment]
@mtrmac - I'll try that.

My debug with httputil.Dump:
```
GET /v2/examplecorp-builds-jenkins_builds/manifests/glibc-v2s1 HTTP/1.1
Host: devel.example.com:5000
User-Agent: Go-http-client/1.1
Accept: application/vnd.docker.distribution.manifest.list.v2+json
Accept: application/vnd.docker.distribution.manifest.v1+prettyjws
Accept: application/json
Accept: application/vnd.docker.distribution.manifest.v2+json
Accept-Encoding: gzip
```

My debug just after this line: https://github.com/projectatomic/docker/blob/master/vendor/src/github.com/docker/distribution/registry/client/repository.go#L490
```
ERRO[0009] XXXXXXXXXX repository.Get() N.6 body={"signatures": [{"header": {"alg": "ES256", "jwk": {"y": "PFrqe4zyMcS2B4FrX7Gtdb5Mjm4DV5V0Ge-Aa6qA4wM", "x": "j0gkRYlw-DAfSmsRCbC1UzjkT9FwNgnH2t250PyNGsw", "crv": "P-256", "kty": "EC", "kid": "SCT5:DTIT:HAX5:5PEC:VQZS:UJXY:J5QQ:5GXF:EEEK:GRQH:FOVD:72MU"}}, "protected": "eyJmb3JtYXRMZW5ndGgiOjE5NzMsImZvcm1hdFRhaWwiOiJmUSIsInRpbWUiOiIyMDE4LTA4LTA4VDE1OjM4OjI0WiJ9", "signature": "yaa_lMs95Xqt-E42Wg-Qo26FOkvRmfJud9FHnIS3h5O81knKBBVVtghNUI6L3bYl0bjZ9JP3igTJACR8Xni3aQ"}], "name": "", "tag": "", "architecture": "amd64", "fsLayers": [{"blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"}, {"blobSum": "sha256:36821101d012523a08f96da625c0627f4b925826e8ee2db19068581e1576b952"}], "schemaVersion": 1, "history": [{"v1Compatibility": "{\"architecture\":\"amd64\",\"config\":{\"Hostname\":\"\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"sh\"],\"ArgsEscaped\":true,\"Image\":\"sha256:a28bb2eca0873d4da914553a6a2edcd9ff527d74ea93043a8b5719816d07579f\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null},\"container\":\"0a4eee1464d16f124729fb24f6c1a7039d6b261bb2b5a325ef74a8cf0dd8725a\",\"container_config\":{\"Hostname\":\"0a4eee1464d1\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\"],\"Cmd\":[\"/bin/sh\",\"-c\",\"#(nop) \",\"CMD [\\\"sh\\\"]\"],\"ArgsEscaped\":true,\"Image\":\"sha256:a28bb2eca0873d4da914553a6a2edcd9ff527d74ea93043a8b5719816d07579f\",\"Volumes\":null,\"WorkingDir\":\"\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":{}},\"created\":\"2018-07-31T22:20:40.734830289Z\",\"docker_version\":\"17.06.2-ce\",\"id\":\"552f757ccf0e9d41b5fed2ae7e2c60380cce59796981f2a4d4daf92d306a9910\",\"os\":\"linux\",\"parent\":\"a7aaeaceba14caba7868d7207e26a7c3c943e064c3af1eae6ecfda32ff772118\",\"throwaway\":true}"}, {"v1Compatibility": "{\"id\":\"a7aaeaceba14caba7868d7207e26a7c3c943e064c3af1eae6ecfda32ff772118\",\"created\":\"2018-07-31T22:20:40.449929617Z\",\"container_config\":{\"Cmd\":[\"/bin/sh -c #(nop) ADD file:a9990867921d579eed0d8d13748f58663a1c79ea4e0ba4bbbde28f7b16d7af13 in / \"]}}"}]} 
```

**Comment by ipanova** [comment]
@thomasmckay thanks a lot for debugging and looking into this.
@mtrmac thanks for the explanation in https://github.com/containers/skopeo/issues/526#issuecomment-411901330 i am closing this issue since skopeo has nothing to do with the current traceback
