### ISSUE TITLE
Allow supplying credentials with colons in usernames

### ISSUE THREAD

**Issue by grdryn** [containers/skopeo#527]
I'm trying to use `skopeo` in a Jenkins pipeline on OpenShift, and copy an image from the built-in registry (using credentials for a ServiceAccount) to an external registry, but I get the following error saying there's an invalid username/password:

```
skopeo --debug copy --src-tls-verify=false --dest-creds null --src-creds system:serviceaccount:mini:jenkins:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtaW5pIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4tYnN4c3MiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjNkM2FkYTNjLThkZmItMTFlOC1iYTJhLTUyNTQwMDQyYTE3OSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptaW5pOmplbmtpbnMifQ.flrhs9eBOuYj0n7uDy4XSogxkZEkOrbO_lycQhYS41rTilUUXxCFbF6XIBBA3J2LFOcdbHmdJjKnSIf6pKu82LLbep3UwzKhYD4pCdRsYjovPzKCGScWu8MxURQrV-P_jEO6vhF4Iq4XvkJZsqVnccemhZsYU3gEx41z5PyrKST7kRyv4TYijAO-9a4CQBtXBnkzbiR4RZ-FtOix2SUlvHzdRS3ONVcN4CSasSWtV5QQoVdsahgSai48wM-mkZcMfDLXeqBmNacw4zGfpKn8cHk0PjFF81YPMWZoApWf4w8QYQ8Le2DUIdwtFrXQOxRsxU3CKh-A4wBBMb0tUb67TQ docker://docker-registry-default.192.168.42.213.nip.io/my/image:latest docker://extregistry.io/me/myimage/tag/grdryn-22
time="2018-07-23T16:16:02Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration" 
time="2018-07-23T16:16:02Z" level=debug msg=" Using "default-docker" configuration" 
time="2018-07-23T16:16:02Z" level=debug msg="  Using file:///var/lib/atomic/sigstore" 
time="2018-07-23T16:16:02Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/extregistry.io" 
time="2018-07-23T16:16:02Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration" 
time="2018-07-23T16:16:02Z" level=debug msg=" Using "default-docker" configuration" 
time="2018-07-23T16:16:02Z" level=debug msg=" No signature storage configuration found for docker-registry-default.192.168.42.213.nip.io/my/image:latest" 
time="2018-07-23T16:16:02Z" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/docker-registry-default.192.168.42.213.nip.io" 
time="2018-07-23T16:16:02Z" level=debug msg="GET https://docker-registry-default.192.168.42.213.nip.io/v2/" 
time="2018-07-23T16:16:02Z" level=debug msg="Ping https://docker-registry-default.192.168.42.213.nip.io/v2/ err <nil>" 
time="2018-07-23T16:16:02Z" level=debug msg="Ping https://docker-registry-default.192.168.42.213.nip.io/v2/ status 401" 
time="2018-07-23T16:16:02Z" level=fatal msg="Error determining manifest MIME type for docker://docker-registry-default.192.168.42.213.nip.io/my/image:latest: unable to retrieve auth token: invalid username/password" 
```

My _guess_ is that this is due to the username passed to `--src-creds` is `system:serviceaccount:mini:jenkins`, and the password being a long token. I can't imagine how it would know which colon to separate on (I guess the password part could more commonly contain a colon, so I guess it splits on the first?). Is there a way to make this work, like escape it or something? Or should I instead be using `--authfile` for such a case?

**Comment by mtrmac** [comment]
Thanks for your report.  Yes, this splits on the first colon, and there is no escaping. (This somewhat mirrors long-standing UNIX practice, where the format of `/etc/passwd` makes it impossible to have usernames with colons, so colon is the ideal separator; compare `chown(1)`.)

`--authfile` should work.

Alternatively, adding separate user name / password options (with password optional, but only possible with an user name specified), would make sense to me. (@runcom ?). PR’s are welcome :)

**Comment by grdryn** [comment]
Thanks for the response @mtrmac. I got an alternative solution from @bparees here: https://github.com/openshift/jenkins/issues/632#issuecomment-407121402

I've tested this with `skopeo` and it works as described: even though the user would be `system:serviceaccount:mini:jenkins` if I do `oc whoami`, I can set it to anything before the colon separator  in `--src-creds` or `--dest-creds`, because it's using a token rather than a password after the colon (at least that's my understanding of what's going on).

I'll leave this issue to you to do with as you please -- maybe it's useful to you if you still think there are other situations where it would be useful to have separate options for username and password?

**Comment by rhatdan** [comment]
@mtrmac @vrothberg, Is this something valuable to work on?  Should we look to an intern to do it?

**Comment by mtrmac** [comment]
“I do think there is some value in implementing that”, but I expect an intern could work on something more impactful. _Maybe_ as a first issue to familiarize with GitHub + Go + the CLI framework.

**Comment by lsm5** [comment]
are we still looking to have this in?

**Comment by mtrmac** [comment]
If someone cares to prepare a PR, sure, why not. OTOH it’s not something I’m likely to work on myself.

**Comment by jaikiran** [comment]
I've opened https://github.com/containers/skopeo/pull/1470 with the proposed changes.
