### ISSUE TITLE
skopeo copy containers-storage:... docker:... should deduplicate layers

### ISSUE THREAD

**Issue by steveb** [containers/skopeo#532]
This issue is intended to track deduplication for copying containers-storage->registry, which is a more specific case for the general RFE #395. My hope is that the required compressed and uncompressed hashes are available in containers-storage to enable deduplication for the same image, and for images which share layers.

**Steps to reproduce the issue:**

1. Install and run docker-distribution locally:
```
dnf install docker-distribution
systemctl start docker-distribution
```

3. Copy in some multi-layer images which have common layers:
```
skopeo copy docker://docker.io/tripleomaster/centos-binary-heat-engine:current-tripleo containers-storage:docker.io/tripleomaster/centos-binary-heat-engine:current-tripleo
skopeo copy docker://docker.io/tripleomaster/centos-binary-heat-api:current-tripleo containers-storage:docker.io/tripleomaster/centos-binary-heat-api:current-tripleo

```

4. Push to the local repository (duplicate copy is deliberate)
```
skopeo copy --dest-tls-verify=false containers-storage:tripleomaster/centos-binary-heat-api:current-tripleo docker://localhost:5000/tripleomaster/centos-binary-heat-api:current-tripleo
skopeo copy --dest-tls-verify=false containers-storage:tripleomaster/centos-binary-heat-api:current-tripleo docker://localhost:5000/tripleomaster/centos-binary-heat-api:current-tripleo
skopeo copy --dest-tls-verify=false containers-storage:tripleomaster/centos-binary-heat-engine:current-tripleo docker://localhost:5000/tripleomaster/centos-binary-heat-engine:current-tripleo
```

**Describe the results you received:**
Every layer was pushed again each time "skopeo copy" was run

**Describe the results you expected:**
The second push of centos-binary-heat-api should have skipped pushing every layer. The copy of centos-binary-heat-engine should have skipped most layers, just like it did for copying from docker.io to containers-storage

**Comment by mtrmac** [comment]
The general case is, I guess https://github.com/containers/image/issues/475 : we need to record a mapping between DiffIDs, compressed layer digests, _and their locations_.

containers/storage does record compressed layer digests, but not the locations; so we don’t know whether the layer is available in the repository (and can be reused directly), somewhere else on the same registry (and can be mounted), or on an entirely different server.

It would be, in principle, possible to use the data anyway, and just hope that the digests apply to the current repository directly, but that’s pretty likely to be wasteful.  I’d rather implement (only) recording and usage of the full mapping.

**Comment by steveb** [comment]
For the simple case of copying the same image twice, isn't there a much simpler fix of doing a HEAD call and only copying the layer if the response is a 404?

**Comment by steveb** [comment]
OK, reading the code and watching skopeo copy --debug I see it is doing a HasBlob check, but for different hashes, which I think means the remote layer is compressed and the local one is uncompressed, so the hashes differ. This sounds like 2. which you mentioned in https://github.com/projectatomic/libpod/issues/1233#issuecomment-411569730

Does this mean HasBlob can be called *again* after "Compressing blob on the fly" but before pushing the layer? We'll have the time penalty of compressing, but not of the network transfer.

**Comment by steveb** [comment]
Never mind, I see now how the computedDigest is extracted after the upload

**Comment by mtrmac** [comment]
> Does this mean HasBlob can be called again after "Compressing blob on the fly" but before pushing the layer? We'll have the time penalty of compressing, but not of the network transfer.

Currently the compression and the upload happen in parallel.  We could, in principle, do them serially, to make such a check possible — but that would make the ”layer not present” case slower, because it would have to take extra time to do the upload afterwards, and there would be an extra disk write+read.

https://github.com/containers/image/issues/475#issuecomment-403939228 shows that for compression and writing _to a local disk_, the compression is surprisingly slow, _by far_ the most time-consuming part.  I haven’t seen a thorough benchmark of what this looks like when writing to remote `docker://` destinations, but I wouldn’t be surprised if the compression time dominated the overall time in such cases as well.

**Comment by giuseppe** [comment]
> `[Don't copy duplicate layers from containers-storage to compressed tar…](/steveb/image/commit/71b31cb9ac2f1eb2cd16205dad940223e0418aa4) `

@steveb are you still using these patches  Would it be worth to open a PR and discuss them for upstream inclusion?

**Comment by mtrmac** [comment]
The caching of compressed/uncompressed relationship mapping, and remote locations, has been implemented in https://github.com/containers/image/pull/536 ; in the original test case, the second push now completes immediately and the third one only copies the few differing layers.
