### ISSUE TITLE
IdentityToken doesn't seem to work for auth

### ISSUE THREAD

**Issue by duglin** [containers/skopeo#533]
Does Skopeo support IdentityToken auth when copying to a destination registry? I can get it to work with userid/password but using a token seems to always be rejected. I can have the docker cmd line talk to the registry just fine so I think the ~/.docker/config.json file is ok - so I'm wondering if skopeo supports it.

**Comment by mtrmac** [comment]
Probably not; what is an “IdentityToken auth”, and where it is documented? Google can find only a little-documented Engine API field, and a vague mention in  config.json supposedly only relevant to credential helpers(?!).

**Comment by duglin** [comment]
Yep, docs are slim in this space, but you can find some refs to it:
- https://godoc.org/github.com/fsouza/go-dockerclient
- (maybe) https://docs.docker.com/registry/spec/auth/token/   ?
- and in registry/service.go and registry/auth.go  in the docker src
 
I was kind of hoping skopeo just vendored in the registry client and it would pick up support automatically.

**Comment by greglanthier** [comment]
Is this only a matter of using the Docker registry client (a la [docker/distribution](https://github.com/docker/distribution/tree/master/registry))?

I've had modest success in the past with some home-grown CLI tools that vendored the distribution client combined and [docker-credential-helpers](https://github.com/docker/docker-credential-helpers) tools to authenticate against various Docker registries (including some that use identity token auth like [IKS](https://www.ibm.com/cloud/container-service)).

I haven't read through the `skopeo` source to see how it makes Docker Registry v2 API calls - if it rolled its own client or if its using another one off the shelf.  Maybe a few gentle PRs would address the gap (without vendoring the world)?

I know my team would be keen to use `skopeo` to move images around in our [IKS](https://www.ibm.com/cloud/container-service) Docker registry - missing identity token support would probably slow them down.

Is there anyone thinking about this at the moment?  Are you looking for any volunteers?

**Comment by mtrmac** [comment]
`skopeo` uses GitHub.com/containers/image, which has its own client implementation.

I don’t know about anyone else working on this (as mentioned above, no documentation at all = no known benefits), PRs to containers/image would be welcome.

**Comment by greglanthier** [comment]
Thanks @mtrmac !

I’ll scan the existing [issues](https://github.com/containers/image/issues).

If nothing seems to fit I’ll draft a new issue for [github.com/containers/image](https://github.com/containers/image) sketching the problem and linking to resources I’ve found that explain Docker Registry v2 [token authentication](https://docs.docker.com/registry/spec/auth/token/) (limited though they may be).



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rhatdan** [comment]
@duglin @greglanthier @mtrmac Has any work ever gone forward on this?  Is this something we want?

**Comment by duglin** [comment]
I'm not aware of any work on this - but I also have had time to try with the latest skopeo to know if anything changed.  I can try in a bit when I get some free time if you think it might work now

**Comment by mtrmac** [comment]
FWIW all of the documentation links so far seem to point at the standard docker/distribution authentication protocol, which is implemented in c/image to be compatible with docker/distribution servers. The word `IdentityToken` does not appear in them at all.

If you want “IdentityToken”, please start by explaining what it is (and how you plan to use it). My best guess, looking at the Docker source code, is that you are referring to the `refresh_token` value from the token authentication specification.

**Comment by mackushev** [comment]
Docker cli use "identitytoken"  as refresh_token for auth2 token authentication. 
https://docs.docker.com/registry/spec/auth/oauth/

My scenario: I use azure provided container registry, so I have to call  
> az acr login foo 

az  ask my credentials and create record at ~/.docker/config.json  with "identitytoken"
 
after that normal docker cli works fine
> docker pull https://foo.azurecr.io/myimage:latest

Internally docker cli exchange _identitytoken_ to auth token making 'https://foo.azurecr.io/oauth2/token' call. 
It will be great if skopeo supports azure repos usage.

**Comment by mtrmac** [comment]
Thanks, that at least gives us a clear target use case.

c/image does not currently support the oauth2 authentication mechanism at all.

**Comment by yihuaf** [comment]
@mtrmac any update on this?

**Comment by yihuaf** [comment]
@mtrmac @vrothberg Now that https://github.com/containers/image/pull/829 is checked in, how do we bring the updates to skepo and libpod? I imagine we need a minor version bump for containers/image? I can help with PR to skepo and libpod, along with the relevant tests in those projects.

**Comment by vrothberg** [comment]
Yes, we need a minor bump and can the vendor it across the projects. @mtrmac, I also need to get the `registries.conf.d` into CRI-O. Can we cut a new release this week?

**Comment by mtrmac** [comment]
Sure, a new release would make sense, it’s been a month and several new features have landed. 

Maybe we can include some of the few outstanding recent open PRs as well, I’ll make a pass through the queue.

**Comment by mtrmac** [comment]
> I can help with PR to skepo and libpod, along with the relevant tests in those projects.

After a new c/image release happens, Dependabot will prepare PRs to vendor updates into the containers/* users automatically. Adding tests would, of course, be very welcome.

**Comment by yihuaf** [comment]
Sounds good. I will keep an eye out for the new release merging.

**Comment by mtrmac** [comment]
c/image update PR: https://github.com/containers/skopeo/pull/861 .

**Comment by sjhx** [comment]
The Docker [oauth2 documentation](https://docs.docker.com/registry/spec/auth/oauth/) states that `client_id` is *required* however this new support does not set the `client_id` oauth2 form field. IBM Cloud Container Registry requires a value so remains incompatible, can you revise the update to set it, ideally before releasing skopeo. Thanks.

**Comment by mtrmac** [comment]
An initial IdentityToken support was vendored in by #861, the client_id fix in #889 ; both were shipped in Skopeo 0.2.0.
