### ISSUE TITLE
make binary-static DISABLE_CGO=1 fails

### ISSUE THREAD

**Issue by tarasglek** [containers/skopeo#546]
I tried to make a static binary per docs and failed: 
`taras@dev-taras:~/skopeo$  make binary-static DISABLE_CGO=1`

```docker run --rm --security-opt label:disable -v $(pwd):/src/github.com/containers/skopeo \
        golang:1.10 make binary-local-static  BUILDTAGS='containers_image_ostree_stub exclude_graphdriver_devicemapper exclude_graphdriver_btrfs containers_image_openpgp'
make: *** No rule to make target 'binary-local-static'.  Stop.
Makefile:83: recipe for target 'binary-static' failed
make: *** [binary-static] Error 2
```

**Comment by mtrmac** [comment]
Thanks for your report; #552 should fix this.

(This could have never worked — and we didn’t notice because we do builds without containers, using the `-local` `Makefile` targets. So, using `make binary-local` is probably a safer bet.)
