### ISSUE TITLE
Support user containers-storage

### ISSUE THREAD

**Issue by lachmanfrantisek** [containers/skopeo#547]
Is there some way to use `skopeo copy` for the **containers-storage** located at `~/.local/share/containers/storage`. I am using **rootless podman** and would like to use the user, not the system-wide (`/var/lib/containers/storage/`) location.

Thanks.

**Comment by rhatdan** [comment]
Not sure if skopeo supports this right now.  But it should.

@lachmanfrantisek You know that most of skopeo interactions are availble via `podman pull` and `podman push`

**Comment by mtrmac** [comment]
The containers/storage transport does not use options for most of this; it is somehow exposed in the reference syntax, e.g. `containers-storage:[vfs@/some/storage/root/dir]busybox`.  I don’t know whether this is documented, in the worst case see `storageTransport.ParseReference`.

It seems that you would have to figure out the options and syntax to match `libpod`’s `GetRootlessStorageOpts`.

**Comment by rhatdan** [comment]
Couldn't we just have skopeo vendor in this code and call it when not running as root?

**Comment by mtrmac** [comment]
\*shrug\* Not _trivially_ because `containers-storage:` embeds this data into the reference instead of using external options like most other transports (where we can, and do, just add more CLI options `skopeo copy`); so we would end up with either some new syntax, or non-transparently reintepreting the user’s actual `containers-storage:…` input to mean something else than what it says.

It’s of course _possible_ to do all of this this, but at some point it raises the question whether there is any difference between `skopeo` and `podman` at all. So far, `skopeo` has been a very dumb wrapper around c/image (the `skopeo sync` PR would be another trend away from that); I’m not saying that it has to stay that way — but is there a _benefit_? E.g.
> `podman push `_sourceName transport_`:`_destName_

 is pretty much
> `skopeo copy containers-storage:`_sourceName transport_`:`_destName_

plus all the extra context from config files, and the edited high-level defaults; if we made `skopeo` use the same high-level defaults, why have `skopeo` at all, and/or would we need another tool for the raw low-level access?

@lachmanfrantisek what are you ultimately trying to do using `skopeo`?

**Comment by lachmanfrantisek** [comment]
@rhatdan @mtrmac Thanks!

The `podman push` was what I need. (It chooses system-wide when root and `~/.local/share/containers/storage` when rootless. Great!)

-----

I am working on  the [user-cont/colin](https://github.com/user-cont/colin/) (container-linter). We are 'checking' dockerfiles and container images. Nowadays, we are switching from the docker to podman... Due to some optimizations, we are using also ostree. (And there is the need for the conversion.)

**Comment by lachmanfrantisek** [comment]
With this format (`containers-storage:[vfs@/some/storage/root/dir]busybox`), I am getting `missing necessary StoreOptions `... Nevertheless, I am ok with the `podman push` solution.

Can I close this issue, or should I leave it for the discussion about podman/skopeo intersection?

**Comment by rhatdan** [comment]
No I think we can close.
@lachmanfrantisek When you are done, please write up a blog explaining what you did I would love to read it and promote it.

**Comment by mtrmac** [comment]
> With this format (`containers-storage:[vfs@/some/storage/root/dir]busybox`), I am getting `missing necessary StoreOptions`

Yeah, the various options from https://github.com/containers/libpod/blob/2e6243b18539175b5ff029a924c4d83834f83d2b/cmd/podman/libpodruntime/runtime.go#L16 need to be added to the string as well (at least the “RunRoot”, which this is complaining about), but maybe also a CGroup manager, hooks directories).

I don’t know what the full string actually looks like, to be honest. `containers-storage:[vfs@/some/storage/root/dir+/run/$UID/run]busybox` might be close enough, but relying on podman to compute all the options is probably the easiest way _most_ of the time.

**Comment by lachmanfrantisek** [comment]
@mtrmac Thanks, I'll stay with podman, since it resolves that automatically...

**Comment by kirbyfan64** [comment]
Okay, so I'm trying to figure some of this, because all I need is to be able to inspect and copy. When I run skopeo, the vfs driver's chown fails with "invalid argument", presumably because of the remap-uids option. However, I can't figure out how to set it, or what to set it to. I know it should be something like `[vfs@$HOME/.local/share/containers/storage+/run/user/$UID/skopeo:remap-uids=whatever]`, but I'm not sure how exactly to make this work.

**Comment by mtrmac** [comment]
Looking at https://github.com/containers/image/blob/4b6d9cf918c1e79a605265568c93cb35185ad25d/storage/storage_transport.go#L260-L262 , it might not be possible to change the mapping using that `[`…`]` syntax.

I have randomly encountered https://github.com/containers/libpod/issues/1087 including a debug log line
`[vfs@/home/tt/.local/share/containers/storage+/run/user/1000/run]docker.io/library/busybox:latest` , which seems to confirm that.

**Comment by kirbyfan64** [comment]
@rhatdan The exact command I was trying is `skopeo --insecure-policy inspect "containers-storage:[vfs@$HOME/.local/share/containers/storage+/run/user/$UID/skopeo:]alpine"`. I'm not necessarily trying to pull; the advantage of Skopeo is that I can interact equally with the Docker daemon as well as podman itself with the same command.

**Comment by rhatdan** [comment]
I don't see why we could not do this.

**Comment by miabbott** [comment]
I'm trying to do a `skopeo inspect` on my rootless storage (using the format discussed in this thread), but failing like this:

```
$ skopeo --debug inspect containers-storage:[overlay@/var/home/miabbott/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/library/alpine:latest
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
FATA[0000] chown /var/home/miabbott/.local/share/containers/storage/overlay/l: operation not permitted 
```

But `podman inspect` works well:

```
$ podman --log-level debug inspect docker.io/alpine
INFO[0000] running as rootless
DEBU[0000] Initializing boltdb state at /var/home/miabbott/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay                                
DEBU[0000] Using graph root /var/home/miabbott/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1000
DEBU[0000] Using static dir /var/home/miabbott/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false
DEBU[0000] parsed reference into "[overlay@/var/home/miabbott/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/library/alpine:latest"
DEBU[0000] parsed reference into "[overlay@/var/home/miabbott/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]@caf27325b298a6730837023a8a342699c8b7b388b8d878966b064a1320043019"
DEBU[0000] exporting opaque data as blob "sha256:caf27325b298a6730837023a8a342699c8b7b388b8d878966b064a1320043019"
DEBU[0000] parsed reference into "[overlay@/var/home/miabbott/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]@caf27325b298a6730837023a8a342699c8b7b388b8d878966b064a1320043019"
DEBU[0000] exporting opaque data as blob "sha256:caf27325b298a6730837023a8a342699c8b7b388b8d878966b064a1320043019"
DEBU[0000] parsed reference into "[overlay@/var/home/miabbott/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]@caf27325b298a6730837023a8a342699c8b7b388b8d878966b064a1320043019"
[
    {
        "Id": "caf27325b298a6730837023a8a342699c8b7b388b8d878966b064a1320043019",
        "Digest": "sha256:25b4d910f4b76a63a3b45d0f69a57c34157500faf6087236581eca221c62d214",
        "RepoTags": [
            "docker.io/library/alpine:latest"
...
```

I'd be great if `skopeo` could also support the rootless container storage.

**Comment by vrothberg** [comment]
> I'd be great if `skopeo` could also support the rootless container storage.

I somehow agree and ran into it myself a few times. But I understand @mtrmac'c concerns from https://github.com/containers/skopeo/issues/547#issuecomment-420038582 as well.

Ultimately, I think that Skopeo should support this use-case, at least to be part of the rootless-containers story of github.com/containers. The tools have a certain overlap as they share functionality (e.g., building, running and distribution). 

However (sharing @mtrmac's concerns), we had to carefully revisit with the Podman and Buildah gurus to avoid further increasing the dependencies among the tools.

@mtrmac @rhatdan what's your take on this topic in 2019?

**Comment by rhatdan** [comment]
Yes I think we should support the rootless use case.  Rootless is getting a lot of traction.  Skopeo should  be able to play in this environment.  Without having to hard code paths by users

**Comment by mtrmac** [comment]
Yeah, with rootless use of `podman` increasingly frequent, I agree support for `skopeo` interacting with the same storage is becoming too useful not to do it.

I do hope we can encapsulate that cleanly, the 88 `GetRootless*`/`IsRootless` references in libpod’s repo look a little scary at a first glance.

**Comment by vrothberg** [comment]
@giuseppe, could you help us with that? Just to be sure we don't miss anything important.

**Comment by giuseppe** [comment]
@vrothberg absolutely!

I think we should just use Podman `pkg/rootless` to setup the user namespace.  The logic here is simpler as it needs only to access the storage, so we'll need the create the namespace in any case (`rootless.BecomeRootInUserNS()`).  When running in rootless user the storage must default to `~/local/share/containers/storage` instead of `/var/lib/containers/storage`, and `storage.conf` must be read from `~/.config/containers/storage.conf`.

There are cases where the namespace cannot be created so we would probably want to skip its creation, e.g. `skopeo --version|--help`

**Comment by rhatdan** [comment]
Should we move pkg/rootless into containers/image or containers/storage.

I would prefer to move this to a lower library rather then cross polinating it to other packages.  I want to stop vendoring libpod into buildah and do not want to make the same mistakes with skopeo.

**Comment by vrothberg** [comment]
> Should we move pkg/rootless into containers/image or containers/storage.

I think the rootless package is currently a bit libpod specific (also in regards to the environment variables) and would not expect this functionality in image or storage. So I find libpod to be the best host of all three but I do understand the point.

> I would prefer to move this to a lower library rather then cross polinating it to other packages. I want to stop vendoring libpod into buildah and do not want to make the same mistakes with skopeo.

I think that's okay as long as the packages that are actually imported don't entail too many things. Looking at the `rootless` package we might drop the dependency on github.com/docker/docker/pkg/signal"?

**Comment by vrothberg** [comment]
I just read https://github.com/containers/libpod/issues/2325#issuecomment-467041118 after dropping the last comment here, which made me change my mind. In this context, I prefer containers/storage.

**Comment by devurandom** [comment]
Reading the comments, I'm a bit confused: Does skopeo pick up user images already or not? What is required from me to make it work? (My build of v0.1.34 appears try to `mkdir /var/run/containers` as a regular user.) Is someone working on implementing it? (It seems like that from the discussion.)

It seems that buildah picks up images from both `/var/lib/containers` and `~/.local/share/containers` automatically, without me having to hardcode the paths anywhere. Is this also what skopeo will do eventually?

**Comment by rhatdan** [comment]
Well we are trying to fix this now by updating containers/storage with the information.

https://github.com/containers/storage/pull/295

Once we have something like that in containers/storage it will be easy to vendor it into skopeo and fix skopeo to do this automatically.

**Comment by terinjokes** [comment]
@rhatdan That was merged over a year and a half ago. Is this another ticket tracking adding this to skopeo?

**Comment by rhatdan** [comment]
It should be in Skopeo now.
