### ISSUE TITLE
Cannot import docker archive with more then one image

### ISSUE THREAD

**Issue by chilicat** [containers/skopeo#556]
It seems like that skopeo does not support to copy a docker-archive with more than one image to a registry

Example:
```
docker pull busybox:latest 
docker pull  alpine:latest
docker save alpine:latest busybox:latest -o test.tar

skopeo  copy docker-archive:./test.tar docker://my-registry:5000

FATA[0000] Error determining manifest MIME type for docker-archive:./test.tar: Unexpected tar manifest.json: expected 1 item, got 2 

```

It would be great to support that use-case.

**Comment by mtrmac** [comment]
Right; you can write `docker-archive:./test.tar:alpine:latest`, but that currently only results in a warning
> docker-archive: references are not supported for sources (ignoring)

**Comment by chilicat** [comment]
What I'm actually looking for is to import all images with one command. The deployment process I'm implementing does not know about the images in the archive.

**Comment by mtrmac** [comment]
`skopeo copy` fundamentally works one image at a time; containers/image does not have a “repository of images” abstraction. #524 is somewhat moving in that direction, but it’s non-trivial.

A single container image is more or less everywhere the same kind of thing with the same semantics, but groups of images have _very_ different semantics (gzipped archives where there is very high cost to setting them up; Docker repositories where some images are only reachable by digests which can’t be listed; arbitrary subdirectory structures; the very complex OCI nested indexes with quite unclear semantics) and it’s very unclear whether hiding all of that behind a single abstraction is viable.

**Comment by chilicat** [comment]
Yes, that looks like the feature I'm looking for. I will close the issue. 
Thank you for your response.
