### ISSUE TITLE
Add --daemon-host parameter to inspect

### ISSUE THREAD

**Issue by alonbl** [containers/skopeo#559]
If docker socket is either in non standard location or using tcp, it is impossible to use docker-daemon: as the DOCKER_HOST environment variable is not considered and there is no parameter to allow override.

**Comment by mtrmac** [comment]
Thanks for your report.

Sure, that is…an implemented and…valid…operation to perform.

#523, while refactoring the CLI, does add the option to `inspect`, so this will be provided.

Still, I can’t overemphasize how inefficient `skopeo inspect docker-daemon:…` is: it downloads the _entire image_ with all layers, _uncompressed_, over the network, and creates a temporary copy of the uncompressed image (possibly many gigabytes!) on local disk — all of this ultimately just to get the manifest/config and the information for `inspect`.

If you can avoid this at all, please do. And if you need to do several operation on the same remote `docker-daemon:` source, it would quite likely be noticeably more efficient to make a temporary local copy (`skopeo copy docker-daemon:… dir:…`), and then work with that copy instead.

**Comment by alonbl** [comment]
Thanks!
I understand that this is inefficient, but in order to debug signature (use the standalone tools) the inspect should be usable... and currently it is unusable when using remote docker host.

So closing this as dup of #253 .

**Comment by mtrmac** [comment]
>  in order to debug signature (use the standalone tools) the inspect should be usable... 

If you are planning to use `skopeo inspect` to fetch the manifest to validate against signatures, note that that won’t work because `docker pull` irrecoverably discards the original manifest.

Using a `docker-daemon:` source creates a new manifest from the other metadata in the `docker save` tar file (which _almost always_ differs from the original, because it refers to the uncompressed versions of the layers); that manifest won’t match any signatures created against the original manifest.

**Comment by alonbl** [comment]
Oh! That's bad... even more reason to address #560  :)

**Comment by masaeedu** [comment]
> Still, I can’t overemphasize how inefficient skopeo inspect docker-daemon:… is: it downloads the entire image with all layers, uncompressed, over the network, and creates a temporary copy of the uncompressed image (possibly many gigabytes!) on local disk — all of this ultimately just to get the manifest/config and the information for inspect.

@mtrmac Could you expand on why this is the case? Shouldn't it be possible to recover this using the Docker API without downloading the actual layers (which constitute the bulk of the many gigabytes you're referring to)?

**Comment by masaeedu** [comment]
For my use case I specifically have several images with shared layers to download, and I want to do this efficiently by identifying their layers and downloading into content addressable storage individually. I was assuming the `skopeo inspect` would be a good way to obtain this information, but I can't quite figure out how to do this.

**Comment by mtrmac** [comment]
> > Still, I can’t overemphasize how inefficient skopeo inspect docker-daemon:… is: it downloads the entire image with all layers, uncompressed, over the network, and creates a temporary copy of the uncompressed image (possibly many gigabytes!) on local disk — all of this ultimately just to get the manifest/config and the information for inspect.
> 
> @mtrmac Could you expand on why this is the case? Shouldn't it be possible to recover this using the Docker API without downloading the actual layers (which constitute the bulk of the many gigabytes you're referring to)?

- I’m not sure it is possible: Docker only provides an “inspect” API which reinterprets / reformats the data.
- The API design makes that difficult: The goal of the `docker-daemon:` source is to copy the _whole image_; for that, the “fetch manifest and config” operations must correspond with the rest, and a single API request to fetch the whole image is the most efficient way to get the full config and to get a single consistent snapshot; the implementation should not be using the “inspect” endpoint to return the manifest/config and then somehow change its mind and fetch the whole image.
- There’s not much benefit to special-casing this: If the goal is to only fetch the image manifest/config for inspection, without using any other features of Skopeo or c/image, a plain `docker inspect` remains available.

> For my use case I specifically have several images with shared layers to download, and I want to do this efficiently by identifying their layers and downloading into content addressable storage individually. I was assuming the `skopeo inspect` would be a good way to obtain this information, but I can't quite figure out how to do this.

There really isn’t a concept of “partial images” that contain only a subset of layers; if omitting layer data ever works, it’s a coincidence that we, at least at this point, wouldn’t probably want to spend much time fixing.

My first recommendation would be to just use a registry; push the build result to a registry, pull from a registry. That allows random access, deduplication, and some level of concurrency.

If this _has_ to use the `docker save` format (and I don’t quite think it is ever the only option possible), https://github.com/containers/image/pull/991 plus a corresponding consumer in `podman` will allow using a single tarball with multiple images, which should share common layers (or at least common parent layers).

**Comment by masaeedu** [comment]
> There really isn’t a concept of “partial images” that contain only a subset of layers; if omitting layer data ever works, it’s a coincidence that we, at least at this point, wouldn’t probably want to spend much time fixing.

Having a "partial image" with missing layers is a different thing from having the metadata part of an image and omitting all the blobs corresponding to the layers. The latter is what I'm trying to accomplish, and there's no conceptual problems with doing so: you can't have an [image layout](https://github.com/opencontainers/image-spec/blob/master/image-layout.md) without having the blobs for all layers packed into it, but [image indices](https://github.com/opencontainers/image-spec/blob/master/image-index.md) and [image manifests](https://github.com/opencontainers/image-spec/blob/master/manifest.md) are independently specified entities that are not coupled to the image layout format.

> There’s not much benefit to special-casing this: If the goal is to only fetch the image manifest/config for inspection, without using any other features of Skopeo or c/image, a plain docker inspect remains available.

Thanks, I'll just use this then.
