### ISSUE TITLE
Ipv6 addresses not recognized in docker references

### ISSUE THREAD

**Issue by uablrek** [containers/skopeo#564]
## Ipv6 addresses in docker url does not work

```
> skopeo inspect --tls-verify=false docker://[fd00:2008::242:ac11:2]:5000/library/alpine:3.8
FATA[0000] invalid reference format
```

Ipv6 works though;
```
# As root;
echo 'fd00:2008::242:ac11:2  skopeotest.com' >> /etc/hosts
# then;
> skopeo inspect --tls-verify=false docker://skopeotest.com:5000/library/alpine:3.8
{
    "Name": "skopeotest.com:5000/library/alpine",
    "Digest": "sha256:cf2d5c15199a1f6161650f2cfe35fd502d0b661823030c7df599050ad895580e",
...
```

## Environment

```
> skopeo -v
skopeo version 0.1.32-dev
```
OS: Ubuntu 18.04.1 LTS

The private docker registry started as described [here](https://github.com/Nordix/xcluster/tree/master/ovl/private-reg)

## Additional info

I am using `skopeo` as a tool for `cri-o` in Kubernetes.  `cri-o` can't handle ipv6 addresses either, for instance in `/etc/crio/crio.conf`;
```
# registries is used to specify a comma separated list of registries to be used
# when pulling an unqualified image (e.g. fedora:rawhide).
registries = [
 "[fd00:2008::242:ac11:2]:5000"
]
```

will not work but the corresponding setting works for ipv4.

This make me think that the problem maybe is in the lib's that both `skopeo` and `cri-o` uses(?).

**Comment by runcom** [comment]
yes, very likely, does it work if you do a normal docker pull instead?

**Comment by mtrmac** [comment]
Thanks for your report.

IPv6 addresses aren’t valid syntax in Docker references, so this would be a big struggle throughout the ecosystem (and it isn’t clear that the syntax can be extended without breaking stuff—e.g. the `containers-storage:` transport uses a `[`…`]` prefix for something entirely different.).

Considering how unwieldy IPv6 addresses are, and how they make deploying TLS difficult, just not introducing support for them at all seems rather attractive—OTOH I do realize that we can’t always just pick and choose which features need or don’t need to be supported.

**Comment by uablrek** [comment]
I see the problem especially with TLS which is the normal case. My test env is of course a corner case and I can live without using ipv6 addresses in docker references. But they look awfully lot like a URL and using `curl` I can access the registry with a http://[.....]:5000/  address.

I close this issue since it is not a bug and not really something necessary.

Thanks for your answer.
