### ISSUE TITLE
`make` fails on centos7

### ISSUE THREAD

**Issue by vbatts** [containers/skopeo#567]
I've installed the podman rpm (`podman-0.9.2-5.git37a2afe.el7_5.x86_64`) to ensure all dependencies are present, and then built&installed podman master

```bash
$ podman version
Version:       0.10.2-dev
Go Version:    go1.11
Git Commit:    "76360d9a6ef73f694138766b81f380e45a860556"
Built:         Mon Nov  5 12:44:35 2018
OS/Arch:       linux/amd64
```

When I attempt to `make` skopeo master (187299a20b864610a55711278856b7a15ae4e37a) it fails at this point:
```
STEP 7: COMMIT skopeobuildimage
/usr/local/bin/podman run --rm --security-opt label:disable -v $(pwd):/src/github.com/containers/skopeo \
        skopeobuildimage make binary-local  BUILDTAGS='  '
Invalid --security-opt 1: "label:disable"
make: *** [binary] Error 125
```

**Comment by rhatdan** [comment]
--security-opt label=disable
                              ^

**Comment by vbatts** [comment]
I think the local build should always be default

**Comment by rhatdan** [comment]
@mtrmac Yes local should be the default.

**Comment by vorburger** [comment]
> --security-opt label=disable : Podman only supports the label=, not the label:

Thanks for recording this here; it helped to fix https://github.com/kubernetes/test-infra/pull/13045.
