### ISSUE TITLE
Create new release 

### ISSUE THREAD

**Issue by gilligan** [containers/skopeo#574]
**Request**: I would like to ask if a new skopeo release could be made sometime soon.

**Rationale**: I think the merging of https://github.com/containers/image/pull/526 warrants a new release since this has quite a big positive user impact for anyone using skopeo to regularly push images to a docker registry - I just built skopeo from master and tried it and it is working nicely.

Is this feasible? Is there anything i can do to help make it happen?

**Comment by rhatdan** [comment]
SGTM
@runcom Could you make this happen.

**Comment by vrothberg** [comment]
I have high hopes we can get the PRs using pgzip and the parallel-copy one in.

**Comment by rhatdan** [comment]
SGTM.

**Comment by runcom** [comment]
I'll wait for what @vrothberg said before releasing, thanks for the ping
