### ISSUE TITLE
Add more integration tests pushing to a registry

### ISSUE THREAD

**Issue by vrothberg** [containers/skopeo#578]
The CI did not catch https://github.com/containers/image/pull/553 which raised my desire to add integration tests pushing to a registry. Similar to Buildah's CI we can setup a locker registry running on `localhost:5000` and use it for push/pull tests.

**Comment by mtrmac** [comment]
We do have _some_ tests pushing to a registry, e.g. `TestCopySimple` was the first one I saw.

We could definitely have more tests, though — the skopeo integration test suite hasn’t been expanded in a _long_ time, and we are not measuring its coverage of c/image/docker at all.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg Any movement on this?

**Comment by mtrmac** [comment]
@rhatdan did you see any integration test changes that could be related?

**Comment by rhatdan** [comment]
Nope.

**Comment by mtrmac** [comment]
@vrothberg Do you think there’s a specific gap in the integration tests? Or could maybe the code coverage infrastructure being built for Podman help us find the gaps?

Returning to this issue a year later, it doesn’t look very actionable to just have “more tests” without a clearer target.

**Comment by vrothberg** [comment]
Very fair point. I support the idea of adding coverage tests to Skopeo as well :+1:

Once Podman is done, I should have enough battle scars to get that into Skopeo as well.
