### ISSUE TITLE
Confusing make targets

### ISSUE THREAD

**Issue by afbjorklund** [containers/skopeo#580]
`make` starts a container, and `sudo make install`fails ?

Seems that you need to "make binary-local" to just do a regular build. And that "skopeo" is missing ?

`make: *** No rule to make target 'skopeo', needed by 'install-binary'.  Stop.`

It would be better if binary-local was called "skopeo", and if the static binary was called "skopeo-static"

**Comment by vrothberg** [comment]
I agree as well. I continuously jump into this trap when working on podman or buildah before. @runcom @mtrmac WDYT?

**Comment by mtrmac** [comment]
Yeah, as mentioned elsewhere here, building dynamically-linked binaries in a container for a different OS version, or an entirely different OS, and expecting them to be usable locally, is just incorrect.

The default should be `binary-local`.

I’m almost tempted to drop the in-container builds entirely, AFAICT we are not using them and thus they sometimes break without anyone noticing, but IIRC from earlier reports there are _some_ users, so probably not.

**Comment by NicolasT** [comment]
FWIW, `make` (Docker-based build) *is* broken right now. In what's below, the build image is built 'from cache', but this 'cache' was seeded only a couple of minutes ago (on first `make` invocation):

```
$ make
docker build  -f Dockerfile.build -t skopeobuildimage .
Sending build context to Docker daemon  24.76MB
Step 1/4 : FROM ubuntu:17.10
 ---> e211a66937c6
Step 2/4 : RUN apt-get update && apt-get install -y     golang     btrfs-tools     git-core     libdevmapper-dev     libgpgme11-dev     go-md2man     libglib2.0-dev     libostree-dev
 ---> Using cache
 ---> cb943960df79
Step 3/4 : ENV GOPATH=/
 ---> Using cache
 ---> 822071e5850f
Step 4/4 : WORKDIR /src/github.com/containers/skopeo
 ---> Using cache
 ---> fd0c9ee16c2d
Successfully built fd0c9ee16c2d
Successfully tagged skopeobuildimage:latest
docker run --rm --security-opt label=disable -v $(pwd):/src/github.com/containers/skopeo \
        skopeobuildimage make binary-local  BUILDTAGS='   ostree '
go build "-buildmode=pie" -ldflags "-X main.gitCommit=b329dd0d4e9586480ef4363ad3c85bc6808ca9c2" -gcflags "" -tags "ostree " -o skopeo ./cmd/skopeo
vendor/github.com/klauspost/compress/flate/inflate.go:13:2: cannot find package "math/bits" in any of:
        /src/github.com/containers/skopeo/vendor/math/bits (vendor tree)
        /usr/lib/go-1.8/src/math/bits (from $GOROOT)
        /src/math/bits (from $GOPATH)
make: *** [binary-local] Error 1
Makefile:84: recipe for target 'binary-local' failed
make: *** [Makefile:74: binary] Error 2
```

**Comment by rhatdan** [comment]
I think the Docker/Podman build is fixed now.  I am going to have an intern tackle fixing this.
