### ISSUE TITLE
Consolidate contribution documentation

### ISSUE THREAD

**Issue by Silvanoc** [containers/skopeo#583]
The documentation needed to read when contributing to the project seems to be spread between the [CONTRIBUTING section of the README.md](https://github.com/containers/skopeo/blob/master/README.md#contributing) and the [CONTRIBUTING.md](https://github.com/containers/skopeo/blob/master/CONTRIBUTING.md).

Wouldn't it be meaningful to move the section [CONTRIBUTING > dependencies-management](https://github.com/containers/skopeo/blob/master/README.md#dependencies-management) to [CONTRIBUTING.md](https://github.com/containers/skopeo/blob/master/CONTRIBUTING.md)?

**Comment by rhatdan** [comment]
Sure, please open a PR.
