### ISSUE TITLE
master failed to build in container due to golang version is 1.8

### ISSUE THREAD

**Issue by rockmenjack** [containers/skopeo#587]
```
docker run --rm --security-opt label=disable -v $(pwd):/src/github.com/containers/skopeo \
        skopeobuildimage make binary-local  BUILDTAGS='   containers_image_ostree_stub '
go build "-buildmode=pie" -ldflags "-X main.gitCommit=17bea86e89730eacf24b985d0125e47ac0000542" -gcflags "" -tags "containers_image_ostree_stub " -o skopeo ./cmd/skopeo
vendor/github.com/klauspost/compress/flate/inflate.go:13:2: cannot find package "math/bits" in any of:
        /src/github.com/containers/skopeo/vendor/math/bits (vendor tree)
        /usr/lib/go-1.8/src/math/bits (from $GOROOT)
        /src/math/bits (from $GOPATH)
```
math/bits was introduced since go 1.9

**Comment by chengyli** [comment]
why not merging this commit?
https://github.com/containers/skopeo/pull/575/commits/85d26de620ea42779c418c0bc43be82ede284e47

**Comment by vrothberg** [comment]
Thanks for the ping. Once #575 is rebased, we can merge it.

**Comment by reenberg** [comment]
Wow, terrible user experience out of the box, especially considering #594 and when you are not running fedora.

Building in a container doesn't seem to have worked since v0.1.32, from Nov 7 2018.  
This Issue was opened Jan 9 and #575 is from Dec 16 2018 as well... Please fix this simple thing.

**Comment by rhatdan** [comment]
@reenberg PRs welcome.

**Comment by rhatdan** [comment]
Since the PR is merged, I will close the issue.
