### ISSUE TITLE
Support no_proxy env var

### ISSUE THREAD

**Issue by cjeanner** [containers/skopeo#588]
Hello,

Apparently, while the support for http(s)_proxy have been added (see #178), it seems the no_proxy env var isn't taken.

A small test showed me that:
in an env, I have set http_proxy, https_proxy and no_proxy - when skopeo is called, it apparently hits the proxy:
```bash
env | grep -i proxy
NO_PROXY=localhost,127.0.0.0/8,172.16.0.0/12,192.168.0.0/16
http_proxy=http://10.10.0.136:3128
https_proxy=http://10.10.0.136:3128
HTTPS_PROXY=http://10.10.0.136:3128
no_proxy=localhost,127.0.0.0/8,172.16.0.0/12,192.168.0.0/16
HTTP_PROXY=http://10.10.0.136:3128

skopeo inspect --tls-verify=false docker://192.168.24.1:8787/rhosp14/openstack-tempest:14.0-99
```
And we can see in the proxy logs:
```
1547111119.127      0 10.10.0.19 TCP_DENIED/403 3877 CONNECT 192.168.24.1:8787 - HIER_NONE/- text/html
1547111179.621  60492 10.10.0.19 TCP_MISS/503 4089 GET http://192.168.24.1:8787/v2/ - HIER_DIRECT/192.168.24.1 text/html
```

Notes: I've added env var in both caps and standard as I suspected it might play a role - apparently it's not the case.

Thank you!

Cheers,

C.

**Comment by rhatdan** [comment]
@vrothberg @runcom @mtrmac Are these flags in containers/image or just skopeo?  Should podman, buildah and CRI-O respect them?

**Comment by vrothberg** [comment]
> Are these flags in containers/image or just skopeo? 

I don't know and I don't see references on any of those variables in the code.

>  Should podman, buildah and CRI-O respect them?

I think that all tools should have the very same behaviour when it comes to pulling images.

**Comment by rhatdan** [comment]
I agree.

**Comment by cjeanner** [comment]
:+1: on having a common behaviour :).
Thank you for your quick feedback!

**Comment by mtrmac** [comment]
The code is, via `c/image/pkg/tlsclientconfig`, ultimately using standard Go https://golang.org/pkg/net/http/#ProxyFromEnvironment , which is already supposed to support `no_proxy`.

With 10.10.0.136 just hanging for me,
```console
$ env -i http_proxy=http://10.10.0.136:3128 https_proxy=http://10.10.0.136:3128 ./skopeo inspect docker://docker.io/busybox
```
hangs as expected, and
```console
$ env -i http_proxy=http://10.10.0.136:3128 https_proxy=http://10.10.0.136:3128 no_proxy=*.docker.io ./skopeo inspect docker://docker.io/busybox
```
works as expected.

I can’t trivially reproduce your exact setup to test your exact inputs, but, adding some extra tracing, this does seem to work, in principle, as expected for me (omitting the full output, only the first connection attempts); notably the CIDR matches work, and the lack of a port on the CIDR match is also not a problem:
```console
$ env -i http_proxy=http://10.10.0.136:3128 ./skopeo inspect docker://8.8.8.8/foo
[https://8.8.8.8/v2/] GetConn 10.10.0.136:3128 
$ env -i http_proxy=http://10.10.0.136:3128 no_proxy=8.8.0.0/16 ./skopeo inspect docker://8.8.8.8/foo
[https://8.8.8.8/v2/] GetConn 8.8.8.8:443 

$ env -i http_proxy=http://10.10.0.136:3128 https_proxy=http://10.10.0.136:3128 no_proxy=localhost,127.0.0.0/8,172.16.0.0/12,192.168.0.0/16 ./skopeo inspect docker://192.168.24.1:8787/rhosp14/openstack-tempest:14.0-99
[https://192.168.24.1:8787/v2/] GetConn 192.168.24.1:8787 
```

What version of Skopeo is this?

**Comment by mtrmac** [comment]
FWIW that package was built using `go-toolset-7-golang-bin-1.10.2-4.el7`, which would indeed be before support for CIDRs, and for ports in `no_proxy` (though AFAICS ports could be included in the string but would be ignored and the addresses would match regardless of ports, which should be fine).

**Comment by rhatdan** [comment]
Seems like a reason to requiest golang 1.11 be added to the RHEL7 build root.

**Comment by frittentheke** [comment]
@cjeanner thanks for opening this issue. I was about to open a similar issue to allow using a proxy for only "one leg" of the communication when doing _skopeo copy_ between two registries.

But I suppose when NO_PROXY is available one can simply place the registry to be accessed without proxy to that list and achieve just that ?

**Comment by cjeanner** [comment]
@frittentheke hey, yep, just put the registry in the NO_PROXY, as a simple IP/hostname (no CIDR), and Voilà.

Please beware of the variable value length limitation (something like 256 chars or around that number) in case you want to push multiple values.

BTW, @rhatdan @mtrmac guess we might close that one, since the issue is more related to rhel7/8 golang version than skopeo itself.

**Comment by jamescassell** [comment]
no_proxy has historically not supported CIDRs.  The workaround I've used is to effectively add all raw IPs to the no_proxy by setting `no_proxy=0,1,2,{...},254,255` -- I've never had a reason to have a raw IP go thru the proxy; they were always local accesses.
