### ISSUE TITLE
skopeo containers build failing at hack/common.sh:223

### ISSUE THREAD

**Issue by pcnreddy** [containers/skopeo#601]
hack/build-go.sh  
++ Building go targets for linux/amd64: cmd/openshift cmd/oc pkg/sdn/plugin/sdn-cni-plugin vendor/github.com/containernetworking/cni/plugins/ipam/host-local vendor/github.com/containernetworking/cni/plugins/main/loopback
/usr/lib/golang/pkg/tool/linux_amd64/link: signal: killed
[ERROR] PID 91: hack/common.sh:223: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags "${version_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/common.sh:223: `GOOS=${platform%/*} GOARCH=${platform##*/} go install -pkgdir "${OS_OUTPUT_PKGDIR}/${platform}" -tags "${OS_GOFLAGS_TAGS-} ${!platform_gotags_envvar:-}" -ldflags "${version_ldflags}" "${goflags[@]:+${goflags[@]}}" "${nonstatics[@]}"`
[INFO] 		  2: hack/common.sh:159: os::build::internal::build_binaries
[INFO] 		  3: hack/build-go.sh:33: os::build::build_binaries
[INFO]   Exiting with code 1.
[ERROR] PID 21: hack/common.sh:153: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/common.sh:153: `( os::build::internal::build_binaries "${binaries[@]+"${binaries[@]}"}" )`
[INFO] 		  2: hack/build-go.sh:33: os::build::build_binaries
[INFO]   Exiting with code 1.
make: *** [Makefile:41: build] Error 1
The command '/bin/sh -c set -x 	&& export GOPATH=$(mktemp -d) 	&& git clone --depth 1 -b v1.5.0-alpha.3 git://github.com/openshift/origin "$GOPATH/src/github.com/openshift/origin" 	&& sed -i -e 's/\[\[ "\${go_version\[2]}" < "go1.5" ]]/false/' "$GOPATH/src/github.com/openshift/origin/hack/common.sh" 	&& (cd "$GOPATH/src/github.com/openshift/origin" && make clean build && make all WHAT=cmd/dockerregistry) && cp -a "$GOPATH/src/github.com/openshift/origin/_output/local/bin/linux"/*/* /usr/local/bin 	&& cp "$GOPATH/src/github.com/openshift/origin/images/dockerregistry/config.yml" /atomic-registry-config.yml 	&& rm -rf "$GOPATH" 	&& mkdir /registry' returned a non-zero code: 2

**Comment by mtrmac** [comment]
Thanks for your report.
> ```
> /usr/lib/golang/pkg/tool/linux_amd64/link: signal: killed
> ```

can you check your kernel log for possible reasons why it was killed? It’s possible that the container, or your system, has run out of memory.

(All of this happens while running the test suite, so you should have a working Skopeo binary already.)

**Comment by pcnreddy** [comment]
Thanks for looking into this and the quick response.

Yes, I am running docker on mac. The default Mem was 2GB. I increased to 6GB. Now the container build for skopeo passes.

With the failure, the container image was not built. Now I see the container image.

Thanks very much.
