### ISSUE TITLE
registries.conf in contrib?

### ISSUE THREAD

**Issue by lsm5** [containers/skopeo#613]
I need to include the registries.conf file in rpm dist-gits and ubuntu forks. Worth putting in contrib? I can send a PR.

@mtrmac @rhatdan @vrothberg

**Comment by rhatdan** [comment]
SGTM

**Comment by vrothberg** [comment]
Is it possible to use the one from containers/image? The manpages are located there as well, so I am afraid of divergence. But if it helps packaging for Ubuntu, it SGTM.

**Comment by lsm5** [comment]
@vrothberg is it possible to vendor a commit of @containers/image with that file into skopeo?

**Comment by vrothberg** [comment]
> @vrothberg is it possible to vendor a commit of @containers/image with that file into skopeo?

https://github.com/containers/skopeo/pull/615 is adding it by avoiding `vndr` from removing it. It will now reside under `vendor/github.com/containers/image/registries.conf`.
