### ISSUE TITLE
Support copying non-root images

### ISSUE THREAD

**Issue by duritong** [containers/skopeo#623]
I'd like to copy images using skopeo built with non-root buildah/podman.

At the moment skopeo only sees images in the global/root image store, though I would like to use skopeo to push my builds as it detects already present layers.

My workaround at the moment is to save an image with podman and the push from the tar.

**Comment by rhatdan** [comment]
Yes this is a planned on feature.  Skopeo now can understand the location of non root configuration, but still needs to enter the User Namespace of the user in order to create files owned by different UIDs like podman and Buildah can.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
so we miss the following features:

1. containers/storage automatically detects when we are in rootless use once we are into the user namespace.  Opened a PR for it:  https://github.com/containers/storage/pull/312
2. adapt containers/image to use the new API call.
3. add code to skopeo to create the namespace

After the first two steps, skopeo already works from a buildah unshare session.  I am not sure yet how to achieve the 3rd one.  We don't need the complex logic used by podman, the buildah unshare module is enough here.  We will need to move it to containers/storage to avoid duplication

**Comment by giuseppe** [comment]
for the third step: https://github.com/containers/storage/pull/313

So now we can easily get rootless support in Skopeo:

https://github.com/containers/skopeo/pull/624

@duritong could you try that version of Skopeo and see if it works for you?
