### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by runcom** [containers/skopeo#63]
With all the new stuff we merged in master the README.md got a bit outdated now. We would need to updated it in order to reflect the current master code with examples. Also, with the upcoming move to libraries it will be far far better to have something easy shown in the main github page.

@mtrmac :)

**Comment by rhatdan** [comment]
Makes sense to me.

**Comment by hmeng-19** [comment]
I just tried skopeo on fedora 23 following the instructions on `README.md`.  
`skopeo inspect docker://docker.io/fedora` works normally.
 
However, when I ran `skopeo inspect docker://registry.access.redhat.com/rhel7`, the following error happened:
 
    hmeng@localhost ~$ skopeo inspect docker://registry.access.redhat.com/rhel7
    FATA[0001] error pinging repository, response code 404

**Comment by hmeng-19** [comment]
BTW, I am an intern working on project atomic at the Westford office this summer, let me know if there is some easy bug I can start to play with.

**Comment by runcom** [comment]
> BTW, I am an intern working on project atomic at the Westford office this summer, let me know if there is some easy bug I can start to play with.

Hey there, and welcome :)



> hmeng@localhost ~$ skopeo inspect docker://registry.access.redhat.com/rhel7
> FATA[0001] error pinging repository, response code 404

Our RH registry is not currently supported in skopeo atm so you can't use it

**Comment by runcom** [comment]
Would be amazing to have the README.md talking about all the `copy`, policies, signatures stuff @mtrmac talked about at yesterday demo - that was awesome!

**Comment by mtrmac** [comment]
#96 adds `copy` and `delete`.

`--signed-by` exists in `master` (and is documented in the man page) but is not really usable before #93 lands.
`--policy` should, similarly, be added together or after the code which implements it.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Could you look into the readme, and make sure it is up2date.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan ack

**Comment by lsm5** [comment]
Closing :)
