### ISSUE TITLE
Introduce vendor-agnostic URI scheme for OCI distribution specification

### ISSUE THREAD

**Issue by hendrikhalkow** [containers/skopeo#633]
As a Skopeo user, I want to interact with registries that implement the [OCI distribution specification](https://github.com/opencontainers/distribution-spec/blob/master/spec.md).

At the moment, this is pretty much exactly the same as the docker:// scheme that is specified in the [Docker Registry HTTP API V2 protocol](https://github.com/docker/distribution/blob/5cb406d511b7b9163bff9b6439072e4892e5ae3b/docs/spec/api.md).

However, skopeo should IMHO use a vendor-agnostic URL scheme. A few ideas:

```
oci://...      # Nice and short, but could be confused with the existing oci: scheme
oci-dist://... # More distinguishable. Actually, I prefer the first one ...
```

**Comment by mtrmac** [comment]
The code implements the docker/distribution protocol, or, more precisely, the protocol that is necessary to interoperate with docker/distribution servers (which is not exactly the documented protocol).  The OCI specification has not been even released at this point, nor it has been, to any extent, considered while developing the existing implementation. (See also https://github.com/containers/image/pull/527 .)

Introducing a new name for the same transport would also require supporting aliases in `policy.json` and dealing with ambiguities; sure, possible in principle, but not quite trivial, and things like `atomic trust` would have to be similarly updated.

It’s all doable, sure, but personally I’m very uninterested in playing politics/marketing with identifiers, and doing extra work in security-critical code just for politics/marketing, unless strictly necessary. Likely enough someone will turn up motivated enough to implement this, and/or it could become “strictly necessary”, but until then I’d very much prefer the simpler, more reliable code, and the current quite accurate naming.

(FWIW, `oci:` is already taken.)
