### ISSUE TITLE
RFE: Make 'skopeo inspect' provide the size of the OCI image

### ISSUE THREAD

**Issue by debarshiray** [containers/skopeo#641]
It would be nice if 'skopeo inspect' provided the size of the OCI image. It seems like useful information that one might want to have before pulling an image to avoid blowing the data cap or interfering with other network activity.

eg., it could be useful to implement https://github.com/containers/toolbox/issues/134, but it's a different question whether one wants to add a dependency on another 20+ MB binary just for a bit of UI niceness. :)

**Comment by TomSweeneyRedHat** [comment]
Thanks @debarshiray for the RFE.

**Comment by infiniteregrets** [comment]
Any progress on this issue? 
I think this would be a really nice feature to have! I tried skopeo using the following command:
`skopeo inspect --override-os linux docker://registry.fedoraproject.org/fedora:latest`
```
{
    "Name": "registry.fedoraproject.org/fedora",
    "Digest": "sha256:8b01cffca564ca914d5d3c8dc8c6eca12a755ee4d1d898e22e83ad7128fae256",
    "RepoTags": [
        "34-aarch64",
        "34-ppc64le",
        "34-x86_64",
        "34",
        "34-s390x",
        "34-armhfp",
        "33-armhfp",
        "32-armhfp",
        "35-aarch64",
        "35-ppc64le",
        "35-s390x",
        "35-x86_64",
        "35",
        "35-armhfp",
        "30-aarch64",
        "30-ppc64le",
        "30-s390x",
        "30-x86_64",
        "30",
        "latest",
        "rawhide",
        "30-armhfp",
        "31-aarch64",
        "31-x86_64",
        "31",
        "31-armhfp",
        "31-s390x",
        "31-ppc64le",
        "32-aarch64",
        "32-ppc64le",
        "32-s390x",
        "32-x86_64",
        "32",
        "33-aarch64",
        "33-ppc64le",
        "33-s390x",
        "33-x86_64",
        "33"
    ],
    "Created": "2021-06-11T05:48:31Z",
    "DockerVersion": "1.10.1",
    "Labels": {
        "license": "MIT",
        "name": "fedora",
        "vendor": "Fedora Project",
        "version": "34"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:ca594071dfff2c0e563feabb63b1df444a7b76eac5be65103e6c047cec6eee3f"
    ],
    "Env": [
        "DISTTAG=f34container",
        "FGC=f34",
        "container=oci"
    ]
}
```
This does not render the size...
I tried looking at the source code but kinda got confused
But I think this is definitely possible. I tried to do this using the docker hub API using a script I wrote:

```
import asyncio
import aiohttp
import json

async def fetch(name=None):
    async with aiohttp.ClientSession() as session:
        async with session.get(f"https://hub.docker.com/v2/repositories/library/{name}/tags") as response:
            if response.status != 200:
                print('`Falied to fetch data | Try again later`')
                exit(1)
            data = await response.text()
            json_data = json.loads(str(data))
            for result in json_data["results"][:10]:
                print(name+':'+result["name"], round(result["full_size"]/(1048576),2))

asyncio.run(fetch(name="fedora"))
```
Results:
```
fedora:latest 61.92
fedora:rawhide 62.04
fedora:35 62.04
fedora:34 61.92
fedora:33 59.0
fedora:32 67.84
fedora:31 58.58
fedora:30 67.54
fedora:29 85.81
fedora:28 85.49
```
I am not completely sure how skopeo is doing it sorry, but having this would be very useful!

**Comment by mtrmac** [comment]
> ```
>         async with session.get(f"https://hub.docker.com/v2/repositories/library/{name}/tags") as response:
> ```

That’s not a documented Registry API per https://github.com/distribution/distribution/blob/main/docs/spec/api.md . (But with new enough images we can get sizes of individual blobs, and sum that up.)

---

Overall, sure, a reasonable RFE.

Note: Compare also #1309 requesting sizes of individual layers, a rather more invasive output format change.

**Comment by infiniteregrets** [comment]
@mtrmac are you working on this? If not, could you please point me in the right direction where I will have to make changes?

**Comment by mtrmac** [comment]
I’m not working on this, PRs would be welcome.

There are two parts to this:
- In containers/image, extend `types.Image.Inspect` to also provide sizes _if known_ (without breaking API, otherwise should be trivial).
- Design how to output this in `skopeo inspect` output, without breaking existing users and without repetition in the default format. This is the harder part. One alternative would be to make this data _only_ available to the `--format` option, though that’s pretty ugly and hard to find. An extra option to output _both_ the existing layer IDs and something with sizes? An extra option to report layer ID+sizes _instead_ of the existing field?

**Comment by lsm5** [comment]
@infiniteregrets are you working on this?

**Comment by infiniteregrets** [comment]
@lsm5 I tried working on this, but got stuck so I just didnt try again. I would love to give it another try, but busy with school ): Sorry

**Comment by lsm5** [comment]
@infiniteregrets thanks and no worries. I'll assign a `volunteers wanted` but feel free to pick this up whenever you can.

**Comment by WarheadsSE** [comment]
A simple method of fetching this information (when the data is present) is with `skopeo inspect --raw IMAGE | jq '[ .layers[].size ] | add'`

Be aware that this will not work on a `"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json"`, such as `docker://registry.docker.com/library/alpine:latest`. For that, you will need to pull out the image manifest appropriate for you before performing the above query for that image.

```
$ skopeo inspect --raw docker://registry.docker.com/library/alpine:latest \
  | jq -r '.manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest'
sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3
$ skopeo inspect --raw docker://registry.docker.com/library/alpine@sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3 \
  | jq -r '[ .layers[].size ] | add'
2818413
```

**Comment by rhatdan** [comment]
Is the solution by @WarheadsSE Enough to close this?

**Comment by mtrmac** [comment]
No, why would it be?

https://github.com/containers/image/pull/1608 is a possible first step.

**Comment by rhatdan** [comment]
I was asking the reporter.  If you think it is important to implement then fine.

**Comment by mtrmac** [comment]
https://github.com/containers/skopeo/pull/1738 (see https://github.com/containers/skopeo/pull/1738#issuecomment-1225943116  for an example) now provides individual layer sizes, if known.

**Comment by debarshiray** [comment]
> Is the solution by @WarheadsSE Enough to close this?

Yeah, the solution by @WarheadsSE might have been enough to improve Toolbx's UI.  However, I am delighted that @ningmingxiao made it easier by removing one step because most of the images Toolbx deals with are `application/vnd.docker.distribution.manifest.list.v2+json`.

**Comment by debarshiray** [comment]
> #1738 (see [#1738 (comment)](https://github.com/containers/skopeo/pull/1738#issuecomment-1225943116) for an example) now provides individual layer sizes, if known.

That's wonderful!  I suppose this issue can now be closed, yes.

**Comment by mtrmac** [comment]
Thanks! Note that the individual layer size _can_ be `-1` if unknown (schema1 images)
