### ISSUE TITLE
skopeo inspect command errors out with 0.1.36-dev for xenial release

### ISSUE THREAD

**Issue by khandelwalankit04** [containers/skopeo#652]
Hi Team,

We are seeing error in inspecting image with latest build of skopeo : 0.1.36-dev. Here is the screenshot : 

![image](https://user-images.githubusercontent.com/36901094/57799109-f16c4780-7713-11e9-9010-fd574d28186d.png)

This works with 0.1.35-dev , but since ppa:projectatomic/ppa only contains the latest version of skopeo we are unable to downgrade it to previous release.  Can you provide the fix as well as update the previous stable releases for skopeo : 

![image](https://user-images.githubusercontent.com/36901094/57799298-63449100-7714-11e9-9cf8-6960bbd8cc1c.png)

Let me know if you need any additional info

**Comment by rhatdan** [comment]
If you install newuid package on Ubuntu, it should fix the issue, but this definitely a bug.

**Comment by khandelwalankit04** [comment]
@rhatdan : Is there a plan to also package and keep older stable version in ppa:projectatomic/ppa ?

**Comment by rhatdan** [comment]
@giuseppe We should check to see if newuidmap and newgidmap exists if not then just don't enter the user namespace.  It should only care if the user is using containers/storage anyways.

**Comment by rhatdan** [comment]
@khandelwalankit04 I think we are planning on shipping skopeo as a snap.  Which would only be the stable versions.

@lsm5 @jnovy Please comment.

**Comment by mtrmac** [comment]
@khandelwalankit04 Is this still an issue for you? It should have been fixed in Skopeo 0.1.36 and later.

**Comment by khandelwalankit04** [comment]
@mtrmac : This is no longer the issue. Thanks for fixing

**Comment by mtrmac** [comment]
Thanks, closing.
