### ISSUE TITLE
Skopeo copy signedby registry: Source image rejected: Invalid crypto engine

### ISSUE THREAD

**Issue by ezaluzec** [containers/skopeo#660]
**Description**

Copying a signed container from a quay registry results in error saying, `FATA[0000] Source image rejected: Invalid crypto engine`. 

 - From the source system (Ubuntu 16.04.6 LTS), the container was imported with podman (1.3.0-dev) and pushed to quay as a signed-by container with a gpg2 (2.1.11) keyring.

- The destination system (embedded Linux), is running skopeo (0.1.37-dev) and runc (1.0.0-rc7)

**Environment details**

policy.json transport: 

			"transports": {
				"docker": {
					"quay.registry": [
					{
						"type": "signedBy",
						"keyType": "GPGKeys",
						"keyPath": "mysignkey.gpg"
					}
				]
				},

registries.d yaml:

	registries.d/default.yaml
		docker: 
			quay.registry:
				sigstore: file:///var/lib/containers/trustedkeys 
				sigstore-staging: file:///var/lib/containers/trustedkeys

				
- Crypto lib on source: `/./lib/x86_64-linux-gnu/libcrypto.so.1.0.0`
- OpenSSL version on source: `OpenSSL 1.0.2g  1 Mar 2016`

- Crypto lib on destination: `/./usr/lib/libcrypto.so.1.1`
- OpenSSL version on destination: `OpenSSL 1.1.1  11 Sep 2018`

- GPG2 Key type:

		Key-Type: RSA
		Key-Length: 2048
		Subkey-Type: RSA
		Subkey-Length: 2048

**Steps to reproduce the issue:**

1. From source system, generate Key

		gpg2 --full-gen-key
		gpg2 --armor --export --output mysignkey.gpg Name.Name@Company.com

2. Frou source system, import and push signed container push

		sudo podman import containername.tar.bz2
	
		sudo podman push --sign-by Name.Name@Company.com af7d69bf19c1e3240507e222b7a4ec318e8399c800ea6124ef0e31eab9b672f7 quay.registry/username/containername
	
		Getting image source signatures
		Copying blob 7d0b5e2df043 done
		Copying config af7d69bf19 done
		Writing manifest to image destination
		Copying config af7d69bf19 done
		Writing manifest to image destination
		Signing manifest
		Storing signatures

3. From destination system, copy trusted signature from source

		ls -al /var/lib/containers/trustedkeys/username/containername@sha256\=b56c3687782b4a8b8f67dd577e7ca5dede8fe6fce30e869f2bc75353baefa64d/signature-1
		-rw-r--r-- 1 root root 581 May 17 20:12 /var/lib/containers/trustedkeys/username/containername@sha256=b56c3687782b4a8b8f67dd577e7ca5dede8fe6fce30e869f2bc75353baefa64d/signature-1

4. From destination system, copy using Skopeo

		skopeo copy docker://quay.registry/username/containername oci:containernamesign-oci:latest
		FATA[0000] Source image rejected: Invalid crypto engine

**Comment by mtrmac** [comment]
Thanks for your report. Does the embedded system have a `gpg`/`gpg2` binary, and the rest necessary for `gpg{2,} -d` to work?

(Alternatively, if the embedded system is going to only do signature verification, not signing, _and you don’t care about the crypto implementation_, compiling skopeo etc. for the embedded system with the `containers_image_openpgp` build tag would use a Golang-only implementation that does not have these external dependencies.)

**Comment by ezaluzec** [comment]
@mtrmac , thank you for the feedback. Rebuilding skopeo with `containers_image_openpgp` resolved error. This issue can be closed.

Full compile command:
`x86_64-poky-linux-go build "-buildmode=pie" -ldflags "-X main.gitCommit=0c90e57eaf6496b77516310faefbe43a6e7e126a" -gcflags "" -tags "containers_image_openpgp " -o skopeo ./cmd/skopeo`

Just to confirm, signatures are still verified with skopeo copy when the `--remove-signatures` option is added? When copying I get message saying, `Can not copy signatures: Pushing signatures for OCI images is not supported`. This was resolved by adding `--remove-signatures`.

Without `--remove-signatures` option:

	~# skopeo --debug copy docker://quay.registry/username/podman-test oci:podmantest1:latest

		DEBU[0000] Trying to pull "quay.registry/username/podman-test:latest" from endpoint "quay.registry/username/podman-test:latest"
		DEBU[0000] reference rewritten from 'quay.registry/username/podman-test:latest' to 'quay.registry/username/podman-test:latest'
		DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
		DEBU[0000]  Using "docker" namespace quay.registry
		DEBU[0000]   Using file:///var/lib/containers/trustedkeys
		DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/quay.registry
		DEBU[0000] GET https://quay.registry/v2/
		DEBU[0000] Ping https://quay.registry/v2/ status 401
		DEBU[0000] GET https://quay.registry/v2/auth?account=username%2Bbuild&scope=repository%3Ausername%2Fpodman-test%3Apull&service=quay.registry
		DEBU[0000] Increasing token expiration to: 60 seconds
		DEBU[0000] GET https://quay.registry/v2/username/podman-test/manifests/latest
		DEBU[0001] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb
		DEBU[0001] IsRunningImageAllowed for image docker:quay.registry/username/podman-test:latest
		DEBU[0001]  Using transport "docker" specific policy section quay.registry
		DEBU[0001] Reading /var/lib/containers/trustedkeys/username/podman-test@sha256=c9836736a24bbba4e1e42d943cc132f7dbbe6ba1daed1d3e5a956eef764784d8/signature-1
		DEBU[0001] Reading /var/lib/containers/trustedkeys/username/podman-test@sha256=c9836736a24bbba4e1e42d943cc132f7dbbe6ba1daed1d3e5a956eef764784d8/signature-2
		DEBU[0001]  Requirement 0: allowed
		DEBU[0001] Overall: allowed
		Getting image source signatures
		Checking if image destination supports signatures
		FATA[0001] Can not copy signatures: Pushing signatures for OCI images is not supported

With `--remove-signatures` option:

	~# skopeo --debug copy --remove-signatures docker://quay.registry/username/podman-test oci:podmantest1:latest

		DEBU[0000] Trying to pull "quay.registry/username/podman-test:latest" from endpoint "quay.registry/username/podman-test:latest"
		DEBU[0000] reference rewritten from 'quay.registry/username/podman-test:latest' to 'quay.registry/username/podman-test:latest'
		DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration
		DEBU[0000]  Using "docker" namespace quay.registry
		DEBU[0000]   Using file:///var/lib/containers/trustedkeys
		DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/quay.registry
		DEBU[0000] GET https://quay.registry/v2/
		DEBU[0000] Ping https://quay.registry/v2/ status 401
		DEBU[0000] GET https://quay.registry/v2/auth?account=username%2Bbuild&scope=repository%3Ausername%2Fpodman-test%3Apull&service=quay.registry
		DEBU[0000] Increasing token expiration to: 60 seconds
		DEBU[0000] GET https://quay.registry/v2/username/podman-test/manifests/latest
		DEBU[0001] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb
		DEBU[0001] IsRunningImageAllowed for image docker:quay.registry/username/podman-test:latest
		DEBU[0001]  Using transport "docker" specific policy section quay.registry
		DEBU[0001] Reading /var/lib/containers/trustedkeys/username/podman-test@sha256=c9836736a24bbba4e1e42d943cc132f7dbbe6ba1daed1d3e5a956eef764784d8/signature-1
		DEBU[0001] Reading /var/lib/containers/trustedkeys/username/podman-test@sha256=c9836736a24bbba4e1e42d943cc132f7dbbe6ba1daed1d3e5a956eef764784d8/signature-2
		DEBU[0001]  Requirement 0: allowed
		DEBU[0001] Overall: allowed
		DEBU[0001] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json]
		DEBU[0001] Downloading /v2/username/podman-test/blobs/sha256:a03e59fe900f34a24fa0e39f057bd95849dd1734d95acc1f7faa4796e4747476
		DEBU[0001] GET https://quay.registry/v2/username/podman-test/blobs/sha256:a03e59fe900f34a24fa0e39f057bd95849dd1734d95acc1f7faa4796e4747476
		DEBU[0002] Detected compression format gzip
		DEBU[0002] Using original blob without modification
		Copying blob a03e59fe900f done
		DEBU[0018] Downloading /v2/username/podman-test/blobs/sha256:3c87dcfbc71a04c2717ecd24679baa2158d3f13510dacc510d9de01ef1a66caf
		DEBU[0018] GET https://quay.registry/v2/username/podman-test/blobs/sha256:3c87dcfbc71a04c2717ecd24679baa2158d3f13510dacc510d9de01ef1a66caf
		DEBU[0020] No compression detected
		DEBU[0020] Using original blob without modification
		Copying config 3c87dcfbc7 done
		Writing manifest to image destination
		Storing signatures

**Comment by mtrmac** [comment]
> @mtrmac , thank you for the feedback. Rebuilding skopeo with `containers_image_openpgp` resolved error. This issue can be closed.

Thanks for the confirmation.

> Just to confirm, signatures are still verified with skopeo copy when the `--remove-signatures` option is added?

Yes, per the configured policy. (You can set up a “reject all” policy to confirm this.)

> When copying I get message saying, `Can not copy signatures: Pushing signatures for OCI images is not supported`. This was resolved by adding `--remove-signatures`.
Yes, that’s expected.

**Comment by Kenzku** [comment]
Hej,

I installed, removed and reinstalled the skopeo on RHEL 8 by: `snap install --edge skopeo --jailmode` https://snapcraft.io/install/skopeo/rhel

I got the same error

```
skopeo --debug standalone-sign \
manifest.json \
docker.io/myrepo/my-image:test \
CE6A935540C343A71587E871591B64380384574D \
-o signature
FATA[0000] Error creating signature: Invalid crypto engine 
```

my gpg2 version is:

```
gpg2 --version
gpg: WARNING: unsafe permissions on homedir '/root/.gnupg'
gpg (GnuPG) 2.2.9
libgcrypt 1.8.3
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Home: /root/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

Any idea what does this error message mean?

My colleagues tried on another RHEL 8 and Ubuntu 18, it seems to work, but the gpg2 versions are different:

```
gpg2 --version
gpg (GnuPG) 2.0.22
libgcrypt 1.5.3
```
and 
```
gpg (GnuPG) 2.2.4
libgcrypt 1.8.1
```
