### ISSUE TITLE
error writing manifest during copy from docker.io to private registry (artifactory)

### ISSUE THREAD

**Issue by zendril** [containers/skopeo#662]
I am able to copy quite a few files from docker.io and gcr.io  into both quay and artifactory just fine.

docker://docker.io/cloudfoundry/cnb:bionic throws an error when writing the manifest

`
bash-4.2$ skopeo copy --dest-creds myname:redacted docker://docker.io/cloudfoundry/cnb:bionic docker://containerimages.myregistry.com/docker-external/cloudfoundry/cnb:bionic
Getting image source signatures
Copying blob 898c46f3b1a1 [======================================] 31.0MiB / 31.0MiB
Copying blob 63366dfa0a50 [======================================] 851b / 851b
Copying blob 041d4cd74a92 [======================================] 545b / 545b
Copying blob 6e1bee0f8701 [======================================] 162b / 162b
Copying blob 736a2f2678d0 [======================================] 2.7MiB / 2.7MiB
Copying blob c14514b920d6 [======================================] 4.4KiB / 4.4KiB
Copying blob 4e1c50360d2b [======================================] 2.6MiB / 2.6MiB
Copying blob 3091b80d6304 [======================================] 39.6MiB / 39.6MiB
Copying blob c2cb47c11953 [======================================] 12.1MiB / 12.1MiB
Copying blob 3982579fd5a8 [======================================] 153b / 153b
Copying blob 531565c98c9c [======================================] 123b / 123b
Copying blob 94b33fc4a632 [======================================] 325b / 325b
Copying blob dd30bd878ed8 [======================================] 7.6MiB / 7.6MiB
Copying blob 3fa3b939ac4e [======================================] 7.2MiB / 7.2MiB
Copying blob 1dc26d7dfc78 [======================================] 7.4MiB / 7.4MiB
Copying blob beba1ba9936c [======================================] 3.3MiB / 3.3MiB
Copying blob fb34d0dd7fb0 [======================================] 4.4MiB / 4.4MiB
Copying blob 154988cf90cd [======================================] 4.3MiB / 4.3MiB
Copying blob d27617308bb9 [======================================] 5.0MiB / 5.0MiB
Copying blob b003504dbe4b [======================================] 4.5MiB / 4.5MiB
Copying blob 8f08ef941506 [======================================] 5.1MiB / 5.1MiB
Copying blob 6eae70700bf8 [======================================] 4.3MiB / 4.3MiB
Copying blob 5b77b1b25f07 [======================================] 4.2MiB / 4.2MiB
Copying blob c7e1b0668958 [======================================] 575b / 575b
Copying blob e5368c153ee7 [======================================] 372b / 372b
Copying config ef7f7c0918 [======================================] 4.6KiB / 4.6KiB
Writing manifest to image destination
Copying config cb43e3fc23 [======================================] 4.3KiB / 4.3KiB
Writing manifest to image destination
FATA[0003] Uploading manifest failed, attempted the following formats: application/vnd.docker.distribution.manifest.v2+json(Error writing manifest: Error uploading manifest bionic to containerimages.myregistry.com/docker-external/cloudfoundry/cnb: manifest invalid: manifest invalid), application/vnd.docker.distribution.manifest.v1+prettyjws(Error creating an updated image manifest: Cannot convert an image with 0 history entries to application/vnd.docker.distribution.manifest.v1+prettyjws), application/vnd.oci.image.manifest.v1+json(Error writing manifest: Error uploading manifest bionic to containerimages.myregistry.com/docker-external/cloudfoundry/cnb: manifest invalid: manifest invalid), application/vnd.docker.distribution.manifest.v1+json(Error creating an updated image manifest: Cannot convert an image with 0 history entries to application/vnd.docker.distribution.manifest.v1+prettyjws)
`

Does this have anything to do with lacking manifest list support?

**Comment by zendril** [comment]
Looks like this also happens when using docker pull, retag and push to private registry.

I get this error when using docker "empty history when trying to create schema1 manifest"

So I assume this isn't a skopeo issue, I'll close this after a day or so, hoping someone who knows what the actual issue is can opine first.

**Comment by vrothberg** [comment]
Which kind of registry are you pushing to? I tried to reproduce with Docker registry 2 (i.e., `docker.io/library/registry:2`) and did not encounter any error.

**Comment by mtrmac** [comment]
Either way, the source image is truly invalid, it is missing a top-level `history` array. This is definitely noticeable on schema1-only registries (because the conversion to schema1 can’t happen, and fails with the two messages shown above), and it might be noticeable on other registries that validate the config as well. OTOH it’s possible that some registries don’t notice, and maybe even likely that runtimes might allow the image to run.

**Comment by mtrmac** [comment]
(FWIW, `History` is optional in OCI; my reading of https://github.com/moby/moby/blob/master/image/spec/v1.2.md is that it is mandatory in Docker schema2.)

Either way, the `manifest invalid: manifest invalid` error is the destination registry refusing to accept the schema2 image unmodified; the other two are caused by trying to upload as schema1, and failing to convert to it because `history` is missing.

**Comment by zendril** [comment]
Very latest artifactory (6.x) as well as quay (v2).

**Comment by zendril** [comment]
Thanks. I'm still new to the spec game so this explanation really helps.

**Comment by zendril** [comment]
Had a nice succinct explanation from someone that also lines up with what you all were saying.  Leaving it here in case someone else hits this.

> `cloudfoundry/cnb:bionic` doesn't populate `history` in the config file, and the registry you're trying to push to doesn't support schema 2 images, so skopeo/docker are trying to downconvert them to schema 1 images, which requires the info from `history` in the config file... either upgrade your registry (unlikely, but preferred) or see if the buildpacks folks can populate a history when they're producing those images

With that I'm going to close this as it definitely doesn't appear to be a skopeo issue. Thanks for the responses.
