### ISSUE TITLE
README: Package 'libbtrfs-dev' doesn't exist on Ubuntu < 18.10

### ISSUE THREAD

**Issue by fhemberger** [containers/skopeo#672]
I'm building skopeo in a container on Ubuntu 18.04 LTS, the package `libbtrfs-dev` only exists in versions 10.10 and above.

(Also at least registry to registry copying seems to work fine without it.)

**Comment by rhatdan** [comment]
Can't you eliminate  btrfs from the build?

**Comment by fhemberger** [comment]
I just left out installing the dependency and so dar, it seems to work fine.
Not sure why you list it as build dependency and where it's needed.

**Comment by rhatdan** [comment]
I think it is needed if you were building with containers/storage == btrfs.

**Comment by mtrmac** [comment]
IIRC the dependency has always been there, it’s just that before 18.10 it was not necessary to install `libbtrfs-dev` for it (#664). I haven’t looked very hard for other ways to get this working on 18.10, to be fair.

PRs are welcome if there is some other dependency that can be used to pull in the required headers, as long as it works on 18.10 and we can keep the README and `Dockerfile.build` consistent; it’s been hard enough to keep `Dockerfile.build` up-to-date when most development of this package is Fedora-based, so keeping a completely separate and likely-to-be-outdated instructions in README for other versions of Ubuntu is not very attractive.
