### ISSUE TITLE
Rootless installation

### ISSUE THREAD

**Issue by alazzaro** [containers/skopeo#687]
Current installation instructions reports

```
sudo make install
```

Is it possible to avoid the sudo?
I tried:

```
make install PREFIX=<local installation>/skope
```
and this is the output:
```
install -d -m 755 /home/alazzaro/Work/containers/charliecloud/deps/skopeo/bin
install -m 755 skopeo /home/alazzaro/Work/containers/charliecloud/deps/skopeo/bin/skopeo
install -d -m 755 /home/alazzaro/Work/containers/charliecloud/deps/skopeo/share/man/man1
install -m 644 docs/*.1 /home/alazzaro/Work/containers/charliecloud/deps/skopeo/share/man/man1/
install -m 755 -d /home/alazzaro/Work/containers/charliecloud/deps/skopeo/share/bash-completion/completions
install -m 644 completions/bash/skopeo /home/alazzaro/Work/containers/charliecloud/deps/skopeo/share/bash-completion/completions/skopeo
install -d -m 755 /var/lib/atomic/sigstore
install: cannot create directory ‘/var/lib/atomic’: Permission denied
```
If I do ignore the error, later on I get the file at `/etc/containers/policy.json ` is missing.

Any comment is welcome.

**Comment by rhatdan** [comment]
sigstore should be optional and configurable.  We should change the default to /var/lib/containers/sigstore also.

skopeo  --insecure-policy 

Should remove the problem with no policy.json

**Comment by mtrmac** [comment]
The policy configuration might be easier to use with https://github.com/containers/image/pull/922 .

**Comment by mtrmac** [comment]
> Is it possible to avoid the sudo?
> I tried:
> 
> ```
> make install PREFIX=<local installation>/skope
> ```

I’m sorry about the terribly late response; the right variable to use is `DESTDIR`. That does allow an unprivileged `make install` to complete, but the built binary will still refer to various paths outside the home directory. (See also https://github.com/containers/skopeo/issues/787 ).

**Comment by mtrmac** [comment]
Closing in favor of #787 .
