### ISSUE TITLE
Export container images from ostree fails

### ISSUE THREAD

**Issue by dcode** [containers/skopeo#702]
I'm trying to use ostree as a storage repository to store container images on ISO media so that I can import them later into container storage for podman to use. My understanding is that if this all works out, I'll be able to potentially save a ton of space by deduplicating layers vs exporting tarballs for each image I need to transfer.

Without further ado, here's what I'm trying:

### Copy into ostree
```bash
mkdir repo
ostree --repo=repo init
skopeo copy docker://docker.io/library/alpine:latest ostree:docker.io/library/alpine:latest@${PWD}/repo
```
Output:
```
Getting image source signatures
Copying blob 050382585609 [======================================] 2.7MiB / 2.7MiB
Copying config b7b28af77f [======================================] 1.5KiB / 1.5KiB
Writing manifest to image destination
Storing signatures
```

### Copy out of ostree
```
sudo skopeo copy ostree:docker.io/library/alpine:latest@${PWD}/repo containers-storage:docker.io/library/alpine:latest
```
Output:
```
Getting image source signatures
Copying blob 1bfeebd65323 [======================================] 5.6MiB / 5.6MiB
FATA[0000] Error writing blob: blob size mismatch
```

### Try export to tar instead
```
sudo skopeo copy ostree:docker.io/library/alpine:latest@${PWD}/repo docker-archive:../alpine.tar
```
Output:
```
Getting image source signatures
Copying blob 1bfeebd65323 [======================================] 5.6MiB / 5.6MiB
FATA[0000] Error writing blob: archive/tar: write too long
```

## Expected Behavior

I expected that I would be able to round-trip export from ostree into local container storage, or at least into a oci archive.

As an aside, I'd like to do this file copy from ostree to containers-storage while installing the OS (i.e. in an Anaconda %post script). Since the installed system is a chroot, to complete the copy do I need to update `/etc/containers/storage.conf` to point to the chroot?

**Comment by mtrmac** [comment]
Thanks for your report.  This should hopefully be fixed by https://github.com/containers/image/pull/678 .

(If you have duplicate _layers_, and not just duplicate files within layers, consider using the `oci:` transport: it stores each layer as a single unfragmented (potentially compressed) bit file, instead of hundreds of small fragmented files all over the filesystem.)

**Comment by mtrmac** [comment]
WRT pointing to a c/storage store created inside a chroot, I’m not sure. @nalind can hopefully help.
