### ISSUE TITLE
Why does Skopeo use so much memory when saving to local dir?

### ISSUE THREAD

**Issue by ivanstanev** [containers/skopeo#714]
I'm running a container inside Kubernetes with a memory limit set to 2 GB. The container has `skopeo` installed (based on `fedora:30`; using `dnf install skopeo`) and I'm trying to copy a very large image (4 GB) to disk using this command:
`skopeo copy docker://jgilli/4gb:latest dir:/cache/jgilli/4gb`
I'm monitoring my container using Grafana and I notice that I hit the 2 GB memory limit (100%) for a period of time... K8s doesn't OOM kill because I seem to have plenty of memory on the node.

What I'm wondering is why the tool is using so much memory (equivalent to the image size) when copying to a local directory? I notice that the file on disk grows in chunks over time so surely skopeo streams it to disk? Could you please advise?

**Comment by mtrmac** [comment]
Thanks for your report.

Is that actually used or virtual memory? On macOS, I see maximum RSS less than 27 MB, which seems plausible nowadays (although, sure, pretty large for a HTTP client compared to the old days of pure C and little RAM) — and 4.25 GB of virtual memory, which does seem a lot, but does not actually hurt anything I think.

Does https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory explain what is going on?

**Comment by ivanstanev** [comment]
OK I think it may not be actually an issue with Skopeo, I've been digging deeper and I have this theory:
The local machine I'm testing on has a modest downloading speed of 3 MB/sec, and indeed skopeo uses a few megabytes of RAM. However, when testing the same code in Google Cloud, the download speed there is 100 MB/sec... Is it plausible to assume the downloading speed is much higher than the speed of writing to disk, which results in buffering of the data in memory?

**Comment by mtrmac** [comment]
Not very; most of the code has, I expect, fixed-size buffers and would just block if the consumers of the data are slower than the producers.

Please start by actually precisely defining what kind of “memory usage” are you measuring, and what that measure means.

**Comment by ivanstanev** [comment]
OK thank you for the insight

What I'm monitoring in Grafana is physical memory used by the pod as reported by kubelet and kube state metrics. While the 4GB Docker image is being copied, the memory usage is 2GB (exactly the limit set for the container). Interestingly enough, the cgroup data (`cat /sys/fs/cgroup/memory/memory.stat`) is:
```...
total_cache 1176494080
total_rss 45084672
...```

So I have to trust the 2GB metric as that is what Kubernetes trusts. What worries me is Kubernetes may decide to randomly kill the pod since I've hit the 2GB memory limit. That's why I'm trying to understand why this memory usage is so high, in this state I won't be able to use skopeo and trusting it won't blow up unexpectedly 😕

**Comment by ivanstanev** [comment]
OK I found out more information about what is happening and I believe you can close this issue as I've gotten to the root of the cause :) 

It seems that the metric reported by Grafana is the following:
`container_memory_usage_bytes = container_memory_rss + container_memory_cache + container_memory_swap`

The actual memory used by the process (RSS) is roughly 50 MB; this is the metric that Kubernetes indeed uses. The top up to 2GB happens because a lot of memory is _cached_, which appears in the Grafana reporting. So the metric I've been looking at is slightly misleading as K8s doesn't treat the cached memory as the real memory usage of the process. So there's nothing wrong with skopeo and it's working just fine, feel free to close this issue!

**Comment by paneda1998** [comment]
hi
i have same problem
after reading this issue i check my grafana and this is some example:
![11](https://user-images.githubusercontent.com/52179148/226090719-1ca08cab-2df1-4636-a2c8-7cc4d43ea6b9.png)

its about 500MB of RSS memory and 0 to 600 Mb of cache memory.
and it seems RSS value is about half of ram limit of pod
for example this result is for 1Gb ram limit
if i set it to 2Gb everything is multiple by 2.


and another problem is RSS+cache is causing oom kill not only RSS
