### ISSUE TITLE
Yaml dependency version

### ISSUE THREAD

**Issue by MericCelik** [containers/skopeo#721]
Hello,

The latest release of skopeo (0.1.39) has a dependency of a quite an old version of yaml package, which can be seen as
`gopkg.in/yaml.v2 v2.0.0-20141029210843-d466437aa4ad`. 

In this commit, the library is licensed under LGPLv3. It seems that this changed to Apache 2.0 in newer releases. Would you consider to update this dependency? 

I also want to mention that there might be a problem with the vendor version. The commit id of the dependency belongs to a much older release, rather than v2.0.0. The license file in the skopeo's yaml vendor and the license file in the v2.0.0 release in the yaml Github repo does not match as well. So if I'm not mistaken, skopeo uses a yaml package version older than 2.0.0. Maybe a problem occured during the vendoring.

Hope it helps!

**Comment by vrothberg** [comment]
Hi @MericCelik, thanks for opening the issue. I've opened PR https://github.com/containers/skopeo/pull/722 to update the dependency to the latest release.

**Comment by mtrmac** [comment]
#736 has updated the library. Thanks for your report!
