### ISSUE TITLE
AWS ECR: skopeo inspect fails because of 403

### ISSUE THREAD

**Issue by maust** [containers/skopeo#726]
skopeo inspect does not work with AWS ECR as the docker registry seems to return 403 when retrieving the tags.

```
skopeo inspect --creds=AWS:`cat token` docker://$AWS_ACCOUNT.dkr.ecr.eu-central-1.amazonaws.com/NAME:TAG
time="2019-09-19T20:46:48Z" level=fatal msg="Error determining repository tags: Invalid status code returned when fetching tags list 403 (Forbidden)"
```

While skopeo works without problems as it doesn't need to list the tags.
```
skopeo copy --src-creds=AWS:`cat token` docker://$AWS_ACCOUNT.dkr.ecr.eu-central-1.amazonaws.com/NAME:TAG dir:temp
Getting image source signatures
Copying blob sha256:xxx
Copying blob sha256:xxx
Copying config sha256:xxx
Writing manifest to image destination
Storing signatures
```

From my understand this is caused by https://github.com/containers/skopeo/blob/c4b0c7ce05cd601e62dfe8ecfde4fed42062dbdd/cmd/skopeo/inspect.go#L180 only gracefully allowing 401 (for IBM Bluemix) but not 403. 

Would it be fine to allow 403 as well?

**Comment by mtrmac** [comment]
Sure, if it is necessary — but we’ve had at least _some_ successful users of the library before, so I’d expect that this has worked previously.

Is this a new behavior change? Or is, perhaps, the credential token restricted so that it’s not allowed to list tags, or something like that? (Supporting less-privileged accounts would still be a good enough reason to make this optional, I’d just like to understand what is actually going on, if possible.)

**Comment by mtrmac** [comment]
(Also, as far as code is concerned, the error detection should be moved to c/image so that all callers benefit.)

**Comment by maust** [comment]
I did some further testing with other AWS accounts and IAM settings. This was caused by not allowing the user the Action "ecr:ListImages".

Not sure how important it is for others to still use skopeo inspect while not giving the users/roles in AWS IAM the action "ecr:ListImages". In our accounts I just added the action.

Feel free to close if you don't see any benefit to change it.

**Comment by mtrmac** [comment]
Thanks, that’s very helpful. I’ve created #738 to not fail fatally in this case. Could you verify that it works as expected, please?
