### ISSUE TITLE
`inspect --raw` fails for manifest list with no amd64 platform

### ISSUE THREAD

**Issue by twaugh** [containers/skopeo#729]
When using `skopeo inspect --raw` against a docker manifest list, an error is given unless the manifest list happens to reference an image manifest for the current platform, or the platform matching the `--override-*` parameters.

See #634 for an example of this.

When `--raw` is provided, can `inspect` show the raw manifest list, without requiring any particular platform to be present?

**Comment by lslebodn** [comment]
I tried to use `skopeo inspect --raw` to get all supported architectures of checked image,
And it does not work if architecture of skopeo (x86_64 in my case) is not available in the `manifest.list.v2`. (arm64 was the only one available in `manifest.list.v2`).

**Comment by vrothberg** [comment]
Hi @twaugh, thanks for opening the issue. @nalind is currently working on proper manifest list support in containers/image which will improve the situation for skopeo.

**Comment by nalind** [comment]
This should have been fixed by #708.  Are you running a version that's older?

**Comment by twaugh** [comment]
Oh, I am running an older version, yes. Thanks, didn't spot that commit.

**Comment by lslebodn** [comment]
I can confirm it works with skopeo-1:0.1.40-0.9.dev.git7eb5f39.fc32.x86_64
