### ISSUE TITLE
Document skopeo copy source and destination are independent

### ISSUE THREAD

**Issue by sagikazarmark** [containers/skopeo#730]
As indicated in the title, the following command results in a tar archive without repo tags:

```bash
skopeo --insecure-policy --override-os linux --override-arch amd64 copy docker://registry:2.7 docker-archive:registry.tar
```

The manifest:

```json
[{"Config":"f32a97de94e13d29835a19851acd6cbc7979d1d50f703725541e44bb89a1ce91.json","RepoTags":[],"Layers":["d9ff549177a94a413c425ffe14ae1cc0aa254bc9c7df781add08e7d2fba25d27.tar","f641ef7a37ad012032e488c4993d85505ad3ac3cc0152f5f46bc561431227262.tar","d5974ddb5a45481f4d5444c8f598c3d9f4af31fb2426114d2dd1a91b58ea23b0.tar","5bbc5831d696eb5c734bfa52770bcfed7ef96435fbde028ceb431994dc413ff0.tar","73d61bf022fd2090ae075becdf0f69f924b3764331b2abba2efb3c88e5ae369e.tar"]}]
```

If I specify additional tags option, the tag shows up in the manifest:

```
skopeo --insecure-policy --override-os linux --override-arch amd64 copy --additional-tag registry:2.7 docker://registry:2.7 docker-archive:registry.tar
```

Is this the expected behavior? Unfortunately, I couldn't find any reference in the docs.

**Comment by mtrmac** [comment]
Thanks for your report.

Yes, this seems to work as expected. The source and destination of `skopeo copy` are treated completely independently, the names used for in source reference don’t influence the behavior of the destination in any way.  A destination `docker-archive:`_path_ means “create an archive with that image, and don’t give it a name”.

As you note, `--additional-tag` is one way to add a tag.

The primary way to do this is to use the full format for the destination reference, `docker-archive:`_path_`:`_tag_.  For example,
```
skopeo … copy docker://registry:2.7 docker-archive:registry.tar:registry:2.7
```
results in a `"RepoTags":["docker.io/library/registry:2.7"]` entry in the manifest.

This is somewhat documented in https://github.com/containers/skopeo/blob/master/docs/skopeo.1.md#image-names or https://github.com/containers/image/blob/master/docs/containers-transports.5.md#docker-archivepathdocker-reference , though it probably could be clearer.

Does this work for you?

**Comment by sagikazarmark** [comment]
Absolutely, thank you!

I think it would be a good idea to clarify this in the documentation, because users (including myself) would expect this command to be a 1:1 alternative to `docker save`.

Thanks again for the detailed answer!

**Comment by mtrmac** [comment]
> users (including myself) would expect this command to be a 1:1 alternative to `docker save`.

That’s not at all what `skopeo` promises (starting with the mandatory `docker://` prefixes). 

1:1 alternative to the docker CLI is one of the goals of `podman`, which does have a `podman save` command — but then again, that one, being equivalent, does not allow creating a tarball directly from a remote registry.

**Comment by mtrmac** [comment]
(Leaving this open to track the possible improvements to the documentation.)

**Comment by sagikazarmark** [comment]
> That’s not at all what `skopeo` promises (starting with the mandatory `docker://` prefixes).

I'm not saying it does 🙂 . All I'm saying users probably expect it.

**Comment by rhatdan** [comment]
@sagikazarmark PR's to improve the docs are always appreciated.
@TomSweeneyRedHat FYI
