### ISSUE TITLE
Block registries 

### ISSUE THREAD

**Issue by Numblesix** [containers/skopeo#739]
Hi,

How can i block a Registry from beeing pulled from when using cri-o & runc ? 

I found this line in `/etc/containers/registries.conf`: 
```
# If you need to block pull access from a registry, uncomment the section below
# and add the registries fully-qualified name.
#
# Docker only
[registries.block]
registries = ["all"]
```
But i was able to pull an image from gcr.io

```
[foo@01 ~]$ sudo crictl images
IMAGE                                                    TAG                 IMAGE ID            SIZE
gcr.io/kubernetes-helm/tiller                            v2.14.3             2d0a693df3ba4       96.6MB
```

**Comment by mtrmac** [comment]
I’m afraid I don’t think blocking `"all"` ever worked.

Blocking individually listed registries was implemented in most tools like CRI-O for some time.  containers/image ≥ 3.0.0 globally enforces the blocking option (but does not add `"all"`), and with the version 2 format that  allows blocking individual repos or namespaces as well.

If you want to set up a whitelist, blocking “all” can alternatively be done by setting a default policy (or a transport-default policy) using signature verification `policy.json`. In OpenShift, the machine-config-operator can set that up based on https://github.com/openshift/api/blob/master/config/v1/types_image.go .

If this does not work, please file a full bug report, including version numbers, against the relevant project; CRI-O bugs should be visible to CRI-O maintainers.
