### ISSUE TITLE
Makefile: drop static and in-container targets

### ISSUE THREAD

**Issue by vrothberg** [containers/skopeo#755]
Based on https://github.com/containers/skopeo/pull/670#issuecomment-548452484:

>Ideally, I’d prefer dropping both statically-linked builds for Linux (which are unreliable and functionally restricted) and in-container builds (which are a good idea in theory, but keep breaking because we don’t use them, and don’t work with dynamically-linked builds).
>
>Dropping the statically-linked targets would be a good first step — though this PR suggests that the in-container builds might also be broken, independently.

**Comment by rhatdan** [comment]
Ok lets drop them, and move to container based.

**Comment by mtrmac** [comment]
Why was this closed? It is still outstanding.

**Comment by vrothberg** [comment]
I agree.

**Comment by rhatdan** [comment]
I saw the two PRs Issues closed and assumed it was no longer present.

**Comment by mtrmac** [comment]
Meanwhile, #932 has replaced `make binary-static` with a Nix-based variant.

What is the consensus now? Keep Nix as opt-in, and drop the container build?

**Comment by rhatdan** [comment]
SGTM,  As long as community maintainers nix build, I am fine with it.  The container build to me is the wrong default.  Just do a local build.

**Comment by rhatdan** [comment]
static builds nix if available, and I am changing defaults.  Leaving binary to build in container in case people want it.

**Comment by lsm5** [comment]
Closing. in-container build target has already been dropped and nix build was recently dropped with https://github.com/containers/skopeo/pull/1463
