### ISSUE TITLE
[Question] Is it possible to upload only the config and manifest, and skip the layers?

### ISSUE THREAD

**Issue by ndbroadbent** [containers/skopeo#759]
I'm working on some very experimental code that allows me to merge and slice the layers in Docker images: https://github.com/DocSpring/docker_merge
(I'm using Docker for Mac.)

The idea is that I use skopeo to copy the image from the docker daemon into a directory. Then I [wrote some code](https://github.com/DocSpring/docker_merge/blob/master/lib/docker/merge.rb) that merges multiple manifests/configs together, and updates the digests, sizes, etc. Finally, I use skopeo to push the merged image from the directory back to the docker daemon.

This is actually working, and [I wrote a few tests that are all passing](https://github.com/DocSpring/docker_merge/blob/master/test/test_docker_merge.rb). (Another thing I tested: I set up a workflow where I compile Ruby using `*-dev` packages. Then I slice out the Ruby layer from the `make install` command, create a new Docker image that only includes runtime packages, and merge those two images together.)

The only problem is that pushing and pulling the layers is really slow, and the layers aren't actually changing. I cloned the skopeo repo and experimented with [commenting out some of the "copy layer" calls](https://github.com/containers/skopeo/blob/master/vendor/github.com/containers/image/v5/copy/copy.go#L578-L580):

```
$GOPATH/src/github.com/containers/skopeo/skopeo --debug --insecure-policy copy docker-daemon:merge-test:latest dir:dump/
DEBU[0001] No compression detected
DEBU[0003] Using blob info cache at /Users/myuser/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0003] No compression detected
DEBU[0003] No compression detected
DEBU[0003] IsRunningImageAllowed for image docker-daemon:docker.io/library/merge-test:latest
DEBU[0003]  Using default policy section
DEBU[0003]  Requirement 0: allowed
DEBU[0003] Overall: allowed
Getting image source signatures
DEBU[0003] No compression detected
DEBU[0003] Using original blob without modification
Copying config 985b312a99 done
Writing manifest to image destination
Storing signatures
```

But that didn't seem to work. (Nothing shows up in `docker images`.)

Is there any way I can hack `containers/image` to skip uploading the layers that already exist in Docker? I often see "Layer already exists" when I push images to a Docker registry, so I'm wondering if skopeo might also be able to skip existing layers. Is that not supported by the docker daemon on my local machine?

Thanks for your help!

(P.S. This is mainly an experimental weekend project to learn more about Docker.)

**Comment by ndbroadbent** [comment]
I was able to get something working with this change: https://github.com/DocSpring/skopeo/commit/80acb3892ab07d3ff05060b5be5bfb051c2368e8

Merging multiple Docker layers now seems to work, and it creates a new tagged image. (`rake TEST=test/test_docker_merge.rb` in my `docker_merge` repo). 

But I also have some layer "slicing" code that breaks with this change. This code removes layers from an image and regenerates the manifest + config. `skopeo` runs without any errors, but then the image doesn't appear in `docker images`:

```
$ rake TEST=test/test_docker_slice.rb
...
Pushing sliced Docker image to docker-daemon:slice-test:bar-ab7ce64208...
DEBU[0000] Using blob info cache at /Users/myuser/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] IsRunningImageAllowed for image dir:/private/var/folders/9t/hpqz7_5s27dc8_j_2hd7p_7h0000gn/T/d20191103-4262-45cwtt
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
DEBU[0000] Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json]
DEBU[0000] ... will first try using the original manifest unmodified
DEBU[0000] No compression detected
DEBU[0000] Using original blob without modification
DEBU[0000] Sending as tar file 48adfdd652357960aa65183c4a29c1b1e0dddb1e2cd2bbe6840105ca4d98febe.json
DEBU[0000] Sending as tar link 3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b/layer.tar -> ../3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b.tar
DEBU[0000] Sending as tar file 3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b/VERSION
DEBU[0000] Sending as tar file 3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b/json
DEBU[0000] Sending as tar link 045e910d44f1e6c336c5d7872f123f33de6f06ae2e84b1a2507d40f63cfd2a04/layer.tar -> ../7cbaf86cafa1d843df6644d03c63c3f1dad0e1c465fef229bdd402cb5ec6d860.tar
DEBU[0000] Sending as tar file 045e910d44f1e6c336c5d7872f123f33de6f06ae2e84b1a2507d40f63cfd2a04/VERSION
DEBU[0000] Sending as tar file 045e910d44f1e6c336c5d7872f123f33de6f06ae2e84b1a2507d40f63cfd2a04/json
DEBU[0000] Sending as tar file repositories
DEBU[0000] Sending as tar file manifest.json
DEBU[0000] docker-daemon: Closing tar stream
DEBU[0000] docker-daemon: Waiting for status
DEBU[0000] docker-daemon: sending done, status <nil>
Unable to find image 'slice-test:bar-ab7ce64208' locally
```

I'd be interested to know why this works when I add *more* layers to an image, but it doesn't work when I remove layers.

**Comment by rhatdan** [comment]
@nalind Are your fixes making this possible?

**Comment by nalind** [comment]
@rhatdan not really.  This looks like it's a result of the way `docker-daemon` handles writing images to the daemon: by creating an [image tarball](https://docs.docker.com/engine/api/v1.24/#image-tarball-format) and uploading it to the daemon using [its `/images/load` endpoint](https://docs.docker.com/engine/api/v1.40/#operation/ImageLoad).

Looking at [the API docs](https://docs.docker.com/engine/api/latest/), I don't see an efficient way of checking which layers the daemon already has, which we'd probably need to be able to do in order to be able to figure out which layers we could omit from the image tarball that we generate for uploading.

Whether or not we can get enough information to be able to confidently skip copying layers is going to vary from transport to transport.

**Comment by ndbroadbent** [comment]
Thanks for looking into this @nalind! Your comment helped me understand more about how the docker daemon API works.

I checked the docker-daemon logs inside the docker VM, and I realized that the `/images/load` endpoint behaves slightly differently depending on the order of the layers.

For example, I am setting up three Docker images like this:

```
FROM alpine:3.7
RUN echo "foo" > /tmp/a
```

```
FROM alpine:3.7
RUN echo "bar" > /tmp/b
```

```
FROM alpine:3.7
RUN echo "baz" > /tmp/c
```

When I merge the second layers from all of these images, the docker-daemon just shows:

```
2019-11-04T16:00:19Z docker time="2019-11-04T16:00:19.260331600Z" level=debug msg="Calling POST /v1.22/images/load?quiet=1"
```

So this works if I omit all of the layers from the uploaded image. 

I found the code in `image/tarexport/load.go` that calls `l.lss[os].Get(r.ChainID())` to see if the layer already exists: https://github.com/moby/moby/blob/ac7306503d237d548e376a89ab0b899ea1a245b0/image/tarexport/load.go#L111-L117

So if the `.Get` call fails and sets `err`, then it tries to read and decompress the layer.

However, when I reverse the order of the layers, then Docker needs to apply diffs to create new layers in the storage:

```
2019-11-04T16:00:19Z docker time="2019-11-04T16:00:19.260331600Z" level=debug msg="Calling POST /v1.22/images/load?quiet=1"
2019-11-04T16:00:20Z docker time="2019-11-04T16:00:20.317554600Z" level=debug msg="Applying tar in /var/lib/docker/overlay2/a15e9178ecd1dfe98d65910edb33f294abeaf63a59a0af9c1edcfd9a2c4cb9b7/diff" storage-driver=overlay2
2019-11-04T16:00:20Z docker time="2019-11-04T16:00:20.499233300Z" level=debug msg="Applied tar sha256:8a2e89c58292658a353f65fe2ffb091f9dd2345fd307742cbbe447947c84256b to a15e9178ecd1dfe98d65910edb33f294abeaf63a59a0af9c1edcfd9a2c4cb9b7, size: 4"
2019-11-04T16:00:20Z docker time="2019-11-04T16:00:20.552154300Z" level=debug msg="Applying tar in /var/lib/docker/overlay2/b035fa41e12d866e980574cbd43afbcf69f2ca6aa5a5c0c7b5bae6a8b72925ba/diff" storage-driver=overlay2
2019-11-04T16:00:20Z docker time="2019-11-04T16:00:20.690301700Z" level=debug msg="Applied tar sha256:5ecb620e7b4c739d9900d25909dd76e61cc8498e09c0fba7267daffb60c6d641 to b035fa41e12d866e980574cbd43afbcf69f2ca6aa5a5c0c7b5bae6a8b72925ba, size: 4"
2019-11-04T16:00:20Z docker time="2019-11-04T16:00:20.767376300Z" level=debug msg="Applying tar in /var/lib/docker/overlay2/2ed5413eeda20ea433817bc7ddcf7ed2c0da176f32fbead86e2040de52d23d99/diff" storage-driver=overlay2
2019-11-04T16:00:20Z docker time="2019-11-04T16:00:20.910371000Z" level=debug msg="Applied tar sha256:5ff35ad8d3abe69ba270edac7dd98c907fb64190c4e03a730608a388b55bfdc6 to 2ed5413eeda20ea433817bc7ddcf7ed2c0da176f32fbead86e2040de52d23d99, size: 4"
2019-11-04T16:00:20Z docker time="2019-11-04T16:00:20.935932800Z" level=debug msg="Applying tar in /var/lib/docker/overlay2/7a197507b6d7adbabdc0087e23e25a5dfac7d7598afd310660313764426acf84/diff" storage-driver=overlay2
2019-11-04T16:00:21Z docker time="2019-11-04T16:00:21.608511800Z" level=debug msg="Applied tar sha256:3fc64803ca2de7279269048fe2b8b3c73d4536448c87c32375b2639ac168a48b to 7a197507b6d7adbabdc0087e23e25a5dfac7d7598afd310660313764426acf84, size: 4206494"
```

And this step fails when the layers are missing:

```
2019-11-04T16:18:42Z docker time="2019-11-04T16:18:42.158727900Z" level=debug msg="Calling POST /v1.22/images/load?quiet=1"
2019-11-04T16:18:42Z docker time="2019-11-04T16:18:42.578028600Z" level=debug msg="Error reading embedded tar: open /var/lib/docker/tmp/docker-import-110379999/8a2e89c58292658a353f65fe2ffb091f9dd2345fd307742cbbe447947c84256b.tar: no such file or directory"
```

Anyway, I think I have a better idea of how this works, and which layers are safe to omit (the base layer, and any layers where I haven't changed the order so the diff doesn't need to be updated.)

Thanks again for your help!
