### ISSUE TITLE
problem with --src-creds and --dest-creds

### ISSUE THREAD

**Issue by jave** [containers/skopeo#761]
I am attempting to copy images between two openshift container registries.

I can log in to podman to both registry endpoints. I can then use the resulting auth.json file to authenticate to both registries, and copy the image. All good so far.

Now I want to use the --src-creds and --dest-creds flags instead, so I dont have to use podman to login.

I get: unable to retrieve auth token: invalid username/password  

username password are the same credentials I use with podman.

**Comment by mtrmac** [comment]
Thanks for your report.

That’s really rather surprising, I can’t see how this could be possible. As a wild last-ditch guess, you entering _passwords_ (the same entered for `podman login`) on the skopeo CLI, not the base64-encoded data stored in `auth.json`, aren’t you?

Can you try `skopeo inspect --creds` one image at a time, to see whether it happens for the source, destination, or both?

**Comment by jave** [comment]
- it happens for both test and prod clusters(these are openshift 4.1 and 4.2 clusters respectively

- I use --creds username:password. For good measure I also tested the base64 encoded password from the .auth file, it was the same result.

- I use the fedora packaged skopeo, version 0.1.3.7

I can test to build skopeo from src and see if it makes any difference

**Comment by jave** [comment]
I tested with a locally built skopeo from todays git. I had the same problem.

I also tested on another fedora machine, and same problem again.

I tried having a look with strace but didnt figure anything out.

both clusters are running on aws, if it makes any difference.

**Comment by mtrmac** [comment]
Does `podman pull --creds …` work?

**Comment by jave** [comment]
Turns out I made a mistake during my testing at some point.

The only thing that is documented to work in my case, is using openshift service accounts with token based security. That works well with skopeo.

Thanks for your patience.
