### ISSUE TITLE
Copy an image index from oci format to a docker registry

### ISSUE THREAD

**Issue by xlucas** [containers/skopeo#764]
I'm trying to leverage `docker buildx` toolchain to create an OCI image index that I can then push to docker hub later with `skopeo`. I'm running this:

```
# docker buildx build --platform=linux/amd64,linux/arm64 -f Dockerfile -o type=oci,dest=./test.tar
# ./skopeo copy oci-archive:test.tar docker://docker.io/myusername/test -a
```

The result of the latter is:

```
Getting image list signatures
Copying 2 of 2 images in list
Copying image sha256:ffe52a6807245eb5fde1b3fd17cd8538d29eda21375b6526a729ac9929a42ba9 (1/2)
Getting image source signatures
Copying blob c7b7d16361e0 skipped: already exists
Copying blob b7a128769df1 skipped: already exists
Copying blob 1128949d0793 skipped: already exists
Copying blob 667692510b70 skipped: already exists
Copying blob c70d80036479 skipped: already exists
Copying blob 50f26e2b5c7f skipped: already exists
Copying blob 2ea72dab87cf skipped: already exists
Copying blob 05b6d4a9b03e skipped: already exists
Copying blob 948eb7bd221f skipped: already exists
Copying blob ab12078a6410 skipped: already exists
Copying config d03553b62e done
Writing manifest to image destination
Storing signatures
Copying image sha256:ef7aa3acf35768448d1530aff5b65c933c949a06726331cea9d18282fa18cc7e (2/2)
Getting image source signatures
Copying blob 5a8521f5974d skipped: already exists
Copying blob dd1378028f1d skipped: already exists
Copying blob 15cab53b0844 skipped: already exists
Copying blob f6b3955dadc0 skipped: already exists
Copying blob 56c70e5b63d1 skipped: already exists
Copying blob 311d908f8944 skipped: already exists
Copying blob 1f21fa0d440a skipped: already exists
Copying blob c88f6a1b2836 skipped: already exists
Copying blob e94fdee810e0 skipped: already exists
Copying blob 102a73ab614b skipped: already exists
Copying config 43606257e0 done
Writing manifest to image destination
Storing signatures
Writing manifest list to image destination
Storing list signatures
```

And nothing appears in docker hub.
Is it possible to do this?

**Comment by mtrmac** [comment]
@nalind ?

**Comment by btashton** [comment]
@xlucas I saw some funny behaviour doing this as well on a non docker.io repository.  I capture the http requests and the manifest list json looked something like this:

```
{
   "schemaVersion":2,
   "manifests":[
      {
         "mediaType":"application/vnd.docker.distribution.manifest.v2+json",
         "digest":"sha256:e9818a25b9c9aa2bfaabd4459ae8baa4c4f02e392cb835a5d8895a2f00bc53c1",
         "size":749,
         "platform":{
            "architecture":"amd64",
            "os":"linux"
         }
      },
      {
         "mediaType":"application/vnd.docker.distribution.manifest.v2+json",
         "digest":"sha256:8cc2a397a9e7dd4e2cef626bad3066e3e8c552a665f09547d3aab52f5b902772",
         "size":749,
         "platform":{
            "architecture":"arm64",
            "os":"linux"
         }
      }
   ]
}
```

Which is missing the `mediaType` for the manifest list itself which I do not believe is valid.  I found this intermediate step produced the correct manifest list.

```
docker buildx build --platform linux/amd64,linux/arm64  -o type=oci,dest=- . > myimage-oci.tar
skopeo  copy  --dest-tls-verify=false --dest-creds=admin:password oci-archive:myimage-oci.tar dir:tmp -f v2s2 --all
skopeo  copy  --dest-tls-verify=false --dest-creds=username:password dir:tmp docker://localhost:8081/docker-local/hello --all
```
I will dig in and see what is going on here with the missing mediaType, but I would be curious if this solves the problem for you with docker.io

**Comment by btashton** [comment]
Adding `-f v2s3` to the copy resolved it for me, but it is not clear why this would need to be explicitly set.

**Comment by vrothberg** [comment]
> -f v2s3

That's looks like a typo and should be `v2s2`. This observation can be explained with Docker Hub having issues displaying images in the OCI format. The images are on the registry but the web UI apparently has issues displaying them, see https://github.com/docker/hub-feedback/issues/1871. According to Docker, the bug should soon be fixed.

**Comment by btashton** [comment]
@vrothberg Yes that was a type'o in my comment, but as I said the manifest list is missing `mediaType` if I copy without supplying the v2s2 which does not seem correct to me and some registries will reject.

**Comment by vrothberg** [comment]
Apologies for missing that part. I reopened the issue and will have a look after a fresh coffee :)

**Comment by vrothberg** [comment]
The mediatype is missing because the go-specs of the image spec do not implement it which to me looks like a bug upstream since the image spec requires the media type. I'll open a PR upstream.

Thanks for the additional report, @btashton !

**Comment by mtrmac** [comment]
@vrothberg is there an upstream (?) issue we could link to?

**Comment by mtrmac** [comment]
… found it I think: https://github.com/opencontainers/image-spec/pull/795 .

An OCI index is valid without the `mediaType` field (in fact, per the above, invalid with it). It is a bit surprising to have an OCI index that points to Docker v2s2 images, admittedly.

Do I understand correctly that the image, using the simplest default workflow (`skopeo copy --oci-archive:… docker://…`, no `--format` option) does work and can be pulled successfully, and it’s _only_ the Docker Hub UI that doesn’t show it?

**Comment by vrothberg** [comment]
> … found it I think: [opencontainers/image-spec#795](https://github.com/opencontainers/image-spec/pull/795) .
> 
> An OCI index is valid without the `mediaType` field (in fact, per the above, invalid with it). It is a bit surprising to have an OCI index that points to Docker v2s2 images, admittedly.

I guess we can close this issue?

> Do I understand correctly that the image, using the simplest default workflow (`skopeo copy --oci-archive:… docker://…`, no `--format` option) does work and can be pulled successfully, and it’s _only_ the Docker Hub UI that doesn’t show it?

Now it does. There was an issue last year where Docker Hub UI did not show OCI images.

**Comment by mtrmac** [comment]
If the code generates valid OCI images, and they are actually usable on the registry, yes, I think we can close this. Thanks for the confirmation.
