### ISSUE TITLE
registries.d option not working

### ISSUE THREAD

**Issue by smekkley** [containers/skopeo#769]
The following command gives an error.
`# skopeo  --registries.d=$conf_dir copy --sign-by someid docker://$registry/$image docker://$registry/$image2`

The error:
`FATA[0001] Error writing signatures: X-Registry-Supports-Signatures extension not supported, and lookaside is not configured`

default.yaml is the following. When I don't set `--registries.d` and use the  /etc/containers/registries.d/ directory by default with the same config, the error doesn't occur.

```
default-docker:
  sigstore-staging: file:///var/lib/atomic/sigstore
```

**Comment by mtrmac** [comment]
Thanks for your report.

Please include the output with the `--debug` option (`skopeo --debug --registries.d…`).

**Comment by smekkley** [comment]
Sorry, it was typo. I was specifying an directory that doesn't exist. Closing the issue.
