### ISSUE TITLE
Skopeo picks wrong credentials from .docker/config.json on copy

### ISSUE THREAD

**Issue by dastrobu** [containers/skopeo#773]
I am trying to copy an image from one private registry to another one with 
```
skopeo copy docker://some-docker-registry.com/source-registry/my-image:1.0.0 docker://src-docker-registry.com/dest-registry/my-image:1.0.0
```
This fails because, skopeo tries to authenticate to `source-registry` with the credentials from `dest-registry`. 

The debug log shows
```
DEBU[0000] GET https://some-docker-registry.com/.../token?account=some-other-name&scope=repository%3Adest-registry%2Fimage%3Apull 
```

I think it might be important here that the registry urls differ only in the last path segment.

The `.docker/config.json` contains two entries
```json
{
  "auths": {
    "some-docker-registry.com/source-registry": {
      "username": "some-name",
      "password": "***",
      "email": "some-name@example.com",
      "auth": "***"
    },
    "some-docker-registry.com/dest-registry": {
      "username": "some-other-name",
      "password": "***",
      "email": "some-other-name@example.com",
      "auth": "***"
    }
  }
}
```
I can successfully inspect both registries individually, when heaving separate config.json files for each registry. 

I think this should either be fixed or one should be able to pass separate config files for source and destination like one can do with the cert paths. This would be something like 
```
skopeo copy --src-authfile some-config.json --dest-authfile some-other-config.json  ...
```

**Comment by TomSweeneyRedHat** [comment]
@dastrobu thanks for sending this along and I like the thought of the `--src/dest-authfile` options.  I don't know if it's palatable to you or not, but say your authfile had the creds for the source directory.  You could use the `--dest-creds` option in the `skopeo copy` command line and get it to work that way for now at least.  Or use the `--src-creds` option if you'd the destination creds in your authfile.

**Comment by mtrmac** [comment]
> I think it might be important here that the registry urls differ only in the last path segment.
> 
> The `.docker/config.json` contains two entries
> 
> ```json
> {
>   "auths": {
>     "some-docker-registry.com/source-registry": {
>     },
>     "some-docker-registry.com/dest-registry": {
>     }
>   }
> }
> ```

I don’t think that’s ever been valid; only the host name part is considered, even if the URL syntax is used. Compare https://github.com/moby/moby/blob/3152f9436292115c97b4d8bb18c66cf97876ee75/registry/auth.go#L228 .

---

It’s honestly surprising to me that a single physical user (= single subject) should use different credentials for two repositories on a single registry (= single user account system and presumably administration domain). Is it something that happens frequently, for a _good_ reason? If so, adding `--src-authfile` and `--dest-authfile` would be warranted, sure, but it looks strange.

**Comment by dastrobu** [comment]
>  You could use the `--dest-creds` option in the `skopeo copy` command line and get it to work that way for now at least. 

@TomSweeneyRedHat I would like to avoid this, since I don't want to leak secrets on the command line (logs, process table). I currently have a different workaround, since one can access the registry by external dns, such as some-docker-registry.com and by service dns form inside OpenShift, such as docker-registry.default.svc:5000. This setup has two different hosts and hence is a workaround. 

@mtrmac my use case is copying images between different namespaces in OpenShift. By default an OpenShift cluster has one registry with repositories for each namespace. Access to the repositories is controlled by the `system:image-puller` and `system:image-pusher` role in each namespace. So in OpenShift it's standard behavior that different auths are required. I am not so familiar with registry access control on other Kubernetes clusters, but the setup and use case seem to make sense to me.

**Comment by mtrmac** [comment]
My first instinct is to model the actual situation accurately in the account / permission system: i.e. have give the principal (personal account, service account) a _single_ account that is simultaneously assigned the puller role for one repository and the pusher role for the other one. That would transparently and accurately record the possible accesses, and allow for auditing of the granted privileges. Having two separate accounts available to the same principal without any trace in the system is less transparent. OTOH I know very little about OpenShift, it may not be possible to set the system up that way.

**Comment by dastrobu** [comment]
@mtrmac using the same user (service account) for the pulling and pushing can be technically an option. However, there are good reasons to keep these separate and discussing the organizational pros and cons of using the same or different credentials for pulling and pushing might be beyond the scope of this issue. 
There are some workarounds (use different hosts as pointed out above) or use the same credentials, as you pointed out. I think it was definitely good to have this discussion, in case someone rans into the same issue. 

Regarding a "fix" I see three options: 
 1. do nothing and let people use the workarounds as pointed out.
 2. add support for the `--src-authfile` and `--dest-authfile` flags.
 3. change the way a docker config is interpreted, by first reading the host only (current state) and in case there are several credentials for the same host, look at the next path segment after the host to resolve any ambiguity.

I can live with all options. The second option would be very transparent but might be a bit confusing  if there are so many options to pass credentials (`--authfile`, `--src-authfile`, `--dest-authfile`, `--src-creds`, `--des-creds`). The last option would be most convenient from a user perspective but since it cannot be fixed inside skopeo would be out of scope for this issue.

**Comment by mtrmac** [comment]
FWIW, I’d prefer option 2: the single `--authfile` option is actually a unique corner case in Skopeo’s option processing, so using the prefixed variant like other `imageOptions` would be consistent with the rest of the code (OTOH, sure, the unique corner case would remain).

**Comment by dastrobu** [comment]
@TomSweeneyRedHat and @mtrmac I create a [pr](https://github.com/containers/skopeo/pull/798) implementation the additional flags (option 2), let me know what you think.
