### ISSUE TITLE
Build is broken if GOBIN is not set

### ISSUE THREAD

**Issue by cHolzberger** [containers/skopeo#779]
Have to explicitly set GOBIN if it is not set skopeo Makefile won't find go-md2man, while libpod makefile fallbacks to GOPATH[0]/bin when GOBIN is not set

**Comment by vrothberg** [comment]
@cHolzberger are you using the latest commit from master? I may have broken that with my last PR :angel:

**Comment by vrothberg** [comment]
#783 to fix it.
