### ISSUE TITLE
Add override-variant flag

### ISSUE THREAD

**Issue by JirkaChadima** [containers/skopeo#790]
Hi, first of all thanks for this great piece of software.

As discussed in https://github.com/containers/skopeo/pull/420, it might be useful to have a `--override-variant` flag along with `--override-arch` and `--override-os` options. For example [redis](https://hub.docker.com/v2/repositories/library/redis/tags/?page_size=25&page=1) is differentiating between `arm/v5` and `arm/v7` via the variant option.

My use case: We are building a custom OS image for Raspberry Pi and we need to populate the OS image with `arm/v7` specific docker images from docker hub during build phase that runs on `amd64` PC. Why? Because the resulting device won't have any internet when it is fired up, so `docker pull` won't work. Without the `--override-variant` flag, I'm unable to download a redis image with `skopeo copy` from https://hub.docker.com/_/redis/ because with `--override-arch=arm`, the `v5` variant gets downloaded.

**Comment by rhatdan** [comment]
Would you be interested in opening a PR for this?
@vrothberg @nalind @mtrmac WDYT?

**Comment by JirkaChadima** [comment]
I can try to put it together over the holidays. I'm no go expert though, so it might be a little rough around the edges.

**Comment by rhatdan** [comment]
SGTM

**Comment by mtrmac** [comment]
Fixed by #793.
