### ISSUE TITLE
skopeo inspect volume and exposed port information?

### ISSUE THREAD

**Issue by laetho** [containers/skopeo#799]
Would it be much work required to make skopeo inspect report the volume and exposed port information about a container image. I'm willing to put in the work, but I would appreciate some pointers where work would be required.

I'm building tooling for manifest generation, and I'd like to be able to do that without having a local docker daemon or a openshift cluster with imagestream api's to query.

Thank you.

**Comment by mtrmac** [comment]
Thanks for your report.

That information seems to be already available with `skopeo inspect --config`:
```console
$ ./skopeo --override-os linux inspect --config docker://mysql | python -mjson.tool
{
    "architecture": "amd64",
    "config": {
        "Cmd": [
            "mysqld"
        ],
        "Entrypoint": [
            "docker-entrypoint.sh"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "GOSU_VERSION=1.7",
            "MYSQL_MAJOR=8.0",
            "MYSQL_VERSION=8.0.19-1debian9"
        ],
        "ExposedPorts": {
            "3306/tcp": {},
            "33060/tcp": {}
        },
        "Volumes": {
            "/var/lib/mysql": {}
        }
    },
    "created": "2020-01-14T23:20:58.194519827Z",
    "history": [
        …
    ],
    "os": "linux",
    "rootfs": {
        "diff_ids": [
            …
        ],
        "type": "layers"
    }
}
```
Is that what you are looking for?

**Comment by laetho** [comment]
Thank you, that will serve my purposes for now. A bit embarrased that i did not figure that one out :)
