### ISSUE TITLE
Jenkins pipeline fails

### ISSUE THREAD

**Issue by 1codingmonkey** [containers/skopeo#803]
I wrote a Jenkins pipeline to copy remote images to a local repository. Unfortunately I can't make the pipeline run due to a "unable to retrieve auth token: 401 unauthorized" error which quits the pipeline. However using the same command in the terminal works fine.

So my guess is that this `Ping https://docker-registry.default.svc:5000/v2/ status 401 ` is interpreted by the Jenkins pipeline as an error and quits the whole command, while when I run the command in the terminal it continues and gives me the proper output.

I'm using skopeo version: 0.1.17-dev commit: d0a41799da7d39555110b1dfd58fefc3f6cf679b
It's the only one I could install in my Debian slave container. (yum or snap not available in Debian).

The Jenkins pipeline output from a skopeo inspect call:

> time="2020-01-24T21:22:39Z" level=debug msg="Using registries.d directory /etc/containers/registries.d for sigstore configuration" 
> time="2020-01-24T21:22:39Z" level=debug msg=" No signature storage configuration found for docker-registry.default.svc:5000/path/image:latest" 
> time="2020-01-24T21:22:39Z" level=debug msg="GET https://docker-registry.default.svc:5000/v2/" 
> time="2020-01-24T21:22:39Z" level=debug msg="Ping https://docker-registry.default.svc:5000/v2/ err <nil>" 
> time="2020-01-24T21:22:39Z" level=debug msg="Ping https://docker-registry.default.svc:5000/v2/ status 401" 
> time="2020-01-24T21:22:39Z" level=fatal msg="unable to retrieve auth token: 401 unauthorized" 

Then quits!

While in the terminal I see the same ping with "status 401", but continues:

> skopeo --tls-verify=false --debug inspect --creds="<user>:<pwd>" docker://docker-registry.default.svc:5000/path/image:latest
> DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
> DEBU[0000]  No signature storage configuration found for docker-registry.default.svc:5000/path/image:latest 
> DEBU[0000] GET https://docker-registry.default.svc:5000/v2/ 
> DEBU[0000] Ping https://docker-registry.default.svc:5000/v2/ err <nil> 
> DEBU[0000] Ping https://docker-registry.default.svc:5000/v2/ status 401 
> DEBU[0000] GET https://docker-registry.default.svc:5000/v2/path/image/manifests/latest 
> DEBU[0000] Downloading path/image-ui/blobs/sha256:aa391f577e589c0515309dde9c623746f32bb93c2a5afc961a873c9bd0b0660c 
> ......
> <displays the image information>

Please help me further. What can I do?

**Comment by mtrmac** [comment]
- My best guess is that the Jenkins container just doesn’t have the right credentials. The log does not show how Skopeo is invoked, so it’s hard to say how they are supposed to get there.
- If `--creds=:`, in the terminal case, is valid at all (AFAICS it should be explicitly rejected), it probably means “use the information recorded by `docker login`/`podman login`”; it’s pretty unlikely that Jenkins has automatically access to the same credentials your personal development account has set up.
- Try updating; you are using a 4 years old version. If there is a bug and we fix it, if you can’t upgrade, what are you going to do? You don’t _have_ to use the latest version but you should at least have the _option_. That includes compiling the software yourself if necessary. Recent versions also add more debugging information in the log that could help diagnose this.

**Comment by mtrmac** [comment]
@1codingmonkey is this still an issue?

**Comment by rhatdan** [comment]
Closing for a lack of information,  Reopen if more information becomes available.
