### ISSUE TITLE
Copyright missing holders

### ISSUE THREAD

**Issue by siretart** [containers/skopeo#804]
I'm working on getting skopeo into Debian and received a rejection related to the copyright declaration (cf. https://salsa.debian.org/go-team/packages/skopeo/blob/master/debian/copyright - at time of writing 98ae4685c86164f9576ecf55c35d9acdf6a84e08 was most recent).

The reason for failing the review was:

> please add a copyright holder of the software to your debian/copyright.

Please help me with what I can reasonably put as copyright holder in that file. Ideally, that would also be mentioned somewhere in the upstream repository.

@vrothberg - FYI this is related to the packaging efforts of podman as discussed in https://github.com/containers/libpod/issues/1742

**Comment by vrothberg** [comment]
In `containers/psgo` we're using `psgo authors` so I suggest using `skopeo authors`.

@mtrmac @runcom @rhatdan WDYT?

**Comment by rhatdan** [comment]
SGTM

**Comment by siretart** [comment]
So who is holding the copyright?

Inclusion into Linux distributions don't (usually) include the git history, which means the receiver / user of such a distribution would be only to see the contents of your release tarballs. The "Skopeo Authors" is pretty non-transparent whom to ask for clarifications, concerns or other inquiries. Wouldn't you want to do your users a favor by becoming at least somewhat approachable?

**Comment by vrothberg** [comment]
`github.com/containers/skopeo authors`? I'd expect users to reach out here on GitHub.

**Comment by mtrmac** [comment]
(IANAL, and all that.)

> So who is holding the copyright?

Looking at https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ :
> The Copyright field collects all relevant copyright notices for the files of this paragraph

says copyright **notices**, not copyright **holders**.

If there are no notices, there is nothing to collect.

---

Note that a copyright notice is not mandatory to establish copyright rights. How does Debian _typically_ handle that? I would expect that for almost every Open Source project that does not have explicit copyright assignment requirements, any existing copyright notices that name individuals don’t actually list all copyright holders.

IIRC, in Europe (hello USA!), copyright even for work for hire is held by the original author, and authorship can’t be given away (only the right to _benefit from_ the right can be licensed). So, I suppose, there should be at least some individual holders. For many of them, we have GitHub usernames, at best. OTOH, for some work coming from countries where copyright can be transferred, there well might be corporate holders that are completely unknown to us.

--

We are also vendoring a whole lot of third-party code in the upstream releases, and all the original authors retain copyright to that.

(I guess Debian does not use that, in favor of properly packaged dependencies, but should the `debian/copyright` file list those holders anyway?)

**Comment by mtrmac** [comment]
@siretart do we need to do anything, and if so, what? Per https://github.com/containers/podman/issues/1742 I guess at least some of the issues were resolved _for Podman_.

**Comment by rhatdan** [comment]
@siretart @mtrmac @vrothberg I am not sure what Podman did to get over the hoop?  What does Skopeo need to do now?  Or is skopeo currently shipping in Debian?

**Comment by siretart** [comment]
Debian does ship skopeo: https://tracker.debian.org/pkg/skopeo

I did reach out to ftp-master and did not hear back. We may be okay for now. I'll reopen when I run into trouble again.
