### ISSUE TITLE
Skopeo support for BigFilesTemporaryDir (SystemContext)

### ISSUE THREAD

**Issue by malaiwah** [containers/skopeo#805]
I am using Skopeo to export docker-daemon images to docker-archive format and I find the tool really useful *but* it seems there is no way to define the temporary directory (it does not honour the TMPDIR environment variable) for the temporary copies made. It defaults to /var/tmp, which on the systems I use is quite tight.

There is a way to instruct containers/image to use a different folder for temporary files, but the option is not exposed thru the skopeo cli with an --option. The SystemContext field is called BigFilesTemporaryDir .

Here is where it is set for its default: https://github.com/containers/image/blob/de5ad242e515688f69225ca6d897cfb221e0f5c7/internal/tmpdir/tmpdir.go#L18

Here is where the copy operation fails on my system: https://github.com/containers/image/blob/d13a90f787a7d3cd58e6f13c7cd1f2307b74a1ef/docker/tarfile/dest.go#L110

Here is the pull request for BigFilesTemporaryDir: https://github.com/containers/image/pull/747

**Comment by malaiwah** [comment]
It might be easy to put it right here:
https://github.com/containers/skopeo/blob/4489ddd8a5caa0181575620c56e912032582374b/cmd/skopeo/utils.go#L128
and
https://github.com/containers/skopeo/blob/4489ddd8a5caa0181575620c56e912032582374b/cmd/skopeo/utils.go#L147
and I might take a try at it.

**Comment by rhatdan** [comment]
We are using this on Buildah now, but we should expose this or at least allow the setting of TMPDIR to modify the setting.

**Comment by mtrmac** [comment]
#868 was merged.
