### ISSUE TITLE
skopeo doesnt check cert for being revoked against a CRL

### ISSUE THREAD

**Issue by MansM** [containers/skopeo#808]
using skopeo version 0.1.40 on macos

We have a current setup:
webserver with wildcard dns serving revoked cert: cert contains url to crl
webserver forwards to registry from a major vendor which has a valid cert.

Timewise the cert is still valid, only has been put on the cert revocation list
so only the http 302 is served over a wrong cert.

Most stuff doesnt do this check, but for security paranoid folks this might be an issue

**Comment by mtrmac** [comment]
Thanks for your report.

This seems to be how the Go TLS stack is implemented; I don’t see any way to opt in into that, and I don’t think Skopeo should implement it independently.

(And anyway, it would be fairly impractical for a short-lived process like Skopeo to download the full CRL on every invocation; something like that should be an OS function with a long-term cache. OCSP, or ideally OCSP stapling, would be much more practical — OTOH I can’t see the Go TLS stack implementing that either.)
