### ISSUE TITLE
Add subcommand add-layer

### ISSUE THREAD

**Issue by shaneing** [containers/skopeo#809]
Usage as follow:

```
skopeo add-layer --src source_image --dest destination_image layer
```

The command is divided into four steps:

1. Save the source image to dir.
2. Add the layer.
3. Update image manifest.
4. Save dir to the destination image.

**Comment by vrothberg** [comment]
Hi @shaneing, is this a feature request or an RFC?

My guts tell me that this is outside of Skopeo's scope and more related to building tools such as Buildah. If you want to have such a feature, please explain _why_ such a feature is needed and also why this is not possible with what the tools offer today.

**Comment by shaneing** [comment]
@vrothberg Oh, I'm so sorry. The Buildah looks good to me.

**Comment by mtrmac** [comment]
Also:
- skopeo typically only exposes functionality already present in containers/image, without adding much logic beyond CLI parsing.
- The “copy source to dir:” step should not, in principle, be necessary (OTOH c/image does not have a way to add a layer to a manifest without manually editing the data).

**Comment by shaneing** [comment]
> Also:
> 
> * skopeo typically only exposes functionality already present in containers/image, without adding much logic beyond CLI parsing.
> * The “copy source to dir:” step should not, in principle, be necessary (OTOH c/image does not have a way to add a layer to a manifest without manually editing the data).

I can not understand the second point. The "copy source to dir" is mean that:

```
% skopeo copy docker://docker.io/busybox  dir:/tmp/busybox
```

I have tried to build an image by Buildah. But, it needs *privilege* in a container.

**Comment by mtrmac** [comment]
Conceptually, what _needs_ to happen is:
- Read a manifest
- Upload the _single_ new layer
- Update the manifest, and write it back.

Copying all of the other layers to `dir:`, or uploading them unmodified back, are not essential to the idea.

**Comment by martinbaillie** [comment]
Sorry to dig up an old thread. Is anyone doing anything like what @mtrmac proposes with skopeo or another tool?
