### ISSUE TITLE
RFE: support REGISTRY_AUTH_FILE for credentials

### ISSUE THREAD

**Issue by edsantiago** [containers/skopeo#822]
[ Slightly related to #434, but unique enough to merit its own issue. ]

podman allows setting `REGISTRY_AUTH_FILE=/path/to/auth.json` to override its default. skopeo should honor that envariable.

**Comment by mtrmac** [comment]
In general I’m not quite thrilled with implicit environment variable overrides (often, although certainly not always, the same thing can be achieved with a shell alias/function), but sure, it might make sense in specific situations.

**Comment by mtrmac** [comment]
Support was added in #829.
