### ISSUE TITLE
Provide prebuild artefacts

### ISSUE THREAD

**Issue by jkroepke** [containers/skopeo#830]
Hello,

please provide pre build artefacts for released versions of skoepo.

The binary can be attached to github releases like here: https://github.com/containers/skopeo/releases/tag/v0.1.41

**Comment by mtrmac** [comment]
Thanks for your report.

This has been previously discussed:
- For Linux in https://github.com/containers/skopeo/issues/594 , notably https://github.com/containers/skopeo/issues/594#issuecomment-492827337 makes this difficult to impractical, compared with using distribution packages
- For non-Linux systems, #330 / #391 , notably https://github.com/containers/skopeo/issues/330#issuecomment-487706334 .
