### ISSUE TITLE
Couldn't install skopeo v0.1.41

### ISSUE THREAD

**Issue by ashoks27** [containers/skopeo#832]
Hi All,

I am new a skopeo and wanted to install it. I have downloaded the source code and built an docker image using the dockerfile which I got from source code. But am unable to create a container using that Image. 

Please advise on how to build a container from here . Basicly I wanted to copy a images from one registry 

[root@serverA ~]# docker images |head
REPOSITORY                      TAG        IMAGE ID            CREATED             SIZE
container/skopeo                latest     3166d8202a8a        3 days ago          2.49 GB
skopeo-test                        latest     3166d8202a8a        3 days ago          2.49 GB
docker.io/fedora                latest     536f3995adeb        3 days ago          193 MB

root@serverA skopeo-0.1.41]# docker run skopeo --image=skopeo
Unable to find image 'skopeo:latest' locally
Trying to pull repository registry.access.redhat.com/skopeo ...
Pulling repository registry.access.redhat.com/skopeo
Trying to pull repository docker.io/library/skopeo ...
Trying to pull repository registry.fedoraproject.org/skopeo ...
Pulling repository registry.fedoraproject.org/skopeo
Trying to pull repository quay.io/skopeo ...
Trying to pull repository registry.centos.org/skopeo ...
Pulling repository registry.centos.org/skopeo
Trying to pull repository docker.pkg.github.com/skopeo ...
Pulling repository docker.pkg.github.com/skopeo
Trying to pull repository docker.io/library/skopeo ...
**/usr/bin/docker-current: repository docker.io/skopeo not found: does not exist or no pull access.**
See '/usr/bin/docker-current run --help'.
[root@serverA skopeo-0.1.41]#

**Comment by mtrmac** [comment]
Thanks for your report.

Some ways to install `Skopeo` are available at https://github.com/containers/skopeo#obtaining-skopeo.  The `Dockerfile` in the repository exists for tests, it does not create an end-user-image.

One reason why Skopeo containers aren’t all that useful is that Skopeo very often needs access to credentials, which are typically set up by `podman login` / `docker login`. So, a Skopeo container could only work by passing the credential files via mounted volumes, for every single command — it’s so much simpler to have a local command and run it directly in the same user account as `podman login`.

**Comment by ashoks27** [comment]
Thanks for your respose Miloslav...

I dont see any installation instructions for Centos/RHEL and the instruction provided for ubuntu is not working either.  would you please elaborate more on the local commands aspect , like to how to install and work on it. I have tried with the below and it didn't work.

[root@server A skopeo]# skopeo sync --src docker --dest dir --scoped myimages /tmp/skop
No help topic for 'sync'
[root@icprhel04 skopeo]#

**Comment by mtrmac** [comment]
So, you do have some version `skopeo` installed already.  (For completeness, the Fedora instructions would apply. I’ve filed a ticket to improve the documentation. Thanks!)

`skopeo sync` is only available since 0.1.41, you probably have an older version installed.

In that case, https://github.com/containers/skopeo#building-without-a-container (with the Fedora variants) should let you create a local build of a later version. Note that some of the dependencies are in explicitly unsupported repositories that have to be enabled separately (CentOS PowerTools / RHEL  CodeReady-Builder ).

**Comment by mtrmac** [comment]
@ashoks27 Were you able to get the version of Skopeo you needed?

**Comment by rhatdan** [comment]
Since this was never answered, closing for lack of info, reopen if info becomes available.
