### ISSUE TITLE
RFE: Provide a skopeo-login/skope-logout

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/skopeo#839]
It would be good to provide a skopeo-login and a skopeo-logout command that works in the same manner as podman-login and podman-logout.  That way another package would not have to be installed in order for login to work.

Bonus points:  Have the guts of the login and logout code live in containers/common so that only minimal implementations would need to be made inside each of the three (Podman, Buildah, Skopeo) projects.

**Comment by vrothberg** [comment]
Sharing everything in containers/common could be tough as Skopeo is not using cobra for the CLI.

**Comment by TomSweeneyRedHat** [comment]
You know what I call that @vrothberg ?  More opportunities!  ;^)

**Comment by mtrmac** [comment]
This was added by #865 .
