### ISSUE TITLE
Can't install skopeo on CentOS 7

### ISSUE THREAD

**Issue by kedmison** [containers/skopeo#845]
I am trying to install the upstream buildah/podman/skopeo set, on CentOS 7.  buildah and podman installation go fine.

For Skopeo, however, installation fails.  

It looks like skopeo is trying to use an RPM Epoch version that is not available: 

```
Requires: containers-common = 1:0.1.40-6.1.el7
Installed: 2:containers-common-0.1.40-6.1.el7.x86_64 (@devel_kubic_libcontainers_stable)
```

Here is a log, showing the containers-common package version is installed, and they trying to install skopeo.
```
[kelvin@turing yum.repos.d]$ sudo yum install containers-common-0.1.40-6.1.el7
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Package 2:containers-common-0.1.40-6.1.el7.x86_64 already installed and latest version
Nothing to do
[kelvin@turing yum.repos.d]$ sudo yum install skopeo
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package skopeo.x86_64 2:0.1.40-6.1.el7 will be installed
--> Processing Dependency: containers-common = 1:0.1.40-6.1.el7 for package: 2:skopeo-0.1.40-6.1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: 2:skopeo-0.1.40-6.1.el7.x86_64 (devel_kubic_libcontainers_stable)
           Requires: containers-common = 1:0.1.40-6.1.el7
           Installed: 2:containers-common-0.1.40-6.1.el7.x86_64 (@devel_kubic_libcontainers_stable)
               containers-common = 2:0.1.40-6.1.el7
           Available: 1:containers-common-0.1.37-1.el7.centos.x86_64 (extras)
               containers-common = 1:0.1.37-1.el7.centos
           Available: 1:containers-common-0.1.37-3.el7.centos.x86_64 (extras)
               containers-common = 1:0.1.37-3.el7.centos
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by TomSweeneyRedHat** [comment]
@lsm5 is this in your neighborhood?

**Comment by lsm5** [comment]
@TomSweeneyRedHat yes, i'm unable to assign this to myself though, is it possible you could give me more permissions on this repo, or do I need commits to this repo to get those perms?

**Comment by mtrmac** [comment]
@lsm5 I clicked _something_ in the GitHub UI, you should have received an invite. Does that help?

**Comment by lsm5** [comment]
@mtrmac yes thank you!

**Comment by lsm5** [comment]
@kedmison I built a new skopeo for OBS, https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/skopeo it should land in the repo soon, please give it a try in a bit and lemme know..

**Comment by kedmison** [comment]
Installation is successful!  

thanks for the amazing turn-around!

**Comment by lsm5** [comment]
@kedmison thanks a lot for verifying!

**Comment by iFelho** [comment]
> Installation is successful!
> 
> thanks for the amazing turn-around!

with what command did you manage to install it?
