### ISSUE TITLE
Verifying signed images from Docker Hub

### ISSUE THREAD

**Issue by countcretinos** [containers/skopeo#850]
Is it possible to verify signed images from Docker Hub? AFAICS, Skopeo's policy definitions support only verifying using GPG keys and Docker Hub's images are signed using Notary (See [Docker Content Trust](https://docs.docker.com/engine/security/trust/content_trust/)) which doesn't seem to use GPG.

**Comment by mtrmac** [comment]
I’m afraid Skopeo does not have Notary integration

It is possible to use “simple signing” with the Docker Hub, by hosting the signatures on a separate server. See e.g. the recent https://github.com/containers/libpod/pull/5495 . OTOH if you want to verify signatures already created on Notary, that doesn’t help.

**Comment by countcretinos** [comment]
> OTOH if you want to verify signatures already created on Notary, that doesn’t help.

Yes, that's thw point. There's no way to trust, say DockerHub official images, since Notary doesn't seem to sign with GPG keys. You'd basically have to host a separate mirror registry and build and sign automatically.

**Comment by rhatdan** [comment]
Theoretically skopeo could be modified to support Notary, but we would need someone to open a PR to do this.

**Comment by mtrmac** [comment]
If Notary support should happen, it should happen in containers/image; either way, with the Notary v2 effort slowly going on, I don’t think we are planning to work on adding support for v1 now.
