### ISSUE TITLE
Skopeo can't create repository in AWS ECR 

### ISSUE THREAD

**Issue by vugardzhamalov** [containers/skopeo#851]
Skopeo Version: 0.1.41

When I execute following in order to push my image (built with buildah/podman) stored on my localhost skopeo won't create a new repository on AWS ECR, is this expected? Am I doing something wrong here?

Please note: the same  works as expected when I push to ECR repository created in advance.

`skopeo copy --format=v2s2 containers-storage:localhost/{{ my-podman-created-image}}:{{ image-tag}} docker://{{ AWS ACCOUNT}}.dkr.ecr.{{ AWS REGION }}.amazonaws.com/{{ NEW REPO NAME }} --dest-creds AWS:$(aws ecr get-login-password --output text)`

This is the output with the error message:

`Getting image source signatures
Copying blob bc21985928b6 [--------------------------------------] 8.0b / 3.5KiB
Copying blob e370c53ec242 [--------------------------------------] 8.0b / 55.3MiB
Copying blob f2cb0ecef392 [--------------------------------------] 8.0b / 69.1MiB
Copying blob ede9dd92d61e [--------------------------------------] 8.0b / 4.0KiB
FATA[0003] Error writing blob: Error initiating layer upload to /v2/{{ NEW REPO NAME }}/blobs/uploads/ in {{ AWS ACCOUNT}}.dkr.ecr.{{ AWS REGION }}.amazonaws.com: name unknown: The repository with name '{{ NEW REPO NAME }}' does not exist in the registry with id '{{ AWS ACCOUNT}}' 
ERRO[0003] exit status 1`

Please let me know if there is any further info required

**Comment by vugardzhamalov** [comment]
I wonder if this is somehow related to 'AWS' user (and permissions of this user) passed as a username to '--dest-creds' switch... Just a guess... not sure at all.

**Comment by mtrmac** [comment]
Thanks for your report.

So far it seems we haven’t had a similar report, so it might indeed be a permissions issue. Or it might a real bug, of course. FWIW https://docs.aws.amazon.com/IAM/latest/UserGuide/list_amazonelasticcontainerregistry.html lists a “CreateRepository” action, but I have no personal experience with that.

**Comment by vugardzhamalov** [comment]
Thank you @mtrmac!

I'll see if I can replicate this issue with Docker... I take it if it is indeed related to 'AWS' user and permissions it has over ECR - I should see similar behaviour with Docker. Everywhere you go these days you see 'AWS' user example almost everywhere, even here: [https://docs.aws.amazon.com/AmazonECR/latest/userguide/Registries.html](url)

I'll post here once I know more

**Comment by vugardzhamalov** [comment]
It seems like this has nothing to do with skopeo. As I understand this is almost like a standard workflow with AWS ECR... One is expected to create repository in advance (well at least when specifically 'AWS' user account is used).

The easiest option around this I can think of at the moment... maybe a one liner similar to this one:

`aws ecr create-repository --repository-name '{{ NEW REPO NAME }} ' && skopeo copy --format=v2s2 containers-storage:localhost/{{ my-podman-created-image}}:{{ image-tag}} docker://{{ AWS ACCOUNT }}.dkr.ecr.{{ AWS REGION }}.amazonaws.com/{{ NEW REPO NAME }} --dest-creds AWS:$(aws ecr get-login-password --output text)`

**Comment by mtrmac** [comment]
Thanks for reporting back!
