### ISSUE TITLE
list-tags is broken for skopeo 0.1.41

### ISSUE THREAD

**Issue by arturrez** [containers/skopeo#859]
`skopeo version 0.1.41`
trying to use 
```
 skopeo list-tags  --creds xxxx:yyyy docker://registry.upbound.io/crossplane/stack-minimal-gcp
```
and getting `No help topic for 'list-tags'`

Also can reproduce it for any other image
for example
```
skopeo list-tags  docker://docker.io/hashicorp/terraform
No help topic for 'list-tags'
```

**Comment by mtrmac** [comment]
Yes, `skopeo list-tags` was added after 0.1.41 and there hasn’t been a release since.

**Comment by rhatdan** [comment]
Are we waiting for the next version of containers/image?  and then can do a release?

**Comment by mtrmac** [comment]
Ideally c/image + #793 .

**Comment by arturrez** [comment]
thank you for explanation. 
I looked into `0.1.41` release date and date when PR https://github.com/containers/skopeo/pull/716 was merged and I thought that it made it into the release even I didn't find it in Release notes.

**Comment by arturrez** [comment]
so I am looking forward to the next release.
