### ISSUE TITLE
Can not push to AWS ECR/JFrog when image is encrypted

### ISSUE THREAD

**Issue by stanltam** [containers/skopeo#869]
Hi expert,
  I am new to skopeo, I would like to encrypt an image and push to AWS ECR/JFrog. I am able to push using unencrypted image, however, failed to push when image is encrypted.

Here is the command I used, I follow the procedure to encrypt using https://medium.com/@lumjjb/encrypting-container-images-with-skopeo-f733afb1aed4. 

skopeo  copy --dest-tls-verify=false --dest-creds=AWS:<<password>> oci:nginx_encrypted:latest docker://<<accountid>>.dkr.ecr.us-east-2.amazonaws.com/nginx_encrypted:latest
With  error response :
Getting image source signatures
Copying blob 2cbe34abbe62 done
Copying blob 85bc197fb258 done
Copying blob a96204f55200 done
Copying config 841217fb19 done
Writing manifest to image destination
FATA[0050] Uploading manifest failed, attempted the following formats: application/vnd.oci.image.manifest.v1+json(Error writing manifest: Error uploading manifest latest to <<accountid>>.dkr.ecr.us-east-2.amazonaws.com/nginx_encrypted: **unsupported: Invalid parameter at 'ImageManifest' failed to satisfy constraint: 'Invalid JSON syntax'),** application/vnd.docker.distribution.manifest.v2+json(Error creating an updated image manifest: Unknown media type during manifest conversion: "application/vnd.oci.image.layer.v1.tar+gzip+encrypted"), application/vnd.docker.distribution.manifest.v1+prettyjws(Error creating an updated image manifest: Unknown media type during manifest conversion: "application/vnd.oci.image.layer.v1.tar+gzip+encrypted"), application/vnd.oci.image.index.v1+json(Error creating an updated image manifest: Conversion of image manifest from application/vnd.oci.image.manifest.v1+json to application/vnd.oci.image.index.v1+json is not implemented), application/vnd.docker.distribution.manifest.list.v2+json(Error creating an updated image manifest: Conversion of image manifest from application/vnd.oci.image.manifest.v1+json to application/vnd.docker.distribution.manifest.list.v2+json is not implemented), application/vnd.docker.distribution.manifest.v1+json(Error creating an updated image manifest: Unknown media type during manifest conversion: "application/vnd.oci.image.layer.v1.tar+gzip+encrypted")

------------------------------------------------------------------------------------------------------------
Error if I push to JFrog docker repo:
FATA[0000] Uploading manifest failed, attempted the following formats: application/vnd.oci.image.manifest.v1+json(Error writing manifest: Error uploading manifest latest to <<jfrog-docker-repo>>/nginx_encrypted: **manifest invalid: manifest invalid**), application/vnd.docker.distribution.manifest.v2+json(Error creating an updated image manifest: Unknown media type during manifest conversion: "application/vnd.oci.image.layer.v1.tar+gzip+encrypted"), application/vnd.docker.distribution.manifest.v1+prettyjws(Error creating an updated image manifest: Unknown media type during manifest conversion: "application/vnd.oci.image.layer.v1.tar+gzip+encrypted"), application/vnd.oci.image.index.v1+json(Error creating an updated image manifest: Conversion of image manifest from application/vnd.oci.image.manifest.v1+json to application/vnd.oci.image.index.v1+json is not implemented), application/vnd.docker.distribution.manifest.list.v2+json(Error creating an updated image manifest: Conversion of image manifest from application/vnd.oci.image.manifest.v1+json to application/vnd.docker.distribution.manifest.list.v2+json is not implemented), application/vnd.docker.distribution.manifest.v1+json(Error creating an updated image manifest: **Unknown media type during manifest conversion**: "application/vnd.oci.image.layer.v1.tar+gzip+encrypted")

**Comment by stanltam** [comment]
My skopeo version: 

# skopeo --version
skopeo version 0.1.41

**Comment by rhatdan** [comment]
Could this be an issue with the registry not supporting it?
@harche @mtrmac PTAL

**Comment by harche** [comment]
@stanltam I tried pushing the image to locally hosted registry, 
```sh
podman  run -d -p 5000:5000 --name registry registry:2
```
```sh
skopeo  copy --encryption-key jwe:./public.key docker://docker.io/library/nginx:1.17.8 --dest-tls-verify=false docker://localhost:5000/encrypted:latest
Getting image source signatures
Copying blob 68ced04f60ab done  
Copying blob c16ce02d3d61 done  
Copying blob c4039fd85dcc done  
Writing manifest to image destination
Storing signatures
``` 
As you can see, I am able to push it to the locally hosted registry, so it's highly likely that the registry you are using is still not supporting it. Please note that, encrypted image support is still an experimental feature. I suggest hosting your own registry until your registry provider adds support for encrypted images. 

/cc @lumjjb

**Comment by harche** [comment]
> Could this be an issue with the registry not supporting it?
> @harche @mtrmac PTAL

Yes

**Comment by rhatdan** [comment]
No way really for skopeo to fix this, Closing, unless I am mistaken.
