### ISSUE TITLE
Ansible Role for Skopeo

### ISSUE THREAD

**Issue by hswong3i** [containers/skopeo#894]
I am now maintenance an Ansible Role for Skopeo installation (https://github.com/alvistack/ansible-role-skopeo), by building the source code manually and install for following OS:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we also introduce this as an alternative installation method, e.g. under https://github.com/containers/skopeo/blob/master/install.md#building-without-a-container section?

**Comment by mtrmac** [comment]
It doesn’t really make sense to me to build Skopeo locally via Ansible on every single host, when all these distributions have packaging mechanisms to distribute built artifacts (RPMs/.Debs).

Also, I haven’t studied the Ansible roles in detail, but things like
```
   - name: cp -rfT /etc/skel /root
      raw: |
        set -ex
        cp -rfT /etc/skel /root
      changed_when: false
      ignore_errors: true

    - name: setenforce 0
      raw: |
        set -ex
        setenforce 0
      changed_when: false
      ignore_errors: true

    - name: systemctl stop firewalld.service
      raw: |
        set -ex
        systemctl stop firewalld.service
      changed_when: false
      ignore_errors: true

    - name: systemctl stop ufw.service
      raw: |
        set -ex
        systemctl stop ufw.service
      changed_when: false
      ignore_errors: true
```
are scary to see and absolutely not requirements for building Skopeo.
