### ISSUE TITLE
Static Binary for Github Release?

### ISSUE THREAD

**Issue by hswong3i** [containers/skopeo#895]
Refer to #894, now we could only install skopeo from source build, in order to provide a synchronized user experience for installation under follow OS combination:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we reference how runc/conmon/cri-o/kubectl/kubeadm/kubelet Github release works (e.g. https://github.com/cri-o/cri-o/releases/tag/v1.17.3), therefore also provide an static binary archive for download with each release?

**Comment by mtrmac** [comment]
There is already https://github.com/containers/skopeo/issues/830 tracking static binaries, so far we haven’t seen a way that works well for Linux.
