### ISSUE TITLE
sync: AWS ECR => private registry incorrect namespace

### ISSUE THREAD

**Issue by tiredpixel** [containers/skopeo#898]
Firstly, please allow me to express my gratitude for such an awesome tool. We're slowly moving from traditional Docker service to Podman serviceless, whilst also migrating images from AWS ECR to a new private registry we've set up using `docker.io/library/registry`, and Skopeo, in particular the `sync` command from Skopeo 0.1.41 onwards, has been extremely helpful.

We've run into a small issue, however, which I've worked around, but I'm afraid haven't attempted to write a patch for: AWS ECR doesn't use namespaces, having a repository format like `000000000000.dkr.ecr.eu-west-1.amazonaws.com/tmp-repo`. When transferring using `sync` to our private registry, that repo name gets doubled as a namespace, with a format like: `example.com/tmp-repo/tmp-repo`. This was present on Skopeo 0.1.41 (CentOS 8 RPM) and Skopeo 0.2.0-dev commit: 2415f3fa4d2e7a9fb8a48b0ee05675e92793ed96 (compiled from source using container). Experimenting with `--scoped` resulted in a format like: `example.com/000000000000.dkr.ecr.eu-west-1.amazonaws.com/tmp-repo/tmp-repo` (or similar; this example is from memory).

Thus, it appears that when syncing from a registry which doesn't have namespaces, it gets incorrectly namespaced by repository. Adding a `base` namespace to the destination applies a namespace, but keeps the duplication, resulting in a format like `example.com/base/tmp-repo/tmp-repo`, instead of `example.com/base/tmp-repo`.

Since this is a one-time migration, I experimented with simply changing the code to remove the path detection, and this worked perfectly:

```
diff --git a/cmd/skopeo/sync.go b/cmd/skopeo/sync.go
index 93f6a362..3decb243 100644
--- a/cmd/skopeo/sync.go
+++ b/cmd/skopeo/sync.go
@@ -523,7 +523,7 @@ func (opts *syncOptions) run(args []string, stdout io.Writer) error {
                        }
 
                        if !opts.scoped {
-                               destSuffix = path.Base(destSuffix)
+                               destSuffix = ""
                        }
 
                        destRef, err := destinationReference(path.Join(destination, destSuffix), opts.destination)
```

This obviously wouldn't be suitable as-is for a patch, however, and I haven't investigated further.

**Comment by mtrmac** [comment]
Could you clarify what is the _precise, full_ name of the intended source and destination repositories, and what’s the command you used, please?

**Comment by tiredpixel** [comment]
Sure. The full names are:

source:
```
000000000000.dkr.ecr.eu-west-1.amazonaws.com/tmp-repo
```
(using TLS)

destination:
```
example.com/tmp-repo
```
(using TLS)

command:
```
skopeo sync --src docker --dest docker 000000000000.dkr.ecr.eu-west-1.amazonaws.com/tmp-repo example.com/tmp-repo
```

That, said, now I'm not sure the hack above worked anyway, since it appears to have copied every source tag to a `latest` destination tag, which isn't what I intended.

**Comment by tiredpixel** [comment]
Oh! It is my fault entirely. :)

I went back and added more debugging:

```
diff --git a/cmd/skopeo/sync.go b/cmd/skopeo/sync.go
index 93f6a362..26b30550 100644
--- a/cmd/skopeo/sync.go
+++ b/cmd/skopeo/sync.go
@@ -509,24 +509,33 @@ func (opts *syncOptions) run(args []string, stdout io.Writer) error {
                options.SourceCtx = srcRepo.Context
                for counter, ref := range srcRepo.TaggedImages {
                        var destSuffix string
+                       fmt.Printf("D0: %s\n", destSuffix)
                        switch ref.Transport() {
                        case docker.Transport:
                                // docker -> dir or docker -> docker
                                destSuffix = ref.DockerReference().String()
+                               fmt.Printf("D1: %s\n", destSuffix)
                        case directory.Transport:
                                // dir -> docker (we don't allow `dir` -> `dir` sync operations)
                                destSuffix = strings.TrimPrefix(ref.StringWithinTransport(), srcRepo.DirBasePath)
+                               fmt.Printf("D2: %s\n", destSuffix)
                                if destSuffix == "" {
                                        // if source is a full path to an image, have destPath scoped to repo:tag
                                        destSuffix = path.Base(srcRepo.DirBasePath)
+                                       fmt.Printf("D3: %s\n", destSuffix)
                                }
                        }
 
                        if !opts.scoped {
                                destSuffix = path.Base(destSuffix)
+                               fmt.Printf("D4: %s\n", destSuffix)
                        }
 
                        destRef, err := destinationReference(path.Join(destination, destSuffix), opts.destination)
+                       fmt.Printf("D5: %s\n", destination)
+                       fmt.Printf("D6: %s\n", destSuffix)
+                       fmt.Printf("D7: %s\n", opts.destination)
+                       fmt.Printf("D8: %s\n", destRef)
                        if err != nil {
                                return err
                        }
```

and running yielded:

```
D0: 
D1: 000000000000.dkr.ecr.eu-west-1.amazonaws.com/tmp-repo:1.1.1-6-g4ff6356
D4: tmp-repo:1.1.1-6-g4ff6356
D5: example.com
D6: tmp-repo:1.1.1-6-g4ff6356
D7: docker
D8: {{{example.com tmp-repo} 1.1.1-6-g4ff6356}}
INFO[0002] Copying image tag 4/143                       from="docker://000000000000.dkr.ecr.eu-west-1.amazonaws.com/tmp-repo:1.1.1-6-g4ff6356" to="docker://example.com/tmp-repo
:1.1.1-6-g4ff6356"
```

that is, `destination` already had that appended. This led me to reread that section of the manual more closely, and found:

> source is a repository hosted on a container registry (e.g.: registry.example.com/busybox).

> destination is a container registry (e.g.: my-registry.local.lan).

I totally missed that on previous look-throughs. Changing the destination to not include the intended destination repository name appears to work fine.

My apologies for the noise. We can close this. :)

**Comment by mtrmac** [comment]
Thanks for the update. In retrospect, it is somewhat irregular (and it makes it difficult to rename a repository while syncing) — but we’ll have to keep this behavior in order not to break existing users.
