### ISSUE TITLE
Document the structure of auth.json

### ISSUE THREAD

**Issue by sarcasticadmin** [containers/skopeo#902]
## Description

Would the team be open to having example of `auth.json` in the `skopeo` documentation? Unless I missed it, I did not see any reference to the structure of `auth.json`. I resorted to dissecting my `.docker/config.json`. I know these .json files are typically generated via `podman login` or `docker login` but in the cases were you'd just like to only have `skopeo` installed to minimize dependencies it'd be good to give an example and snippet of how to generate a basic `auth.json`.

It could be as simple as:
```
$ echo -n 'sarcasticadmin:mysupersecretpassword' | base64
c2FyY2FzdGljYWRtaW46bXlzdXBlcnNlY3JldHBhc3N3b3Jk

$ cat << EOF > auth.json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "c2FyY2FzdGljYWRtaW46bXlzdXBlcnNlY3JldHBhc3N3b3Jk"
                }
        }
}
EOF
```

**Comment by mtrmac** [comment]
Thanks for your report.

The documentation, if any, should probably be in in the containers/image repository that maintains the code. To an extent https://docs.docker.com/engine/reference/commandline/login applies.

But maybe you are actually more interested in a good way to add credentials to that file. Currently the best way is `podman login`, but there’s already work in progress to add `login`/`logout` to Skopeo: https://github.com/containers/skopeo/pull/865

**Comment by TomSweeneyRedHat** [comment]
I'll let @mtrmac have the final say, but if you're suggesting adding something to the README.md pointing out its use and a pointer to its man page, I'd be OK with that.  Just in case you haven't stumbled across it, the man page lives in [containers/image](https://github.com/containers/image/blob/fe9e1741e53189457e49f8014b8d4c79f4fc32fe/docs/containers-auth.json.5.md)

**Comment by mtrmac** [comment]
Oh, there already is a man page. Silly me.

Anyway, I’d prefer to point at `skopeo login`, when it arrives, rather than a script that does that  manually.

**Comment by sarcasticadmin** [comment]
@mtrmac The docker source seems to have the same problem with not telling the user what `config.json` (similar to `auth.json`) actually contains, if anything its just snippets of things like `credsStore` and `credHelpers` options but not a complete `config.json` example.

@TomSweeneyRedHat thank you, the manpage in [containers/image](https://github.com/containers/image/blob/fe9e1741e53189457e49f8014b8d4c79f4fc32fe/docs/containers-auth.json.5.md) is exactly what I was looking for! Do you think it'd be beneficial to put in the base64 one-liner of username, colon, password in the `Format` section of `containers-auth.json`?

Once #865 finishes: Would it be beneficial to have `skopeo-login` `manpage`  reference `containers-auth.json` to `Also see` section? Otherwise its seems like `containers-auth.json` would be hard to find

**Comment by TomSweeneyRedHat** [comment]
@sarcasticadmin Glad that helped.  I think what you're suggesting to add could be helpful.  I'd say open a PR and we can discuss in there.

**Comment by mtrmac** [comment]
A link to `containers-auth.json(5)` was added to `skopeo-login(1)` and `skopeo-logout(1)` in #914.
