### ISSUE TITLE
Support retries on commands

### ISSUE THREAD

**Issue by mitchfriedman** [containers/skopeo#918]
Sometimes we run a command and our AWS ECR returns a 504 (or similar, retryable status code). It would be good if skopeo commands supported retries with exponential backoff either by default or opt in.

**Comment by TomSweeneyRedHat** [comment]
I like the thought.  I don't think I'd want to do that by default, but adding a `--retry` option or such could be interesting and useful.

**Comment by mitchfriedman** [comment]
Seems fine for it to be opt-in, as long as you don't need to provide too many parameters on the command line to use it (i.e. `--retry-times`, `--retry-backoff-time`, etc).`--retry` would be good 👍

**Comment by mtrmac** [comment]
(c/image automatically retries on 429 with Retry-After. As a library, it shouldn’t in general make retry decisions without opt-in, to let callers manage retry behavior. But Skopeo as a top-level caller would be a fair place to do that opt-in/opt-out.)

There’s an interesting discussion about retries on https://github.com/containers/libpod/issues/6190 … the various situations where one might want to, or not want to, try again, are numerous, and it seems difficult to pick a single default behavior that makes sense for most callers. E.g. Buildah retries only on ECONNREFUSED and internal registry errors.

Similarly, making some kind of format commitment for the Skopeo error output to allow writing reliable scripts that make automatic decisions based on the kind of error encountered seems difficult.

“Difficult” is of course not “impossible”, and there well may exist an 80% solution that solves 95% of the cases.

**Comment by mitchfriedman** [comment]
I'm not intimately familiar with skopeo, nor any of the underlying libraries that it leverages for performing image operations, so i'll defer to those who are more closely involved in the projects as to where these belong, but I do think there is room for allowing skopeo (or something lower level than skopeo) to manage retry logic, for common failures (I don't know the situations why/how, but aws ECR often gives 504s when pushing images, and if you try to inspect an image, skopeo times out, as the server is non-responsive). I'd like to delegate to skopeo instead of trying to parse the output and determining if I should retry at my application layer, as it has no context on the failure.

**Comment by rhatdan** [comment]
@QiWang19  PTAL

**Comment by QiWang19** [comment]
I opened a PR #933 to enable skopeo to retry on the root command level. But I am not sure if this should enable for all commands or part of the function.
