### ISSUE TITLE
skopeo-login doesn't appear to work on macOS Catalina. 

### ISSUE THREAD

**Issue by Sher-Chowdhury** [containers/skopeo#923]
I get the following error message when trying to do a skopeo login:

```
$ brew install skopeo
...
Warning: skopeo 1.0.0 is already installed and up-to-date
$ skopeo --version
skopeo version 1.0.0
$ skopeo login myregistry.com -u myusername -p xxxx
FATA[0002] error creating directory "/run/containers/501": mkdir /run: read-only file system
```

I tried with sudo too and got the same error. The equivalent docker-login command works find though, which means that my registry url and login credentials are correct.

**Comment by mtrmac** [comment]
Thanks for your report.

I’m afraid the current default does not account for macOS.

Right now you can use `skopeo login --authfile ~/.docker/config.json …`, or set $XDG_RUNTIME_DIR to something (preferably matching https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html ).

Cc: @rhatdan for another thing to design. It’s very tempting to just point the macOS default path to ~/.docker/config.json , if we are not benefiting from moving it to a directory with substantially different properties.

**Comment by rhatdan** [comment]
Does MAC have the concept of XDG_RUNTIME_DIR, or any runtime dir at all?
Pointing it at ~/.docker/config.json might be the best we can do.  Although ~/.containers/config.json would be my preferred root.

@Sher-Chowdhury WDYT?

**Comment by mtrmac** [comment]
I can’t find any similarly-behaving directory in https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/Introduction/Introduction.html .

Alternatively, if we are considering system keyrings on Linux, it might make sense to ship a configuration that points at https://github.com/docker/docker-credential-helpers/tree/master/osxkeychain (disclaimer: I have never tried this).

Cc:ing recent contributors to the Brew formula for their opinions on such a default (or help if there is a different good solution we are missing): @chenrui333 @glensc @EricFromCanada

**Comment by chenrui333** [comment]
It might be better to create `~/. containers` folder, many MacOS software version managers are doing that (`rbenv`, `nvm`, `gvm`, `pyenv` and so on).

But we also ship `amazon-ecr-credential-helper` in homebrew side, so pointing to  `~/.docker/config.json` (`skopeo login --authfile ~/.docker/config.json …` also works for me (as user perspective) too.

**Comment by rhatdan** [comment]
@QiWang19 PTAL
I think reading ~/.containers/config.json and ~/.docker/config.json Would be fine for MAC and Windows

**Comment by Sher-Chowdhury** [comment]
@rhatdan Very sorry for the late response. 

I tried the authfile appraoch but it didn't seem to work:

```
$ cat ~/tmp/docker-config.json
{
  "auths": {
    "exampleregistry.com": {
      "username": "iamapikey",
      "password": "xxxxxx",
      "email": "a@b.c",
      "auth": "xxxxxxxxxxx"
    }
  }
}
$ skopeo login exampleregistry.com --authfile ~/tmp/docker-config.json
Authenticating with existing credentials...
Existing credentials are invalid, please enter valid username and password
Username (iamapikey): iamapikey
Password:      (had to copy and paste here)
Login Succeeded!
```

I had copy+plus paste the password to successfully login. At least it did seem to read the config file to set the default username, which in this example was 'iamapikey'.

**Comment by QiWang19** [comment]
@Sher-Chowdhury Is the "auth" value in base64 format? The auth file format should look like this https://github.com/containers/image/blob/master/docs/containers-auth.json.5.md
