### ISSUE TITLE
Suggestion for "$skopeo  -h "

### ISSUE THREAD

**Issue by doyoungim999** [containers/skopeo#924]
I would appreciate if the example can be provided with "$skopeo -h " on cli  simply. 
If I missed how to see example, please let me know.

**Comment by TomSweeneyRedHat** [comment]
@doyoungim999 just to make sure I'm on the same page, are you suggesting adding a few examples to the end of the output that you get from `skopeo -h`?  Perhaps something like these which are on the README.md?

```
$ skopeo inspect docker://registry.fedoraproject.org/fedora:latest
$ skopeo inspect docker://registry.fedoraproject.org/fedora:latest | jq '.Digest'
$ skopeo copy docker://quay.io/buildah/stable docker://registry.internal.company.com/buildah
$ skopeo copy oci:busybox_ocilayout:latest dir:existingemptydirectory
$ skopeo delete docker://localhost:5000/imagename:latest
```

**Comment by mtrmac** [comment]
There already is a list of subcommands, and most of the individual subcommands contain examples:
```console
% ./skopeo copy --help
Container "IMAGE-NAME" uses a "transport":"details" format.

Supported transports:
containers-storage, dir, docker, docker-archive, docker-daemon, oci, oci-archive, ostree, tarball

See skopeo(1) section "IMAGE NAMES" for the expected format

Usage:
skopeo copy [command options] SOURCE-IMAGE DESTINATION-IMAGE

Examples:
skopeo copy --sign-by dev@example.com container-storage:example/busybox:streaming docker://example/busybox:gold

Flags:
…
```

What are you struggling with? Is that hard to find, hard to figure out some specific parameter? Is it unclear that there are man pages (or are they somehow missing on your system)?

**Comment by doyoungim999** [comment]
@TomSweeneyRedHatI tried to use the command. 
$skopeo copy docker://quay.io/manasmohsin/webhook_j3:v6 docker://quay.io/doyblackcat/webhook_j3:v6

**Comment by zhangguanzhang** [comment]
@doyoungim999  you should use the sync subcommand, like this:
```
skopeo sync --src docker --dest docker docker://quay.io/manasmohsin/webhook_j3:v6 docker://quay.io/doyblackcat/webhook_j3:v6
```

**Comment by mtrmac** [comment]
For a single image, `skopeo copy` works just fine and is easier to reason about.
