### ISSUE TITLE
[skopeo-sync doc] there is an error in skopeo/docs/skopeo-sync.1.md

### ISSUE THREAD

**Issue by yuhuijiang** [containers/skopeo#944]
"TLS verification is normally enabled, and it can be disabled setting tls-verify to true."
Here the "true" should be false to disable TLS verification.

**Comment by rhatdan** [comment]
Could you open a PR to make the change?

**Comment by zhangguanzhang** [comment]
@rhatdan 
I see the doc has been change to correct, Please close the issue
