### ISSUE TITLE
man skopeo/skopeo-copy outdated

### ISSUE THREAD

**Issue by mskarbek-bnp** [containers/skopeo#951]
`skopeo copy --help` shows those supported transports: `containers-storage, dir, docker, docker-archive, docker-daemon, oci, oci-archive, ostree, tarball` but `man skopeo-copy` mentions only **IMAGE NAMES** section in `skopeo` which lists `containers-storage, dir, docker, docker-archive, docker-daemon, oci`.

```
# skopeo -v
skopeo version 1.0.0
# rpm -q skopeo
skopeo-1.0.0-1.fc32.x86_64
```

**Comment by rhatdan** [comment]
Would you be interested in opening a PR to fix this?

**Comment by mtrmac** [comment]
FWIW `ostree` is deprecated, and `tarball` is not really usable via CLI.  But `oci-archive` should be listed.
