### ISSUE TITLE
skopeo standalone-sign cannot sign docker's fat manifest

### ISSUE THREAD

**Issue by Kenzku** [containers/skopeo#953]
Hej, 

Anybody notice the `skopeo` signing image does not support docker's fat manifest, or I missed something?

e.g. here: https://hub.docker.com/layers/ibmcom/transformation-advisor-operator/2.2.0/images/sha256-58e2f4cf5fb66c3e8387956d082ab25e9ddaca7f28b5c0bfbc4e61d7abe0056d?context=explore

we have 3 architecture images 2.2.0-amd64 ,2.2.0-ppcle and 2.2.0-s390x combined into 1 tag: 2.2.0

`skopeo copy` cannot copy from ibmcom/transformation-advisor-operator:2.2.0
as it will say:

```
skopeo copy docker://docker.io/ibmcom/transformation-advisor-operator:2.2.0 dir:/Users/ibm/Downloads/test/amd6

FATA[0002] Error choosing an image from manifest list docker://ibmcom/transformation-advisor-operator:2.2.0: no image found in manifest list for architecture amd64, variant , OS darwin
```

At the moment, what I did is to sign each images of the platform, and give instruction to customers for verification. The drawback is normally, customers will just pull with the 2.2.0 tag, not the specific tag of a platform e.g. 2.2.0-amd64

**Comment by mtrmac** [comment]
Thanks for your report.

Does `skopeo copy --all …` work closer to what you expect?

The design is such that each individual architecture image carries a signature (the manifest list signature can be created but is ignored), and the signature should contain the tag the user uses to pull (in this case `:2.2.0`, although the tag points to the manifest list, not to the individual image).

**Comment by Kenzku** [comment]
Hej, thanks for replying.

Looks like you have a solution already for this issue, but it was not so clear to me.

I was wondering

1. I got the same issues as stated at https://github.com/containers/skopeo/issues/954
   possibly caused by the same compressed layers from Docker Hub:

   To reproduce, I run

        skopeo copy --all \
        docker://docker.io/ibmcom/transformation-advisor-operator:2.2.0 \
        dir:/Users/xxx/Downloads/test/transformation-advisor-operator/2.2.0

    If I run `docker pull ibmcom/transformation-advisor-operator:2.2.0`

    then run

        skopeo copy \
        --dest-tls-verify=false \
        docker-daemon:docker.io/ibmcom/transformation-advisor-operator:2.2.0 \
        dir:/Users/xxx/Downloads/test/transformation-advisor-operator/2.2.0-docker

    I got a different digest of each layers:

    <img width="834" alt="Screenshot 2020-06-17 at 14 24 43" src="https://user-images.githubusercontent.com/1387249/84903684-4eb89200-b0a6-11ea-943e-3449d6073282.png">

2. What is the industry standard to sign and verify a fat manifest?

   The way we created the manifest is:
        
        # I noticed that docker mentioned that `docker manifest` is an experimental feature
        sudo docker manifest create --amend ${OPERATOR_IMAGE_NAME} ${OPERATOR_IMAGE_NAME}-amd64 ${OPERATOR_IMAGE_NAME}-ppc64le ${OPERATOR_IMAGE_NAME}-s390x || exit 0
        sudo docker manifest push --purge ${OPERATOR_IMAGE_NAME}  || exit 0
        sudo docker manifest inspect ${OPERATOR_IMAGE_NAME}  || exit 0

    and then this is the manifest:

        {
           "schemaVersion": 2,
           "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
           "manifests": [
              {
                 "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                 "size": 2202,
                 "digest": "sha256:58e2f4cf5fb66c3e8387956d082ab25e9ddaca7f28b5c0bfbc4e61d7abe0056d",
                 "platform": {
                    "architecture": "amd64",
                    "os": "linux"
                 }
              },
              {
                 "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                 "size": 2202,
                 "digest": "sha256:aef686afc42984c9a7294c78d6f99320d81fe448c316a9143b6d7c2669f31d9d",
                 "platform": {
                    "architecture": "ppc64le",
                    "os": "linux"
                 }
              },
              {
                 "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
                 "size": 2202,
                 "digest": "sha256:cdaacb9d44397d79e27a7ce75c1a163842925690b3240ec930f8391c3d58e97e",
                 "platform": {
                    "architecture": "s390x",
                    "os": "linux"
                 }
              }
           ]
        }

**Comment by mtrmac** [comment]
>    To reproduce, I run
>    ```
>     skopeo copy --all \
>     docker://docker.io/ibmcom/transformation-advisor-operator:2.2.0 \
>     dir:/Users/xxx/Downloads/test/transformation-advisor-operator/2.2.0
>    ```
>    
>    If I run `docker pull ibmcom/transformation-advisor-operator:2.2.0`
>    then run
>    ```
>     skopeo copy \
>     --dest-tls-verify=false \
>     docker-daemon:docker.io/ibmcom/transformation-advisor-operator:2.2.0 \
>     dir:/Users/xxx/Downloads/test/transformation-advisor-operator/2.2.0-docker
>    ```    
>    I got a different digest of each layers:

Yes; `docker pull` discards the original representation of the image (with the compressed layers) and it can’t be recreated from the local storage any more.

> 2. What is the industry standard to sign and verify a fat manifest?

As mentioned above, the “simple signatures” are not enforced on the multi-arch manifests.

`skopeo copy --all --sign-by` should work for an already-created multi-arch image, or probably `podman manifest` + `podman push --sign-by`, but I don’t have direct experience with the latter.

**Comment by mtrmac** [comment]
@Kenzku Were you able to make this work?

**Comment by rhatdan** [comment]
Since we never got additional information, I am closing this issue.  Reopen if more info is provided.
