### ISSUE TITLE
copy of v1 image to v2 registry fails

### ISSUE THREAD

**Issue by dsbrng25b** [containers/skopeo#959]
When I try to copy an image with a v1 schema to a registry which only supports v2 (docker registry dropped the support for v1 images by default in 2.7.0) I get the following error:
```
Error writing manifest: Error uploading manifest v2.0.0 to localhost/k8scsi/livenessprobe: received unexpected HTTP status: 500 Internal Server Error
```
The same does work with docker pull/tag/push. It seems that docker converts the image under the hood.
Does skopeo support to convert the image somehow?

Steps to reproduce:
```
openssl req -x509 -newkey rsa:4096 -keyout tls.key -out tls.crt -days 365 -nodes -subj '/CN=localhost' -extensions v3_req -config <( echo -e "[req]\ndistinguished_name=req\n[v3_req]\nsubjectAltName = @alt_names\n[alt_names]\nDNS.1 = localhost\nIP.1 = 127.0.0.1" )

docker run -it --rm -p 443:5000 --name registry -v "$(pwd)"/tls.key:/certs/tls.key -v "$(pwd)"/tls.crt:/certs/tls.crt -e REGISTRY_HTTP_TLS_CERTIFICA=/certs/tls.crt -e REGISTRY_HTTP_TLS_KEY=/certs/tls.key  registry:2.7.1

skopeo copy --insecure-policy docker://quay.io/k8scsi/livenessprobe:v2.0.0 docker://localhost/k8scsi/livenessprobe:v2.0.0
```

**Comment by mtrmac** [comment]
Thanks for your report.

This is https://github.com/containers/skopeo/issues/651 :
> Right now, `skopeo copy --format=v2s2` will work around both issues, but that’s not at all a satisfactory resolution.
