### ISSUE TITLE
Skopeo Docker Image

### ISSUE THREAD

**Issue by abergmeier** [containers/skopeo#968]
For Google Cloud Build, I want Skopeo to run as a step. Therefor I need optimally it prepacked into a Docker Image.
Is there any official Docker Image? My Google Foo seems weak.

**Comment by abergmeier** [comment]
Found it by accident: quay.io/skopeo/stable
Seems like quay is not liked by Google.

**Comment by vrothberg** [comment]
Thanks for reaching out! We recently wrote a blog on that image: https://www.redhat.com/sysadmin/how-run-skopeo-container
