### ISSUE TITLE
[Question] Syntax for list for copy --all ?

### ISSUE THREAD

**Issue by nsteinmetz** [containers/skopeo#970]
Hello,

To allow offline installation of our product, I try to export all images from our registry.

I saw that skopeo could do that with `skopeo copy --all` but I don't get the right format. Could you please precise it ?

```
skopeo copy --all --src-creds=user:password docker://corp/image:tag docker://corp/image2:tag dir:/opt/export/
```

I tried several variations without any success so far.

I use skopeo 1.1

Thanks !

**Comment by nsteinmetz** [comment]
Ok it does not fit my use case.

all is for a given image to get all related images. For ex if you use nginx:stable as sample and pass the `--all` parameter; then it will fetch all available images variant per os (arm, amd64, etc)

It does not aim to have  a list of different images to export.

**Comment by mtrmac** [comment]
Yes. You might want to use `skopeo sync`, or just a plain shell script that runs `skopeo copy` one image at a time.
