### ISSUE TITLE
skopeo copy doesn't fail if --encryption-key is ignored

### ISSUE THREAD

**Issue by esomir** [containers/skopeo#982]
```
# skopeo --version
skopeo version 1.1.0
```

When copying a Docker image to a Docker Archive, the `--encryption-key` option is ignored, and instead the unencrypted image is saved:

This is because Docker archives are saved as schema 2 manifest, and not OCI with encrypted layer support.

```
root@65f8c6547c03:/# skopeo copy --encryption-key jwe:./publickey.pem docker://docker.io/library/nginx:1.17.8 docker-archive://test.tar
Getting image source signatures
Copying blob 68ced04f60ab done  
WARN[0006] Uncompressed digest for blob sha256:68ced04f60ab5c7a5f1d0b0b4e7572c5a4c8cce44866513d30d9df1a15277d6b previously recorded as sha256:f2cb0ecef392f2a630fa1205b874ab2e2aedf96de04d0b8838e4e728e28142da, now sha256:8191de27094c89bab360d57bdca35c0f6bfe50e5fc1028b906062c351754c404 
WARN[0006] Uncompressed digest for blob sha256:68ced04f60ab5c7a5f1d0b0b4e7572c5a4c8cce44866513d30d9df1a15277d6b previously recorded as sha256:8191de27094c89bab360d57bdca35c0f6bfe50e5fc1028b906062c351754c4Copying blob 68ced04f60ab done  
Copying blob c4039fd85dcc done  
WARN[0010] Uncompressed digest for blob sha256:c4039fd85dccc8e267c98447f8f1b27a402dbb4259d86586f4097acb5e6634af previously recorded as sha256:fe08d5d042ab93bee05f9cda17f1c57066e146b0704be2ff755d14c25e6aa5e8, now sha256:896d87efd59746ef1f97939a2306dcf9ce8747ca447f9df7003730c33752a369 
WARN[0010] Uncompressed digest for blob sha256:c4039fd85dccc8e267c98447f8f1b27a402dbb4259d86586f4097acCopying blob 68ced04f60ab done  
Copying blob c4039fd85dcc done  
Copying blob c16ce02d3d61 done  
WARN[0011] Uncompressed digest for blob sha256:c16ce02d3d6132f7059bf7e9ff6205cbf43e86c538ef981c37598afd27d01efa previously recorded as sha256:318be7aea8fc62d5910cca0d49311fa8d95502c90e2a91b7a4d78032a670b644, now sha256:77f548253a09e0587826e769cad0b6cb5fab2c76effa16360bfb7ab6e711994d 
WARN[0011] Uncompressed digest for blob sha256:c16ce02d3d6132f7059bf7e9ff6205cbf43e86c538ef981c37598afd27d01efa previously recorded as sha256:77f548253a09e0587826e769cad0b6cb5fab2c76effa16360bfb7ab6e711994d, now sha256:318be7aea8fc62d5910cca0d49311fa8d95502c90e2a91b7a4d78032a670b644 
Copying config a1523e8593 done  
Writing manifest to image destination
Storing signatures
```

Above command succeeds, but is not encrypting the layers. The tar-file can be loaded directly into Docker and run.

```
$ docker load -i test.tar
Loaded image ID: sha256:a1523e859360df9ffe2b31a8270f5e16422609fe138c1636383efdc34b9ea2d6

$ docker run --rm -it --entrypoint=/bin/bash sha256:a1523e859360df9ffe2b31a8270f5e16422609fe138c1636383efdc34b9ea2d6

root@19df5a673ef3:/# ls
bin   dev  home  lib64	mnt  proc  run	 srv  tmp  var
boot  etc  lib	 media	opt  root  sbin  sys  usr
```

If we instead first save the encrypted image to oci, and _then_ saves the Docker tarball, it will fail, because the format is not supported:

```
root@65f8c6547c03:/# skopeo copy --encryption-key jwe:./publickey.pem docker://docker.io/library/nginx:1.17.8 oci://encrypted_nginx:latest
Getting image source signatures
Copying blob 68ced04f60ab done  
Copying blob c4039fd85dcc done  
Copying blob c16ce02d3d61 done  
Copying config 82cc4ad146 done  
Writing manifest to image destination
Storing signatures

root@65f8c6547c03:/# skopeo copy oci://encrypted_nginx:latest docker-archive://test_from_oci.tar
Getting image source signatures
Copying blob 7ad1514e4f72 done  
Copying blob c33bb0a5c06c done  
Copying blob e891716107c0 [======================================] 203.0b / 203.0b
FATA[0000] Error creating an updated image manifest: Unknown media type during manifest conversion: "application/vnd.oci.image.layer.v1.tar+gzip+encrypted"
```

Here with the forced OCI format it fails as well:
```
skopeo copy --format=oci oci://encrypted_nginx:latest docker-archive://test_from_oci2.tar
Getting image source signatures
Copying blob 7ad1514e4f72 done  
Copying blob c33bb0a5c06c done  
Copying blob e891716107c0 done  
Copying config 82cc4ad146 done  
Writing manifest to image destination
FATA[0000] Error writing manifest: Unsupported manifest type, need a Docker schema 2 manifest
```

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 can you take a look at this please?

**Comment by mtrmac** [comment]
@esomir Can you re-check whether the created docker-archive is encrypted, please? In my testing, the config is unencrypted, but the layers are neither valid tar files nor valid `gzip`; it seems skopeo does encrypt the layers, it “only” discards the encryptions annotations that would allow decrypting them.

Is it possible that your Docker daemon already had the same `nginx` image present locally, so `docker load` only read the (unencrypted) config and determined that they layer files are not necessary to read, so it did not notice that they are unreadable?

It would be best to test this with an empty Docker image store.

**Comment by esomir** [comment]
@mtrmac Just tried loading the tar into a clean dind, and it correctly fails importing the tar file with `Error processing tar file(exit status 1): archive/tar: invalid tar header`. So far so good.

And I can't extract the tarballs either.

If I try decrypting it with skopeo, it also fails, so there is an issue there (probably because the config is not made correctly).

```
skopeo copy --decryption-key ./key.pem docker-archive://test.tar docker-archive://test_unencrypted.tar
Getting image source signatures
Copying blob f2cb0ecef392 [======================================] 69.1MiB / 69.1MiB
Copying blob fe08d5d042ab [--------------------------------------] 0.0b / 55.4MiB
Copying blob 318be7aea8fc [--------------------------------------] 0.0b / 3.5KiB
FATA[0000] Error writing blob: Digest did not match, expected sha256:f2cb0ecef392f2a630fa1205b874ab2e2aedf96de04d0b8838e4e728e28142da, got sha256:f2af5aa68d4a7a84cdbf142a93cacd833ebb63db6b87ec5f6ad41604ca831309 
```

**Comment by mtrmac** [comment]
Thanks for confirmation. Yes, the `docker-archive` format can’t represent the encryption metadata, so it’s not surprising that it can’t be decrypted.

**Comment by rhatdan** [comment]
I take it that this is not an issue, reopen if I am mistaken.

**Comment by mtrmac** [comment]
It’s not OK to silently “succeed” in creating a non-decryptable encrypted image.

Transfering to c/image, though.

**Comment by mtrmac** [comment]
… actually, we only strictly need https://github.com/containers/image/pull/1002 to track this, not a separate issue. So, closing again.

**Comment by QiWang19** [comment]
containers/image#1002 is a PR, not an issue, will you transfer this issue to c/image?

**Comment by mtrmac** [comment]
De-facto @rhatdan is setting the policies as to what is kept open/closed, so I’ll leave it up to him.

**Comment by rhatdan** [comment]
@mtrmac No problem keeping issues open, if they are going to be worked on and fixed.  Just leaving them rotting, forever, I have a problem with.  If this issue is going to be fixed in containers/image then the issue should be there.
