### ISSUE TITLE
How to copy all images from a repository to any other new repository

### ISSUE THREAD

**Issue by Sandeepgo** [containers/skopeo#985]
Hi Concern,

I have one registry with the name docker.io under which there is a folder/repository with library name which contains multiple images(httpd,centos,ubuntu, etc) and now I want to copy all this local images from my system to a new repository(Quay) where
quay.io/username/library folder. 

Can you share the suitable command or example for copying multiple images from a repository to some other repository?
skopeo copy -a docker://docker.io/library/* docker://quay.io/username/library ...

Or will skopeo can copy a single image from one repository to other at a single time...??

Any help would be greatly appreciated...

Thanks..
Sandeep

**Comment by mtrmac** [comment]
There is `skopeo sync` that allows copying _tagged_ images from a _single_ repository. (There isn’t any way to enumerate images only reachable using a digest, and) there isn’t any reliable way to list all repositories in a namespace; I’m afraid you’ll have to obtain the list of library/* repositories some other way, and iterate through that list manually / using a shell script.

**Comment by Sandeepgo** [comment]
Hi mtrmac,
Many thanks for your kind response. But I am unable to found skopeo sync in skopeo 1.40 version. Therefore tried to upgrade to skope 1.41 where sync is avaialable and my current O.S where I am trying it on Cent7.8 and RHEL8.2 but it's not updating.

any help would be greatly appreciated.

Thanks..
Sandeep

**Comment by mtrmac** [comment]
If you are using distribution packages, it’s up to the distribution as to when/if they will be updated.

**Comment by mtrmac** [comment]
(You might find https://access.redhat.com/errata/RHSA-2020:3053 of interest, but I’m not much of an expert on the way Skopeo is delivered in the various versions and streams. I’d suggest contacting official Red Hat support for that.)

**Comment by rhatdan** [comment]
I am not sure we are talking about the same thing, but `skope 1.41 `, did you mean skopeo 0.1.41?
skopeo-1.0.0-1.module+el8.2.1+6676+604e1b26 is being released today or so for RHEL8, which is beyond 0.1.41.

We have no intention of updating skopeo-0.1.40-11.el7_8 in RHEL7.  But you can also use newer versions of skopeo inside of a container if you wanted launched in Podman or Docker.
quay.io/stable/skopeo.

**Comment by Sandeepgo** [comment]
Hi rhatdan,
Many thanks for your kind support. Now we are able to see skopeo sync in RHEL8. But still unable to sync our existing docker registry to quay registry.

The command that I am using is: 

skopeo sync --src docker --dest quay.io quay.io/sandeepgo/ library
FATA[0000] "quay.io" is not a valid destination transport

Also it would be great if you could share some steps for using skopeo sync on RHEL7 using docker container.

Thanks..
Sandeep

**Comment by rhatdan** [comment]
No such thing as a `docker` container.  I don't use the `docker` adjective.  If you were do do the same command above
Something like:

$ podman run --privileged quay.io/skopeo/stable sync --src docker --dest quay.io quay.io/sandeepgo/ library
Or a similar command using the docker command.

**Comment by mtrmac** [comment]
>  there isn’t any reliable way to list all repositories in a namespace; I’m afraid you’ll have to obtain the list of library/* repositories some other way, and iterate through that list manually / using a shell script.

**Comment by Sandeepgo** [comment]
Hi rhatdan,
Many thanks for your kind support. It would be great if you could share me with the command for Redhat 8. I am specifically looking for skopeo sync option to sync all the images from my docker hub repository to Quay in single shot.

Thanks..
Sandeep

**Comment by rhatdan** [comment]
@mtrmac would be more likely to know this, but I am not sure if it is possible at that level.

**Comment by mtrmac** [comment]
I’ve already said twice that the enumeration of repositories isn’t possible to automate.

**Comment by mtrmac** [comment]
@Sandeepgo were you able to set up a working process?

**Comment by Sandeepgo** [comment]
No

**Comment by Sandeepgo** [comment]
[root@ip-172-31-32-162 nginx:latest]# skopeo sync --src docker --dest dir --scoped sandeepgoeldec29/nginx:latest /tmp/
INFO[0000] Tag presence check                            imagename="sandeepgoeldec29/nginx:latest" tagged=true
FATA[0000] Refusing to overwrite destination directory "/tmp/docker.io/sandeepgoeldec29/nginx:latest"
[root@ip-172-31-32-162 nginx:latest]#

It's not working and it's only copying the address in /tmp/

/tmp/docker.io/sandeepgoeldec29/nginx:latest
[root@ip-172-31-32-162 nginx:latest]# ls
version

Kindly help here.

**Comment by rhatdan** [comment]
This is what I see.

```
$ skopeo sync --src docker --dest dir --scoped sandeepgoeldec29/nginx:latest /tmp/dan
INFO[0000] Tag presence check                            imagename="sandeepgoeldec29/nginx:latest" tagged=true
INFO[0000] Copying image tag 1/1                         from="docker://sandeepgoeldec29/nginx:latest" to="dir:/tmp/dan/docker.io/sandeepgoeldec29/nginx:latest"
FATA[0006] Error copying tag "docker://sandeepgoeldec29/nginx:latest": Error initializing source docker://sandeepgoeldec29/nginx:latest: Error reading manifest latest in docker.io/sandeepgoeldec29/nginx: manifest unknown: manifest unknown 
```

**Comment by mtrmac** [comment]
Assuming this is either resolved, or no longer relevant. Please reopen if that’s not the case.
