### ISSUE TITLE
Export inspectOutput struct /cmd/skopeo/inspect.go

### ISSUE THREAD

**Issue by ashokponkumar** [containers/skopeo#989]
If an external program needs to read output of skopeo inspect, then they have to define its own struct. Instead, if we export inspectOutput by making it InspectOutput, it will help in reading the output by using it as a library.

**Comment by rhatdan** [comment]
Could you add you description here to the PR to help explain why you want to do this.

**Comment by ashokponkumar** [comment]
@rhatdan I have added the same description to the PR. Or do we need more info?

**Comment by TomSweeneyRedHat** [comment]
@ashokponkumar I'm not seeing any file changes with this PR?  Perhaps your push to fix the description didn't get them?

**Comment by ashokponkumar** [comment]
> @ashokponkumar I'm not seeing any file changes with this PR? Perhaps your push to fix the description didn't get them?

I edited the same PR. I am able to see the changes in https://github.com/containers/skopeo/pull/990/commits/aec17bd8f5f20c60eb95bcad01d219157578bebf. Am I missing something?

**Comment by TomSweeneyRedHat** [comment]
If I go to that commit I see the file, but I'm not seeing it here.  Did you rebase after makng the change to the description?

**Comment by ashokponkumar** [comment]
> If I go to that commit I see the file, but I'm not seeing it here. Did you rebase after makng the change to the description?

I just rebased, edited and force pushed as per @rhatdan's guidance.

**Comment by mtrmac** [comment]
#992 was merged.
