### ISSUE TITLE
Image copy fails for multi-arch images using `scratch`

### ISSUE THREAD

**Issue by mnaser** [containers/skopeo#991]
If you use the following Dockerfile:

```
FROM scratch
ADD http://icanhazip.com /ip
```

and build it using `buildx` for multiple architectures with this command:

```
DOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --platform=linux/amd64,linux/arm64 --tag 127.0.0.1:5100/test:latest --push .
```

The registry at `127.0.0.1:5100` is simply an instance of `registry:2`.  Once the image is built, any attempt to copy it will fail.

```
skopeo --insecure-policy copy --src-tls-verify=false --dest-tls-verify=false --all docker://127.0.0.1:5100/test:latest docker://127.0.0.1:5100/test:latest
Getting image list signatures
Copying 2 of 2 images in list
Copying image sha256:9e67fe4b66bf9999ad5076e4bab3914f4cdb4c844da1beb627c14dc2e4ac6138 (1/2)
FATA[0000] Error initializing image from source docker://127.0.0.1:5100/test:latest: unsupported docker v2s2 media type: "application/vnd.oci.image.layer.v1.tar+gzip" 
```

**Comment by mtrmac** [comment]
Thanks for your report. This seems to be an invalid image (using OCI layers in v2s2 images, conflicting with https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#image-manifest-field-descriptions ).

Still, can you paste the full output of the failing `skopeo --debug … copy …`, please?

**Comment by rhatdan** [comment]
Closing do to lack of information, reopen if info becomes available.
