### ISSUE TITLE
Last versions are not available in RHEL 7

### ISSUE THREAD

**Issue by sepulvedablanco** [containers/skopeo#997]
When trying to install skopeo in CentOS 7 the latest available version is v0.1.40.

How could I get skopeo v1.1.1 binary without compiling the source code?

Thank you!

**Comment by TomSweeneyRedHat** [comment]
you could use it as a container image

`podman run quay.io/containers/skopeo:v1.1.0` {favorite skopeo command}

I'm not sure that v1.1.1 has reached stable yet, after it does it too will be there.  Reference [here](https://github.com/containers/skopeo/tree/master/contrib/skopeoimage)

**Comment by sepulvedablanco** [comment]
yes I know but I just need to copy images between two registries so I dont want to install docker, podman or whatever

**Comment by TomSweeneyRedHat** [comment]
@lsm5 do you know when/how/if Skopeo v1.0+ will land in CentOS 7?

**Comment by lsm5** [comment]
RE: Vanilla CentOS 7, can't say for sure.

@sepulvedablanco have you tried the OBS repo? https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/skopeo . Click the `Download Package` link and it will show you instructions on how to install on CentOS 7.

**Comment by lsm5** [comment]
@TomSweeneyRedHat is there a recommended place to list installation steps?

**Comment by TomSweeneyRedHat** [comment]
Maybe something in https://github.com/containers/skopeo/blob/master/install.md, I'm not sure there's a better landing spot.

**Comment by lsm5** [comment]
PTAL https://github.com/containers/skopeo/pull/1053
